src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status from MBA</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back to Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT/QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpublished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coming Soon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft - Under Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Share Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The subscription is not related to the account on the opportunity</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>The subscription is not related to the account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestOppsForConsole.cls
@isTest
public class TestOppsForConsole {

static testMethod void testContactConsole() 
    {
    	TestDataGenerator td = new TestDataGenerator();
    	
    	// Create some accounts, contacts and subs
    	td.getAccounts(true);
    	td.getContacts(true); 	
    	list<Subscription__c> lstSubs = td.getSubscriptions(true);
    	List<Opportunity> lstOpps = td.getOpportunities(true);
    	
    	Id accountId = td.accounts[0].Id;
    	Id contactId = td.contacts[0].Id;
    	
    	// Update the first contact record to be associated with the account
    	td.contacts[0].AccountId = accountId;
    	update td.contacts;
    	
    	// Loop through the subscriptions and set the account id
    	for (Subscription__c sub : lstSubs)
    	{
    		sub.Account__c = accountId;
    	}
    	    	
    	update(lstSubs);
    	
    	// Loop through the opportunities and set the account id
    	Id trialRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_Trial).getRecordTypeId();
	 
    	for (Opportunity opp : lstOpps)
    	{
    		opp.AccountId = accountId;
    		opp.RecordTypeId = trialRecordTypeId;
    		opp.Subscription__c = lstSubs[0].Id;
    	}
    	    	
    	update(lstOpps);
    	list<Opportunity> returnOpps = [SELECT Id, Status__c FROM Opportunity WHERE AccountId = :accountId];
    	
    	system.debug('@@@ TestSubsForConsole:testContactConsole - Subs for Account Id: ' + accountId); 
    	system.debug('@@@ TestSubsForConsole:testContactConsole - Subs for Contact Id: ' + contactId);
    	system.debug('@@@ TestSubsForConsole:testContactConsole - Subs for Test: ' + lstOpps); 
    	system.debug('@@@ TestSubsForConsole:testContactConsole - Subs for Contact: ' + returnOpps);
    	
    	Test.startTest();
    				
		PageReference pageRef = Page.OppForConsole;
		pageRef.getParameters().put('Id', contactId);
		pageRef.getParameters().put('selId', lstOpps[0].Id);
		Test.setCurrentPage(pageRef);		
		
		OppForConsoleController cont = new OppForConsoleController();			
		
		cont.LoadOpportunities();
		
		// ensure the correct number of subscriptions loaded
//		system.assertEquals(td.subscriptionNum, cont.getSubs().size());
		
		string acctPrefix = cont.accountPrefix;
		string contPrefix = cont.contactPrefix;
//		string casePrefix = cont.caseCreateURLPrefix;
		
		accountId = cont.getAcctId();
		contactId = cont.getContactId();
		
		system.debug('@@@ TestSubsForConsole:testContactConsole - Account Id for page: ' + accountId);
		system.debug('@@@ TestSubsForConsole:testContactConsole - Contact Id for page: ' + contactId);
		
		// By calling this all subs should not be selected	
		cont.SelectOpp();
		
		system.assertEquals(null, cont.getSelectedOppId());
		
		// Now actually select a sub
		for (OppForConsoleController.OpportunityWrapper wrap : cont.getOpps())
		{
			if (wrap.objOpp.Id == lstOpps[0].Id)
			{
				wrap.isSelected = true;
				break;
			}
		}
		
		cont.SelectOpp();
		
		system.assertNotEquals(null, cont.getSelectedOppId());
		string oppName = cont.getSelectedOppName();
		cont.CreateCase();
//		list<SelectOption> caseOpts = cont.lstCaseRTs;
//		list<OppForConsoleController.CaseRTWrapper> lstCaseWrap = cont.lstCaseRTWraps;
				
		
		Test.stopTest();
    }
}