src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Launch_Team_Commando__c</fullName>
        <label>zLaunch Team Commando OLD</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ltc__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SSC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enterprise Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Indicates whether the account exists in MBA or BMP</description>
        <inlineHelpText>Indicates whether the account exists in MBA or BMP</inlineHelpText>
        <label>Provisioning System</label>
        <picklist>
            <picklistValues>
                <fullName>BMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Success_Squad_Consultant__c</fullName>
        <inlineHelpText>Consultant of the most recently created session</inlineHelpText>
        <label>zSuccess Squad Consultant OLD</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Source__c</fullName>
        <description>Indicates whether the account exists in MBA or BMP</description>
        <inlineHelpText>Indicates whether the account exists in MBA or BMP</inlineHelpText>
        <label>Provisioning System</label>
        <picklist>
            <picklistValues>
                <fullName>BMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Success_Squad_Consultant__c</fullName>
        <description>Old - was used by SSquad when they worked contacts but can probably be removed.  Steven Bennett would know for sure</description>
        <formula>Account.SSC__r.FirstName&amp;&quot; &quot;&amp; Account.SSC__r.LastName</formula>
        <label>zSuccess Squad Consultant</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Launch_Team_Commando__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Launch Team Commando</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Indicates whether the account exists in MBA or BMP</description>
        <inlineHelpText>Indicates whether the account exists in MBA or BMP</inlineHelpText>
        <label>Provisioning System</label>
        <picklist>
            <picklistValues>
                <fullName>MBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Store Purchase Opportunity that this is related to.</inlineHelpText>
        <label>Store Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity does not have the same Account</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>Select a Store purchase opportunity</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Professional Services)</relationshipLabel>
        <relationshipName>PSOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The subscription is not related to the account on the opportunity</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>The subscription is not related to the account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Success_Squad_Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Success Squad Consultant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportuity1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact associated with the subscription</description>
        <inlineHelpText>Contact associated with the subscription</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Launch_Team_Commando__c</fullName>
        <formula>Account__r.Ltc__r.Full_Name__c</formula>
        <label>zLaunch Team Commando</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Used in the partner portal apex code to designate when a sub was created via the portal rather than by MBA</description>
        <inlineHelpText>Used in the partner portal apex code to designate when a sub was created via the portal rather than by MBA</inlineHelpText>
        <label>UNDER REVIEW Source</label>
        <picklist>
            <picklistValues>
                <fullName>Direct Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRM Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acquisition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Success_Squad_Consultant__c</fullName>
        <formula>Account__r.SSC__r.Full_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>zSuccess Squad Consultant</label>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OpportunityHelper.cls
public class OpportunityHelper {

 public static Id idOppRecordType =  Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Professional Services').getRecordTypeId();

	public  Opportunity createOppProfFromAcc(Id acctId)
	{
        //create an opportunity
        Account acc = [select id, name, SSC__c, LTC__c from Account where id =:acctId];
         
        Opportunity opp = defaultOpportunityProf();
        opp.AccountId = acc.Id;
        opp.Name = acc.Name + '- Professional Services';
        opp.RecordTypeId = idOppRecordType;
        opp.Success_Squad_Consultant__c = acc.SSC__c;
        opp.Launch_Team_Commando__c = acc.ltc__c;
	    try {																 
			insert opp;
			}
		catch(Exception e) 
		{
        		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Error inserting Opportunity - ' + e.getMessage()));
        }		    
	        
	     return opp;
	}
	
	public  Opportunity createOppProfFromCon(Id conId)
	{
        //create an opportunity
       Contact con = [select id, name, AccountId, Account.Name from Contact where id =:conId];
         
        Opportunity opp = defaultOpportunityProf();
        opp.AccountId = con.AccountId;
        opp.RecordTypeId = idOppRecordType;
        opp.Name = con.Account.Name + '- Professional Services';
        string crole ='Professional Services Contact';
       try {																 
			insert opp;
			createContactRole(opp.Id, con.Id, crole);
		}
		catch(Exception e) 
		{
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Error inserting Opportunity - ' + e.getMessage()));
        }		
	    return opp;
	}
	
	public static Opportunity createOppProfFromOpp(Id oppId)
	{
        //create an opportunity
       Opportunity o = [select id, name, AccountId, Contact__r.Id, Account.Name, Subscription__c, Source__c from Opportunity where id =:oppId];
         
        Opportunity opp = defaultOpportunityProf();
        opp.AccountId = o.AccountId;
        opp.RecordTypeId = idOppRecordType;
//        opp.Name = o.Account.Name + '- Professional Services';
		opp.Name = 'PS: ' + DataUtility.TruncateString(o.Name, 75);
        opp.Store_Opportunity__c = o.Id;
        opp.Subscription__c = o.Subscription__c;
        string crole ='Professional Services Contact';
        if (o.Source__c == 'BMP') opp.Pricebook2Id = Label.Zuora_PS;
       try {																 
			insert opp;
			createContactRole(opp.Id, o.Contact__r.Id, crole);
		}
		catch(Exception e) 
		{
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Error inserting Opportunity - ' + e.getMessage()));
        }		
	    return opp;
	}
	
	public static Opportunity defaultOpportunityProf()
	{
		    Opportunity opp = new Opportunity();
	        opp.RecordTypeId = idOppRecordType;
	        opp.Pricebook2Id = Label.Bigcommerce_Pricebook;
	        opp.StageName ='Lead';
	        opp.Type = 'Existing Client';
	        opp.CloseDate = date.today().addDays(14);
	        return opp;
	}
	
	public static  map<Id, Id> getContactFromRole(Set<Id> oppIds, string crole)
	{
		List<OpportunityContactRole> crs = new List<OpportunityContactRole>([Select Role,ContactId, OpportunityId, Id
																		From OpportunityContactRole 
																		where OpportunityId in :oppIds
																		and role =:crole]);
		Map <Id, Id> oppCon = new Map<Id, Id>();														
        for (OpportunityContactRole cr :crs)
        {
        	oppCon.put(cr.OpportunityId, cr.ContactId);
        }
        return oppCon;
	}
	public static void  createContactRole(Id oppId, Id conId, string crole)
	{
		OpportunityContactRole cr = new OpportunityContactRole(Role = crole,ContactId =conId, 
																OpportunityId =oppId);
		try {																 
			insert cr;
			}
		catch(Exception e) 
		{
        		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Error inserting Contact role - ' + e.getMessage()));
        }														
        
        
	}
	
	public static void storeOppTeamMembers(map<Id, Opportunity> oldMap, map<Id, Opportunity> newMap)
{
	if(oldMap != null && newMap != null)
	{
		Id oId;
		
		map<Id, list<OpportunityTeamMember>> mapOTMs = new map<Id, list<OpportunityTeamMember>>();
		list<OpportunityTeamMember> lstOTMs = new list<OpportunityTeamMember>();
		list<OpportunityTeamMember> existlstOTMs = new list<OpportunityTeamMember>([SELECT o.UserId, o.OpportunityId, o.TeamMemberRole
	                 						 FROM OpportunityTeamMember o
	                 						 WHERE o.OpportunityId =: newMap.keySet()
	                 						 ORDER BY OpportunityId]);
                 						 
		system.debug('## hlpr_Opportunity storeOppTeamMembers lstOTMs: ' + lstOTMs);
		if (!existlstOTMs.isEmpty())
		{
	        for(OpportunityTeamMember otm : existlstOTMs)
			{
				if(oId == null)
					oId = otm.OpportunityId;
					
				if(oId == otm.OpportunityId)
					lstOTMs.add(otm);
				else
				{
					mapOTMS.put(oId, lstOTMs);
					oId = otm.OpportunityId;
					lstOTMs = new list<OpportunityTeamMember>();
					lstOTMs.add(otm);
				}
			}
			
			if(!lstOTMs.isEmpty())
				mapOTMS.put(oId, lstOTMS);
			
			system.debug('## hlpr_Opportunity storeOppTeamMembers mapOTMS: ' + mapOTMS);
			StaticVariables.mapOOTMs = mapOTMS;
	    }
/*		for (Opportunity Opp : newMap.values())
		{
            if (oldMap.get(Opp.id).OwnerId != Opp.OwnerId)
 //               Opp.OpportunityTeamMembers__c = String.valueOf(mapOTMs.get(Opp.Id));
                
//			system.debug('## hlpr_Opportunity storeOppTeamMembers Opp.OpportunityTeamMembers__c: ' + Opp.OpportunityTeamMembers__c);
		}
		*/
	}
}

	public static void setOppTeamMembers(map<Id, Opportunity> mapOppsOld, map<Id, Opportunity> mapOppsNew)
 {
 		OpportunityTeamMember otm;
 		
 		list<OpportunityTeamMember> lstOTMs = new list<OpportunityTeamMember>();
// 		Schema.DescribeFieldResult fieldResult = OpportunityTeamMember.TeamMemberRole.getDescribe();
//		List<Schema.PicklistEntry> lstPickVals  = fieldResult.getPicklistValues();
//		String tmRole = lstPickVals[0].getValue();
 		
 	
 		if(mapOppsOld != null)
 		{
  		//Insert old team members
	  		for (Opportunity Opp : mapOppsNew.values())
	  		{
	            // Only if the record owner changed
	            if (mapOppsOld.get(Opp.id).OwnerId != Opp.OwnerId)
				{            	
	   //             system.debug('##  setOppOwnerTeamMember Opp.OpportunityTeamMembers__c: ' + Opp.OpportunityTeamMembers__c);
	                list<OpportunityTeamMember> otms = StaticVariables.mapOOTMs.get(Opp.Id);
		            if (otms <> null && otms.size() >0 )
		            {
		                for (OpportunityTeamMember ot:otms)
		   				{
		                   if (ot.userid <> Opp.OwnerId)  
		                   {  otm = new OpportunityTeamMember();
							 otm.UserId = ot.UserId;
							 otm.OpportunityId = ot.OpportunityId;
							 otm.TeamMemberRole = ot.TeamMemberRole;
	//	                     lstOTMs.addAll(otms);
							lstOTMs.add(otm);
		                   }
						} 
		            }
				  }
	  			}	  		
		}
		system.debug('## hlpr_Opportunity setOppTeamMembers lstOTMs: ' + lstOTMs);
 	
		if(!lstOTMs.isEmpty())
		{ Try{
			 	insert lstOTMs;
		  }catch(exception e) {system.debug ('*** failed to insert');}
		}
  }
  
}