src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client_Record_Type</fullName>
        <active>true</active>
        <description>Bigcommerce Clients</description>
        <label>Client Record Type</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Promoter_io_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promoter.io Feedbacks</relationshipLabel>
        <relationshipName>Promoter_io_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Promoter.io Feedbacks</relationshipLabel>
        <relationshipName>Promoter_io_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Promoter.io Feedback</label>
    <nameField>
        <displayFormat>PIO-{00000000}</displayFormat>
        <label>Promoter.io Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoter.io Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PromoterioSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Case_Category__c</fullName>
        <label>Case Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Origin__c</fullName>
        <label>Case Origin</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Reason__c</fullName>
        <label>Case Reason</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Subject_Starting__c</fullName>
        <label>Case Subject Starting</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Point__c</fullName>
        <label>End Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fetch_All__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fetch All</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Specific_Campaign_ID__c</fullName>
        <label>Specific Campaign ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Promoter.io Settings</label>
</CustomObject>

src/classes/BatchProcessPromoterIo_Test.cls
/**
 * BatchProcessPromoterIo_Test
 * Author: Bala Rajagopal
 * Purpose: Test Class for Promoter.io to Salesforce Integration Batch classes
 * Ticket: BAP-3171
 * 
 */
@isTest
public class BatchProcessPromoterIo_Test{
    public static string accid;
    public static string conid;
    @isTest
    public static void testSchedulerStart() {
        List<Account> accounts = TestDataFactory.createTestAccounts(1, false, TestDataFactory.AccountRecordType.Client_Record_Type);
		List<Contact> contacts = TestDataFactory.createTestContacts(1, accounts);
        Contact con = contacts[0];
        con.Email = 'TestPromoterioContact@test.com';
        update con;
        accid = con.AccountId;
        conid = con.id;
        Promoter_io_Feedback__c po = TestDataFactory.createPromoterIoFeedback(con);
        po.Email__c = 'TestPromoterioContact@test.com';
        po.Contact__c = con.id;
        update po;
        List<contact> contList = new List<Contact>([select id, email, accountid from Contact where id = :con.id]);
        
        
        promoterioSettings__c pios = promoterioSettings__c.getOrgDefaults();
        pios.Specific_Campaign_ID__c = '999999';
        pios.End_Point__c = 'https://app.promoter.io/api/feedback/';
        pios.Token__c = 'd8ff7573a2631540377b793bbd4396ac1c5699a9';
        pios.Case_Subject_Starting__c = 'NPS Survey Response from';
        pios.Case_Origin__c = 'Promoter.io';
        pios.Case_Reason__c = 'Surveys';
        pios.Case_Category__c = 'Company NPS';
        pios.Fetch_All__c = false;
        upsert pios;
        
        Id idCSCaseRecordType =  Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Client Success').getRecordTypeId();
        /*
        Case cas = new Case();
        cas.Subject = 'NPS Survey Response from Test';
        cas.Origin = 'Promoter.io';
        cas.Reason = 'Surveys';
        cas.Description = '<br> Contact Email: TestPromoterioContact@test.com <br> Date: June 29, 2016<br> <br> Score: 0<br>Feedback:<br><br>Your staff Test';
        cas.ContactId = con.id;
        cas.RecordTypeId = idCSCaseRecordType;
        insert cas;
        */
        test.startTest();
        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        // Call method to test.
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock. 
        SchedulePromoterIoQuery sc = new SchedulePromoterIoQuery();
		sc.execute(null);
        
		Case cas2 = new Case();
        cas2.Subject = 'NPS Survey Response from Test';
        cas2.Origin = 'Promoter.io';
        cas2.Reason = 'Surveys';
        cas2.Description = '<br> Contact Email: TestPromoterioContact@test.com <br> Date: June 29, 2016<br> <br> Score: 0<br>Feedback:<br><br>Your staff Test';
        //cas2.ContactId = con.id;
        cas2.RecordTypeId = idCSCaseRecordType;
        insert cas2;
        
        test.stopTest();
        // Verify response received contains fake values
        List<Promoter_io_Feedback__c> piofList = new List<Promoter_io_Feedback__c>([select id, contact__c,Account__c from Promoter_io_Feedback__c limit 10]);
        Set<Id> ConIds = new Set<Id>();
        for(Promoter_io_Feedback__c pio:piofList){
            conIds.add(pio.contact__c);
        }
        List<contact> conL = new List<contact>([select id, Last_Promoter_io_NPS__c from Contact where id in :conIds limit 10]);
        system.assertNotEquals(null, piofList);
        //system.assertEquals(25, conL[0].Last_Promoter_io_NPS__c);

    }
}