src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>iDev_Partner_ID__c</fullName>
        <description>Used to port new partner ID from the iDev commissions system; assigns new leads coming from the partner to the partner account owner. jw</description>
        <externalId>true</externalId>
        <label>iDev Partner ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_T_C_Agreement__c.object
<CustomObject>
    <description>PRM Portal terms and conditions for Channel Partners</description>
    <fields>
        <fullName>Accepted_By__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Accepted By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Partner_T_C_Agreements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accepted_Date__c</fullName>
        <label>Accepted Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>Partner Account that has accepted the T&amp;C record</description>
        <inlineHelpText>Partner Account that has accepted the T&amp;C record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Partner_T_C_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Terms_Conditions__c</fullName>
        <label>Terms &amp; Conditions</label>
        <referenceTo>Terms_Conditions__c</referenceTo>
        <relationshipName>Partner_T_C_Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>zPartner T&amp;C Agreement</label>
    <nameField>
        <displayFormat>PTCA-{0}</displayFormat>
        <label>Partner T&amp;C Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner T&amp;C Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsTrial__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Value pushed from MBA and is used in a trigger to convert leads when it&apos;s unchecked. Can also be used to force the account rollups to recalculate</description>
        <inlineHelpText>Value pushed from MBA and is used in a trigger to convert leads when it&apos;s unchecked. Can also be used to force the account rollups to recalculate</inlineHelpText>
        <label>MBA Is Trial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <description>Unique identifier from MBA of account/user.  ID of the account which owns this subscription</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier from MBA of account/user.  ID of the account which owns this subscription</inlineHelpText>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBAPartnerID__c</fullName>
        <description>Used to map Partner Source from MBA.  The iDev Affiliate ID of the partner, if this subscription is attributed to one</description>
        <label>MBA Partner ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <description>ID specific to the store/product purchased</description>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <description>From MBA to distinguish stores from SSLs and Domains</description>
        <inlineHelpText>Type of product (store, SSL, domain, etc)</inlineHelpText>
        <label>MBA Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Store</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Domain Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSL Certificate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>From MBA saying which plan/trial the store is on</description>
        <inlineHelpText>From MBA saying which plan/trial the store is on</inlineHelpText>
        <label>MBA Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date the trial or store was first created. Pushed from MBA</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Terms_Conditions__c.object
<CustomObject>
    <description>Holds the Terms &amp; Conditions for any use</description>
    <label>Terms &amp; Conditions</label>
    <nameField>
        <displayFormat>TC-{0}</displayFormat>
        <label>Terms &amp; Conditions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms &amp; Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestPartnerHomeController.cls
@isTest
public class TestPartnerHomeController
{
    static Id RTID_MBASub = Subscription__c.getSObjectType().getDescribe().getRecordTypeInfosByName().get('MBA Subscription').getRecordTypeId();
    
    static testMethod void testPartnerHome1() 
    {
        TestDataGenerator td = new TestDataGenerator();
        
        // Create a test account
        list<Account> lstAcct = td.getAccounts(false);
        Account objA = lstAcct[0];
        objA.iDev_Partner_ID__c = 9990055;
        insert objA;
        
        // Create a contact
        list<Contact> lstContact = td.getContacts(false);
        Contact objC = lstContact[0];
        objC.AccountId = objA.Id;
        insert objC;
        
        // Create T&C record
        list<Terms_Conditions__c> lstTC = td.getTermsConditions(true);
        
        // Turn the contact into a portal user
        Profile p = [SELECT id 
                        FROM profile
                        WHERE name = 'PRM Portal User'
                        LIMIT 1];  
        
        String testemail = 'puser000@amamama.com';

        User pu = new User(profileId = p.id, username = testemail, email = testemail,
                            emailencodingkey = 'UTF-8', localesidkey = 'en_US',
                            languagelocalekey = 'en_US', timezonesidkey = 'America/Chicago',
                            alias='cspu', lastname='lastname', firstname='firstname', contactId = objC.id);

        insert pu;
        
        test.startTest();
        
        system.RunAs(pu)
        {
            pageReference pageRef = Page.PartnerHome;
            test.setCurrentPage(pageRef);
    
            // Instantiate a new controller      
            PartnerHome controller = new PartnerHome();
            
            // Call all the methods
            pageReference pr1 = controller.PartnerStart();
        }
        
        test.stopTest();
    }
    
    static testMethod void testPartnerHome2() 
    {
        TestDataGenerator td = new TestDataGenerator();
        
        // Create a test account
        list<Account> lstAcct = td.getAccounts(false);
        Account objA = lstAcct[0];
        objA.iDev_Partner_ID__c = 9990055;
        insert objA;
        
        // Create a contact
        list<Contact> lstContact = td.getContacts(false);
        Contact objC = lstContact[0];
        objC.AccountId = objA.Id;
        insert objC;
        
        list<Terms_Conditions__c> lstTC = td.getTermsConditions(true);      
        Terms_Conditions__c tc1 = lstTC[0];
        
        // Now agree to the terms
        Partner_T_C_Agreement__c tc = new Partner_T_C_Agreement__c();
        tc.Account__c = objA.Id;
        tc.Terms_Conditions__c = tc1.Id;
        tc.Accepted_By__c = objC.Id;
        tc.Accepted_Date__c = system.now();
        insert tc;
        
        // Turn the contact into a portal user
        Profile p = [SELECT id 
                        FROM profile
                        WHERE name = 'PRM Portal User'
                        LIMIT 1];  
        
        String testemail = 'puser000@amamama.com';

        User pu = new User(profileId = p.id, username = testemail, email = testemail,
                            emailencodingkey = 'UTF-8', localesidkey = 'en_US',
                            languagelocalekey = 'en_US', timezonesidkey = 'America/Chicago',
                            alias='cspu', lastname='lastname', firstname='firstname', contactId = objC.id);

        insert pu;
        
        // Create Subscriptions for this new account    
        list<Subscription__c> lstSub = new list<Subscription__c>();
        Subscription__c objSub;
        
        for (integer x = 0; x < 202; x++)
        { 
            objSub = new Subscription__c();
            objSub.MBAAccountID__c = td.getAccounts(true)[1].Id;
            objSub.MBAPartnerID__c = string.valueOf(objA.iDev_Partner_ID__c);
            objSub.MBASubscriptionID__c = '123990' + string.valueOf(x);
            objSub.RecordTypeId = RTID_MBASub;
            objSub.Status__c = 'Active';
            objSub.ProductType__c = 'Store';
            
            if (x < 50)
            {
                objSub.isTrial__c = true;
                objSub.StartDate__c = System.today() - 10;
                objSub.Product__c = '15 Free Trial';
            }
            else if (x >= 50 && x < 100)
            {
                objSub.isTrial__c = true;
                objSub.StartDate__c = System.today() - 35;
                objSub.Product__c = '15 Free Trial';
            }
            else if (x >= 100 && x < 150)
            {
                objSub.isTrial__c = false;
                objSub.StartDate__c = System.today() - 10;
                objSub.Product__c = 'Gold Package';
            }
            else if (x >= 150 && x < 200)
            {
                objSub.isTrial__c = false;
                objSub.StartDate__c = System.today() - 35;
                objSub.Product__c = 'Silver Package';
            }
            
            lstSub.add(objSub);
        }
        
        insert lstSub;
        
        test.startTest();
        
        system.RunAs(pu)
        {
            pageReference pageRef = Page.PartnerHome;
            test.setCurrentPage(pageRef);
    
            // Instantiate a new controller      
            PartnerHome controller = new PartnerHome();
            
            // Call all the methods
            pageReference pr1 = controller.PartnerStart();
            list<PartnerHome.SubByProduct> lstStoresByProd = controller.PurchasedStoresByProduct;
            list<PartnerHome.SubByMonth> lstSubsByMonth = controller.SubsByMonth;           
            
            // Client Store Controller properties and methods
            list<Subscription__c> lstClientStored = controller.ClientStores;
            string storePgSize = controller.getClientStores_PageSize();
            controller.setClientStores_PageSize('10');
            list<SelectOption> lstStorePgOpts = controller.ClientStores_PageNumber_All;
            integer storePgNum = controller.ClientStores_PageNumber_Total;
            string storeCurPg = controller.ClientStores_PageNumber_Cur;
            controller.ClientStores_PageNumber_Cur = '2';
            integer storeTotal = controller.ClientStores_TotalRecords;
            boolean storeHasNext = controller.ClientStores_HasNext;
            controller.ClientStores_Next();
            boolean storeHasPrev = controller.ClientStores_HasPrevious;
            controller.ClientStores_Previous();
            controller.ClientStores_Last();
            controller.ClientStores_First();
            controller.ClientStores_SortedBy = 'CreatedDate';
            controller.ClientStores_SortDir = 'DESC';
            controller.ClientStores_Sort();
            
            // Active Trials Controller properties and methods
            list<Subscription__c> lstTrials = controller.ActiveTrials;
            string trialPgSize = controller.getActiveTrials_PageSize();
            controller.setActiveTrials_PageSize('10');
            list<SelectOption> lstTrialPgOpts = controller.ActiveTrials_PageNumber_All;
            integer trialPgNum = controller.ActiveTrials_PageNumber_Total;
            string trialCurPg = controller.ActiveTrials_PageNumber_Cur;
            controller.ActiveTrials_PageNumber_Cur = '2';
            integer trialTotal = controller.ActiveTrials_TotalRecords;
            boolean trialHasNext = controller.ActiveTrials_HasNext;
            controller.ActiveTrials_Next();
            boolean trialHasPrev = controller.ActiveTrials_HasPrevious;
            controller.ActiveTrials_Previous();
            controller.ActiveTrials_Last();
            controller.ActiveTrials_First();
            controller.ActiveTrials_SortedBy = 'CreatedDate';
            controller.ActiveTrials_SortDir = 'DESC';
            controller.ActiveTrials_Sort();
            
            // Check the variables
            boolean isValidUser = controller.InvalidUser;
            decimal storeCnt = controller.PurchasedStoresCount_Total;
            decimal MRRTotal = controller.PurchasedStoresMRR_Total;
            decimal MRRAvg = controller.PurchasedStoresMRR_Avg;
        }
        
        test.stopTest();
    }
}