src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SupportPin__c</fullName>
        <label>Support Pin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Support_PIN__c</fullName>
        <formula>Account.SupportPin__c</formula>
        <label>Support PIN</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>SupportPin__c</fullName>
        <inlineHelpText>MBA account pin used to verify account access for cases</inlineHelpText>
        <label>zSupport Pin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <description>ID specific to the store/product purchased</description>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <description>From MBA to distinguish stores from SSLs and Domains</description>
        <inlineHelpText>Type of product (store, SSL, domain, etc)</inlineHelpText>
        <label>MBA Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Store</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Domain Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSL Certificate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>From MBA saying which plan/trial the store is on</description>
        <inlineHelpText>From MBA saying which plan/trial the store is on</inlineHelpText>
        <label>MBA Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StoreURL__c</fullName>
        <description>URL of the BC trial or store populated by MBA</description>
        <inlineHelpText>URL of the BC trial or store populated by MBA</inlineHelpText>
        <label>MBA Store URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Support_PIN__c</fullName>
        <description>Formula pulling the pin value from the associated account or lead</description>
        <formula>IF(
ISBLANK(Account__r.SupportPin__c), Lead__r.SupportPin__c ,Account__r.SupportPin__c)</formula>
        <label>Support Pin</label>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestDataGenerator_SubscriptionValidation.cls
public with sharing class TestDataGenerator_SubscriptionValidation {

	//Always allow for the creation of one or more users
	public list<User> users;
	public map<String,list<User>> profileToUserMap;      
 
	public list<Account> accounts;
	public list<Contact> contacts;
	public list<Lead> leads;  
	public list<Subscription__c> lstSubscriptions;

	public Integer userNum;
	public Integer accountNum;
	public Integer contactNum;
	public Integer leadNum;      
	public Integer subscriptionNum;

	public TestDataGenerator_SubscriptionValidation()
	{
		userNum = 5;
		accountNum = 5;
		contactNum = 5;  // Contacts count should be equal to opptynum size
		leadNum = 5;
		subscriptionNum = 5;
        
	}

      public list<Account> getAccounts(Boolean xCommit) 
      {
            if(accounts == null) {
                  accounts = new list<Account>();
                  for(Integer i = 0; i < accountNum; i++) {
                        Account a = new Account();
                        a.Name = 'Test ' + i;
                        a.SupportPin__c = '0000'+i;
                        a.BillingStreet='Main St';
                        a.BillingCity='Dallas';
                        a.BillingState = 'TX';      
                        a.BillingPostalCode='70000';
                        a.BillingCountry = 'US';
                        accounts.add(a);
                  }
                  if(xCommit) insert accounts;
            }
            
            if(xCommit && accounts.size() > 0 && accounts[0].Id == null) insert accounts;                                            
            
            return accounts;
      }

	public list<Subscription__c> getSubscriptions (boolean xCommit)  
    {
		if(lstSubscriptions == null) 
		{
			lstSubscriptions = new list<Subscription__c>();
			for(Integer i = 0; i < subscriptionNum; i++) 
			{
				Subscription__c sub = new Subscription__c();
				sub.RecordTypeId = Subscription__c.getSObjectType().getDescribe().getRecordTypeInfosByName().get('MBA Subscription').getRecordTypeId();
				sub.MBASubscriptionID__c = '12345-' + i;
				sub.Status__c = 'Active';
				sub.ProductType__c = 'Store';
				sub.Product__c = 'Silver Store';
				sub.StoreURL__c = 'http://www.testingthis.com';
                Integer j = Math.mod(i,getAccounts(true).size());
				sub.Account__c = getAccounts(true)[j].Id;
							
				lstSubscriptions.add(sub);
			}
  			
  			if(xCommit) insert lstSubscriptions;
		}

		if(xCommit && lstSubscriptions.size() > 0 && lstSubscriptions[0].Id == null) insert lstSubscriptions;
		system.debug('***** lstSubs: '+lstSubscriptions);
		
		
		list<Subscription__c> lstSubscriptionsFinal = [SELECT Id, Account__r.Id, Account__r.OwnerId, Lead__r.Id, Support_PIN__c, StoreURL__c 
					FROM Subscription__c WHERE Id IN :lstSubscriptions];
		
		system.debug('***** subsFinal: '+lstSubscriptionsFinal);
		return lstSubscriptionsFinal;
	}

}