src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Indicates whether the account exists in MBA or BMP</description>
        <inlineHelpText>Indicates whether the account exists in MBA or BMP</inlineHelpText>
        <label>Provisioning System</label>
        <picklist>
            <picklistValues>
                <fullName>BMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Big_Brand__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this client/prospect a big brand?</description>
        <inlineHelpText>Is this client/prospect a big brand?</inlineHelpText>
        <label>Big Brand</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Client_Reference_Status__c</fullName>
        <description>What is the status of this store in our Client reference program?</description>
        <inlineHelpText>What is the status of this store in our Client reference program?</inlineHelpText>
        <label>Client Reference Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsTrial__c</fullName>
        <defaultValue>true</defaultValue>
        <description>MH - This field indicates whether the store associated with this opportunity was ever a trial</description>
        <inlineHelpText>MH - This field indicates whether the store associated with this opportunity was ever a trial</inlineHelpText>
        <label>IsTrial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is what MBA is sending</inlineHelpText>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MKT_Case_Study__c</fullName>
        <description>Do we have a case study on this store?</description>
        <inlineHelpText>Do we have a case study on this store?</inlineHelpText>
        <label>MKT Case Study</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MKT_Friendly__c</fullName>
        <description>Is this a &quot;Friendly&quot; client, as designated by marketing?</description>
        <inlineHelpText>Is this a &quot;Friendly&quot; client, as designated by marketing?</inlineHelpText>
        <label>MKT Friendly :)</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MKT_Showcase__c</fullName>
        <description>Is this store in our Marketing Showcase?</description>
        <inlineHelpText>Is this store in our Marketing Showcase?</inlineHelpText>
        <label>MKT Showcase</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MKT_Testimonial__c</fullName>
        <description>Is this store used in a marketing testimonial?</description>
        <inlineHelpText>Is this store used in a marketing testimonial?</inlineHelpText>
        <label>MKT Testimonial</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Former</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MostRecentSubscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Most recent subscription from the Lead mapping - irrelevant on the opp</description>
        <label>zMost Recent Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities (Most Recent Subscription)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent Opportunity for Upsells</description>
        <label>Parent Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Upsell Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchaseDate__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Purchase_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchase Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchase_Team__c</fullName>
        <label>Purchase Team</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Rep__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Revenue Rep</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Revenue_Team__c</fullName>
        <label>Revenue Team</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Indicates whether the account exists in MBA or BMP</description>
        <inlineHelpText>Indicates whether the account exists in MBA or BMP</inlineHelpText>
        <label>Provisioning System</label>
        <picklist>
            <picklistValues>
                <fullName>MBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubscriptionType__c</fullName>
        <label>Subscription Type</label>
        <picklist>
            <picklistValues>
                <fullName>Domain Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Store</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSL Certificate.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The subscription is not related to the account on the opportunity</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>The subscription is not related to the account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zuora_External_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This field holds the Zuora object ID, and is used as external ID for data synchronization between Salesforce and Zuora.</description>
        <externalId>true</externalId>
        <label>Zuora Sub External Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Trial</fullName>
        <active>true</active>
        <businessProcess>Sales Process %28Trial to Purchase%29</businessProcess>
        <description>Use when the client has created a trial store.</description>
        <label>Trial</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsTrial__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Value pushed from MBA and is used in a trigger to convert leads when it&apos;s unchecked. Can also be used to force the account rollups to recalculate</description>
        <inlineHelpText>Value pushed from MBA and is used in a trigger to convert leads when it&apos;s unchecked. Can also be used to force the account rollups to recalculate</inlineHelpText>
        <label>MBA Is Trial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <description>Unique identifier from MBA of account/user.  ID of the account which owns this subscription</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier from MBA of account/user.  ID of the account which owns this subscription</inlineHelpText>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <description>ID specific to the store/product purchased</description>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PurchaseDate__c</fullName>
        <description>From MBA.  Date when the sub became a paid plan</description>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Purchase_Rep__c</fullName>
        <description>Workflow captures owner name when when store upgrades</description>
        <inlineHelpText>Subscription owner at the time of purchase</inlineHelpText>
        <label>Purchase Rep</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Purchase_Team__c</fullName>
        <description>Workflow captures owner&apos;s team/departmetn when when store upgrades</description>
        <label>Purchase Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Rep__c</fullName>
        <description>Formula used in reporting to capture the rep to be paid for the upgrade based on ownership and upgrade fields</description>
        <formula>IF( OR(Purchase_Team__c = &quot;Partner Sales&quot;,Purchase_Team__c = &quot;Acquisition Sales&quot;, Purchase_Team__c = &quot;Partner Sales-AU/NZ&quot;), Owner:User.Full_Name__c ,
IF ( (MONTH( PurchaseDate__c ) = MONTH(TODAY()) ) &amp;&amp; YEAR(PurchaseDate__c ) = YEAR(TODAY() ) || (MONTH( PurchaseDate__c ) = MONTH( Last_Month_s_Date__c ))&amp;&amp; YEAR(PurchaseDate__c ) = YEAR(Last_Month_s_Date__c ), Owner:User.Full_Name__c ,
IF ( ISBLANK( Upgrade_Rep__c ) = FALSE &amp;&amp; NOT(ISPICKVAL( Upgrade_Stage__c ,&quot;New&quot;) &amp;&amp; NOT(ISPICKVAL( Upgrade_Stage__c ,&quot; &quot;))), Upgrade_Rep__r.Full_Name__c, NULL) )
)</formula>
        <label>Revenue Rep</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Revenue_Team__c</fullName>
        <description>Formula used in reporting to capture the team credited for the upgrade based on ownership and upgrade fields</description>
        <formula>IF( OR(Purchase_Team__c = &quot;Partner Sales&quot;,Purchase_Team__c = &quot;Acquisition Sales&quot;, Purchase_Team__c = &quot;Partner Sales-AU/NZ&quot;),Purchase_Team__c,
IF ( (MONTH( PurchaseDate__c ) = MONTH(TODAY()) ) &amp;&amp; YEAR(PurchaseDate__c ) = YEAR(TODAY() ) || (MONTH( PurchaseDate__c ) = MONTH( Last_Month_s_Date__c ))&amp;&amp; YEAR(PurchaseDate__c ) = YEAR(Last_Month_s_Date__c ), Owner:User.Department ,
IF ( ISBLANK( Upgrade_Rep__c ) = FALSE &amp;&amp; NOT(ISPICKVAL( Upgrade_Stage__c ,&quot;New&quot;) &amp;&amp; NOT(ISPICKVAL( Upgrade_Stage__c ,&quot; &quot;))), Upgrade_Rep__r.Department, NULL) )
)</formula>
        <label>Revenue Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Used in the partner portal apex code to designate when a sub was created via the portal rather than by MBA</description>
        <inlineHelpText>Used in the partner portal apex code to designate when a sub was created via the portal rather than by MBA</inlineHelpText>
        <label>UNDER REVIEW Source</label>
        <picklist>
            <picklistValues>
                <fullName>Direct Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRM Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acquisition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CreateopportunityController.cls
/**********************************************************************
Name:  Opportunity Controller
============================================================
 Purpose: Create Opportunities from Buttons using onclick js

1. Create Opportunity from Subscription.
2. Create Trial Opportunity from Account.
3. Create Upsell Opportunity from Store purchase opportunity.
============================================================
 
History:   
                                                      
VERSION AUTHOR   DATE       DETAIL     
 
1.0 Maggie Frederick 3/5/2014  Initial development
 
***********************************************************************/

public without sharing class CreateopportunityController {

    public database.saveresult [] result{get; set;}
    public ID theID;
 
 
  // creating Instance of OpportunityOperations Class.
      OpportunityOperations OppOperation = new OpportunityOperations(); 

    // Calling autorun method.
    public PageReference autoRun()
    {
        Id OppId;
        theId = ApexPages.currentPage().getParameters().get('id');
        system.debug('theId'+theId);
        Schema.SObjectType sobjectType = theId.getSObjectType();
		String sobjectName = sobjectType.getDescribe().getName();
		system.debug('my object'+sobjectname);
		if (sobjectName =='Account') //create trial opportunity
		{
			Opportunity newOpp = CreateTrialopportunity(theId);
			OppId = newOpp.Id;
		}
		else if (sobjectName =='Opportunity') //create upsell opportunity
		{
			 if (ApexPages.currentPage().getUrl().containsIgnoreCase ('CreateOpportunity'))
			 {
					Opportunity newOpp = CreateUpgradeOpportunity(theId);
					OppId = newOpp.Id;
					system.debug(OppId);
			 }
			 else
			 {
			 		Opportunity newOpp = CreatePSOpportunity(theId);
					OppId = newOpp.Id;
					system.debug(OppId);
			 }
		}
		
		else {
	    // List to collect All Subscription Id.
	        list<String> lstSubID = new list<String>();
	        lstSubID.add(theId);
	        system.debug('lstSubID'+lstSubID);
	        
	    // Calling Createopportunity method to perform further Operations.
	        Createopportunity(lstSubID);
	        for(Integer i=0;i<result.size();i++)
	        {
	            OppId=result[0].id;
	        }
	        system.debug(OppId);
		}
		
		if (OppId <> null)
		{
			PageReference newocp = new PageReference('/'+OppId);
	        newocp.setRedirect(true);
	        return newocp;
		}
	    else
	    {
	    	PageReference newocp = new PageReference('/'+theId);
	        newocp.setRedirect(true);
	        return newocp;
	    }
    }

    // Method to perform Opportunity Creation Operation.
    public void Createopportunity(List<String> lstSubId)
    {
    
//      Id StoreRecordTypeId = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_Recordtype_StorePurchase).getRecordTypeId();
    	
   // creating Instance of OpportunityOperations Class.
      OpportunityOperations OppOperation = new OpportunityOperations(); 

    //List to Hold Opportunity to be insert. 
        List<Opportunity> lstopp = new List<Opportunity>();
    // Set to hold All AccountId.   
        Set<Id> staccid = new Set<Id>();
        
        for(Subscription__c obj:[SELECT Account__c, Account__r.Name, Id,MBASubscriptionID__c, PurchaseDate__c, Purchase_Rep__c, Purchase_Team__c, Revenue_Rep__c, Revenue_Team__c, OwnerId 
        						 FROM Subscription__c WHERE Id IN:lstSubId])
        {   
            System.debug('Subscription object'+obj);
            if(obj.Account__c!= null)
            {
                staccid.add(obj.Account__c);
                Opportunity Opp = new Opportunity();
                Opp.Name= obj.Account__r.Name + ' - ' + obj.MBASubscriptionID__c;
                Opp.StageName = Label.Opportunity_Stage_Purchased;
//                Opp.RecordTypeId = StoreRecordTypeId;
                Opp.SubscriptionType__c = 'Store';
				Opp.pricebook2Id =Label.Sales_Pricebook;
                Opp.isTrial__c = false;
                Opp.AccountId = obj.Account__c;
                Opp.MostRecentSubscription__c=obj.Id;
                if (obj.Purchase_Rep__c <> null) Opp.Purchase_Rep__c = DLUtility.getuserbyName(obj.Purchase_Rep__c).Id;
                Opp.Purchase_Team__c = obj.Purchase_Team__c;
                if (obj.Revenue_Rep__c <> null) 
                {
                	Opp.Revenue_Rep__c = DLUtility.getuserbyName(obj.Revenue_Rep__c).Id;
                }
                else
                {
                	Opp.Revenue_Rep__c = obj.OwnerId;
                }
           
			    Opp.Revenue_Team__c = obj.Revenue_Team__c;
                if (obj.PurchaseDate__c <> null) Opp.CloseDate= obj.PurchaseDate__c;
                else Opp.CloseDate= Date.Today().addDays(30);
                lstopp.add(Opp);
            }
        }
        system.debug('lstopp'+lstopp);
        
    // Checking for empty.  
        if(!lstopp.isEmpty())
        {
            result=Database.insert(lstopp);
            system.debug(result);
        // Calling method to Perform Creation Of OpportunityContactRole.        
            OppOperation.createOpportunityContactRole(staccid,lstopp);
        }
        
    }   
    
 
   // Method to perform Upgrade Opportunity Creation Operation.
    public Opportunity CreateUpgradeOpportunity(Id OppId)
    {
       
       Opportunity Opp = new Opportunity();
       if(OppId != null)
       {     
			Id UpgradeRecordTypeId = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_Upgrade).getRecordTypeId();
			
	       String query = 'Select ';     
	       Map<String, Schema.SObjectField> objectFields = Schema.getGlobalDescribe().get('Opportunity').getDescribe().fields.getMap();
	
			// Grab the fields from the describe method and append them to the queryString one by one.
			for(String s : objectFields.keySet()) {
	   			query += ' ' + s + ', ';
			}
	
			// Manually add related object's fields that are needed.
			query += 'Account.Name from Opportunity where Id =\'' +OppId + '\''; // modify as needed
	        system.debug('***'+query);
	         
	        Opportunity o = database.query(query)  ;    
         
            Opp = o.clone(false, true,false, false);
            Opp.Name=  o.Name + ' - Upgrade';
            Opp.RecordTypeId = UpgradeRecordTypeId;
            Opp.pricebook2Id =Label.UpgradePricebook;
            Opp.OwnerId = UserInfo.getUserId();
            Opp.forecastCategoryName = 'Pipeline';
            Opp.Revenue_Rep__c = UserInfo.getUserId();
            Opp.Revenue_Team__c = DLUtility.getuserbyName(UserInfo.getName()).Department;
            Opp.isTrial__c = false;
            Opp.StageName = 'Qualify';
            Opp.Amount = 0.00;
            Opp.ParentOpportunity__c = o.Id;
            Opp.MKT_Friendly__c = null;
            Opp.MKT_Case_Study__c = null;
            Opp.MKT_Showcase__c = null;
            Opp.MKT_Testimonial__c = null;
            Opp.Client_Reference_Status__c = null;
            Opp.Big_Brand__c = null;
            Opp.Zuora_External_Id__c = null;
             
            Opp.CloseDate=Date.today().addDays(30);
            insert Opp;
		 
        }
        
        return Opp;
    }   
    
	// Method to perform Trial Opportunity Creation Operation.
    public Opportunity CreateTrialopportunity(Id accId)
    {
    
 		Id TrialRecordTypeId = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_Trial).getRecordTypeId();
        //List to Hold Opportunity to be insert. 
        List<Opportunity> lstopp = new List<Opportunity>();
     	// Set to hold All AccountId.   
        Set<Id> staccid = new Set<Id>();
         
        Account obj= [SELECT Id, name, MBAAccountID__c, Source__c 
        						 FROM Account WHERE Id =:accId];
        Opportunity Opp = new Opportunity();
            
            if(obj!= null)
            {
                staccid.add(obj.Id);
                Opp.Name= obj.Name ;
                Opp.RecordTypeId = TrialRecordTypeId;
                If (obj.Source__c == 'BMP')
                {Opp.pricebook2Id = Label.Zuora_Base_Products_Pricebook;}
                else 
                {Opp.pricebook2Id =Label.Sales_Pricebook;}
                Opp.isTrial__c = true;
                Opp.StageName = 'Prospect';
                Opp.CloseDate=system.today();
                Opp.AccountId = obj.Id;
                Opp.MBAAccountId__c = obj.MBAAccountId__C;
				lstopp.add(Opp);
            	
            }
            
           // Checking for empty.  
        if(!lstopp.isEmpty())
        {
          	result=Database.insert(lstopp);
            	system.debug(result);
         // Calling method to Perform Creation Of OpportunityContactRole.        
            OppOperation.createOpportunityContactRole(staccid,lstopp);
         }
        
        return Opp;
    } 
	// Method to perform PS Opportunity Creation Operation.
    public Opportunity CreatePSOpportunity(Id oppId)
    {
     //create an opportunity
      
        Opportunity opp = OpportunityHelper.createOppProfFromOpp(oppId);
        
        return Opp;
    } 

 
}