src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner source - for use in determining source of client account.</description>
        <inlineHelpText>Partner source - for use in determining source of client account.</inlineHelpText>
        <label>zPAR Partner Source</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>zOLD State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>9/6/12 - changed field label from Partner Account to Partner Source to distinguish this field used by the Partner team from the Design Partner used by Conversion Sales. Left Field Name the same to keep API integrity. jw</description>
        <inlineHelpText>Designates if a partner of BigCommerce brought this lead to us</inlineHelpText>
        <label>z PAR Partner Source</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestLeadShareTrigger.cls
@isTest
private class TestLeadShareTrigger {

    static testMethod void LeadShareTrigger() {
        
        Account acc1 = new Account();
        acc1.Name = 'TestAccount1';
        insert acc1;
        
        Contact con = new Contact(LastName='Test Name', AccountId=acc1.Id);
        insert con;

        Id partnerProfileId = '00e30000001UPDe';
        
        User u = new User();
        u.FirstName = 'Test fn';
        u.LAstName = 'Test ln';
        u.ContactId = con.Id;
        //u.AccountId = acc1.Id;
         u.email = 'test@gmail.com';
         u.username='testmail@gmail.com';
         u.profileId = partnerProfileId;
         u.alias = 'tst';
         u.TimeZoneSidKey = '(GMT-05:00) Central Daylight Time (America/Mexico_City)';
         u.LocaleSidKey = 'English (United States)';
         u.EmailEncodingKey = 'General US & Western Europe (ISO-8859-1, ISO-LATIN-1)';
         u.LanguageLocaleKey = 'English';
        //insert u;
        
        Account acc2 = new Account();
        acc2.Name = 'TestAccount2';
        acc2.State__c = 'Pending';
        insert acc2;
        
        Lead newLead = new Lead();
        newLead.LastName = 'Test';
        newLead.Company = 'Arxxus'; 
        newLead.Status = 'Open';
        newLead.Partner_Account__c = acc1.id;
        insert newLead;
        newLead.Partner_Account__c = acc2.id;
        update newLead;
        newLead.Partner_Account__c = null ;
        update newLead;
    }
}