src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MBAHostingID__c</fullName>
        <description>The ID of this record in MyBigAccount</description>
        <label>zOLD MBAHostingID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Migration_Partner__c</fullName>
        <description>Migrations : The Channel or SBD Partner from whom the Migration Request is sourced.</description>
        <inlineHelpText>Who is the Channel or SBD Partner from whom the Migration Request is sourced?</inlineHelpText>
        <label>Migration Partner</label>
        <picklist>
            <picklistValues>
                <fullName>EIG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portable Studios</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Migration_Platform__c</fullName>
        <description>Migrations : picklist</description>
        <label>Migration Platform</label>
        <picklist>
            <picklistValues>
                <fullName>1Shopping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3dCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AceShop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon Webstore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon Webstores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AspDotNetSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ayacart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bigcommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ChannelAdvisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CoreCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CreateAShoppe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRE Loaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CubeCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>digiSHOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBAY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoDaddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HHG multistore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interspire (standard SOW)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JooCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LemonStand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lemon Stand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaded Commerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaded Commerce (CRELoaded/OSCommerce)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magento Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magento Go</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mal&apos;s eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MijoShop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miva Merchant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>of_Products__c</fullName>
        <description>Migrations : The number of products that currently exist in the Client&apos;s current store</description>
        <inlineHelpText>How many products does the Client have in their current store?</inlineHelpText>
        <label>z# of Products</label>
        <picklist>
            <picklistValues>
                <fullName>&lt;500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>501 - 5k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5k - 10k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10k - 30k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30k - 50k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>50k - 75k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>75k - 100k</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;100k</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Migration</fullName>
        <active>true</active>
        <businessProcess>Migration Case Process</businessProcess>
        <description>Used by Sales to request store migrations</description>
        <label>Migration</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/CaseToJiraTest.cls
@isTest(seeAllData=true) 
public class CaseToJiraTest{
    public static testmethod void testJiraCallout() {
 //       SingleRequestMock fakeResponse = new SingleRequestMock(200,
   //                                              'Complete',
    //                                             '[{"Name": "sForceTest1"}]',
    //                                             null);
        SingleRequestMock fakeResponse = new SingleRequestMock(200, 'Complete','[Status=OK, StatusCode=200]',null);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
 
 // create test data       
        Account a = new Account();
        a.Name = 'Test Account';
        a.MBAHostingID__c = '341726';
        insert a;
        
        Id migRecordType =  Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Migration').getRecordTypeId();
    
        Case c = new Case();
        c.AccountId = a.Id;
        c.Status = 'New';
        c.Origin = 'Email';
        c.RecordTypeId = migRecordType;
        c.of_Products__c = '<500';
        c.Migration_Platform__c  ='Test';
        c.Subject='Testing new case';
        c.Migration_Partner__c = 'EIG';
        
        insert c;
        String objectId = c.id;
        String jiraType = 'Jira for EIG';   
                             
         //Execute the callout
        JIRAConnectorWebserviceCallout.createIssue(jiraType, objectId);
        JIRAConnectorWebserviceCallout.syncIssue(jiraType, objectId);
 //       System.assertEquals(/*check for expected results here...*/);
    }
}