src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner source - for use in determining source of client account.</description>
        <inlineHelpText>Partner source - for use in determining source of client account.</inlineHelpText>
        <label>zPAR Partner Source</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <description>Revenue share field used by finance and bizdev</description>
        <label>zPayment Method</label>
        <picklist>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EFT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Client_Record_Type</fullName>
        <active>true</active>
        <description>Bigcommerce Clients</description>
        <label>Client Record Type</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Invoice_Transaction__c.object
<CustomObject>
    <description>To record all financial transactions with BigCommerce customers, such as invoice payments and refunds.</description>
    <fields>
        <fullName>Date_Paid__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The date that the payment was made</inlineHelpText>
        <label>Date Paid</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>Descriptive name of the invoice product, including the date range the payment applies to</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <inlineHelpText>The number of payment terms that this payment applies to.  For example, if the customer is paying for an annual plan, the term would be 12.</inlineHelpText>
        <label>Payment Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Transaction</label>
    <nameField>
        <displayFormat>TRAN-{0000000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>rvpe__RVAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RV Account</label>
        <referenceTo>rvpe__RVAccount__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Store_Purchase</fullName>
        <active>true</active>
        <businessProcess>Sales Process %28Trial to Purchase%29</businessProcess>
        <description>Use when the trial becomes a store.</description>
        <label>Store Purchase</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Commission_Payment__c.object
<CustomObject>
    <description>For BAP-3698 - Partner Commissions v2

Records the payments made out to our referral partners for their commissions</description>
    <fields>
        <fullName>Custom_Note__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>Notes for the transaction</inlineHelpText>
        <label>Custom Note</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>Description of the payment</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fee__c</fullName>
        <description>For BAP-3698 - Partner Commission v2</description>
        <inlineHelpText>Fees associated with the transaction</inlineHelpText>
        <label>Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>Message attached to the transaction</inlineHelpText>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The partner (RV Account) that this payment was issued to</inlineHelpText>
        <label>Partner Account</label>
        <referenceTo>rvpe__RVAccount__c</referenceTo>
        <relationshipLabel>Partner Commission Payments</relationshipLabel>
        <relationshipName>Partner_Commission_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The amount paid to the partner</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>Date that the payment was issued to the partner</inlineHelpText>
        <label>Payment Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The method of payment to the partner</inlineHelpText>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>PayPal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reason_Code__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>Reason code returned from the bank</inlineHelpText>
        <label>Reason Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recipient__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The email of the recipient at the time of the payment.  May not necessarily match the RV Account&apos;s paypal Id if it has changed over time.</inlineHelpText>
        <label>Recipient</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Partner Commission Payment</label>
    <nameField>
        <displayFormat>PCP-{00000}</displayFormat>
        <label>Partner Commission Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Commission_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Partner Commissions  functionality.
When making a change to the start date, make sure to also change the Partner Commission Payment rollup on RV Account so that the numbers can be calculated properly.  The date there should reflect one month after the date on this custom setting.</description>
    <fields>
        <fullName>Earliest_Possible_Start_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>If the start date is left blank on a partner commission run, this is the earliest BI Data to pull in</inlineHelpText>
        <label>Earliest Possible Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Day_of_Bill_Cycle__c</fullName>
        <description>For BAP-3698 - Partner Commission v2</description>
        <inlineHelpText>Indicates the day of the month we should consider as the start of a new bill cycle.  If the number is greater than the number of days in the month, the first day of the following month will be used.</inlineHelpText>
        <label>First Day of Bill Cycle</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Commission Settings</label>
</CustomObject>

src/objects/Partner_Commission_Summary__c.object
<CustomObject>
    <description>Roles up all customer payments to a reselling partner and calculates the earned commission</description>
    <fields>
        <fullName>Commissionable_Revenue__c</fullName>
        <description>For BAP-3698 - Partner Commission v2</description>
        <inlineHelpText>Net transactions that can be used to pay out commissions</inlineHelpText>
        <label>Commissionable Revenue</label>
        <summarizedField>Partner_Commission_Invoice_Transaction__c.Accrued_Transaction_Amount__c</summarizedField>
        <summaryForeignKey>Partner_Commission_Invoice_Transaction__c.Partner_Commission_Summary__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The latest payment date that can be used to collect payment data for this partner</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The Partner Account (RV Account) that this Partner Commission is tied to.</inlineHelpText>
        <label>Partner Account</label>
        <referenceTo>rvpe__RVAccount__c</referenceTo>
        <relationshipLabel>Partner Commission Summaries</relationshipLabel>
        <relationshipName>Partner_Commission_Summaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner_Commission_Earned__c</fullName>
        <description>For BAP-3698 - Partner Commission v2</description>
        <inlineHelpText>Total commissions earned in this summary</inlineHelpText>
        <label>Partner Commission Earned</label>
        <summarizedField>Partner_Commission_Invoice_Transaction__c.Partner_Commission_Earned__c</summarizedField>
        <summaryForeignKey>Partner_Commission_Invoice_Transaction__c.Partner_Commission_Summary__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The earliest customer payment date to include when calculating this partner&apos;s commissions</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Partner Commission Summary</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Partner Commission Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Commission Summaries</pluralLabel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <description>For partner commissions that have been marked as being paid</description>
        <label>Closed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Open</fullName>
        <active>true</active>
        <description>This partner commission summary has not yet been closed out</description>
        <label>Open</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestPartnerCommissions.cls
@isTest
private class TestPartnerCommissions {
	private static List<Account> testAccounts;
	private static List<Opportunity> testOpportunities;
	private static List<Invoice_Transaction__c> testInvoiceTransactions;
	private static List<rvpe__RVAccount__c> testRVAccounts;

	/**
	 * Creates test data for testing the partner commission batches
	 * @author Steve O'Neal
	 * @date   2016-07-01
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
	 */
	private static void SetupTestData()
	{
		// create instance of partner commission settings
		Partner_Commission_Settings__c pcs = Partner_Commission_Settings__c.getInstance();
		if (pcs == null || pcs.First_Day_of_Bill_Cycle__c == null || pcs.Earliest_Possible_Start_Date__c == null)
		{
			pcs = new Partner_Commission_Settings__c();
			pcs.First_Day_of_Bill_Cycle__c = 1;
			pcs.Earliest_Possible_Start_Date__c = Date.newInstance(2013, 1, 1);
			insert pcs;
		}

		testRVAccounts = TestDataFactory.createTestRVAccounts(4);

		testAccounts = TestDataFactory.createTestAccounts(4, false, TestDataFactory.AccountRecordType.Client_Record_Type);

		testOpportunities = TestDataFactory.createTestOpportunities(1, testAccounts, TestDataFactory.OpportunityRecordType.Store_Purchase);
		
		// give credit to the RV Accounts for the opportunities
		for (Opportunity opp : testOpportunities)
		{
			// randomly assign an rv account
			opp.rvpe__RVAccount__c = testRVAccounts[MathUtility.RandomInteger(0,testRVAccounts.size()-1)].Id;
		}
		update testOpportunities;

		// add payments from customers
		testInvoiceTransactions = TestDataFactory.createTestInvoiceTransactions(20, testOpportunities);
		// test bad data for trigger InvoiceTransactionTrigger
		testInvoiceTransactions[0].Payment_Term__c = 0;
		testInvoiceTransactions[1].Date_Paid__c = null;
		update testInvoiceTransactions;

	}

	/**
	 * Tests the BatchPartnerCommissionCleanupScheduler
	 * @author Steve O'Neal
	 * @date   2016-07-02
	 * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
	 * @return Nothing
	 */
	@isTest static void testScheduler() {
		Test.startTest(); 
		BatchPartnerCommissionCleanupScheduler schedJob = new BatchPartnerCommissionCleanupScheduler(); 
		String schedule = '0 0 23 * * ?'; 
		system.schedule('Test Batch Partner Commission Cleanup Scheduler', schedule, schedJob); 
		Test.stopTest();

	}
	

	/**
	 * Tests all of the Partner Commission batch jobs
	 * @author Steve O'Neal
	 * @date   2016-07-05
	 * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
	 * @return Nothing
	 */
	@isTest static void testBatchPartnerCommission() {
		SetupTestData();
        Test.startTest(); 
		
		BatchPartnerCommissionCreateSummaries bpccs = new BatchPartnerCommissionCreateSummaries();
		bpccs.targetPartnerAccounts = testRVAccounts;
		bpccs.ProcessEveryMonthUntilToday = false;
		bpccs.CreateDetailsWhenFinished = false;
		bpccs.startDate = Date.newInstance(1990,1,1);
		// run last month's and this month's batch for maximum coverage
		bpccs.endDate = Date.newInstance(Date.today().year(), Date.today().month(), 1).addDays(-1);
		Database.executeBatch(bpccs);
		
		bpccs.endDate = Date.newInstance(Date.today().year(), Date.today().month(), 1).addMonths(1).addDays(-1);
		// test BatchPartnerCommissionCreateDetails and BatchPartnerCommissionCreateHistory as well
		bpccs.CreateDetailsWhenFinished = true;
		Database.executeBatch(bpccs);



		// test BatchPartnerCommissionCleanup
		BatchPartnerCommissionCleanup bpcc = new BatchPartnerCommissionCleanup();
		string query = '';
		bpcc.CurrentAction = BatchPartnerCommissionCleanup.BatchCleanupAction.deleteAllOpenSummaries;
		query = bpcc.buildQuery();
		bpcc.query = null;
		bpcc.CurrentAction = BatchPartnerCommissionCleanup.BatchCleanupAction.deleteAllZeroDollarSummaries;
		query = bpcc.buildQuery();
		bpcc.query = null;
		bpcc.CurrentAction = BatchPartnerCommissionCleanup.BatchCleanupAction.closeAllOpenPastSummaries;
		query = bpcc.buildQuery();
		bpcc.query = null;
		bpcc.CurrentAction = BatchPartnerCommissionCleanup.BatchCleanupAction.closeAllOpenSummaries;
		query = bpcc.buildQuery();
		bpcc.query = null;



		// add partner payment information based on the closed summary data
		List<Partner_Commission_Summary__c> pcSummaries = [Select Id, Name, RecordTypeId, Commissionable_Revenue__c, Start_Date__c, End_Date__c, Partner_Account__c, Partner_Commission_Earned__c from Partner_Commission_Summary__c where RecordTypeId =: PartnerCommissionSummaryTriggerHandler.ClosedRecordType.Id];
		List<Partner_Commission_Payment__c> pcPayments = new List<Partner_Commission_Payment__c>();
		for (Partner_Commission_Summary__c pcSummary : pcSummaries)
		{
        	String seed1 = String.valueof(MathUtility.RandomInteger(10000, 99999));

			Partner_Commission_Payment__c pcPayment = new Partner_Commission_Payment__c();
			pcPayment.Payment_Amount__c = pcSummary.Partner_Commission_Earned__c;
			pcPayment.Custom_Note__c = 'Test Data';
			pcPayment.Description__c = pcPayment.Custom_Note__c;
			pcPayment.Fee__c = 0;
			pcPayment.Message__c = pcPayment.Custom_Note__c;
			pcPayment.Partner_Account__c = pcSummary.Partner_Account__c;
			pcPayment.Payment_Date__c = Date.today().addDays(-4);
			pcPayment.Payment_Method__c = 'PayPal';
			pcPayment.Reason_Code__c = '';
			pcPayment.Recipient__c = 'me@bigcommerce.com';
			pcPayment.Status__c = 'Completed';
			pcPayment.Transaction_ID__c = seed1;

			pcPayments.add(pcPayment);
		}
		insert pcPayments;


		// execute the batch for closing all open summaries
		bpcc.CurrentAction = BatchPartnerCommissionCleanup.BatchCleanupAction.closeAllOpenSummaries;
		bpcc.query = null;
		bpcc.CreateSummariesWhenFinished = true;
		Database.executeBatch(bpcc);

		BatchPartnerCommissionCreateHistory  bpch = new BatchPartnerCommissionCreateHistory();
		Database.executeBatch(bpch);

		// delete all the Partner Commission objects
		bpcc.CurrentAction = BatchPartnerCommissionCleanup.BatchCleanupAction.deleteAllSummaries;
		bpcc.query = null;
		Database.executeBatch(bpcc);
		
    	Test.stopTest();

	}


	/**
	 * Tests the logic of the PartnerCommissionToolsController
	 * @author Steve O'Neal
	 * @date   2016-07-05
	 * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
	 * @return Nothing
	 */
	@isTest static void testToolsPageController()
	{
		SetupTestData();
        Test.startTest();

        PageReference testPageRef = Page.PartnerCommissionTools;
        Test.setCurrentPage(testPageRef);

        PartnerCommissionToolsController pctc = new PartnerCommissionToolsController();
        pctc.RefreshPageData();
        pctc.GetPartnerCommissionSummaryHistory();
        PartnerCommissionToolsController.BatchMonitor testBatchStatus = pctc.getBatchStatus();
        testBatchStatus.getNumberOfRecords();
        testBatchStatus.getNumberOfRecordsProcessed();
        testBatchStatus.NumberOfBatches = 0;
        testBatchStatus.getProgressPercent();
        testBatchStatus.NumberOfBatches = 10;
        testBatchStatus.getProgressPercent();

        DateTime tmpDate = testBatchStatus.CreatedDate;

        Test.stopTest();
	}

}