src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field used to associate cases to leads</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product of the Subscription associated with this case.</description>
        <formula>IF( ISBLANK( Opportunity__c ) = FALSE, Opportunity__r.Product__c, 
IF( ISBLANK( Subscription__c ) = FALSE, Subscription__r.Product__c , 
NULL))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Product of the Subscription associated with this case.</inlineHelpText>
        <label>Product Plan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the store this case is in reference to</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>From MBA saying which plan/trial the store is on</description>
        <inlineHelpText>From MBA saying which plan/trial the store is on</inlineHelpText>
        <label>MBA Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StoreName__c</fullName>
        <description>Field originally designed to be populated by the MBA sync but only used to capture the old lead date prior to the hierarchy project.  Can probably be deleted</description>
        <label>zStore Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StoreURL__c</fullName>
        <description>URL of the BC trial or store populated by MBA</description>
        <inlineHelpText>URL of the BC trial or store populated by MBA</inlineHelpText>
        <label>MBA Store URL</label>
        <type>Url</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SubsForConsole_Controller.cls
public without sharing class SubsForConsole_Controller 
{	
	private String objectType = '';
    private String acctId = '';
    private String contactId = '';
    private String leadId = '';
    private String leadName = '';
    private Id selectedSubId = null;
    private string selectedSubName = null;
    private list<SubscriptionWrapper> Subs = new list<SubscriptionWrapper>();
        
    public static map<String, Schema.RecordTypeInfo> mpCSRTByName = Case.getSObjectType().getDescribe().getRecordTypeInfosByName();
    
    public String passedInSubId {get;set;}
    
    public String getObjectType()
    {
        return objectType;
    }
    
    public void setAcctId(String n)
    {
        acctId = n;
    }
    
    public String getAcctId()
    {
        return acctId;
    }
    
    public void setContactId(String n)
    {
        contactId = n;
    }
    
    public String getContactId()
    {
        return contactId;
    }
    
    public String getLeadId()
    {
        return leadId;
    }
    
    public String getLeadName()
    {
        return leadName;
    }
    
    public String contactPrefix
    {
    	get
    	{
    		return Contact.sObjectType.getDescribe().getKeyPrefix();
    	}
    }
    
    public String accountPrefix
    {
    	get
    	{
    		return Account.sObjectType.getDescribe().getKeyPrefix();
    	}
    }
    
     public String leadPrefix
    {
    	get
    	{
    		return Lead.sObjectType.getDescribe().getKeyPrefix();
    	}
    }
    
    // Generate the URL to open the new subtab in
    public String caseCreateURLPrefix
    {
        get
        {
            if(caseCreateURLPrefix == null)
            {                
                // Prefix to create the case (/500/e)
                PageReference pageRef = new PageReference('/' + Case.sObjectType.getDescribe().getKeyPrefix() + '/e');
                pageRef.getParameters().put('isdtp','vw');
                pageRef.getParameters().put('ent', Case.sObjectType.getDescribe().getName());
                
                caseCreateURLPrefix = pageRef.getURL();             
            }
            system.debug('***SubsForConsole_Controller:caseCreateURLPrefix - caseCreateURLPrefix: ' + caseCreateURLPrefix);
            
            return caseCreateURLPrefix;
        }
        private set;
    }
    
    public String getSelectedSubName()
    {
    	return selectedSubName;
    }
    
    public Id getSelectedSubId()
    {
    	return selectedSubId;
    }
    
    public list<CaseRTWrapper> lstCaseRTWraps
    {
        get
        {
            list<CaseRTWrapper> lstOpt = new list<CaseRTWrapper>();
            CaseRTWrapper cw;           
            
            for (string s : mpCSRTByName.keySet())
            {
                system.debug('@@@ Case RT Name: ' + s);
                
                if (mpCSRTByName.get(s).isAvailable() && s != 'Master')
                {
                    system.debug('@@@ Case RT Name Available: ' + s);
                    system.debug('@@@ Case RT ID Available: ' + string.valueOf(mpCSRTByName.get(s).getRecordTypeId()));
                    
                    cw = new CaseRTWrapper();
                    cw.RTID = string.valueOf(mpCSRTByName.get(s).getRecordTypeId());
                    cw.RTName = s;
                    lstOpt.add(cw);
                }
            }
            
            return lstOpt;
        }
    }
    
    public list<SelectOption> lstCaseRTs
    {
        get
        {
            list<SelectOption> lstOpt = new list<SelectOption>();
            lstOpt.add(new SelectOption('', 'Case Type'));
            
            for (string s : mpCSRTByName.keySet())
            {
                if (mpCSRTByName.get(s).isAvailable() && s != 'Master')
                {
                    lstOpt.add(new SelectOption(mpCSRTByName.get(s).getRecordTypeId(), s));
                }
            }
            
            return lstOpt;
        }
    }
    
    public list<SubscriptionWrapper> getSubs()
    {
        return Subs;
    }
    
    public SubsForConsole_Controller()
    {
    	string recId = ApexPages.currentPage().getParameters().get('Id');
    	acctId = '';
    	contactId = '';
    	leadId = '';
    	objectType = '';
    	
    	// Check which object this page is loading from
    	if (recId != null)
    	{
    		if (recId.startsWith(accountPrefix))
	    	{ 
	    		acctId = recId;
	    		objectType = 'Account';  		
	    	}
	    	else if (recId.startsWith(contactPrefix))
	    	{
	    		contactId = recId;
	    		objectType = 'Contact';
	    		
	    		acctId = [SELECT AccountId FROM Contact WHERE Id = :contactId].AccountId;
	    	}
	    	else if (recId.startsWith(leadPrefix))
	    	{	    		
	    		leadId = recId;
	    		leadName = [SELECT Name FROM Lead WHERE Id = :leadId].Name;
	    		objectType = 'Lead';
	    	}
    	}
    	
    	system.debug('@@@AcctId: ' + acctId);
    	system.debug('@@@ContactId: ' + contactId);
    	system.debug('@@@LeadId: ' + leadId);
    }
    
    public PageReference LoadSubscriptions()
    {
        system.debug('***SubsForConsole_Controller:LoadSubs - Start');       
        
        list<Subscription__c> lstSubs = new list<Subscription__c>();
        Subs = new list<SubscriptionWrapper>();
		SubscriptionWrapper wrapSub;
		
        system.debug('***SubsForConsole_Controller:LoadSubs - acctId: ' + acctId);
        system.debug('***SubsForConsole_Controller:LoadSubs - leadId: ' + leadId);
        
        // If either a Lead or Account Id exist
        if ((leadId != null && leadId != '') || (acctId != null && acctId != ''))
        {        	
        	if (leadId != null && leadId != '')
        	{
				lstSubs = [SELECT Id, Name, StoreName__c, StoreURL__c, Product__c, Status__c, Account__c, Lead__c
	                        FROM Subscription__c
	                        WHERE RecordTypeId = :Subscription__c.getSObjectType().getDescribe().getRecordTypeInfosByName().get('MBA Subscription').getRecordTypeId()
	                            AND Lead__c = :leadId];
        	}
        	else if (acctId != null && acctId != '')
        	{
        		lstSubs = [SELECT Id, Name, StoreName__c, StoreURL__c, Product__c, Status__c, Account__c, Lead__c
	                        FROM Subscription__c
	                        WHERE RecordTypeId = :Subscription__c.getSObjectType().getDescribe().getRecordTypeInfosByName().get('MBA Subscription').getRecordTypeId()
	                            AND Account__c = :acctId];
        	}
        	
            for (Subscription__c s : lstSubs)
			{
				wrapSub = new SubscriptionWrapper(s, false);
				Subs.add(wrapSub);
			}
        }
        
        return null;
    }
    
    public void CaptureSub()
	{
		//id subId = ApexPages.currentPage().getParameters().get('passedInId');
		
		system.debug('***SubsForConsole_Controller.CaptureSub - passedInId: ' + passedInSubId);
    	
    	if (passedInSubId != null)
    	{
    		// Set the selected sub variable
    		for (SubscriptionWrapper wrap : Subs)
	    	{	    			    
	    		if (wrap.objSub.Id != passedInSubId)
	    		{
					wrap.isSelected = false;
	    		}
	    		else
	    		{

	    			wrap.isSelected = true;
	    			
    				selectedSubId = wrap.objSub.Id;
    				selectedSubName = wrap.objSub.Name;
	    		}
	    	}
    	} 
	}
    
   	public void SelectSub()
    {
    	id subId = ApexPages.currentPage().getParameters().get('selId');
    	
    	system.debug('***SubsForConsole_Controller.SelectSub - subId: ' + subId);
    	
    	if (subId != null)
    	{
    		// Set the selected sub variable
    		for (SubscriptionWrapper wrap : Subs)
	    	{	    			    
	    		if (wrap.objSub.Id != subId)
	    		{
					wrap.isSelected = false;
	    		}
	    		else
	    		{
	    			// If the sub has just been selected the set the selected sub variable to the sub id, otherwise clear it
	    			if (wrap.isSelected)
	    			{
	    				selectedSubId = wrap.objSub.Id;
	    				selectedSubName = wrap.objSub.Name;
	    			}
	    			else
	    			{
	    				selectedSubId = null;
	    				selectedSubName = null;
	    			}
	    		}
	    		//system.debug('***SubsForConsole_Controller.SelectSub - wrap Sub: ' + wrap.objSub);
	    		//system.debug('***SubsForConsole_Controller.SelectSub - wrap Selected: ' + wrap.isSelected);
	    	}
    	}    	
    }
    
    public class SubscriptionWrapper
    {
    	public boolean isSelected {get; set;} 
    	public Subscription__c objSub {get; set;}  
    	
    	public SubscriptionWrapper (Subscription__c sub, boolean selected)
    	{
    		this.isSelected = selected;
    		this.objSub = sub;
    	}
    }
    
    public class CaseRTWrapper
    {
        public string RTID {get; set;}
        public string RTName {get; set;}       
        
        public CaseRTWrapper ()
        {
        }
    }
}