src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Valid_Activity_By__c</fullName>
        <description>Last valid Activity by Account Owner</description>
        <label>Valid Activity By Owner</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_Activity_Date__c</fullName>
        <description>Last date of valid activity  - call, email</description>
        <label>Valid Activity Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Activity.object
<CustomObject>
    <fields>
        <fullName>ToutApp__Tout_Replied__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether Tout detected a response to this email.</description>
        <label>Tout Replied</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TaskHandler.cls
public class TaskHandler {
	
	public static void validActivityUpdate(List<Task> lstTasks)
	{
		Set<String> setCallResult = new Set<String>{'correct contact','contact','set callback', 'Success'};
        Set<String> lstAccIds = new Set<String>();  
 //       List<Account> updAcc = new List<Account>();
        Map<Id, Account> mapUpdAccts = new Map<Id, Account>();
		
		for (Task t :lstTasks)
		{
			lstAccIds.add(t.AccountId);
		}

		Map<Id, Account> mapAccounts = new Map<Id, Account>([Select Id, Owner.Name, OwnerId, Valid_Activity_Date__c, Valid_Activity_By__c from Account where Id in :lstAccIds]);
		
		Boolean updValidActivity = false;
		
		for (Task obj :lstTasks)
		{
		  
		  if (mapAccounts.get(obj.AccountId) <> null)
		  {	
			Account acc = mapAccounts.get(obj.AccountId);
			if ( acc.Valid_Activity_Date__c == null  ||
			    ( acc.Valid_Activity_Date__c <> null && obj.ActivityDate > acc.Valid_Activity_Date__c))
//			system.debug('test '+acc.Id);
			{
				Id AccOwner = acc.OwnerId;
	            if(obj.OwnerId == AccOwner && obj.Subject!=null && obj.Type.equalsIgnoreCase('Email') && (obj.Subject.startsWith('←') || obj.ToutApp__Tout_Replied__c == true ))
	            {
	                updValidActivity = true;
	            }
	             
	            if(obj.OwnerId == AccOwner && obj.Type!=null && obj.Type.equalsIgnoreCase('Call') && obj.CallDisposition!=null && setCallResult.contains(obj.CallDisposition.toLowerCase()))
	            {   
	                updValidActivity = true;
	            }  
	            
	            if (updValidActivity == true)
	            {
	             	acc.Valid_Activity_By__c =acc.Owner.Name;
	            	acc.Valid_Activity_Date__c = obj.ActivityDate;
	            	system.debug(' activity date' +obj.ActivityDate);
	   		 		
	             	if (mapUpdAccts.containsKey(acc.Id)) 
	            	 { 
	            	 	
	            	 	if (obj.ActivityDate > acc.Valid_Activity_Date__c)
	            	 	{
	             	 		system.debug(' latest activity date' +obj.ActivityDate);
	            	 		mapUpdAccts.put(acc.Id, acc);
	            	 	}
	                 }
	            	 else
	            	 {	system.debug(' adding'+obj.ActivityDate);
	            	     mapUpdAccts.put(acc.Id, acc);
	            	 }
	            }
		 	 }
		  }
		}
		
		update mapUpdAccts.Values();
	}

}