src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date of the client&apos;s first store purchase with Bigcommerce</description>
        <inlineHelpText>Date of the client&apos;s first store purchase with Bigcommerce</inlineHelpText>
        <label>Client Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Indicates whether the account exists in MBA or BMP</description>
        <inlineHelpText>Indicates whether the account exists in MBA or BMP</inlineHelpText>
        <label>Provisioning System</label>
        <picklist>
            <picklistValues>
                <fullName>BMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SupportPin__c</fullName>
        <label>Support Pin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Source__c</fullName>
        <description>Indicates whether the account exists in MBA or BMP</description>
        <inlineHelpText>Indicates whether the account exists in MBA or BMP</inlineHelpText>
        <label>Provisioning System</label>
        <picklist>
            <picklistValues>
                <fullName>BMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Old - was used by Acq when they worked contacts but can probably be removed.  hass would know for sure</description>
        <label>zStage</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type is set from BMP on the contact.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner RV Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>SupportPin__c</fullName>
        <inlineHelpText>MBA account pin used to verify account access for cases</inlineHelpText>
        <label>zSupport Pin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Lead type. No default set.</description>
        <inlineHelpText>Lead type. No default set.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal/BC Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer/Dev Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Target (DM)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>ProductType__c</fullName>
        <description>From MBA to distinguish stores from SSLs and Domains</description>
        <inlineHelpText>Type of product (store, SSL, domain, etc)</inlineHelpText>
        <label>MBA Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Store</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Domain Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSL Certificate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purchase_Team__c</fullName>
        <description>Workflow captures owner&apos;s team/departmetn when when store upgrades</description>
        <label>Purchase Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Used in the partner portal apex code to designate when a sub was created via the portal rather than by MBA</description>
        <inlineHelpText>Used in the partner portal apex code to designate when a sub was created via the portal rather than by MBA</inlineHelpText>
        <label>UNDER REVIEW Source</label>
        <picklist>
            <picklistValues>
                <fullName>Direct Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRM Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acquisition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StoreURL__c</fullName>
        <description>URL of the BC trial or store populated by MBA</description>
        <inlineHelpText>URL of the BC trial or store populated by MBA</inlineHelpText>
        <label>MBA Store URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Used to differentiate store plans from SSL &amp; Domain products.  Pushed by MBA</description>
        <label>MBA Type</label>
        <picklist>
            <picklistValues>
                <fullName>New Store</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Plan Upgrade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Upgrade_Stage__c</fullName>
        <description>Updated by team leads once they verify that the upgrade rep really caused the upgrade.  Used in Revenue Rep formula</description>
        <label>Upgrade Stage</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pipeline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Won</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Totango_Engagement__c.object
<CustomObject>
    <description>Houses store activity by clients</description>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Totango Engagements</relationshipLabel>
        <relationshipName>Totango_Engagements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Totango Engagement</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Totango Engagements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Webinar__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>zWebinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUtilityBox.cls
/**
* @Bigcommerce 2012

* Class Name: TestUtilityBox

* Object Name: 

* Developed By: CG

* Date: 10/16/2012

* Version: 1.0

* Purpose: produces our test USERS, Subscription, and Totango Engagement records

* History: 


***/

public with sharing class TestUtilityBox {	
	
	public static User getTestUsers(Integer i, String profileName){
        
        User newUser  = new User();
        
        newUser.FirstName = 'Name' + i;
        newUser.LastName = 'Last Name' + i;
        newUser.Alias = 'user' + i;
        newUser.Email = 'big'+ i + '@commerce.com';
        newUser.Username = 'test' + i + '@bigcommerce.com';
        newUser.CommunityNickname = 'test_' + i + '@bigcommerce.com';
        newUser.ProfileId = [SELECT Id FROM Profile WHERE name =: profileName].Id;
        newUser.TimeZoneSidKey = 'America/Los_Angeles';
        newUser.LocaleSidKey = 'en_US';
        newUser.EmailEncodingKey = 'UTF-8';
        newUser.LanguageLocaleKey = 'en_US';
        newUser.isActive = true;   
        newUser.Department = 'Sales Operations' ;    
        
        system.debug('User created with a profile  ' + profileName + ' and a last name  ' + newUser.LastName);
        
        return newUser;         
    }
    
    public  static List<Account> getTestAccounts(String recordType,Integer numberOfRecords){
		    	
    	Account[] newAccounts = new Account[]{};  

        Id recType = Account.getSObjectType().getDescribe().getRecordTypeInfosByName().get(recordType).getRecordTypeId();

    	for(Integer x=0; x<numberOfRecords;x++){
    		
    		Account AccountTocreate = new Account( 
    		RecordTypeId =  recType,           	
    		Name = 'AccountTest ' + x,      		
            BillingStreet='Main St',
            BillingCity='Austin',
            BillingState = 'TX',     
            BillingPostalCode='70000',
            BillingCountry = 'US',
            Type = 'Client',
            Status__c = 'Open',                       
            SupportPin__c = '000' + x,
            Client_Start_Date__c = date.today()
                       	     		
    		);
    		
    		newAccounts.add(AccountTocreate);   		
    	}
    	   	
    	system.debug('Success we created ' + newAccounts.size() + '  Account records');
    	
    	return newAccounts;       
    }  
    
    
    public static List<Contact> getTestContacts( List<Account> accountRecs, String email){   	
    	
    	Contact[] newContacts = new Contact[]{};      	
    	
    	if(accountRecs != null){   		
    		
    		system.debug('Acquired ' + accountRecs.size() +' Account records IDs');    		
    		
    		for(Integer x=0; x<accountRecs.size();x++){    			
    			 			
    			Contact createContact = new Contact(    			
    			lastname='last' + x,
                firstname='first' + x,
                accountId= accountRecs[x].Id,
                email=  x + email						
    			);    			
    			
    			newContacts.add(createContact);
    		}   
    		system.debug('Success we created ' + newContacts.size() + '  Contact records');	
    	}	   	    	
    	return newContacts;    
    }      
   
    public  static List<Subscription__c> getTestSubscriptions(String recordType,List<Account> accountRecs, Integer numberOfRecords){
    	
    	Subscription__c[] newSubs = new Subscription__c[]{}; 

        if(accountRecs == null){

            Id recType = Subscription__c.getSObjectType().getDescribe().getRecordTypeInfosByName().get(recordType).getRecordTypeId();

            for(Integer x=0; x<numberOfRecords;x++){
                
                Subscription__c subscriptionTocreate = new Subscription__c( 
                RecordTypeId = recType,
                ProductType__c = 'Store',
                StoreURL__c = 'http://www.testingStore'+ x + 'bigcommerce.com',         
                Purchase_Team__c = 'Sales Operations' + x,
                Source__c = 'Direct Trial',
                Upgrade_Stage__c = 'New',
                Sales_Stage__c = 'New',          
                Status__c = 'Active',
                IsTrial__c = true,
                Was_Trial__c = true,
                Product__c = 'Open',
                Totango_Insights__c = 'Subscription test' + x                                       
                );
                
                newSubs.add(subscriptionTocreate);          
            } 

            system.debug('Success we created ' + newSubs.size() + '  Subscription records'); 
        }else{

            if(accountRecs != null){
                Id recType = Subscription__c.getSObjectType().getDescribe().getRecordTypeInfosByName().get(recordType).getRecordTypeId();

                for(Integer x=0; x<accountRecs.size();x++){
                
                Subscription__c subscriptionTocreate = new Subscription__c( 
                RecordTypeId = recType,
                ProductType__c = 'Store',
                StoreURL__c = 'http://www.testingStore'+ x + 'bigcommerce.com',         
                Purchase_Team__c = 'Sales Operations' + x,
                Source__c = 'Direct Trial',
                Upgrade_Stage__c = 'New',
                Sales_Stage__c = 'New',          
                Status__c = 'Active',
                IsTrial__c = true,
                Was_Trial__c = true,
                Product__c = 'Open',
                Totango_Insights__c = 'Subscription test' + x,
                Account__c = accountRecs[x].Id                                      
                );
                
                newSubs.add(subscriptionTocreate);          
            } 

            system.debug('Success we created ' + newSubs.size() + '  Subscription with Accounts records'); 

            }
        }    		 	
    	
    	return newSubs;       
    }

    public static List<Totango_Engagement__c> getTestTotangoEngagements(List<Subscription__c> subList){
        
        Totango_Engagement__c[] newTotangos = new Totango_Engagement__c[]{};        
        
        if(subList != null){            
            
            System.debug('getTestTotangoEngagements : Create' + subList.size() + '  records');
            //for(Subscription__c subsRec : subList){
            for(Integer x=0; x<subList.size();x++){
                
                Totango_Engagement__c createTotango = new Totango_Engagement__c(                
                Subscription__c = subList[x].Id,                
                TotangoInsights__c = 'Totango testing' + x          
                );
                
                newTotangos.add(createTotango);
            }   
            system.debug('Success we created ' + newTotangos.size() + '  Totango with subscription records');   
        }               
        return newTotangos;    
    } 

    public static List<Lead> getTestLeads(String recordType,String email, Integer numberOfRecords) {
    	
    	Lead[] newLeads = new Lead[]{};  

        Id recType = Lead.getSObjectType().getDescribe().getRecordTypeInfosByName().get(recordType).getRecordTypeId();    		
    
    	for(Integer x=0; x<numberOfRecords;x++){
    		
    		Lead LeadTocreate = new Lead(     		
    		RecordTypeId = recType, 		
    		FirstName = 'First ' + x,
			LastName = 'Last ' + x,
			Email =  x + email,
			Type__c = 'Trial',
			LeadSource = 'Web Trial',
			Lead_Assignment_Method__c = 'Round Robin',
			Phone = '555-555-555' + x,
			Assign_Now__c = true,
			Company = 'Test Company' + x,
			Country = 'US',		
//			Stage__c = 'New', 
			Status = 'Open',
			Expected_Plan__c = 'Bronze',
			Temperature__c = 'Cold' 	    	     		
    		);
    		
    		newLeads.add(LeadTocreate);   		
    	}
    	   	
    	system.debug('Success we created ' + newLeads.size() + '  Lead records');
    	
    	return newLeads;       
    }    
  
    public static List<Webinar__c> getTestWebinars(String email, Integer numberOfRecords ) {
    	
    	Webinar__c[] newWebinars = new Webinar__c[]{};       	
    	
    		for(Integer x=0; x<numberOfRecords;x++){
    			    					    		
    			Webinar__c WebinarTocreate = new Webinar__c(    			    		
    			Name = 'Webinar ' + x,	    			    			   				
				Registrant_Email__c =  x + email			    	     		
    			);    		
    			newWebinars.add(WebinarTocreate); 
    		}      	   	
    		
    	   	
    	system.debug('Success we created ' + newWebinars.size() + '  Webinar records');
    	
    	return newWebinars;       
    }   
}