src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Testing_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Manually populated field that indicates if the account is a testing account. WARNING: This field is not proactively populated. There could be test accounts that do not have this box checked.</description>
        <inlineHelpText>Manually populated field that indicates if the account is a testing account. WARNING: This field is not proactively populated. There could be test accounts that do not have this box checked.</inlineHelpText>
        <label>Testing Account - manually populated</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BI_Data__c.object
<CustomObject>
    <description>To hold store information from BI.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lifetime_GMV__c</fullName>
        <inlineHelpText>Lifetime GMV since 1/1/13 or Store provision date if provisioned after.</inlineHelpText>
        <label>Lifetime GMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_MBA_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Contact with an email match to the MBA Account admin email address</inlineHelpText>
        <label>Primary MBA Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BA_Testing_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is this a testing opportunity? MANUALLY POPULATED</description>
        <inlineHelpText>Is this a testing opportunity? MANUALLY POPULATED</inlineHelpText>
        <label>BA Testing Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BI_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BI Data</label>
        <referenceTo>BI_Data__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MonthlyRecurringRevenue__c</fullName>
        <label>Monthly Recurring Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PurchaseDate__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status from MBA</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back to Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT/QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpublished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coming Soon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft - Under Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Share Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchRetentionCampaign.cls
/***********************************************************************
  File                  : BatchAddToCampaign 
  Created by            : Maggie Frederick
  Created Date          : 1/2016
  Description           : This class  also allows for the
                          process to be scheduled using the APEX scheduler.
***********************************************************************/

global class BatchRetentionCampaign  implements Schedulable {
    
    global void execute(SchedulableContext SC) {
        
        RetentionCampaignUpdate opps = new RetentionCampaignUpdate();
 //       String criteria = Label.Query_Criteria;
       
       Id storeRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_StorePurchase).getRecordTypeId();
 
        String query1 = 'Select contact__r.Id, contact__r.Primary_MBA_Contact__c, AccountId, bi_Data__r.Lifetime_GMV__c From Opportunity where RecordTypeId = :storeRecordTypeId and Status__c = \'Active\'  ';
        query1 += ' and purchaseDate__c = LAST_N_DAYS:180  and purchasedate__c < LAST_N_DAYS:30 ';
		query1 += ' and contact__r.MailingCountry like \'US%\' and MonthlyRecurringRevenue__c > 0 and contact__r.HasOptedOutOfEmail=false and Contact__r.Email <> null ';
 		query1 += ' and BA_Testing_Opportunity__c = false and Account.Testing_Account__c = false ';
 		
 		if(Test.isRunningTest()){   query1 = query1 + ' limit 2';}
         
        opps.query = query1;
        Database.executeBatch(opps,90);
    }
 

}