src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product of the Subscription associated with this case.</description>
        <formula>IF( ISBLANK( Opportunity__c ) = FALSE, Opportunity__r.Product__c, 
IF( ISBLANK( Subscription__c ) = FALSE, Subscription__r.Product__c , 
NULL))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Product of the Subscription associated with this case.</inlineHelpText>
        <label>Product Plan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the store this case is in reference to</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Migration</fullName>
        <active>true</active>
        <businessProcess>Migration Case Process</businessProcess>
        <description>Used by Sales to request store migrations</description>
        <label>Migration</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/MarketingTrial__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Trial__c</fullName>
        <label>Trial #</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Marketing Trial</label>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>April_Revenue__c</fullName>
        <label>BA April Revenue</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>August_Revenue__c</fullName>
        <description>August month of revenue for subscription, only visible on admin page layout</description>
        <label>BA August Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>December_Revenue__c</fullName>
        <description>Dec revenue, only on admin layout</description>
        <label>BA December Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Feb_Revenue__c</fullName>
        <label>BA Feb Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>IsTrial__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Value pushed from MBA and is used in a trigger to convert leads when it&apos;s unchecked. Can also be used to force the account rollups to recalculate</description>
        <inlineHelpText>Value pushed from MBA and is used in a trigger to convert leads when it&apos;s unchecked. Can also be used to force the account rollups to recalculate</inlineHelpText>
        <label>MBA Is Trial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Jan_Revenue__c</fullName>
        <label>BA Jan Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>July_Revenue__c</fullName>
        <label>BA July Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>June_revenue__c</fullName>
        <label>BA June revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>March_Revenue__c</fullName>
        <label>BA March Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>May_revenue__c</fullName>
        <label>BA May revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MonthlyRecurringRevenue__c</fullName>
        <description>Monthly value of plan regardless of billing cycle. Sent from MBA</description>
        <inlineHelpText>Monthly value of plan regardless of billing cycle and amount</inlineHelpText>
        <label>Monthly Recurring Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>November_Revenue__c</fullName>
        <description>Nov Revenue only on admin layout</description>
        <label>BA November Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>October_Revenue__c</fullName>
        <description>Oct Revenue, only on Admin layout</description>
        <label>BA October Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_Upgrade_Amount__c</fullName>
        <description>Workflow updates when the product changes - used in upgrade calculations</description>
        <formula>IF( ISBLANK( Previous_Product_Name__c ) = FALSE,   MonthlyRecurringRevenue__c - Previous_Product_Value__c , NULL)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Previous Upgrade Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Previous_Upgrade_Date__c</fullName>
        <description>Workflow updates when the product changes - used in upgrade calculations</description>
        <label>Previous Upgrade Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>From MBA saying which plan/trial the store is on</description>
        <inlineHelpText>From MBA saying which plan/trial the store is on</inlineHelpText>
        <label>MBA Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseDate__c</fullName>
        <description>From MBA.  Date when the sub became a paid plan</description>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBD_Value__c</fullName>
        <description>Formula used to add an MRR value to the SBD reseller deals that come in from MBA with $0 MRR.  Engineering is working to push a value for these stores to the Monthly Recurring Revenue field, however, it will show the full store worth and not the BC revenue amount (may be an issue for dashboards)</description>
        <formula>IF(  OR(Strategic_Partner_Type__c  &lt;&gt;&quot;Reseller&quot;,Referral_ID__c = &quot;heartland_referral&quot;),MonthlyRecurringRevenue__c,
/*
IF( ProductID__c=&quot;49&quot;, 24.95,
IF( ProductID__c=&quot;50&quot;, 39.95,
IF( ProductID__c=&quot;98&quot;, 79.95,
IF( ProductID__c=&quot;52&quot;, 149.95,
IF( ProductID__c=&quot;53&quot;, 299.95,
IF( ProductID__c=&quot;57&quot;, 14.99,
IF( ProductID__c=&quot;58&quot;, 29.99,
IF( ProductID__c=&quot;101&quot;, 29.95,
IF( ProductID__c=&quot;102&quot;, 79.95,
IF( ProductID__c=&quot;103&quot;, 199.95,
NULL)))))))))))
*/
CASE(ProductID__c,
&quot;49&quot;, 24.95,
&quot;50&quot;, 39.95,
&quot;97&quot;, 29.95,
&quot;98&quot;, 79.95,
&quot;99&quot;, 199.95,
&quot;52&quot;, 149.95,
&quot;53&quot;, 299.95,
&quot;57&quot;, 14.99,
&quot;58&quot;, 29.99,
&quot;101&quot;, 29.95,
&quot;102&quot;, 79.95,
&quot;103&quot;, 199.95,
&quot;115&quot;, 79.95,
null)
)</formula>
        <label>SBD Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>September_Revenue__c</fullName>
        <description>Sept Revenue, only on admin layout</description>
        <label>BA September Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date the trial or store was first created. Pushed from MBA</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Strategic_Partner_Type__c</fullName>
        <description>Formula pulling the Type value from the associated strategic partner account.  Used in dashboard reports and the SBD value field</description>
        <formula>TEXT(Strategic_Partner__r.Type)</formula>
        <inlineHelpText>Formula pulling the Type value from the associated strategic partner account.  Used in dashboard reports and the SBD value field</inlineHelpText>
        <label>SBD Strategic Partner Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>X1st_Upgrade_Amount__c</fullName>
        <description>Formula calculating the worth of the initial upgrade. Based on workflows capturing when a product name changes and what the MRR delta is</description>
        <formula>IF( ISBLANK(X1st_Upgrade_Product_Name__c ) = FALSE,  X1st_Upgrade_Product_Value__c - Original_Plan_Value__c,NULL)</formula>
        <inlineHelpText>Formula calculating the worth of the initial upgrade. Based on workflows capturing when a product name changes and what the MRR delta is</inlineHelpText>
        <label>First Upgrade Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X1st_Upgrade_Date__c</fullName>
        <description>Populated by WFR https://na13.salesforce.com/01Qa0000000Vnaj to capture when a store upgrades</description>
        <inlineHelpText>Populated by WFR https://na13.salesforce.com/01Qa0000000Vnaj to capture when a store upgrades</inlineHelpText>
        <label>First Upgrade Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Totango_Engagement__c.object
<CustomObject>
    <description>Houses store activity by clients</description>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Totango Engagements</relationshipLabel>
        <relationshipName>Totango_Engagements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Totango Engagement</label>
    <nameField>
        <displayFormat>TE-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Totango Engagements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Subscription_TriggerHandler.cls
/**
* @Bigcommerce 2013

* Class Name: SubscriptionC_TriggerHandler

* Object Name: Subscription__c

* Developed By: Bigcommerce

* Date: 10/16/2013

* Version: 1.0

* Purpose: Create a Totango Engagement records when the Subscription record meets given criteria

* History: 

***/

public without sharing class Subscription_TriggerHandler
{

    public static Boolean ALREADY_RAN = false;    
    public static Id subRecType = Subscription__c.getSObjectType().getDescribe().getRecordTypeInfosByName().get('MBA Subscription').getRecordTypeId(); 
    public static MarketingTrial__c mt ;
    
 /* commented out 11/15/14   
    public static void insertTotango(List<Subscription__c> subList){
 
        List<Totango_Engagement__c> dbTotango = [SELECT Id FROM Totango_Engagement__c WHERE Subscription__c IN : subList];

        if(dbTotango.isEmpty()){

            for(Subscription__c s : subList){

                if(s.RecordTypeId == subRecType){
                    if(s.Status__c == 'Active'){
                        if(s.Product__c == null){
                            dbTotango.add(new Totango_Engagement__c (Subscription__c = s.Id));
                            System.debug('Record is Active and product is empty');
                        }else{
                            if(!s.Product__c.contains('SSL')){
                                if(!s.Product__c.contains('Domain')){
                                    dbTotango.add(new Totango_Engagement__c (Subscription__c = s.Id));
                                    System.debug('Record is Active and does not contain SSL or Domain');
                                }
                            }
                        }
                    }
                }               
            }
            
            
            Try{
                insert dbTotango;
            }
            catch(Exception e) {
               ErrorEmailHelper.notifyOnError('Subscription Trigger Handler', 'Create Totango', 'Error in Sub Trigger Handler - Create Totango', 'Error Creating Totango for: ' + subList[0].Id);
                system.debug('Error in Subscription  Trigger Handler - Create Totango');
                }   
        
            
            
        }
    }       
    
    public static void UpdateCalcFields(Subscription__c[] newList, Map<ID, Subscription__c> SubscriptionMap, Subscription__c[] oldList)
    {
        integer currentyear = Date.today().year();
        integer currentmonth = Date.today().month();
        
        Map<Integer, String> mapMonth = new Map<Integer, String>();
               
        for (integer i =0; i < newList.size(); i++)
        {   
           if (!newList[i].IsTrial__c)  
           {
                decimal monthlyrev =0.00 ;
                system.debug(' test' +newList[i].purchasedate__c);
                
                if (newList[i].PurchaseDate__c <> null && newList[i].PurchaseDate__c.year() == currentyear  && newList[i].PurchaseDate__c.month() == currentmonth
                   && newList[i].X1st_Upgrade_Date__c <> null && newList[i].X1st_Upgrade_Date__c.year() == currentyear  && newList[i].X1st_Upgrade_Date__c.month() == currentmonth
                   && newList[i].Previous_Upgrade_Date__c <> null && newList[i].Previous_Upgrade_Date__c.year() == currentyear  && newList[i].Previous_Upgrade_Date__c.month() == currentmonth
                   )
                {
                    monthlyrev = newList[i].MonthlyRecurringRevenue__c ;
                }
                else if (
                        newList[i].PurchaseDate__c <> null && newList[i].PurchaseDate__c.year() == currentyear  && newList[i].PurchaseDate__c.month() == currentmonth
                        && newList[i].X1st_Upgrade_Date__c <> null && newList[i].X1st_Upgrade_Date__c.year() == currentyear  && newList[i].X1st_Upgrade_Date__c.month() == currentmonth
                         )
                   
                       {
                        monthlyrev = newList[i].MonthlyRecurringRevenue__c ;
                       }
                 else if ( newList[i].PurchaseDate__c <> null && newList[i].PurchaseDate__c.year() == currentyear  && newList[i].PurchaseDate__c.month() == currentmonth)
                       {
                         monthlyrev = newList[i].MonthlyRecurringRevenue__c ;
                       }
                 else if  ( newList[i].X1st_Upgrade_Date__c <> null && newList[i].X1st_Upgrade_Date__c.year() == currentyear  && newList[i].X1st_Upgrade_Date__c.month() == currentmonth
                   && newList[i].Previous_Upgrade_Date__c <> null && newList[i].Previous_Upgrade_Date__c.year() == currentyear  && newList[i].Previous_Upgrade_Date__c.month() == currentmonth
                   )
                     {
                        monthlyrev = newList[i].Previous_Upgrade_Amount__c  +  newList[i].X1st_Upgrade_Amount__c; 
                        
                     }
                 else if  (  newList[i].X1st_Upgrade_Date__c <> null && newList[i].X1st_Upgrade_Date__c.year() == currentyear  && newList[i].X1st_Upgrade_Date__c.month() == currentmonth
                   )
                     {
                        monthlyrev =  newList[i].X1st_Upgrade_Amount__c; 
                        
                     }  
                  else if  ( newList[i].Previous_Upgrade_Date__c <> null && newList[i].Previous_Upgrade_Date__c.year() == currentyear  
                            && newList[i].Previous_Upgrade_Date__c.month() == currentmonth)
                   
                     {
                        monthlyrev =  newList[i].Previous_Upgrade_Amount__c; 
                        
                     }  
                  else if (newList[i].Strategic_Partner_Type__c == 'Reseller'
                           && newList[i].StartDate__c.month() == currentmonth && newList[i].StartDate__c.year() == currentyear)
                        {
                            monthlyrev =  newList[i].SBD_Value__c;
                        }

// TODO  dynamically get field names for months from custom setting and update 

                  if (currentmonth == 1)             
                    {newList[i].jan_revenue__c = monthlyrev;}
                  else if (currentmonth == 2)
                    {newList[i].feb_revenue__c = monthlyrev;}
                  else if (currentmonth == 3)             
                    {newList[i].march_revenue__c = monthlyrev;}
                  else if (currentmonth == 4)
                    {newList[i].april_revenue__c = monthlyrev;}
                  else if (currentmonth == 5)
                    {newList[i].may_revenue__c = monthlyrev;}
                  else if (currentmonth == 6)
                    {newList[i].june_revenue__c = monthlyrev;}
                  else if (currentmonth == 7)
                    {newList[i].july_revenue__c = monthlyrev;}
                 else if (currentmonth == 8)
                    {newList[i].august_revenue__c = monthlyrev;}
                 else if (currentmonth == 9)
                    {newList[i].september_revenue__c = monthlyrev; }  
                 else if (currentmonth == 10)
                    {newList[i].october_revenue__c = monthlyrev;  }
                 else if (currentmonth == 11)
                    {newList[i].november_revenue__c = monthlyrev;  }
                 else if (currentmonth == 12)
                    {newList[i].december_revenue__c = monthlyrev;  }

                } 
               
        } //end  for
        
        
    }
    
*/
    public static void insertCases(Subscription__c[] subList)
    {
       List<Case> newCases = new List<Case>();
       Id idCaseRecordType = Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Professional Services').getRecordTypeId();
       Id idMigCaseRecordType = Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Migration').getRecordTypeId();
       Map<Id, Subscription__c> mapacct = new Map<Id, Subscription__c>([select Id, Account__R.Ltc__c, Account__r.SBD_Segment__c, Account__r.SBD_Orion_Persona__c from Subscription__c where Id in :subList]);
       
       for (integer i =0; i < subList.size(); i++)
       {     
            Boolean createSScase = false;
            Subscription__c sub = mapacct.get(subList[i].Id);
            
            If ( (sub.Account__r.SBD_Orion_Persona__c <> null 
                     && (sub.Account__r.SBD_Orion_Persona__c.containsIgnoreCase('royal') || sub.Account__r.SBD_Orion_Persona__c.containsIgnoreCase('owen')))
                  || subList[i].New_Product_Plan__c.containsIgnoreCase('Platinum')
                )
            {
              if (subList[i].SBD_Store_Id__c <> null)   
                createSScase = true;
                
            }
            
            Case newCase = new Case();
            newCase.Origin = 'Orion Request';
            newCase.Reason = 'Migration';
            newCase.Subject = 'Your Bigcommerce Migration';
            newCase.Description = 'Migration for Orion Client ' ;
            newCase.AccountId = subList[i].Account__c;
            newCase.Subscription__c = subList[i].Id;
            newCase.ContactId = subList[i].Contact__c ;          
          
           if (subList[i].Requested_Migration__c == 'Yes')
                {   
                    newCase.RecordTypeId = idMigCaseRecordType;
                    newCase.Department__c = 'Migration';
                    newCase.OwnerId = Label.Migration_Case_Queue;
                    if (createSScase)
                     {newCase.Needs_Store_setup__c = true; }  
                    newCases.add(newCase);
                }   
            else if (subList[i].Requested_Migration__c == 'No'
                     && createSScase)
                   
            {
                newCase.RecordTypeId = idCaseRecordType;
                newCase.Reason = 'Store Setup';
                newCase.Description = 'Store Setup for Orion Client ' ;
                newCase.Department__c = 'Professional Services';
                if (mapacct.get(subList[i].Id).Account__r.ltc__c <>null)  
                {
                        newCase.OwnerId =mapacct.get(subList[i].Id).Account__r.ltc__c;
                }
                else
                {
                    newCase.OwnerId = Label.PS_Queue;
                }
                newCases.add(newCase);
            }
//           if (newCase.OwnerId == null) newCase.OwnerId =$Current_User;
            
           
            
        }
        
        if (newCases.size() > 0)
        {
            Try{
                insert newCases;
            }
            catch(Exception e) {
               ErrorEmailHelper.notifyOnError('Subscription Trigger Handler', 'Create Case', 'Error in Sub Trigger Handler - Create Case', 'Error Creating case for: ' + subList[0].Id);
                system.debug('Error in Subscription  Trigger Handler - Create Case');
                }   
        
        
        }
    }
    
/*    
 public static void updateStrategicPartner(Subscription__c[] subList)   
 {
    
    Map<String, ID> mpLpValueId = new Map <string, Id>();
	Map<String, ID> mpRValueId = new Map <string, Id>();

	List<StrategicPartner__c> strpar = StrategicPartner__c.getall().Values();
	for (StrategicPartner__c sp :strpar)
	{
		if (sp.LandingPage__c <> null) mpLpValueID.put(sp.LandingPage__c, sp.Strategic_Partner__c);
		if (sp.Referral_ID__c <> null) mpRValueID.put(sp.Referral_ID__c, sp.Strategic_Partner__c);
		
	}
	
	for (Subscription__c s :subList)
	{

	  if (s.Test_store__c == false && s.Strategic_Partner__c ==null
		  && (s.LandingPage__c <> null && (s.LandingPage__c <> '/' ) || s.referral_id__c <> null) 
     	 )							 
	 {
//	 		if (!s.Email__c.contains('bigcommerce.com') )
		{
			for (String str :mpLpValueId.KeySet())
			{
			
				if (s.LandingPage__c <> null && s.LandingPage__c.contains(str))
                {
				    s.Strategic_Partner__c = mpLpValueID.get(str);
                     system.debug(' found sub '+s.Name);
   
                }
            }
            for (String str :mpRValueId.KeySet())
			{
                if (s.Referral_ID__c <> null && s.referral_id__c.contains(str))
                {
                    s.Strategic_Partner__c  = mpRValueID.get(str);    
                     system.debug(' found sub '+s.Name);
                  
                }   
                    
				   
			}
          
		}	
	  }	
	}
 }
    
    public static void UpdateMktTest(Subscription__c[] newList)
    {
 		integer currentyear = Date.today().year();
 		Boolean updMktTrial = false;
 		
        for (Subscription__c s:newList)
        {
            String Trial;
  			getMarketingTrial();
  // remove (s.LandingPage__c == null || s.LandingPage__c == '/') && 
            
            if (s.Referral_ID__c == null  
                && s.Strategic_Partner__c == null && s.MBAPartnerID__c == null && s.ProductType__c == 'Store'
                 && s.Product__c <> null && s.Product__c <> '' && !s.Product__c.contains('Domain')
                 && s.StartDate__c <> null && s.StartDate__c.year() == currentyear
                 )
            {

			     Decimal   trialNum = mt.Trial__c;
			        
			        if (trialNum > Decimal.valueOf(Label.Marketing_Test_Number))
			        {
			            trial = Label.Marketing_Test_Group;
			            mt.Trial__c =  1;
			        }
			        else
			        {
			            trial =  String.valueof(mt.Trial__c);
			            mt.Trial__c =  mt.Trial__c +1;
			        }
       
              
                s.Marketing_Test_Group__c = trial;
                updMktTrial = true;
            }
            
        }
        
          if (updMktTrial) UpdMarketingTrial();
    }

  
   public static void getMarketingTrial()
    {
       if(!Test.isRunningTest()){       
        	mt = MarketingTrial__c.getInstance('SalesTrial');
       }
 
       else if (mt==null || Test.isRunningTest())
        {
   	       
   	       mt = new MarketingTrial__c (Name ='SalesTrial', Trial__c =1);
  //  	   insert mtest;
  //  	   mt = MarketingTrial__c.getInstance('SalesTrial');
  
        }
    }
    
    public static void UpdMarketingTrial()
    {
        if (mt <> null && !Test.isRunningTest() )
        {
   	       update mt;
        }
    }
 */ 
}