src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Partner source - for use in determining source of client account.</description>
        <inlineHelpText>Partner source - for use in determining source of client account.</inlineHelpText>
        <label>zPAR Partner Source</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Partner_Commission_Payment__c.object
<CustomObject>
    <description>For BAP-3698 - Partner Commissions v2

Records the payments made out to our referral partners for their commissions</description>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The partner (RV Account) that this payment was issued to</inlineHelpText>
        <label>Partner Account</label>
        <referenceTo>rvpe__RVAccount__c</referenceTo>
        <relationshipLabel>Partner Commission Payments</relationshipLabel>
        <relationshipName>Partner_Commission_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The amount paid to the partner</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>Date that the payment was issued to the partner</inlineHelpText>
        <label>Payment Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>For BAP-3698 - Partner Commission v2</description>
        <inlineHelpText>The status of the payment - only &quot;Completed&quot; means that the monies were received</inlineHelpText>
        <label>Status</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Partner Commission Payment</label>
    <nameField>
        <displayFormat>PCP-{00000}</displayFormat>
        <label>Partner Commission Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Commission_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Partner Commissions  functionality.
When making a change to the start date, make sure to also change the Partner Commission Payment rollup on RV Account so that the numbers can be calculated properly.  The date there should reflect one month after the date on this custom setting.</description>
    <fields>
        <fullName>Earliest_Possible_Start_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>If the start date is left blank on a partner commission run, this is the earliest BI Data to pull in</inlineHelpText>
        <label>Earliest Possible Start Date</label>
        <type>Date</type>
    </fields>
    <label>Partner Commission Settings</label>
</CustomObject>

src/objects/Partner_Commission_Summary_History__c.object
<CustomObject>
    <description>Stores daily metrics against Partner Commissions to ease in reporting

For BAP-3698 - Partner Commissions v2</description>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total amount paid out to partners</inlineHelpText>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payments__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The number of payments made to our partners</inlineHelpText>
        <label>Payments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Commission Summary History</label>
    <nameField>
        <displayFormat>PCM-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Partner Commission Summary History Numbe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Commission Summary Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchPartnerCommissionAddPaymentHistory.cls
global class BatchPartnerCommissionAddPaymentHistory implements Database.Batchable<sObject> {
	
	global Date endDate;
	global Date startDate;
	private Date earliestDate;
	global String query;

	/**
	 * Builds the query for the batch process.  Note that this will not run if the query is manually overridden.
	 * @author Steve O'Neal
	 * @date   2016-06-20
	 * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
	 * @return String representing a SOQL query
	 */
	private string buildQuery()
	{
		if (!String.isEmpty(query))
		{
			return query;
		}

		if (startDate == null || startDate < earliestDate)
		{
			startDate = earliestDate;
		}

		string retVal = 'SELECT Id, Payment_Amount__c, Payment_Date__c, Partner_Account__c, Partner_Account__r.Most_Recent_Commission_Payment__c, Partner_Account__r.Most_Recent_Commission_Payment__r.Payment_Date__c  from Partner_Commission_Payment__c where Partner_Account__r.rvpe__ExtAccountId__c != 0 and Status__c = \'Completed\' and Payment_Date__c  <= ' + BatchPartnerCommissionCreateDetails.formatDateForQuery(endDate) + ' and Payment_Date__c  >= ' + BatchPartnerCommissionCreateDetails.formatDateForQuery(startDate);
		System.Debug('Generated SOQL query: ' + retVal);

		return retVal;
	}

	/**
	 * Instantiator
	 * @author Steve O'Neal
	 * @date   2016-06-20
	 * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
	 * @return nothing
	 */
	global BatchPartnerCommissionAddPaymentHistory() {
		endDate = Date.today();
		Partner_Commission_Settings__c pcs = Partner_Commission_Settings__c.getInstance();
		earliestDate = (pcs.Earliest_Possible_Start_Date__c != null)?pcs.Earliest_Possible_Start_Date__c:Date.newInstance(2013, 1, 1);
		// assume that we pay in arears, so any payment made out to a partner would need to be at least one month after the minimum start date for Invoice Transactions
		earliestDate = earliestDate.addMonths(1);
		startDate = earliestDate;
	}
	
	/**
	 * QueryLocator gets the records from the db based on the generated query
	 * @author Steve O'Neal
	 * @date   2016-06-20
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
	 * @param  BC         Batchable context
	 * @return            Query locator that represents the scope of the batch
	 */
	global Database.QueryLocator start(Database.BatchableContext BC) {
		Partner_Commission_Summary_History__c pcsh = BatchPartnerCommissionCreateHistory.getPartnerCommissionSummaryHistory(endDate);
		pcsh = initalizePaymentHistory(pcsh);
		upsert pcsh;
		return Database.getQueryLocator(buildQuery());
	}


	private static Partner_Commission_Summary_History__c initalizePaymentHistory(Partner_Commission_Summary_History__c pcsh)
	{
		pcsh.Payment_Amount__c = 0;
		pcsh.Payments__c = 0;
		return pcsh;
	}


 	/**
	 * Execute the scope
	 * @author Steve O'Neal
	 * @date   2016-06-20
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
	 * @param  BC         Batchable context
	 * @param  scope      Current scope of batch
	 * @return            Nothing
	 */
  	global void execute(Database.BatchableContext BC, List<sObject> scope) {
  		if (scope.size() > 0)
  		{
	  		// get the history record from the database
	   		Partner_Commission_Summary_History__c pcsh = BatchPartnerCommissionCreateHistory.getPartnerCommissionSummaryHistory(endDate);

	   		Set<Id> RVPartnerIdsThatNeedMostRecentPayment = new Set<Id>();

	   		for (sObject sobj : scope)
	   		{
	   			Partner_Commission_Payment__c pcp = (Partner_Commission_Payment__c)sobj;
	   			pcsh.Payment_Amount__c += pcp.Payment_Amount__c;
	   			pcsh.Payments__c++;

	   			// see if the payment being processed is the most recent
	   			if (pcp.Partner_Account__r.Most_Recent_Commission_Payment__c == null || pcp.Partner_Account__r.Most_Recent_Commission_Payment__r.Payment_Date__c < pcp.Payment_Date__c)
	   			{
	   				System.Debug('RV Account with outdated payment data: ' + pcp.Partner_Account__c);
	   				RVPartnerIdsThatNeedMostRecentPayment.add(pcp.Partner_Account__c);
	   			}
	   		}


	   		if (RVPartnerIdsThatNeedMostRecentPayment.size() > 0)
	   		{
	   			// if we found partners who have an out-of-date most recent payment, update it
	   			List<rvpe__RVAccount__c> rvAccounts = [Select Id, Most_Recent_Commission_Payment__c, Most_Recent_Commission_Payment__r.Payment_Date__c from rvpe__RVAccount__c where Id in:RVPartnerIdsThatNeedMostRecentPayment];
	   			for (rvpe__RVAccount__c rvAccount : rvAccounts)
	   			{
			   		for (sObject sobj : scope)
			   		{
			   			Partner_Commission_Payment__c pcp = (Partner_Commission_Payment__c)sobj;
			   			if (pcp.Partner_Account__c == rvAccount.Id)
			   			{
			   				if (rvAccount.Most_Recent_Commission_Payment__c == null || rvAccount.Most_Recent_Commission_Payment__r.Payment_Date__c < pcp.Payment_Date__c)
			   				{
				   				System.Debug('Adding new payment data: ' + pcp.Partner_Account__c);
				   				rvAccount.Most_Recent_Commission_Payment__c = pcp.Id;
				   				rvAccount.Most_Recent_Commission_Payment__r = pcp;
				   			}
			   			}
			   		}
	   			}

   				System.Debug('Updating RV Accounts: ' + rvAccounts.size());
	   			update rvAccounts;
	   		}

	   		upsert pcsh;
   		}
	}
	
	/**
	 * Post-processing logic
	 * @author Steve O'Neal
	 * @date   2016-06-20
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
	 * @param  BC         Batchable context
	 * @return            nothing
	 */
	global void finish(Database.BatchableContext BC) {
	}
	
	
}