src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestSubsForConsole.cls
@isTest
private class TestSubsForConsole 
{
    static testMethod void testLeadConsole() 
    {
    	TestDataGenerator td = new TestDataGenerator();
    	
    	// Create some leads and subs
    	td.getLeads(true);    	
    	list<Subscription__c> lstSubs = td.getSubscriptions(true);
    	
    	Id leadId = td.leads[0].Id;
    	
    	// Loop through the subscriptions and set the lead id to the newly created leads
    	for (Subscription__c sub : lstSubs)
    	{
    		sub.Lead__c = leadId;
    	}
    	    	
    	update(lstSubs);    	
    	
    	list<Subscription__c> returnSubs = [SELECT Id, Status__c FROM Subscription__c WHERE Lead__c = :leadId];
    	
    	system.debug('@@@ TestSubsForConsole:testLeadConsole - Subs for LeadId: ' + leadId); 
    	system.debug('@@@ TestSubsForConsole:testLeadConsole - Subs for Test: ' + lstSubs); 
    	system.debug('@@@ TestSubsForConsole:testLeadConsole - Subs for Lead: ' + returnSubs);
    	
    	Test.startTest();
    				
		PageReference pageRef = Page.SubsForConsole;
		pageRef.getParameters().put('Id', leadId);
		pageRef.getParameters().put('selId', lstSubs[0].Id);
		Test.setCurrentPage(pageRef);		
		
		SubsForConsole_Controller cont = new SubsForConsole_Controller();			
		
		cont.LoadSubscriptions();
		
		// ensure the correct number of subscriptions loaded
		system.assertEquals(td.subscriptionNum, cont.getSubs().size());
		
		string acctPrefix = cont.accountPrefix;
		string contPrefix = cont.contactPrefix;
		string casePrefix = cont.caseCreateURLPrefix;
		string leadPrefix = cont.leadPrefix;
		leadId = cont.getLeadId();
		
		system.debug('@@@ TestSubsForConsole:testLeadConsole - Lead Id for page: ' + leadId);
		
		string leadName = cont.getLeadName();
		string objType = cont.getObjectType();
		
		// By calling this all subs should not be selected	
		cont.SelectSub();
		
		system.assertEquals(null, cont.getSelectedSubId());
		
		// Now actually select a sub
		for (SubsForConsole_Controller.SubscriptionWrapper wrap : cont.getSubs())
		{
			if (wrap.objSub.Id == lstSubs[0].Id)
			{
				wrap.isSelected = true;
				break;
			}
		}
		
		cont.SelectSub();
		
		system.assertNotEquals(null, cont.getSelectedSubId());
		string subName = cont.getSelectedSubName();
		
		list<SelectOption> caseOpts = cont.lstCaseRTs;
		list<SubsForConsole_Controller.CaseRTWrapper> lstCaseWrap = cont.lstCaseRTWraps;
				
		Test.stopTest();
    }
    
    static testMethod void testContactConsole() 
    {
    	TestDataGenerator td = new TestDataGenerator();
    	
    	// Create some accounts, contacts and subs
    	td.getAccounts(true);
    	td.getContacts(true); 	
    	list<Subscription__c> lstSubs = td.getSubscriptions(true);
    	
    	Id accountId = td.accounts[0].Id;
    	Id contactId = td.contacts[0].Id;
    	
    	// Update the first contact record to be associated with the account
    	td.contacts[0].AccountId = accountId;
    	update td.contacts;
    	
    	// Loop through the subscriptions and set the lead id to the newly created account
    	for (Subscription__c sub : lstSubs)
    	{
    		sub.Account__c = accountId;
    	}
    	    	
    	update(lstSubs);
    	
    	list<Subscription__c> returnSubs = [SELECT Id, Status__c FROM Subscription__c WHERE Account__c = :accountId];
    	
    	system.debug('@@@ TestSubsForConsole:testContactConsole - Subs for Account Id: ' + accountId); 
    	system.debug('@@@ TestSubsForConsole:testContactConsole - Subs for Contact Id: ' + contactId);
    	system.debug('@@@ TestSubsForConsole:testContactConsole - Subs for Test: ' + lstSubs); 
    	system.debug('@@@ TestSubsForConsole:testContactConsole - Subs for Contact: ' + returnSubs);
    	
    	Test.startTest();
    				
		PageReference pageRef = Page.SubsForConsole;
		pageRef.getParameters().put('Id', contactId);
		pageRef.getParameters().put('selId', lstSubs[0].Id);
		Test.setCurrentPage(pageRef);		
		
		SubsForConsole_Controller cont = new SubsForConsole_Controller();			
		
		cont.LoadSubscriptions();
		
		// ensure the correct number of subscriptions loaded
		system.assertEquals(td.subscriptionNum, cont.getSubs().size());
		
		string acctPrefix = cont.accountPrefix;
		string contPrefix = cont.contactPrefix;
		string casePrefix = cont.caseCreateURLPrefix;
		string leadPrefix = cont.leadPrefix;
		accountId = cont.getAcctId();
		contactId = cont.getContactId();
		
		system.debug('@@@ TestSubsForConsole:testContactConsole - Account Id for page: ' + accountId);
		system.debug('@@@ TestSubsForConsole:testContactConsole - Contact Id for page: ' + contactId);
		
		Test.stopTest();
    }
}