src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Total_Active_Store_GMV__c</fullName>
        <description>Roll up of all active store GMV for this account.</description>
        <label>Total Active Store GMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BI_Data__c.object
<CustomObject>
    <description>To hold store information from BI.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Payment_Amount__c</fullName>
        <label>Last Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Payment_Date__c</fullName>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lifetime_GMV__c</fullName>
        <inlineHelpText>Lifetime GMV since 1/1/13 or Store provision date if provisioned after.</inlineHelpText>
        <label>Lifetime GMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BI_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BI Data</label>
        <referenceTo>BI_Data__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The subscription is not related to the account on the opportunity</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>The subscription is not related to the account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rvpe__RVAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RV Account</label>
        <referenceTo>rvpe__RVAccount__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lifetime_GMV__c</fullName>
        <description>Lifetime GMV from the BI Data object</description>
        <inlineHelpText>Lifetime GMV, rolled up from the BI Data object</inlineHelpText>
        <label>Lifetime GMV</label>
        <summarizedField>BI_Data__c.Lifetime_GMV__c</summarizedField>
        <summaryForeignKey>BI_Data__c.Subscription__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Was used by Acq on forecast subs but can probably be deleted now</description>
        <label>zOpportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestBIDataTrigger.cls
@isTest(SeeAllData=true)
private class TestBIDataTrigger {
	
	static testMethod void testTrigger() 
    {
      TestDataGenerator td = new TestDataGenerator();
      Test.startTest();
      list<Account> lstAcc = td.getAccounts(true);
      list<Subscription__c> subs = td.getSubscriptions(true);
      // Create a new opportunity for the account
      Id StoreRecordTypeId = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_Recordtype_StorePurchase).getRecordTypeId();
	  rvpe__RVAccount__c  rva = new rvpe__RVAccount__c (Name = 'Test Partner', rvpe__ExtAccountId__c = 912345);
	  insert rva;
	  
      Opportunity o = new Opportunity();
        o.Name = 'Test ';
        o.RecordTypeId = StoreRecordTypeId;
        o.CloseDate = Date.today().addDays(1);
        o.StageName = 'Purchased';
        o.rvpe__RVAccount__c = rva.Id;
       
        o.AccountId = lstAcc[0].Id;
        //o.Pricebook2Id = getPricebook(true).Id;
        insert o;
        
        BI_Data__c bi = new BI_Data__c (Lifetime_GMV__c =1000.00, Opportunity__c = o.Id, Subscription__c = subs[0].Id, Last_Payment_Amount__c =20.00, Last_Payment_Date__c = Date.Today() );
  		insert bi;
      	
      	BI_Data__c objbid =[SELECT Id, Account__c, Lifetime_GMV__c FROM BI_Data__c WHERE 
                id  =:bi.Id ];
        
		// Check For Account
        System.assertEquals(objbid.Account__c, o.AccountId );
        
        Account acc = [select Id, Total_Active_Store_GMV__c from Account where Id = :objbid.Account__c];
         
//        System.assertEquals(objbid.Lifetime_GMV__c, acc.Total_Active_Store_GMV__c);
		
		Test.stopTest();
    }
}