src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>iDev_Partner_ID__c</fullName>
        <description>Used to port new partner ID from the iDev commissions system; assigns new leads coming from the partner to the partner account owner. jw</description>
        <externalId>true</externalId>
        <label>iDev Partner ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type is set from BMP on the contact.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner RV Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_T_C_Agreement__c.object
<CustomObject>
    <description>PRM Portal terms and conditions for Channel Partners</description>
    <fields>
        <fullName>Accepted_By__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Accepted By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Partner_T_C_Agreements</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Accepted_Date__c</fullName>
        <label>Accepted Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>Partner Account that has accepted the T&amp;C record</description>
        <inlineHelpText>Partner Account that has accepted the T&amp;C record</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Partner_T_C_Agreements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Terms_Conditions__c</fullName>
        <label>Terms &amp; Conditions</label>
        <referenceTo>Terms_Conditions__c</referenceTo>
        <relationshipName>Partner_T_C_Agreements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>zPartner T&amp;C Agreement</label>
    <nameField>
        <displayFormat>PTCA-{0}</displayFormat>
        <label>Partner T&amp;C Agreement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner T&amp;C Agreements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Terms_Conditions__c.object
<CustomObject>
    <description>Holds the Terms &amp; Conditions for any use</description>
    <fields>
        <fullName>Active_Date__c</fullName>
        <label>Active Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Partner Portal</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Terms &amp; Conditions</label>
    <nameField>
        <displayFormat>TC-{0}</displayFormat>
        <label>Terms &amp; Conditions</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms &amp; Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PartnerPortalHelper.cls
public without sharing class PartnerPortalHelper 
{
    public static Terms_Conditions__c PartnerPortalTC;
    public static Partner_T_C_Agreement__c PartnerPortalTCAgree;
    
    public static User CurrentUserRecord
    {
    	get
    	{
    		User retUser = null;
    		
    		if (CurrentUserRecord == null)
    		{	        
		        if (UserInfo.getUserId() != null)
		        {
		            retUser = [SELECT Id, Contact.AccountId, ContactId, Email, FirstName, LastName, UserName FROM User WHERE Id = :UserInfo.getUserId()];
		            
		            system.debug('***PartnerPortalHelper:CurrentUserRecord - User Found: ' + retUser);
		            system.debug('***PartnerPortalHelper:CurrentUserRecord - User Contact Id: ' + retUser.ContactId);
		            system.debug('***PartnerPortalHelper:CurrentUserRecord - User Contact Account Id: ' + retUser.Contact.AccountId);
		        }
		        else
		        {
		        	system.debug('***PartnerPortalHelper:CurrentUserRecord - No getUser Found');
		        }
    		}
    		else
    		{
    			retUser = CurrentUserRecord;
    		}
    		
    		return retUser;
    	}
    }

    public static Account PartnerAccount
    {
    	get
    	{
    		Account retAcct = null;
    		
    		if (PartnerAccount == null)
	        {   
		        if (CurrentUserRecord != null)
		        {
		            // Check if the User has contact info (should always since they are already logged into the Portal)
		            if (CurrentUserRecord.ContactId != null)
		            {
		                for (Account a : [SELECT Id, iDev_Partner_ID__c, Name, OwnerId FROM Account WHERE Id = :CurrentUserRecord.Contact.AccountId])
		                {
		                    system.debug('***PartnerPortalHelper:PartnerAccount - Account Found: ' + a);
		                                
		                    retAcct = a;
		                    break;
		                }
		            }
		        }		        
	        }
	        else
	        {
	        	retAcct = PartnerAccount;
	        }
	        
	        return retAcct;
    	}
    }
    
    public static boolean HasPartnerAcceptedCurrentTerms()
    {
        boolean hasAccepted = false;
        
        PartnerPortalTC = null;
        PartnerPortalTCAgree = null;
        
        // Find the most current Terms and Conditions for the Partner Portal
        for (Terms_Conditions__c tc : [SELECT Id, Active_Date__c, Expiration_Date__c, Type__c
                                        FROM Terms_Conditions__c
                                        WHERE Type__c = 'Partner Portal'
                                            AND Active_Date__c <= TODAY
                                            AND (Expiration_Date__c >= TODAY 
                                                    OR Expiration_Date__c = null)])
        {
            PartnerPortalTC = tc;
            break;
        }
        
        // If no T&Cs exist then default to true
        if (PartnerPortalTC == null)
        {
            system.debug('***PartnerPortalHelper:HasPartnerAcceptedCurrentTerms - No Terms Found');
            hasAccepted = true;
        }
        // If partner account is not found
        else if (PartnerAccount == null)
        {
            system.debug('***PartnerPortalHelper:HasPartnerAcceptedCurrentTerms - No Partner Account Found');
            hasAccepted = false;
        }
        else
        {
            system.debug('***PartnerPortalHelper:HasPartnerAcceptedCurrentTerms - Terms Found: ' + PartnerPortalTC.Id);
            system.debug('***PartnerPortalHelper:HasPartnerAcceptedCurrentTerms - Partner Account Id: ' + PartnerAccount.Id);
            
            // Check if a record exists for the current Partner Portal T&Cs
            for (Partner_T_C_Agreement__c p : [SELECT Id, Account__c, Terms_Conditions__c, Accepted_Date__c, Accepted_By__c
                                                FROM Partner_T_C_Agreement__c
                                                WHERE Account__c = :PartnerAccount.Id
                                                    AND Terms_Conditions__c = :PartnerPortalTC.Id])
            {
                PartnerPortalTCAgree = p;
                
                // If the partner has already accepted
                if (p.Accepted_Date__c != null)
                {
                    hasAccepted = true;
                }
                
                break;
            }
        }
        
        return hasAccepted;
    }
}