src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MBA_Staging_Contact__c.object
<CustomObject>
    <description>Used for the integration between MBA and Salesforce. Fields are to be read only for all users and object is only visible to admins.</description>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MBA Staging Contact</label>
    <nameField>
        <displayFormat>MSC-{0000}</displayFormat>
        <label>MBA Staging Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MBA Staging Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MBA_Staging_Subscription__c.object
<CustomObject>
    <description>Used for the integration between MBA and Salesforce. Fields are to be read only for all users and object is only visible to admins.</description>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>MBA Staging Subscription</label>
    <nameField>
        <displayFormat>MSS-{0000}</displayFormat>
        <label>MBA Staging Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MBA Staging Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <description>Unique identifier from MBA of account/user.  ID of the account which owns this subscription</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier from MBA of account/user.  ID of the account which owns this subscription</inlineHelpText>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <description>ID specific to the store/product purchased</description>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestMBAStagingSubscription.cls
@isTest(seeAllData=true) 
public class TestMBAStagingSubscription 
{
	static testMethod void testStagingSubscription() 
	{
		// Create Test Data
		TestDataGenerator td = new TestDataGenerator();
		
		// List of Staging Contact Records
		list<MBA_Staging_Contact__c> stgConList = new list<MBA_Staging_Contact__c>();
		set<string> stgConSet = new set<string>();
					 	
		// Create Map of Contacts Associated with a Staging Account Record
		map<string, Contact> ConMap = new map<string, Contact>();
		map<string, MBA_Staging_Contact__c> stgConMap = new map<string, MBA_Staging_Contact__c>();  
					 	
		// Start Test
		test.startTest();
					 	
		// Initialize the Custom Setting Map    
		td.getStagingToTableMappingSettings();
		
		// Create Staging Account Records 
		td.getAccountMBAs(true, true);
				    	 
		// Create Staging Contact Records 
		td.getContactMBAs(true, true);
		
		// Create Staging Subscription Records
		td.getStagingSubscriptions(true, false, td.AccountMBAs[0].MBAAccountID__c, 99999980);
		
		// Capture all the Subscription Ids
		set<string> stSubIds = new set<string>();
		
		for (MBA_Staging_Subscription__c sub : td.lstStagingSubscriptions)
		{
			stSubIds.add(sub.MBASubscriptionID__c);
		}
		
		// Validate that actual subscriptions were created
		system.assertEquals(stSubIds.size(), [SELECT count() FROM Subscription__c WHERE MBASubscriptionID__c IN : stSubIds]);	         	
		   
        test.stopTest();
	}
}