src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AppDeveloperContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary Contact</description>
        <inlineHelpText>Primary Contact</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (App Developer Contact)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Bad_MBA_Phone_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bad MBA Phone 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bad_MBA_Phone_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bad MBA Phone 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bad_MBA_Phone_3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bad MBA Phone 3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bad_MBA_Phone_4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bad MBA Phone 4</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Bad_Phone_Number__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bad Phone Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBA_Phone_1__c</fullName>
        <label>MBA Phone 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>MBA_Phone_2__c</fullName>
        <label>MBA Phone 2</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>MBA_Phone_3__c</fullName>
        <label>MBA Phone 3</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>MBA_Phone_4__c</fullName>
        <label>MBA Phone 4</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Sales_Phone__c</fullName>
        <description>Phone number entered by Sales Rep</description>
        <inlineHelpText>Use this field to store a preferred phone number for this contact.</inlineHelpText>
        <label>Sales Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The subscription is not related to the account on the opportunity</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>The subscription is not related to the account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account_ID__c</fullName>
        <description>Formula pulling the field value of unique Ifrom the associated account record. Needed for sub reporting and vlookups</description>
        <formula>IF( Account__c &lt;&gt; NULL, Account__r.Account_Unique_ID__c, NULL)</formula>
        <inlineHelpText>Salesforce Account ID</inlineHelpText>
        <label>Account Salesforce ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bad_Phone_Number__c</fullName>
        <description>Formula pulling the field value from either the associated contact or lead to show if the sales rep has marked this client info as bad data. Used in reporting.</description>
        <formula>Lead__r.Bad_Phone_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bad Phone Number</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact associated with the subscription</description>
        <inlineHelpText>Contact associated with the subscription</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Populated by a workflow capturing the associated contact or lead email address each time the contact name is changed.  Also used in case workflows to send email notifications if no lead or contact is called out on the case</description>
        <inlineHelpText>Populated by a workflow capturing the associated contact or lead email address each time the contact name is changed. Also used in case workflows to send email notifications if no lead or contact is called out on the case</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Populated by workflow if contact or lead changes</description>
        <label>zPhone</label>
        <type>Phone</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Account_ID__c</fullName>
        <formula>Contact.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account ID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Webinar__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Webinars</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Webinars</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registrant_Email__c</fullName>
        <label>Registrant Email</label>
        <type>Email</type>
    </fields>
    <label>zWebinar</label>
    <nameField>
        <label>Webinar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Contact_TriggerHandler.cls
public class Contact_TriggerHandler {

/*
    Map<String,Id> emailToContactId = new Map<String,Id>();
    Map<String,Id> emailToAccountId = new Map<String,Id>();
    //Map<String,Id> emailToOwnerId = new Map<String, Id>();
    //List<Id> updatedOwners = new List<Id>();
    
    public void getWebinar(List<Contact> contactList){

        for (Contact c : contactList){

            if (!String.isBlank(c.email)) {
              emailToContactId.put(c.email.toLowerCase(), c.Id);
              emailToAccountId.put(c.email.toLowerCase(), c.AccountId);
             // emailToOwnerId.put(c.email.toLowerCase(), c.OwnerId);             
            }
        }   

        if (!emailToContactId.keySet().isEmpty()) {

            System.debug('getWebinar : emailToContactId.keySet() ' +  emailToContactId.keySet());
            
            List<Webinar__c> dbWebinars = [SELECT Id, Contact__c, Account__c, OwnerId,Registrant_email__c FROM Webinar__c WHERE Contact__c = null AND Registrant_email__c IN : emailToContactId.keySet()];
            System.debug('getWebinar : dbWebinars ' +  dbWebinars);
            
            if (!dbWebinars.isEmpty()) {                

              for (Webinar__c webinar : dbWebinars) {

                    if (webinar.Contact__c == null) {
                      webinar.Contact__c = emailToContactId.get(webinar.Registrant_email__c.toLowerCase());
                    }
                    if (webinar.Account__c == null) {
                      webinar.Account__c = emailToAccountId.get(webinar.Registrant_email__c.toLowerCase());
                    }
                   // webinar.OwnerId = emailToOwnerId.get(webinar.Registrant_email__c.toLowerCase());
                }
                update dbWebinars;
            }
        }    
    }   

  //  public void newContactOwner(List<Contact> contactList){
  //    User webinarOwner = [SELECT Id FROM User WHERE LastName = 'Bedrock'];
  //    List<Webinar__c> dbWebinars = [SELECT Id, Contact__r.OwnerId, OwnerId FROM Webinar__c WHERE Contact__c IN : contactList];       

     //   if(dbWebinars[0].OwnerId != webinarOwner.Id){
     //     if (!dbWebinars.isEmpty()) {
                   
     //       for(Webinar__c web : dbWebinars){       
     //         web.OwnerId = web.Contact__r.OwnerId;    
     //       }           
     //       update dbWebinars;
     //     } 
     //   }         
    //}
    */
    
    public void UpdateSubsContact(Boolean isBefore, Boolean isAfter, Boolean isInsert, Boolean isUpdate,
                                    List<Contact> newList,  List<Contact> oldList, Map<Id, Contact> newMap)
    {    
 	  if (!SObjectUtils.SubscriptionLogicRunning)
 	  {
        Set<id> contIds = new Set<Id>();  
       
        for(integer i = 0; i < newList.size(); i++)
        {
            if ((newList[i].phone != null
                && (isInsert || (!isInsert &&  newList[i].phone != oldList[i].phone )))
                || (newList[i].email != null
                && (isInsert || (!isInsert &&  newList[i].email != oldList[i].email )))
                )
            { contIds.add(newList[i].Id); }
        }
        
        List <Subscription__c> subs = new List<Subscription__c>([Select s.Id, s.Phone__c, s.Email__c, s.Contact__c, s.Account__c, s.Account_ID__c 
                                                                From Subscription__c s
                                                                where Contact__c in :contIds]);
        for (Subscription__c s : subs)
        {
            Contact con = newmap.get(s.Contact__c);
            If (con <> null)
            {
                s.Email__c = con.Email;
                s.Phone__c = con.Phone;
            }
        }                                                       
        update subs;                                                        
 	  }

    }   
     
    public void UpdateOppContact(Boolean isBefore, Boolean isAfter, Boolean isInsert, Boolean isUpdate,
                                    List<Contact> newList,  List<Contact> oldList, Map<Id, Contact> newMap)
    {    
 	  if (!SObjectUtils.SubscriptionLogicRunning)
 	  {
        Set<id> contIds = new Set<Id>();  
       
        for(integer i = 0; i < newList.size(); i++)
        {
            if (newList[i].phone != null
                && (!isInsert &&  newList[i].phone != oldList[i].phone )
                )
            { contIds.add(newList[i].Id); }
        }
        
        List <Opportunity> updopps = new List<Opportunity>();
        for (Opportunity o : [Select Id, Contact_Phone__c, Contact__c
                                From Opportunity
                                where Contact__c in :contIds])
        {
            Contact con = newmap.get(o.Contact__c);
            If (con <> null && con.Phone <> o.Contact_Phone__c)
            {
               
                o.Contact_Phone__c = con.Phone;
                updopps.add(o);
            }
        }                                                       
        update updopps;                                                        
 	  }

    }   
       
 
 // Method To Set State,timeZone in Contact.
    
    public void UpdateTZ(List<Contact> consList){
        
	     AreaCodeUtility areacodes = new AreaCodeUtility();
	     areacodes.UpdateContacts(consList);
 
    }
    
  public  void updatePhoneNumbers(List<Contact> newList, List<Contact> oldList)
  {
  	
  	  List<Contact> updList = new List<Contact>();
  	  
  	  for (integer i =0; i < newList.size(); i++)
        {

            if (newList[i].Phone <> null 
                && oldList[i].Phone <> null
                 && newList[i].Phone.replaceAll('[^0-9]', '') <> oldList[i].Phone.replaceAll('[^0-9]', ''))
 //               || (newList[i].Sales_Phone__c <> oldList[i].Sales_Phone__c && newList[i].Bad_Phone_Number__c == true))
                {
 
                   if (newList[i].MBA_Phone_3__c<> null) newList[i].MBA_Phone_4__c =  oldList[i].MBA_Phone_3__c;
                   newList[i].Bad_MBA_Phone_4__c = oldList[i].Bad_MBA_Phone_3__c ;
                   if (newList[i].MBA_Phone_2__c<> null) newList[i].MBA_Phone_3__c =  oldList[i].MBA_Phone_2__c;
                   newList[i].Bad_MBA_Phone_3__c = oldList[i].Bad_MBA_Phone_2__c ;
                   if (newList[i].MBA_Phone_1__c<> null) newList[i].MBA_Phone_2__c =  oldList[i].MBA_Phone_1__c;
                   newList[i].Bad_MBA_Phone_2__c = oldList[i].Bad_MBA_Phone_1__c ;
                   if (newList[i].Phone <> null) newList[i].MBA_Phone_1__c =  oldList[i].Phone;
                   newList[i].Bad_MBA_Phone_1__c = newList[i].Bad_Phone_Number__c;
 
/*                  if (newList[i].Sales_Phone__c <> oldList[i].Sales_Phone__c && 
                      newList[i].Bad_Phone_Number__c == true)
                  {
                  	newList[i].Phone = newList[i].Sales_Phone__c;
                  } 
 */                  
                  newList[i].Bad_Phone_Number__c= false ;
                   
                }
         }
  
    }
    
    public void updAcctAppContact(List<Contact> contactList)   	
	{
	   Id partnerRecordTypeId  = Account.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Channel Partner Record Type').getRecordTypeId();
		 
		Map<Id, Contact> mapcont = new Map<Id,Contact>([select Id, AccountId, Account.AppDeveloperContact__c, Account.RecordTypeId from Contact where Id in : Trigger.New]);
 		List<Account> accts = new List<Account>();
 		
        for (Contact c : contactList)
        {
        	Contact con = mapcont.get(c.Id);
        	if (con.Account.RecordTypeId == partnerRecordTypeId
        	    && con.Account.AppDeveloperContact__c == null)
        	{
        		Account updAcc = new Account();
        		updAcc.Id = con.AccountId;
        		updAcc.AppDeveloperContact__c = con.Id;
        		accts.add(updAcc);
        	}

            
        }   
		update accts;
	}  
                                                            
}