src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SupportPin__c</fullName>
        <label>Support Pin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Community_Article__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>kb_Community_Article_kav</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>KB_Public_Community_Article_kav</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Template for community advice articles</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Needs Work Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Work Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete Article</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Community Article</label>
    <pluralLabel>Community Articles</pluralLabel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_MBA_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Contact with an email match to the MBA Account admin email address</inlineHelpText>
        <label>Primary MBA Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Support_PIN__c</fullName>
        <formula>Account.SupportPin__c</formula>
        <label>Support PIN</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <formula>Contact__r.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <description>ID specific to the plan name since plans can have different ID iterations yet maintain the same name in MBA.</description>
        <label>Product ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status from MBA</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back to Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT/QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpublished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coming Soon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft - Under Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Share Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StoreURL__c</fullName>
        <label>Store URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The subscription is not related to the account on the opportunity</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>The subscription is not related to the account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SupportPin__c</fullName>
        <description>Support Pin from the Account</description>
        <formula>Account.SupportPin__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Support Pin</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PKB_Content__c.object
<CustomObject>
    <description>The content for the Home, Contact, and Community pages of the Support Portal</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether this field should be active(display) or not</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <description>The contents of the section of the section(HTML)</description>
        <label>Content</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Text_Content__c</fullName>
        <label>Text Content</label>
        <length>25500</length>
        <type>LongTextArea</type>
    </fields>
    <label>PKB_Content</label>
    <nameField>
        <label>PKB_Content</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Support Portal Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Public__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>kb_Internal_Public_Article</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>kb_Public_Article_kav</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Needs Work Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Work Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Move Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delete Article</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Public</label>
    <pluralLabel>Public</pluralLabel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact associated with the subscription</description>
        <inlineHelpText>Contact associated with the subscription</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <description>ID specific to the plan name since plans can have different ID iterations yet maintain the same name in MBA
Populated by MBA</description>
        <inlineHelpText>ID specific to the plan name since plans can have different ID iterations yet maintain the same name in MBA</inlineHelpText>
        <label>MBA Product ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StoreURL__c</fullName>
        <description>URL of the BC trial or store populated by MBA</description>
        <inlineHelpText>URL of the BC trial or store populated by MBA</inlineHelpText>
        <label>MBA Store URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Support_PIN__c</fullName>
        <description>Formula pulling the pin value from the associated account or lead</description>
        <formula>IF(
ISBLANK(Account__r.SupportPin__c), Lead__r.SupportPin__c ,Account__r.SupportPin__c)</formula>
        <label>Support Pin</label>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DLUtility.cls
public without sharing class DLUtility {

     //This method will bring the contact record using account id
    
    public static List<Contact> getContactFromAcct(Id accId){
        
        List<Contact> cons = new List<Contact>([select Id, firstName, lastName, AccountId, email from Contact 
                                                where AccountId = :accId
                                                AND Primary_MBA_Contact__c = true]);
        
         return cons;

    }
      //This method will bring the contact record using account id
    
    public static Contact findPrimaryContactFromAcct(Id accId){
        
        List<Contact> cons = new List<Contact>([select Id, firstName, lastName, AccountId, email from Contact 
                                                where AccountId = :accId
                                                AND Primary_MBA_Contact__c = true Limit 1]);
        
         return cons[0];

    }   
    //This method will bring the subscription
    
    public static Id getSubfromStoreurl(String formUrl, String supportpin){
        
        String fullStoreUrl = 'http://' + formUrl;
        List<Subscription__c> subs = new List<Subscription__c> ([SELECT Id, Account__r.Id,  Contact__c,  Account__r.SupportPIN__c, StoreURL__c FROM Subscription__c
                                                                WHERE (StoreURL__c = :formUrl OR StoreURL__c = :fullStoreUrl)
                                                                AND Support_PIN__c = :supportpin 
                                                                AND Status__c = 'Active' LIMIT 1]);
         if (!subs.isEmpty())
           { return subs[0].Account__r.ID;}
           else 
           {return null;}

    }
    
 //This method will bring the opportunity with store url and support pin
    
    public static Opportunity getOppfromurlpin(String formUrl, String supportpin){
        
        Id ProfOppRecordTypeId =  Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Professional Services').getRecordTypeId();
	    Id UpgradeRecordTypeId = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_Upgrade).getRecordTypeId();
	    Id AppRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_App).getRecordTypeId();
        
        Set<Id> notStoreRecIds = new Set<Id>();
	    notStoreRecIds.add(AppRecordTypeId);
	    notStoreRecIds.add(ProfOppRecordTypeId);
	    notStoreRecIds.add(UpgradeRecordTypeId);

        String fullStoreUrl = 'http://' + formUrl;
        List<Opportunity> opps = new List<Opportunity> ([SELECT Id, AccountId,   StoreURL__c, Subscription__c, Contact__c, Contact_Email__c , ProductId__c
        														FROM Opportunity 
        														WHERE SupportPIN__c =: supportpin AND (StoreURL__c = :formUrl OR StoreURL__c = :fullStoreUrl)
                    											AND Status__c = 'Active' 
                    											AND RecordTypeId not in :notStoreRecIds Limit 1 ]);
           if (!opps.isEmpty())
           { return opps[0];}
           else 
           {return null;}

    }
    
   //This method will bring the subscription with store url and support pin
    
    public static Subscription__c getSubfromurlpin(String formUrl, String supportpin){
        
        String fullStoreUrl = 'http://' + formUrl;
        List<Subscription__c> subs = new List<Subscription__c> ([SELECT Id, Account__c, Account__r.OwnerId, Support_PIN__c, StoreURL__c, Contact__c, Contact__r.Email, ProductId__c 
        														FROM Subscription__c 
        														WHERE Support_PIN__c =: supportPIN AND (StoreURL__c = :formUrl OR StoreURL__c = :fullStoreUrl)
		                    									AND Status__c = 'Active' LIMIT 1]);
         if (!subs.isEmpty())
           { return subs[0];}
           else 
           {return null;}

    }

    //This method will bring the contact record using account id and email. If it doesn't exist create it.
    
    public static Contact findContactByEmailAcct(Id accId, string emailaddress, string fname, string lname){
        
        Contact con = new Contact();
        Id accountOwnerId ;
        List<Contact> cons = new List<Contact>([select Id, firstName, lastName, AccountId, email, Account.OwnerId from Contact 
                                                where AccountId = :accId 
                                                ]);
         for (Contact c :cons)
         {
         	accountOwnerId = c.Account.OwnerId;
         	if (c.Email == emailaddress)
         	con = c;
         }
         return con;
    }

    public static User getUserbyName( String userName) {
 
    List<User> cusers;
    if(userName <> null) 
    {
       cusers = [SELECT Id,Email, Department FROM User WHERE name =:userName and isActive = true ];
    }
    if (cusers.isEmpty())
    {
       cusers = [SELECT Id,Email, Department FROM User WHERE name =:userName limit 1];
    }
    
     return cusers[0];
  }

    
    public static Map<String, PKB_Content__c > getPKBContentMap() {
 
    Map<String, PKB_Content__c > mapPKBContent = new Map<String, PKB_Content__c>();
    
    for ( PKB_Content__c pkbc :[Select p.Name, p.Id, p.Content__c, Text_Content__c, p.Active__c From PKB_Content__c p where Active__c = true])
    { 
         mapPKBContent.put(pkbc.Name, pkbc);
          
    }
    return mapPKBContent;
  }
    
    public static String  getDataCategoryByArtId(Id artId) 
    {
        List <Public__kav> peaList = new List <Public__kav> ([Select p.Id, (Select DataCategoryName From DataCategorySelections) From Public__kav p WHERE PublishStatus = 'Online' AND Language = 'en_US' and KnowledgeArticleId =:artId]) ;
        String dcsName ='';
        for (Public__kav pea :peaList)
        {
            for (Public__DataCategorySelection dcs : pea.DataCategorySelections)
            {
                dcsName = dcs.DataCategoryName;
            }
            
        }
        
        return dcsName;
    }
     
     public static String  getDataCategoryByArtIdUniv(Id artId) 
    {
        List <University__kav> peaList = new List <University__kav> ([Select p.Id, (Select DataCategoryName From DataCategorySelections) From University__kav p WHERE PublishStatus = 'Online' AND Language = 'en_US' and KnowledgeArticleId =:artId]) ;
        String dcsName ='';
        for (University__kav pea :peaList)
        {
            for (University__DataCategorySelection dcs : pea.DataCategorySelections)
            {
                dcsName = dcs.DataCategoryName;
            }
            
        }
        
        return dcsName;
    }
    
     public static String  getDataCategoryByArtIdComm(Id artId) 
    {
        List <Community_Article__kav> peaList = new List <Community_Article__kav> ([Select p.Id, (Select DataCategoryName From DataCategorySelections) From Community_Article__kav p WHERE PublishStatus = 'Online' AND Language = 'en_US' and KnowledgeArticleId =:artId]) ;
        String dcsName ='';
        for (Community_Article__kav pea :peaList)
        {
            for (Community_Article__DataCategorySelection dcs : pea.DataCategorySelections)
            {
                dcsName = dcs.DataCategoryName;
            }
            
        }
        
        return dcsName;
    }
    public static String  getDataCategoryByArtId(Id artId, string articleTypeName) 
    {
        String dcsName ='';
        if (articleTypeName.contains('Public')) dcsName = getDataCategoryByArtId(artId);
        else
        if (articleTypeName.contains('University')) dcsName = getDataCategoryByArtIdUniv(artId);
        else
        if (articleTypeName.contains('Community')) dcsName = getDataCategoryByArtIdComm(artId);
               
        return dcsName;
    }
    
    public static List <University__kav>  getUnivArticles(String datacat) 
    {
        List <University__kav> peaList = new List <University__kav> ([Select Id, UrlName, Short_Title__c, Short_Description__c , Sort_Order__C ,Thumbnail_Image_URL__c, Video_Duration__c, (Select DataCategoryName From DataCategorySelections) 
                                                                        From University__kav p 
                                                                        WHERE PublishStatus = 'Online' AND Language = 'en_US'
                                                                        ORDER by Sort_Order__c]) ;
        List <University__kav> artList = new List <University__kav>();
        
        for (University__kav pea :peaList)
        {
            for (University__DataCategorySelection dcs : pea.DataCategorySelections)
            {
                if (dcs.DataCategoryName == datacat)
                artList.add(pea);
            }
            
        }
        
        return artList;
    }
    
    public static Map<String, List<University__kav>>  getUnivArticles() 
    {
        Map<String, List<University__kav>>  mapArtList = new Map <String, List<University__kav>>();
        
        List <University__kav> peaList = new List <University__kav> ([Select Id, UrlName, Short_Title__c, Short_Description__c , Sort_Order__C ,Thumbnail_Image_URL__c, Video_Duration__c, (Select DataCategoryName From DataCategorySelections) 
                                                                        From University__kav p 
                                                                        WHERE PublishStatus = 'Online' AND Language = 'en_US'
                                                                        ORDER by Sort_Order__c]) ;
        List <University__kav> artList1 = new List <University__kav>();
        List <University__kav> artList2 = new List <University__kav>();
        List <University__kav> artList3 = new List <University__kav>();
        List <University__kav> artList4 = new List <University__kav>();
        
        String dcname1 = Label.University_Article_Category_1;
        String dcname2 = Label.University_Article_Category_2;
        String dcname3 = Label.University_Article_Category_3;
        String dcname4 = Label.University_Article_Category_4;
        
        for (University__kav pea :peaList)
        {
            
            for (University__DataCategorySelection dcs : pea.DataCategorySelections)
            {
                
                
                if (dcs.DataCategoryName == dcname1)
                    artList1.add(pea);
                else if (dcs.DataCategoryName == dcname2)
                    artList2.add(pea);
                else if (dcs.DataCategoryName == dcname3)
                    artList3.add(pea);
                else if (dcs.DataCategoryName == dcname4)
                    artList4.add(pea);
            }
            
        }
        
        mapArtList.put(dcname1, artList1);
        mapArtList.put(dcname2, artList2);
        mapArtList.put(dcname3, artList3);
        mapArtList.put(dcname4, artList4);
        
        return mapArtList;
    }
    
}