src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>gaClientID__c</fullName>
        <label>GA Client ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>gaClientID__c</fullName>
        <label>GA Client ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>gaClientID__c</fullName>
        <label>GA Client ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Client_Prospect</fullName>
        <active>true</active>
        <businessProcess>Client Process</businessProcess>
        <description>Store trial leads - convert to Clients / Accounts upon purchase</description>
        <label>Client Prospect</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MBA_Staging_Subscription__c.object
<CustomObject>
    <description>Used for the integration between MBA and Salesforce. Fields are to be read only for all users and object is only visible to admins.</description>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MonthlyRecurringRevenue__c</fullName>
        <label>Monthly Recurring Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deleted in MBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>MBA Staging Subscription</label>
    <nameField>
        <displayFormat>MSS-{0000}</displayFormat>
        <label>MBA Staging Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MBA Staging Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GACalloutsTest.cls
/**
 * GACalloutsTest
 * Author: Steve O'Neal
 * Purpose: For testing GAUtility and GARequestMock
 * Ticket: BAP-3444
 *
 * Updates:
 * *********
 * 
 */
@isTest
public class GACalloutsTest {

    /**
     * Test leads
     * @author Steve O'Neal
     * @date   2016-05-25
     * @ticket link          https://jira.bigcommerce.com/browse/BAP-3444
     * @return nothing
     */
	static testmethod void testLeadHits() 
    {
    	Test.setMock(HttpCalloutMock.class, new GARequestMock());
        Test.startTest();

        // Create a bevy of leads to test with
        List<lead> testLeads = TestDataFactory.createTestLeads(4, true, TestDataFactory.LeadRecordType.Client_Prospect);


        ////////////////////////////////////////////////////////
        // Convert lead to an account with a Google Analytics //
        ////////////////////////////////////////////////////////
        LeadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];

        List<Database.LeadConvert> leadConversions = new List<Database.LeadConvert>();
        Database.LeadConvert lc = new database.LeadConvert();
    	lc.setLeadId( testLeads[0].id );
    	lc.setConvertedStatus( convertStatus.MasterLabel );
    	leadConversions.add( lc );
     
    	List<Database.LeadConvertResult> results = Database.convertLead( leadConversions );
    	System.assert(results[0].isSuccess());

        // get the account and contact from the converted lead  	
    	Contact testContact = [SELECT Id, AccountId, Email, GAClientID__c FROM Contact WHERE GAClientID__c = :testLeads[0].GAClientID__c];     
    	 
    	Account testAcct = [SELECT Id, GAClientID__c FROM Account WHERE Id = :testContact.AccountId];     
        system.debug(testAcct.GAClientID__c);
		

        /////////////////////////////////////////////
        // Convert a lead into an existing Account //
        /////////////////////////////////////////////
		Database.LeadConvert lc2 = new  database.LeadConvert();
		lc2.setLeadId(testLeads[1].Id);

   		lc2.setConvertedStatus(convertStatus.MasterLabel);
		lc2.setAccountId(testContact.AccountId);
		
		Database.LeadConvertResult lcr2 = Database.convertLead(lc2);
		System.assert(lcr2.isSuccess());
		
		List<Contact> testContacts = [SELECT Id, AccountId FROM Contact WHERE AccountId = :testContact.AccountId];     
 	

        ////////////////////////////////
        // Create MBA Staging Records //
        ////////////////////////////////
        List<MBA_Staging_Subscription__c> mbaSubs = TestDataFactory.createTestMBAStagingSubscriptionsAccountsContacts(1);
        System.debug(mbaSubs.size());
        System.debug(mbaSubs[0].MBAAccountID__c);
 		mbaSubs[0].Status__c = 'Terminated';
 		mbaSubs[0].MonthlyRecurringRevenue__c = 0.00;
 		update mbaSubs;
        test.stoptest();
    }
    

    /**
     * Test leads
     * @author Steve O'Neal
     * @date   2016-05-25
     * @ticket link          https://jira.bigcommerce.com/browse/BAP-3444
     * @return nothing
     */
    static testmethod void testLeadHits2() 
    {
    	Test.setMock(HttpCalloutMock.class, new GARequestMock());
        test.startTest();
        
        List<lead> testLeads = TestDataFactory.createTestLeads(1, true, TestDataFactory.LeadRecordType.Client_Prospect);
		
		testLeads[0].Status = 'Qualified';
		update testLeads[0];
		
		testLeads[0].Status = 'Unqualified';
		update testLeads[0];
		
		testLeads[0].Status = 'Open';
		update testLeads[0];

        test.stoptest();
    }
    
    
    /**
     * Test negative results for greater code coverage
     * @author Steve O'Neal
     * @date   2016-05-25
     * @ticket link          https://jira.bigcommerce.com/browse/BAP-3444
     * @return nothing
     */
    static testMethod void testExceptions()
    {
    	Test.setMock(HttpCalloutMock.class, new GARequestMock());
    	// make sure that the settings are reset
    	GAUtility.APISettings = null;
    	
    	try
    	{
    		List<String> httpRequests = GAUtility.getGARequestStrings(null, null);
	    	// make sure that the settings are reset
	    	GAUtility.APISettings = null;
	    	GAUtility.GARequest(httpRequests);
    	}
    	catch(Exception e)
    	{
    		
    	}

    	try
    	{
	    	GAUtility.GARequest(GAUtility.getGARequestStrings(GAUtility.GAAction.subscription_termination, null));
	    	// if an exception was not thrown, we want to fail the test
	    	System.assert(false);
    	}
    	catch(Exception e)
    	{
    		
    	}

    	try
    	{
            User currentUser = [Select Id from User where Id = :UserInfo.getUserId()];
	    	GAUtility.GARequest(GAUtility.getGARequestStrings(GAUtility.GAAction.subscription_termination, currentUser));
    	}
    	catch(Exception e)
    	{
    		
    	}
    }



}