src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Change_Owner__c</fullName>
        <label>Change Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Support Queue</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Me</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>API Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Out of Scope</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Design Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager Callback</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Account on the Case does not match the Account on the Opportunity</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Opportunity.AccountId</valueField>
            </filterItems>
            <infoMessage>Select Opportunity related to the Account</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Cases</relationshipLabel>
        <relationshipName>OpportunityCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the store this case is in reference to</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Billing</fullName>
        <active>true</active>
        <businessProcess>Billing Support Process</businessProcess>
        <description>For account merges, splits, credits, refunds and invoices</description>
        <label>Billing</label>
    </recordTypes>
    <recordTypes>
        <fullName>Cancellations</fullName>
        <active>true</active>
        <businessProcess>Cancellation Support Process</businessProcess>
        <description>For all cancellation requests and saves</description>
        <label>Cancellations</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CaseQueueRouting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Queue names and IDs used for picklist on Web2Case form.  Use the Name field to define sort order in the picklist.</description>
    <fields>
        <fullName>Queue_ID__c</fullName>
        <label>Queue ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <label>Queue Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Queue Routing</label>
</CustomObject>

src/objects/Opp_RecordTypes_for_Case_Creation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Opp_RecordTypes_to_Show__c</fullName>
        <description>Enter the Opportunity RecordTypes (separated by comma) that needs to be shown when a Case is created through the Service Console.</description>
        <inlineHelpText>Enter the Opportunity RecordTypes (separated by comma) that needs to be shown when a Case is created through the Service Console.</inlineHelpText>
        <label>Opp RecordTypes to Show</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Statuses_to_show__c</fullName>
        <description>Enter the Opportunity Statuses (Separated by Comma) that needs to be shown when a case is created through the Service Console.</description>
        <inlineHelpText>Enter the Opportunity Statuses (Separated by Comma) that needs to be shown when a case is created through the Service Console.</inlineHelpText>
        <label>Opp Statuses to show</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Opps_with_Blank_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enable Opportunities with blank Statuses to be shown when a Case is created through the Service Console.</description>
        <inlineHelpText>Enable Opportunities with blank Statuses to be shown when a Case is created through the Service Console.</inlineHelpText>
        <label>Show Opps with Blank Status</label>
        <type>Checkbox</type>
    </fields>
    <label>Opp RecordTypes for Case Creation</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>New_Product_Plan__c</fullName>
        <description>Friendly product plan name (ie not what MBA/BMP is sending)</description>
        <formula>IF( ProductID__c =&apos;65&apos;, &apos;Silver NEXT&apos;, 
IF(ProductID__c =&apos;90&apos;, &apos;Silver NEXT v2 (29.95)&apos; , 
IF (ProductID__c =&apos;66&apos;, &apos;Gold NEXT&apos; , 
IF (ProductID__c =&apos;67&apos;, &apos;Platinum NEXT&apos; , 
IF (ProductID__c =&apos;118&apos;, &apos;Standard Plan&apos; ,  
IF (ProductID__c =&apos;119&apos;, &apos;Plus Plan&apos; ,
IF (ProductID__c =&apos;101&apos;, &apos;Standard&apos; , 
IF (ProductID__c =&apos;130&apos;, &apos;Standard - $14 Test&apos; , 
IF (ProductID__c =&apos;129&apos;, &apos;Standard - $10 Test&apos; ,
IF (ProductID__c =&apos;131&apos;, &apos;15 Day Free Trial - $10 Test&apos; ,
IF (ProductID__c =&apos;132&apos;, &apos;15 Day Free Trial - $14 Test&apos; ,
Product__c ) ))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Friendly product plan name (ie not what MBA/BMP is sending)</inlineHelpText>
        <label>New Product Plan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status from MBA</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back to Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT/QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpublished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coming Soon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft - Under Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Share Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StoreURL__c</fullName>
        <label>Store URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The subscription is not related to the account on the opportunity</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>The subscription is not related to the account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Was used by Acq on forecast subs but can probably be deleted now</description>
        <label>zOpportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StoreURL__c</fullName>
        <description>URL of the BC trial or store populated by MBA</description>
        <inlineHelpText>URL of the BC trial or store populated by MBA</inlineHelpText>
        <label>MBA Store URL</label>
        <type>Url</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OppForConsoleController.cls
public class OppForConsoleController 
{   
    private String objectType = '';
    private String acctId = '';
    private String contactId = '';
    private String leadId = '';
    private String leadName = '';
    private String oppId = '';
    private String oppName = '';
    private String subId = '';
    private Id selectedOppId = null;
    
    private string selectedOppName = null;
    private Id selectedSubId = null;
    private string selectedSubName = null;
    public boolean caseCreated {get;set;}
    public string errorMsg {get;set;}
    public String CaseSubject {get; set;}
    public String CallerName {get; set;}
    public List<String> ContactNames {get; set;}
    public string errorMsgCaseSubject {get;set;}
    
    private list<OpportunityWrapper> Opps = new list<OpportunityWrapper>();

    public String passedInOppId {get;set;}
    public String passedInSubId {get;set;}
    public Case newCase {get;set;}
    public Id newCaseId {get;set;}
    public Id caseRecordTypeId {get;set;}
    public String getObjectType()
    {
        return objectType;
    }
    public String getCaseSubject() 
    { 
        return CaseSubject; 
    } 
    public String getCallerName() 
    { 
        return CallerName; 
    } 
	public List<String> getContactNames() 
    { 
        return ContactNames; 
    } 
    public void setAcctId(String n)
    {
        acctId = n;
    }
    
    public String getAcctId()
    {
        return acctId;
    }
    
    public void setContactId(String n)
    {
        contactId = n;
    }
    
    public String getContactId()
    {
        return contactId;
    }
    
    public String getLeadId()
    {
        return leadId;
    }
    
    public String getLeadName()
    {
        return leadName;
    }
    public String getErrorMsg()
    {
        return ErrorMsg;
    }
    public String contactPrefix
    {
        get
        {
            return Contact.sObjectType.getDescribe().getKeyPrefix();
        }
    }
    
    public String accountPrefix
    {
        get
        {
            return Account.sObjectType.getDescribe().getKeyPrefix();
        }
    }
 
    public String oppPrefix
    {
        get  { return Opportunity.sObjectType.getDescribe().getKeyPrefix(); }
    }
    
    //Map all Recordtype Id and Name
    public Map<Id,String> caseRecordTypeName
    {
        get{
            Map<Id, String> CaseRecordTypesMap = new Map<Id,String>();
        	Schema.DescribeSObjectResult R = Case.SObjectType.getDescribe();
            List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos();
            if(RT.size()>1){
                for(RecordTypeInfo rec:RT){
                    CaseRecordTypesMap.put(rec.getRecordTypeId(),rec.getName());                
                }
            }
            return CaseRecordTypesMap;
        }
        
    }
    
    //Get the Custom Settings that has holds the defenition of what 
    //Opportunities to show during case creation
    public Opp_RecordTypes_for_Case_Creation__c getOppstoShow
    {
        get { return Opp_RecordTypes_for_Case_Creation__c.getOrgDefaults(); }
    }
    
    //Get the Opportunity Record Types we want to show during case creation
    //This is defined in a custom setting Opp_RecordTypes_for_Case_Creation 
    public Set<String> OppRTstoShow
    {
        get {
            Set<String> setString = new Set<String>();
            if(getOppstoShow.Opp_RecordTypes_to_Show__c!=null){
                for(String key:getOppstoShow.Opp_RecordTypes_to_Show__c.split(',')){
                    setString.add(key);
                }
            }
            return setString;
        }
    }
    
    //Get the Opportunity Statuses we want to show during case creation
    //This is defined in a custom setting Opp_RecordTypes_for_Case_Creation 
    public Set<String> OppStatusestoShow
    {
        get {
            Set<String> setString = new Set<String>();
            if(getOppstoShow.Opp_Statuses_to_show__c!=null){
                for(String key:getOppstoShow.Opp_Statuses_to_show__c.split(',')){
                    setString.add(key);
                }
            }
            if(getOppstoShow.Show_Opps_with_Blank_Status__c){
                setString.add('');
                setString.add(null);
            }
            return setString;
        }
    }
  
    public String getSelectedOppName()
    {
        return selectedOppName;
    }
    
    public Id getSelectedOppId()
    {
        return selectedOppId;
    }
    
    public String getSelectedSubName()
    {
        return selectedSubName;
    }
    
    public Id getSelectedSubId()
    {
        return selectedSubId;
    }
 

    public list<OpportunityWrapper> getOpps()
    {
        return Opps;
    }
    
    public OppForConsoleController()
    {
        string recId = ApexPages.currentPage().getParameters().get('Id');
        acctId = '';
        contactId = '';
        errorMsg ='';
        oppId = '';
        objectType = '';

        // Check which object this page is loading from
        if (recId != null)
        {
            if (recId.startsWith(accountPrefix))
            { 
                acctId = recId;
                objectType = 'Account';         
            }
            else if (recId.startsWith(contactPrefix))
            {
                contactId = recId;
                objectType = 'Contact';
                
                acctId = [SELECT AccountId FROM Contact WHERE Id = :contactId].AccountId;
                
                List<Contact> cList= new List<contact>([select name from contact where accountid = :acctId]);
                ContactNames = new List<String>();
                if(!cList.isEmpty()){
                    for(contact con:cList){
                        ContactNames.add(con.Name);    
                    }
                }
            }

            else if (recId.startsWith(oppPrefix))
            {               
                oppId = recId;
                oppName = [SELECT Name FROM Opportunity WHERE Id = :oppId].Name;
                objectType = 'Opportunity';
            }
        }
    }
    
    public PageReference CreateCase()
    {
 		PageReference currentPage = ApexPages.currentPage();    
        Map<String,Id> caseQueueMap = new Map<String,Id>();
        List<CaseQueueRouting__c> csList = CaseQueueRouting__c.getAll().values();
        for(CaseQueueRouting__c cs:csList){
            caseQueueMap.put(cs.Queue_Name__c, cs.Queue_ID__c);
        }
        If (caseCreated == true) 
        {
        	errorMsg= 'Case already created, refresh the page to create another case';
        	return null;
        }
        If(CaseSubject == null || CaseSubject == ''){
            errorMsgCaseSubject = 'Please enter a Subject for the Case';
        	newCaseId = null;
        } else{
            If(CaseSubject.length()>255){
                errorMsgCaseSubject = 'Please type in 255 characters or less in the Subject';
            } else {
                        If (selectedOppId == null)
                        {
                            errorMsg= 'Please select an Opportunity!';
                            system.debug('### no selected');
                            newCaseId = null;
                            
                        }
                        else {

                            Case newCase = new Case(subject = CaseSubject,
                                            Caller_name__c = CallerName,
                                            origin = 'Phone',
                                            accountid= acctId,
                                            Opportunity__c = selectedOppId,
                                            ContactId = contactId,
                                            Change_Owner__c = 'Tier 2', 
                                            Subscription__c = selectedSubId,
                                            RecordTypeId = caseRecordTypeId
                                            );

                            if(caseRecordTypeName.get(caseRecordTypeId)=='Billing'||caseRecordTypeName.get(caseRecordTypeId)=='Cancellations'){
                                newCase.Ownerid = caseQueueMap.get('Billing');
                            } else {
                                newCase.Ownerid = caseQueueMap.get('Tier 2 Support Queue');
                            }
                             insert newCase;  
                             newCaseId = newCase.Id;
                             errorMsg= 'Case created ....';
                             system.debug('### new case id  '+newCaseId);
                             caseCreated = true;
                            }
            	}
            }
            return null;
    }
    public PageReference LoadOpportunities()
    {
        list<Opportunity> lstOpps = new list<Opportunity>();
        Opps = new list<OpportunityWrapper>();
        OpportunityWrapper wrapOpp;
        
        Id ProfOppRecordTypeId =  Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Professional Services').getRecordTypeId();
        Id UpgradeRecordTypeId = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_Upgrade).getRecordTypeId();
        Id AppRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_App).getRecordTypeId();
   		Set<Id> notStoreRecIds = new Set<Id>();
        notStoreRecIds.add(AppRecordTypeId);
        notStoreRecIds.add(ProfOppRecordTypeId);
        notStoreRecIds.add(UpgradeRecordTypeId);

        if (oppId != null && oppId != '')
        {           
            lstOpps = [SELECT Id, Name, StoreURL__c, New_Product_Plan__c, Product__c, Status__c, AccountId, Subscription__r.Id, Subscription__r.Name, Contact__r.Id, RecordType.Name, OppSortNumber__c
                       FROM Opportunity
                       WHERE RecordType.Name in :OppRTstoShow
                       AND Id = :oppId
                       ORDER BY OppSortNumber__c ASC];//Sort the Opportunities listed based on this field
            
            for (Opportunity s : lstOpps)
            {
                acctId = s.AccountId;
                contactId = s.Contact__r.Id;
                passedInOppId = s.Id;
				wrapOpp = new OpportunityWrapper(s, false);
				Opps.add(wrapOpp);
            }
            
            CaptureOpp();
        }
        else
        if (acctId != null && acctId != '')
        {           
            lstOpps = [SELECT Id, Name, StoreURL__c, New_Product_Plan__c, Product__c, Status__c, AccountId, Subscription__r.Id, Subscription__r.Name, RecordType.Name, OppSortNumber__c
                       FROM Opportunity
                       WHERE RecordType.Name in :OppRTstoShow
                       AND AccountId = :acctId
                       AND Status__c in :OppStatusestoShow
                       ORDER BY OppSortNumber__c ASC];
            
            
            for (Opportunity s : lstOpps)
            {
				wrapOpp = new OpportunityWrapper(s, false);
                Opps.add(wrapOpp);
            }
            
            if (lstOpps.size() == 1) 
            {
              	passedInOppId = lstOpps[0].Id;
            	CaptureOpp();
            }
        }
        
        Schema.DescribeSObjectResult R = Case.SObjectType.getDescribe();
		List<Schema.RecordTypeInfo> RT = R.getRecordTypeInfos();
        if(RT.size()>1){
            for(RecordTypeInfo rec:RT){
                //isMaster() method failed with the error :Method does not exist or incorrect signature: [Schema.RecordTypeInfo].isMaster() 
                //So using the getName() in the condition 
                if(rec.isAvailable()&&rec.getName()!='Master'&&rec.isDefaultRecordTypeMapping()){
                    caseRecordTypeId = rec.getRecordTypeId();
                }
            }
        } else {
            caseRecordTypeId = RT[0].getRecordTypeId();
        }
        
        return null;
    }
    
    public void CaptureOpp()
    {
        if (passedInOppId != null)
        {
            // Set the selected Opp variable
            for (OpportunityWrapper wrap : Opps)
            {                       
                if (wrap.objOpp.Id != passedInOppId)
                {
                    wrap.isSelected = false;
                }
                else
                {

                    wrap.isSelected = true;
                    
                    selectedOppId = wrap.objOpp.Id;
                    selectedOppName = wrap.objOpp.Name;
                    selectedSubId = wrap.objOpp.Subscription__r.Id;
                    selectedSubName = wrap.objOpp.Subscription__r.Name;
                }
            }

        } 
        
        
    }
    
    public void SelectOpp()
    {
        Id  OppId = ApexPages.currentPage().getParameters().get('selId');

        if (OppId != null)
        {
            // Set the selected Opp variable
            for (OpportunityWrapper wrap : Opps)
            {                       
                if (wrap.objOpp.Id != OppId)
                {
                    wrap.isSelected = false;
                }
                else
                {
                    // If the Opp has just been selected the set the selected Opp variable to the Opp id, otherwise clear it
                    if (wrap.isSelected)
                    {
                        selectedOppId = wrap.objOpp.Id;
                        selectedOppName = wrap.objOpp.Name;
                        selectedSubId = wrap.objOpp.Subscription__r.Id;
                        selectedSubName = wrap.objOpp.Subscription__r.Name;
                    }
                    else
                    {
                        selectedOppId = null;
                        selectedOppName = null;
                    }
                }
            }
        }       
    }
    
    public void doNothing()
    {
     return;
    }
    
    public class OpportunityWrapper
    {
        public boolean isSelected {get; set;} 
        public boolean isSelectable {get; set;} 
        public String OppRecordType {get; set;} 
        public Opportunity objOpp {get; set;} 
        public Opp_RecordTypes_for_Case_Creation__c getOppstoShow
    	{
        	get { return Opp_RecordTypes_for_Case_Creation__c.getOrgDefaults(); }
    	}
        
        //Get the Opportunity Record Types that are selectable on the Case Form. 
        //These are defined in the Custom Setting Opp_RecordTypes_for_Case_Creation__c
        public Set<String> SelectableOppRTs
        {
            get {
                Set<String> setString = new Set<String>();
                if(getOppstoShow.Selectable_Opp_RecordTypes__c!=null){
                    for(String key:getOppstoShow.Selectable_Opp_RecordTypes__c.split(',')){
                        setString.add(key);
                    }
                }
                return setString;
            }
        }
        
        //Get the Opportunity Statuses that are selectable on the Case Form. 
        //These are defined in the Custom Setting Opp_RecordTypes_for_Case_Creation__c
        public Set<String> SelectableOppStatuses
        {
            get {
                Set<String> setString = new Set<String>();
                if(getOppstoShow.Selectable_Opp_Statuses__c!=null){
                    for(String key:getOppstoShow.Selectable_Opp_Statuses__c.split(',')){
                        setString.add(key);
                    }
                }
                if(getOppstoShow.Select_Opps_with_Blank_Status__c){
                	setString.add('');
                    setString.add(null);
            	}
                return setString;
            }
        }
        
        //Based on the Selectable Opportunity Record Types and Statuses 
        //set the attribute isSelectable which will be used in the OppForConsole VF Page
        //to decide whether it's a selectable opportunity or not
        public OpportunityWrapper (Opportunity Opp, boolean selected)
        {
            this.isSelected = selected;
            if(SelectableOppRTs.contains(opp.RecordType.Name)&&SelectableOppStatuses.contains(opp.Status__c)){
                this.isSelectable = true;
            } else {
                this.isSelectable = false;
            }
            this.OppRecordType = opp.RecordType.Name;
            this.objOpp = Opp;
        }
    }
   
    //@author: Bala Rajagopal
    //@date: 08/11/16
    //Get all the Case Record Types accessible by the current user for selection during case creation in the service console.
    public static Map<String, Id> getAvailableCaseRecordTypes(){
        Schema.DescribeSObjectResult Res = Case.SObjectType.getDescribe();
		List<Schema.RecordTypeInfo> RT = Res.getRecordTypeInfos();
        List<String> names = new List<String>();
        Map<String,id> RTmap = new Map<String,id>();
        if(RT.size()>1){
            for(RecordTypeInfo rec:RT){
                //isMaster() method failed with the error :Method does not exist or incorrect signature: [Schema.RecordTypeInfo].isMaster() 
                //So using the getName() in the condition 
                if(rec.isAvailable()&&rec.getName()!='Master'){
                    names.add(rec.getName());
                    RTmap.put(rec.getName(),rec.getRecordTypeId());
                }
            }
        } else {
            RTmap.put(RT[0].getName(),RT[0].getRecordTypeId());
        }
        return RTmap;
    }

}