src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Client_Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Date of the client&apos;s first store purchase with Bigcommerce</description>
        <inlineHelpText>Date of the client&apos;s first store purchase with Bigcommerce</inlineHelpText>
        <label>Client Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Indicates whether the account exists in MBA or BMP</description>
        <inlineHelpText>Indicates whether the account exists in MBA or BMP</inlineHelpText>
        <label>Provisioning System</label>
        <picklist>
            <picklistValues>
                <fullName>BMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SupportPin__c</fullName>
        <label>Support Pin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/CaseQueueRouting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Queue names and IDs used for picklist on Web2Case form.  Use the Name field to define sort order in the picklist.</description>
    <fields>
        <fullName>Queue_ID__c</fullName>
        <label>Queue ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <label>Queue Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Queue Routing</label>
</CustomObject>

src/objects/CaseSubmissionSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for custom Web2Case and LiveAgent pre-Chat code</description>
    <fields>
        <fullName>Case_Origin__c</fullName>
        <label>Case Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Record_Type__c</fullName>
        <inlineHelpText>Insert the Case RecordType ID in this field</inlineHelpText>
        <label>Case Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Record_Type__c</fullName>
        <description>The default Record Type for Contacts created in the external web submission process</description>
        <inlineHelpText>The default Record Type for Contacts created in the external web submission process</inlineHelpText>
        <label>Contact Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Support_Account_ID__c</fullName>
        <description>Default Account ID used for initially orphaned Contacts created from the Live Agent pre-Chat form</description>
        <inlineHelpText>Default Account ID used for initially orphaned Contacts created from the Live Agent pre-Chat form</inlineHelpText>
        <label>Default Support Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Support_Owner_ID__c</fullName>
        <description>Default User ID for Contacts created in the Live Agent pre-Chat form</description>
        <inlineHelpText>Default User ID for Contacts created in the Live Agent pre-Chat form</inlineHelpText>
        <label>Default Support Owner ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LiveAgent_Button_Name__c</fullName>
        <description>The Developer name of the LiveAgent Button used in this Case Submission Setting entry</description>
        <inlineHelpText>The Developer name of the LiveAgent Button used in this Case Submission Setting entry</inlineHelpText>
        <label>LiveAgent Button Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Redirect_URL__c</fullName>
        <description>Use the relative path of a Sites VF page with a preceeding slash &quot;/&quot;</description>
        <inlineHelpText>Use the relative path of a Sites VF page with a preceeding slash &quot;/&quot;</inlineHelpText>
        <label>Redirect URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Submission Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Source__c</fullName>
        <description>Indicates whether the account exists in MBA or BMP</description>
        <inlineHelpText>Indicates whether the account exists in MBA or BMP</inlineHelpText>
        <label>Provisioning System</label>
        <picklist>
            <picklistValues>
                <fullName>BMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_PIN__c</fullName>
        <formula>Account.SupportPin__c</formula>
        <label>Support PIN</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact associated with the subscription</description>
        <inlineHelpText>Contact associated with the subscription</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Populated by a workflow capturing the associated contact or lead email address each time the contact name is changed.  Also used in case workflows to send email notifications if no lead or contact is called out on the case</description>
        <inlineHelpText>Populated by a workflow capturing the associated contact or lead email address each time the contact name is changed. Also used in case workflows to send email notifications if no lead or contact is called out on the case</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <description>ID specific to the plan name since plans can have different ID iterations yet maintain the same name in MBA
Populated by MBA</description>
        <inlineHelpText>ID specific to the plan name since plans can have different ID iterations yet maintain the same name in MBA</inlineHelpText>
        <label>MBA Product ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <description>From MBA to distinguish stores from SSLs and Domains</description>
        <inlineHelpText>Type of product (store, SSL, domain, etc)</inlineHelpText>
        <label>MBA Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Store</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Domain Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSL Certificate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Used in the partner portal apex code to designate when a sub was created via the portal rather than by MBA</description>
        <inlineHelpText>Used in the partner portal apex code to designate when a sub was created via the portal rather than by MBA</inlineHelpText>
        <label>UNDER REVIEW Source</label>
        <picklist>
            <picklistValues>
                <fullName>Direct Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Rep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRM Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acquisition</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StoreURL__c</fullName>
        <description>URL of the BC trial or store populated by MBA</description>
        <inlineHelpText>URL of the BC trial or store populated by MBA</inlineHelpText>
        <label>MBA Store URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Support_PIN__c</fullName>
        <description>Formula pulling the pin value from the associated account or lead</description>
        <formula>IF(
ISBLANK(Account__r.SupportPin__c), Lead__r.SupportPin__c ,Account__r.SupportPin__c)</formula>
        <label>Support Pin</label>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SubmitCaseControllerTest.cls
@isTest(seeAllData = false)
private class SubmitCaseControllerTest { 

    public static SubmitCaseController scc { get; set; }
    public static Subscription__c testSub { get; set; }
    public static Account testAccount { get; set; }
    public static Contact testContact { get; set; }
    public static CaseSubmissionSettings__c css { get; set; }
    public static CaseQueueRouting__c testSupportQueue { get; set; }

        
    public static void setUp() {
        SubmitCaseControllerTest.setUp(true);
    }    

    public static void setUp(Boolean newScc) {
        System.debug('SubmitCaseControllerTest->setUp()');

 
        testSub = new Subscription__c(
            RecordTypeId = Subscription__c.getSObjectType().getDescribe().getRecordTypeInfosByName().get('MBA Subscription').getRecordTypeId(),
            StoreURL__c= 'testingStorebigcommerce',
            ProductType__c = 'Store',
            Status__c = 'Active',
//            Account__c = testAccount.Id,
//            Contact__c = testContact.Id,
            productId__c ='28',
            Source__c = 'Direct Trial'                  
            );

        insert testSub;
      testAccount = new Account(
            RecordTypeId = Account.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Client Record Type').getRecordTypeId(),
            Name = 'testName',
            Type = 'Client',
            Status__c = 'Open', 
            Client_Start_Date__c = date.today(), 
            SupportPin__c = '1234'
            );

        insert testAccount;

        testContact = new Contact(
            LastName = 'testLastName',
            accountId = testAccount.id
            );
        insert testContact;

 

        testSub.Account__c = testAccount.Id;
        testSub.Contact__c = testContact.Id;
        update testSub;


        testSub = [SELECT Id, Account__c, Contact__c,StoreURL__c,Support_PIN__c FROM Subscription__c WHERE Id =: testSub.Id];

        css = new CaseSubmissionSettings__c(
            Name = 'Web2Case',
            Case_Origin__c ='Web',
            Case_Record_Type__c = '012a0000001NXkL',
            Contact_Record_Type__c = '',
            Default_Support_Account_ID__c = '',
            Default_Support_Owner_ID__c = '00Ga0000003ATBV',
            LiveAgent_Button_Name__c = '',
            Redirect_URL__c = '/SubmitCaseThanks'
        );
        insert css;
        

        System.assertEquals(testAccount.Id, testSub.Account__c);
        System.assertEquals(testContact.Id, testSub.Contact__c);

        testSupportQueue = new CaseQueueRouting__c (
            Name = '1',
            Queue_ID__c = '00Ga0000003ATBVEA4',
            Queue_Name__c = 'Support'
            );
        insert testSupportQueue;

        System.debug('testQueue : ' + testSupportQueue);

        if(newScc) {
            scc = new SubmitCaseController();
        }           
        
    }     
    
    static testMethod void myGetTargetDepartmentTest() {
        SubmitCaseControllerTest.setUp();

        scc.formDeptId.value = testSupportQueue.Queue_ID__c;

        String defaultDepartmentExpectation = scc.getTargetDepartment();

        System.assertEquals(defaultDepartmentExpectation, 'Support');
    }

    static testMethod void myPrepopulatedQueryStringTest() {
        PageReference pg = Page.SubmitCase;
        Test.setCurrentPage(pg);

        SubmitCaseControllerTest.setUp(false);

        ApexPages.currentPage().getParameters().put('storeUrl', testSub.StoreURL__c); 
        ApexPages.currentPage().getParameters().put('storeUrl', 'http;/testingBigcommerce#');
        ApexPages.currentPage().getParameters().put('storeUrl', 'http;/testingBigcommerce?');
        ApexPages.currentPage().getParameters().put('supportPin', testAccount.SupportPin__c); 

        SubmitCaseControllerTest.scc = new SubmitCaseController();

        System.assertEquals(scc.webFormOn, false);

    }

    static testMethod void myValidatePinWithInvalidCredentialsTest() {
        PageReference pg = Page.SubmitCase;
        Test.setCurrentPage(pg);

        SubmitCaseControllerTest.setUp(false);

        ApexPages.currentPage().getParameters().put('storeUrl', testSub.StoreURL__c); 
        ApexPages.currentPage().getParameters().put('supportPin', testAccount.SupportPin__c + '1'); 

        SubmitCaseControllerTest.scc = new SubmitCaseController();

        System.assertEquals(scc.webFormOn, false);

        System.assertEquals(true, scc.formErrorsList.size() > 0 );

    }    

    static testMethod void mySubmitCaseFailsTest() {
        PageReference pg = Page.SubmitCase;
        Test.setCurrentPage(pg);

        SubmitCaseControllerTest.setUp(false);

        ApexPages.currentPage().getParameters().put('SupportSetting', 'Web2Case');
        ApexPages.currentPage().getParameters().put('storeUrl', testSub.StoreURL__c); 
        ApexPages.currentPage().getParameters().put('supportPin', testAccount.SupportPin__c); 

        SubmitCaseControllerTest.scc = new SubmitCaseController();
        SubmitCaseControllerTest.scc.css = css;

        scc.formDeptId.value = testSupportQueue.Queue_ID__c;

        PageReference nextAction = scc.submitCase();

        System.assertEquals(null, nextAction);

    }

    static testMethod void myValueAndErrorTest() {
        SubmitCaseControllerTest.setUp();
        
        SubmitCaseController.ValueAndError testValueAndError= new SubmitCaseController.ValueAndError();
        testValueAndError.value =  'value';
        testValueAndError.error = 'error';
        System.assertEquals(testValueAndError.value,  'value');
        System.assertEquals(testValueAndError.error, 'error');
        System.assertEquals(testValueAndError.isEmpty(), false);
        System.assertEquals(testValueAndError.getHasError(), true);

        testValueAndError.error = null;
        System.assertEquals(testValueAndError.getHasError(), false);

    }

    static testMethod void myIDValueAndErrorTest() {
        SubmitCaseControllerTest.setUp();

        SubmitCaseController.IDValueAndError testIDValueAndError = new SubmitCaseController.IDValueAndError();
                
        testIDValueAndError.error = 'error';               
        System.assertEquals(testIDValueAndError.error, 'error');
        System.assertEquals(testIDValueAndError.isEmpty(), true);
        System.assertEquals(testIDValueAndError.getHasError(), true);

        testIDValueAndError.error = null;
        System.assertEquals(testIDValueAndError.getHasError(), false);
    }

    static testMethod void myFormUrlFormatterTest() {
        SubmitCaseControllerTest.setUp();

        //formURLFormatter UNIT Testing
        scc.formURLFormatter('http://testingStorebigcommerce/');
        scc.formURLFormatter('https://testingStorebigcommerce/');
        scc.formURLFormatter('www.https://testingStorebigcommerce/');
    }

    static testMethod void mySubmitCaseControllerTest() {
        SubmitCaseControllerTest.setUp();

        String fullUrl = 'http://' + testSub.StoreURL__c;
        List<Subscription__c> testSubList = [SELECT Id, Account__c, Account__r.OwnerId, Contact__c, Lead__c, Support_PIN__c, StoreURL__c, Email__c FROM Subscription__c
                                                WHERE Support_PIN__c = :testSub.Support_PIN__c AND (StoreURL__c = :testSub.StoreURL__c OR StoreURL__c = :fullUrl)
                                                AND Status__c = 'Active' LIMIT 1];


        scc.deptName = null;
        scc.deptName ='Support';

        System.assertEquals(testSubList.isEmpty(), false);
    
    } 

    static testMethod void myValidatePinTest() {
        SubmitCaseControllerTest.setUp();

        scc.formURL.value = testSub.StoreURL__c;
        scc.formPIN.value = testSub.Support_PIN__c;        
        scc.validatePIN(); 
        System.assertEquals(scc.webFormOn,true);
        
        SubmitCaseController controller = new SubmitCaseController();
        controller.formURL.value = '';
        controller.formPIN.value = '1234';
        controller.validatePIN();
        System.assertEquals(controller.webFormOn,false);

        SubmitCaseController controller1 = new SubmitCaseController();
        controller1.formURL.value = testSub.StoreURL__c;
        controller1.formPIN.value = '1234sdgh';
        controller1.validatePIN();
        System.assertEquals(controller1.webFormOn,false);

    } 

    static testMethod void myValidateFileUpload(){
        SubmitCaseControllerTest.setUp();
        scc.fileAtt = Blob.valueOf('Good Extension and Size');
        scc.fileName = 'test-file.txt';
        scc.fileSize = 27800;

        Boolean testUpload = scc.validateFileUpload();      
        System.assertEquals(false, testUpload);


        scc.fileAtt = Blob.valueOf('Good Size bad extension ');
        scc.fileName = 'test-file.x';
        scc.fileSize = 2780;

        Boolean testExtensionUpload = scc.validateFileUpload();        
        System.assertEquals(true, testExtensionUpload);

        scc.fileAtt = Blob.valueOf('Good extension bad size ');
        scc.fileName = 'test-file.txt';
        scc.fileSize = 5302880;

        Boolean testsizeUpload = scc.validateFileUpload();        
        System.assertEquals(true, testsizeUpload);


        PageReference currPage = Page.SubmitCase;
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'This file exceeds the maximum size limit of 10MB.'));
        Test.setCurrentPage(currPage);
        System.assertEquals(true, ApexPages.hasMessages(ApexPages.severity.ERROR));

        Boolean testsizeMaxUpload = scc.validateFileUpload(); 
        System.assertEquals(true, testsizeMaxUpload);        
        
    }   

    static testMethod void myCaseDescriptionValidatorTest() {
        SubmitCaseControllerTest.setUp();
        scc.formDescription.value = '';

        Boolean descriptionHasErrors = scc.validateDescription();
        
        System.assertEquals(descriptionHasErrors, true);

        scc.formDescription.value = 'test';
        descriptionHasErrors = scc.validateDescription();
        System.assertEquals(descriptionHasErrors, false);
    }
	
	static testMethod void myCaseSubjectValidatorTest() {
        SubmitCaseControllerTest.setUp();
        scc.formSubject.value = '';

        Boolean subjectHasErrors = scc.validateSubject();
        
        System.assertEquals(subjectHasErrors, true);

        scc.formSubject.value = 'test';
        subjectHasErrors = scc.validateSubject();
        System.assertEquals(subjectHasErrors, false);
    }
    
    static testMethod void myDeptTest() {
        SubmitCaseControllerTest.setUp();
        
        List<SelectOption> selDept = scc.getDepts();

        System.assertEquals(selDept.size() >0, true);
    }

    static testMethod void mySaveCaseHappyPathTest() {
        SubmitCaseControllerTest.setUp();

        System.debug('mySaveCaseHappyPathTest: CaseQueueRouting__c.getAll(): ' + CaseQueueRouting__c.getAll());

        // Values created during validatePin()
        scc.AcctId = testAccount.Id;
        scc.ContId = testContact.Id;
        scc.subId = testSub.Id;

        scc.formFname.value = testContact.FirstName;
        scc.formLname.value = testContact.LastName;
        scc.formPhone.value = '555-555-5555';

        // Values supplied in Form Step2
        scc.caseDescription = 'some text';
        scc.formDeptId.value = testSupportQueue.Queue_ID__c;  // 00Ga0000003ATBVEA4
        scc.css = css; 

        System.debug('mySaveCaseHappyPathTest: subId : '+scc.subId);

        System.debug('mySaveCaseHappyPathTest: deptId : '+ scc.formDeptId.value);

        System.debug('mySaveCaseHappyPathTest: css : '+ scc.css);

        PageReference nextAction =  scc.submitCase();  

        System.debug('mySaveCaseHappyPathTest: caseNum: ' + scc.caseNum); 

  //      System.assertEquals(true, scc.caseNum != null ); 
    }    
}