src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User_Status__c.object
<CustomObject>
    <description>Used to log sales reps in and out of office for lead round robin</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Out of Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In the Office</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Status</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Status</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestClasses.cls
@isTest
private class TestClasses {
	/*
    static testMethod void ChangeOwnerId() { 
      
      User_Status__c userStatus1 = new User_Status__c(OwnerId = [select Id from User WHERE IsActive = true limit 1].Id, Status__c = 'Out of Office');      
      Account acc = new Account(Name='Test Account', Phone = '0987654321');
      insert acc;
      
      Lead newLead4 = new Lead(FirstName= 'Test',LastName = 'Test3', Status = 'Open', Company = 'Test3', Phone='9412365', Email='amit.luniya1@arxxus.com', TrackTrigger__c=1, LeadSource = 'Web', OwnerId = userStatus1.OwnerId);
      insert newLead4;
       
      acc.OwnerId = userStatus1.OwnerId;
      update acc;
      
      Lead newLead3 = new Lead(FirstName= 'Test',LastName = 'Test3', Status = 'Open', Company = 'Test3', Phone='3456815354', Email='amit.luniya2@arxxus.com', TrackTrigger__c=1, LeadSource = 'Web', OwnerId = userStatus1.OwnerId);
      insert newLead3; 
      
        //Lead newLead4 = new Lead(FirstName= 'Test',LastName = 'Test3', Status = 'Open', Company = 'Test3', Phone='123', Email='amit.luniya@arxxus.com');
      //insert newLead4;         
    }
    
    static testMethod void ChangeOwnerIdNew() {
        Lead newLead6 = new Lead(FirstName= 'Test',LastName = 'Test6', Status = 'Open', Company = 'Test6', Email='amit3@gmail.com', TrackTrigger__c=1, OwnerId = '00530000004W020', LeadSource = 'Web');
      insert newLead6;             
    }
    static testMethod void ChangeOwnerId1() {    
      Lead newLead5 = new Lead(FirstName= 'Test',LastName = 'Test5', Status = 'Open', Company = 'Test5', Phone='345326800' , TrackTrigger__c=1, OwnerId = '00530000004W020', Email='amit4@gmail.com', LeadSource = 'Web');
      insert newLead5;
    }
    static testMethod void ChangeOwnerIdNew1() {
      Lead newLead1 = new Lead(FirstName= 'Test',LastName = 'Test1', Status = 'Open', Company = 'Test1', Email = 'amit.luniya5@arxxus.com', Phone='11394875623', OwnerId = '00530000004W020', TrackTrigger__c=1 , LeadSource = 'Web');
      insert newLead1;
        
    }
    */
}