src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AppDeveloperContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary Contact</description>
        <inlineHelpText>Primary Contact</inlineHelpText>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (App Developer Contact)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Area_Codes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Area_Code__c</fullName>
        <label>Area Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Area Codes</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MBA_Phone_1__c</fullName>
        <label>MBA Phone 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>US_Time_Zone__c</fullName>
        <label>US Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>Alaskan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eastern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaiian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mountain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>MBA_Phone_1__c</fullName>
        <label>MBA Phone 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>US_Time_Zone__c</fullName>
        <inlineHelpText>Based on the State populated in the address field &quot;State/Province&quot;</inlineHelpText>
        <label>US Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>Alaskan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eastern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaiian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mountain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pacific</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Contact_TriggerHandlerTest.cls
@isTest(SeeAllData = false)
private class Contact_TriggerHandlerTest {

    static testmethod void testContactTZUpdate()
    {
        test.startTest();
        
        //Insert Test Custom Settings Records
        Area_Codes__c areaCode = new Area_Codes__c();
        areaCode.Name = '1';
        areaCode.Area_code__c = '410';
        areaCode.Location__c = 'Maryland';
        areaCode.Timezone__c = 'Eastern';
        insert areaCode;
        
        //Insert Test Lead Record
        
        TestDataGenerator td = new TestDataGenerator();
      
        list<Contact> lstCon = td.getContacts(true);
      
        Contact ContactObj = lstCon[0];
        
        ContactObj.Phone = '(410) 894-5314';
       
        
        update ContactObj;
       
        test.stopTest();
        
        //Compare State and Time zone
        Contact cObj = [Select id, US_Time_Zone__c, MailingState from Contact where id = :ContactObj.Id];
        
        system.assertEquals(cObj.US_Time_Zone__c, 'Eastern');
        system.assertEquals(cObj.MailingState, 'Maryland');
    }
    
    static testMethod void testPhoneUpdates() 
    {
		
        TestDataGenerator td = new TestDataGenerator();
    	
    	list<Contact> lstCon = td.getContacts(true);
      
        Contact ContactObj = lstCon[0];
        
        ContactObj.Phone = '4108945314';
         
        update ContactObj;
        
         ContactObj.Phone = '5128945314';
         update ContactObj;
		
	 	 Contact cObj = [Select id, MBA_Phone_1__c, Phone from Contact where id = :ContactObj.Id];
        
	 	// System.assertEquals('4108945314' , cObj.MBA_Phone_1__c);
	 	System.assertEquals('5128945314' , cObj.Phone);	
    }     
    
    static testMethod void testAcctAppContactUpd() 
    {
	    Id partnerRecordTypeId  = Account.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Channel Partner Record Type').getRecordTypeId();
		
        TestDataGenerator td = new TestDataGenerator();
    	
    	list<Account> lstAcct = td.getAccounts(false);
      	lstAcct[0].RecordTypeId = partnerRecordTypeId ;
      	insert lstAcct;
      	
        Contact ContactObj = new Contact(AccountId= lstAcct[0].Id,lastName = 'Test');
        insert ContactObj;
        Account a = [select Id, AppDeveloperContact__c from Account where Id = :ContactObj.AccountId];
        
        System.assertEquals(a.AppDeveloperContact__c, ContactObj.Id);
    }  
}