src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Owner_ID__c</fullName>
        <description>for reporting purposes only; not visible on layouts</description>
        <formula>OwnerId</formula>
        <label>Owner ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Team__c</fullName>
        <formula>Owner.Department</formula>
        <inlineHelpText>Current team / department of the account owner</inlineHelpText>
        <label>Owner Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PAR_Total_Active_MRR__c</fullName>
        <label>zPAR: Total Active MRR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead_Retrieved__c.object
<CustomObject>
    <fields>
        <fullName>Lead_ID__c</fullName>
        <label>Lead ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Owner_Assign_Date__c</fullName>
        <label>Lead Owner Assign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Owner_ID__c</fullName>
        <label>Owner ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Team__c</fullName>
        <label>Owner Team</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <label>zLead Owner Assignment</label>
    <nameField>
        <displayFormat>LR{00000000}</displayFormat>
        <label>Sequence No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads Retrieved</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead_Update_Owner__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Queue_Owner__c</fullName>
        <label>Queue/Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TO run in Update mode</description>
        <label>Update?</label>
        <type>Checkbox</type>
    </fields>
    <label>Lead Update Owners</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated via a trigger that fires if the MBA Partner ID is populated. Finds the partner account with the matching value in its iDev Partner ID field and puts the account name here</description>
        <label>Channel Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Integrator, Partner, Reseller, Designer, Strategic Partner, Referral, Interspire, Agency Partner, App Partner, Affiliate Partner, Internal,  Theme Partner, Marketing Services, Full Service Agency, Solution Partner, Technology Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Opportunities</relationshipLabel>
        <relationshipName>ClientOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MonthlyRecurringRevenue__c</fullName>
        <label>Monthly Recurring Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Owner_Team__c</fullName>
        <formula>Owner.Department</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseDate__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status from MBA</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back to Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT/QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpublished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coming Soon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft - Under Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Share Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Trial</fullName>
        <active>true</active>
        <businessProcess>Sales Process %28Trial to Purchase%29</businessProcess>
        <description>Use when the client has created a trial store.</description>
        <label>Trial</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RollupConfigs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Child_Object_Name__c</fullName>
        <description>Stores the API name of the child object which contains fields to be rolled up by the Parent</description>
        <inlineHelpText>Stores the API name of the child object which contains fields to be rolled up by the Parent</inlineHelpText>
        <label>Child Object Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Object__c</fullName>
        <description>Stores the API name of the Parent object which will display the roll-up summaries of lookup fields</description>
        <inlineHelpText>Stores the API name of the Parent object which will display the roll-up summaries of lookup fields</inlineHelpText>
        <label>Parent Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>parentQueryField1__c</fullName>
        <description>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</description>
        <inlineHelpText>Holds the API name of the field on the Parent object which will display the rolled-up summary of fields on the Child. Example: total_hours_spent__c</inlineHelpText>
        <label>parentQueryField1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>queryField1__c</fullName>
        <description>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</description>
        <inlineHelpText>Holds the API name of the field on the Child object which will be rolled up by the Parent. Example: hours_spent__c</inlineHelpText>
        <label>queryField1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>queryField_parentRelationshipName__c</fullName>
        <description>Holds the API name of the field on the Child that is the Lookup relationship to the parent. Example: parent_account__c</description>
        <inlineHelpText>Holds the API name of the field on the Child that is the Lookup relationship to the parent. Example: parent_account__c</inlineHelpText>
        <label>queryField_parentRelationshipName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>RollupConfigs</label>
</CustomObject>

src/classes/UpdateOwnerTest.cls
@isTest
private class UpdateOwnerTest {

  @testSetup static void setup() {
        // Create 
        List<Lead_Update_Owner__c > rules = new List<Lead_Update_Owner__c >();
        Lead_Update_Owner__c ruleis = new Lead_Update_Owner__c (
        				Name = Label.Outbound_Sales,
        				Update__c = false,
        				SLA__c =90,
        				Queue_Owner__c = Label.BCT_ID);
        rules.add(ruleis);
        Lead_Update_Owner__c ruleo = new Lead_Update_Owner__c (
        				Name = Label.Inbound_Sales,
        				Update__c = false,
        				SLA__c =90,
        				Queue_Owner__c = Label.BCT_ID);
        rules.add(ruleo);
        insert rules;   
        
        List<RollupConfigs__c > rrules = new List<RollupConfigs__c >();
        RollupConfigs__c opprule = new RollupConfigs__c (
        				Name = 'Account - Opportunity Active',
        				Parent_Object__c = 'Account',
        				Child_Object_Name__c = 'Opportunity',
        				queryField_parentRelationshipName__c ='Channel_Partner__c',
        				parentQueryField1__c ='PAR_Total_Active_MRR__c',
        				Criteria__c ='',
        				queryField1__c = 'MonthlyRecurringRevenue__c');
  //      rules.add(ruleis);
        insert opprule;  
        
        List<String > ProfileName = new List<String>();
        ProfileName.add('Sales Rep');
         
        TestDataGenerator td = new TestDataGenerator();
        List<User> usrs = td.getUsers(ProfileName);
         
    }
 
 public static testMethod void testBatch_Trial(){
   
    	
   	Id trialRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_Trial).getRecordTypeId();
    User usr1 = [Select Id,Name, Department, UserRoleId,UserRole.Name from User Where IsActive=true and Department =:Label.Inbound_Sales LIMIT 1];
   		User usr2 = [Select Id,Name, Department, UserRoleId,UserRole.Name from User Where IsActive=true and Department =:Label.Outbound_Sales LIMIT 1];
   		System.Debug('#usr1#'+usr1);
   		System.Debug('#usr2#'+usr2);  
   
 //  System.runAs(usr1){
     TestDataGenerator td = new TestDataGenerator();
      
      list<Contact> lstCon = td.getContacts(true);
      
      Opportunity obj = new Opportunity();
        obj.Name = 'Test ';
        obj.CloseDate = Date.today().addDays(1);
        obj.StageName = 'Trial';
        obj.OwnerId = usr1.Id;
        obj.AccountId = lstCon[0].AccountId;
        obj.RecordTypeId = trialRecordTypeId;
        obj.Status__c = 'Active';
        insert obj;
  
    Opportunity obj1 = new Opportunity();
        obj1.Name = 'Test ';
        obj1.CloseDate = Date.today().addDays(1);
        obj1.StageName = 'Trial';
        obj1.OwnerId = usr2.Id;
        obj1.AccountId = lstCon[1].AccountId;
        obj.RecordTypeId = trialRecordTypeId;
        obj.Status__c = 'Active';
        insert obj1;
 
       
   Lead_Retrieved__c objRec = new Lead_Retrieved__c();
   objRec.Owner_ID__c = usr1.Id;
   objRec.Lead_ID__c = obj.Id;
   objRec.Lead_Owner_Assign_Date__c = System.Today();
   objRec.Processed__c =false;  
   insert objRec;
  
   Lead_Retrieved__c objRec1 = new Lead_Retrieved__c();
   objRec1.Owner_ID__c = usr1.Id;
   objRec1.Lead_ID__c = obj1.Id;
   objRec1.Lead_Owner_Assign_Date__c = System.Today().addDays(-1);
   objRec1.Processed__c =false;  
   insert objRec1;
   
   Task tskPast = new Task(WhatId = obj.AccountId, ActivityDate=System.today().addDays(-30),Subject='Test Task');
   insert tskPast;
   System.Debug('#Task#'+tskPast);
   Task tskPast1 = new Task(WhatId = obj.AccountId, ActivityDate=System.today().addDays(-45),Subject='Test Task');
   insert tskPast1;
   
   Task tskPast2 = new Task(WhatId = obj.AccountId, ActivityDate=System.today().addDays(-60),Subject='Test Task');
   insert tskPast2;
   
   Task tskPast3 = new Task(WhatId = obj.AccountId, ActivityDate=System.today().addDays(-90),Subject='Test Task');
   insert tskPast3;
   
   Task tskPresent = new Task(WhatId = obj.AccountId,ActivityDate=System.today(),Subject='Test Task');
   insert tskPresent;
   
   Test.StartTest();
 
     string queryTrial ='Select Id, Name, PurchaseDate__c, AccountId, OwnerId, StageName, CreatedDate, CreatedById, RecordTypeId, Owner_Team__c,Status__c from Opportunity Where  RecordTypeId = :trialRecordTypeId  ' ;
 		queryTrial = queryTrial + Label.ROE_Trial_Query;
   	   queryTrial = queryTrial + ' limit 1';
   	
      UpdateOwner b = new UpdateOwner(); 
      b.query = queryTrial;
      database.executebatch(b);
      
   Test.StopTest();
   
 
}

public static testMethod void testBatch_Upsell(){
   
   	User usr1 = [Select Id,Name, Department, UserRoleId,UserRole.Name from User Where IsActive=true and Department =:Label.Inbound_Sales LIMIT 1];
   	User usr2 = [Select Id,Name, Department, UserRoleId,UserRole.Name from User Where IsActive=true and Department =:Label.Outbound_Sales LIMIT 1];
   	
    Id upgradeRecordTypeId = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_Upgrade).getRecordTypeId();
	    
 //  System.runAs(usr1){
     TestDataGenerator td = new TestDataGenerator();
      
      list<Contact> lstCon = td.getContacts(true);
      
      // Create a new opportunity for the account
      
      Opportunity obj = new Opportunity();
        obj.Name = 'Test ';
        obj.CloseDate = Date.today().addDays(1);
        obj.StageName = 'Demo';
        obj.OwnerId = usr1.Id;
        obj.AccountId = lstCon[0].AccountId;
        obj.RecordTypeId = upgradeRecordTypeId;
        insert obj;
  
    Opportunity obj1 = new Opportunity();
        obj1.Name = 'Test ';
        obj1.CloseDate = Date.today().addDays(1);
        obj1.StageName = 'Demo';
        obj1.OwnerId = usr2.Id;
        obj1.AccountId = lstCon[1].AccountId;
        obj.RecordTypeId = upgradeRecordTypeId;
        insert obj1;
  
   Task tskPast = new Task(WhatId = obj.AccountId, ActivityDate=System.today().addDays(-30),Subject='Test Task', OwnerId = usr1.Id);
   insert tskPast;
   System.Debug('#Task#'+tskPast);
 
   
   Test.StartTest();
   string queryUpsell ='Select Id, Name, AccountId, OwnerId, StageName, CreatedDate, CreatedById, RecordTypeId, Owner_Team__c from Opportunity Where  RecordTypeId = :upgradeRecordTypeId  ' ;
   queryUpsell= queryUpsell + ' limit 1';
   
      UpdateOwner b = new UpdateOwner(); 
      b.query = queryUpsell;
      database.executebatch(b);
      
   Test.StopTest();
   
 
}

public static testMethod void testBatch_Purchase(){
   
  	
    Id storeRecordTypeId = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_StorePurchase).getRecordTypeId();
	  User usr1 = [Select Id,Name, Department, UserRoleId,UserRole.Name from User Where IsActive=true and Department =:Label.Inbound_Sales LIMIT 1];
   		User usr2 = [Select Id,Name, Department, UserRoleId,UserRole.Name from User Where IsActive=true and Department =:Label.Outbound_Sales LIMIT 1];
   		System.Debug('#usr1#'+usr1);
   		System.Debug('#usr2#'+usr2);  
     TestDataGenerator td = new TestDataGenerator();
      
      list<Contact> lstCon = td.getContacts(true);
      
      // Create a new opportunity for the account
      
      Opportunity obj = new Opportunity();
        obj.Name = 'Test ';
        obj.CloseDate = Date.today().addDays(-180);
        obj.StageName = 'Purchased';
        obj.OwnerId = usr1.Id;
        obj.PurchaseDate__c = Date.today().addDays(-180);
        obj.AccountId = lstCon[0].AccountId;
        obj.RecordTypeId = storeRecordTypeId;
        insert obj;
  
    Opportunity obj1 = new Opportunity();
        obj1.Name = 'Test ';
        obj1.CloseDate = Date.today().addDays(1);
        obj1.StageName = 'Demo';
        obj1.OwnerId = usr2.Id;
        obj1.AccountId = lstCon[1].AccountId;
        obj.PurchaseDate__c = Date.today().addDays(-180);
        obj.RecordTypeId = storeRecordTypeId;
        insert obj1;
  
     Task tskPast = new Task(WhatId = obj.AccountId, ActivityDate=System.today().addDays(-30),Subject='Test Task', OwnerId = usr1.Id);
   		insert tskPast;
   		System.Debug('#Task#'+tskPast);
 
   
   Test.StartTest();
   string queryPurchase ='Select Id, Name, AccountId, OwnerId, StageName, CreatedDate, CreatedById, RecordTypeId, Owner_Team__c from Opportunity Where  RecordTypeId = :upgradeRecordTypeId  ' ;
    queryPurchase= queryPurchase + ' limit 1';
   
      UpdateOwner b = new UpdateOwner(); 
      b.query = queryPurchase;
      database.executebatch(b);
      
   Test.StopTest();
   
 
}

}