src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>iDev_Partner_ID__c</fullName>
        <description>Used to port new partner ID from the iDev commissions system; assigns new leads coming from the partner to the partner account owner. jw</description>
        <externalId>true</externalId>
        <label>iDev Partner ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated via a trigger that fires if the MBA Partner ID is populated. Finds the partner account with the matching value in its iDev Partner ID field and puts the account name here</description>
        <label>Channel Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Integrator, Partner, Reseller, Designer, Strategic Partner, Referral, Interspire, Agency Partner, App Partner, Affiliate Partner, Internal,  Theme Partner, Marketing Services, Full Service Agency, Solution Partner, Technology Partner</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Opportunities</relationshipLabel>
        <relationshipName>ClientOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBAPartnerID__c</fullName>
        <label>MBA Partner ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The subscription is not related to the account on the opportunity</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>The subscription is not related to the account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Channel_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Populated via a trigger that fires if the MBA Partner ID is populated.  Finds the partner account with the matching value in its iDev Partner ID field and puts the account name here</description>
        <inlineHelpText>Partner Account (only matched is MBA Partner ID is populated and a corresponding iDev Parter ID exists on a partner account)</inlineHelpText>
        <label>PAR Channel Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Subscriptions</relationshipLabel>
        <relationshipName>Client_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBAPartnerID__c</fullName>
        <description>Used to map Partner Source from MBA.  The iDev Affiliate ID of the partner, if this subscription is attributed to one</description>
        <label>MBA Partner ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestAccountTrigger.cls
/**
 * This class contains unit tests for validating the Account triggers and 
 * other functionality.
 */
@isTest
private class TestAccountTrigger {
  
    static testMethod void testOwnerChange() 
    {
		Id idPartnerRecordType = Account.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Channel Partner Record Type').getRecordTypeId();
 		Id idClientRecordType = Account.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Client Record Type').getRecordTypeId();
		
		TestDataGenerator td = new TestDataGenerator();
	    	
	    list<Account> lstAcct = td.getAccounts(true);
	    User ao = td.getUsers(null)[0];
		lstAcct[0].OwnerId = ao.Id;
		lstAcct[0].RecordTypeId = idClientRecordType;
		
		
		User co = td.getUsers(null)[0];
		lstAcct[1].OwnerId = co.Id;
		lstAcct[1].RecordTypeId = idPartnerRecordType;
		lstAcct[1].Type = 'Agency Partner';
		lstAcct[1].iDev_Partner_ID__c = 1234;
		update lstAcct;
		
	    list<Subscription__c> lstSubs = td.getSubscriptions(true);
	    for (Subscription__c s :lstSubs)
	    {
	    	s.Account__c = lstAcct[0].Id;
	    }
	    
	    lstSubs[1].Channel_Partner__c = lstAcct[1].Id;
	    lstSubs[1].MBAPartnerID__c = '1234';
	    update lstSubs;
	    
	    list<Opportunity> lstOpps = td.getOpportunities(true);
	    for (Opportunity o :lstOpps)
	    {
	    	o.AccountId = lstAcct[0].Id;
	    	o.OwnerId = ao.Id;
	    }
	   
	    lstOpps[1].Channel_Partner__c = lstAcct[1].Id;
	    lstOpps[1].MBAPartnerID__c = '1234';
	    update lstOpps;
	    
	     Contact c = new Contact();
                        c.FirstName = 'First ' ;
                        c.LastName = 'Last ' ;
                        c.MailingCountry ='US';
                        c.Email = 'testmail' + '@bigcommerce.com';
                        c.AccountId = lstAcct[0].Id;
         insert c;
         
	    Test.startTest();
		User ao2 = td.getUsers(null)[0];
		lstAcct[0].OwnerId = ao2.Id;
		
		update lstAcct[0];
		User co2 = td.getUsers(null)[0];
		lstAcct[1].OwnerId = co2.Id;
		
		update lstAcct[1];
		Test.stopTest();
    }
}