src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account_Mismatch__c</fullName>
        <formula>IF(MBAAccountID__c &lt;&gt;  Account__r.MBAAccountID__c , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Mismatch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductType__c</fullName>
        <description>From MBA to distinguish stores from SSLs and Domains</description>
        <inlineHelpText>Type of product (store, SSL, domain, etc)</inlineHelpText>
        <label>MBA Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Store</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Domain Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SSL Certificate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>From MBA saying which plan/trial the store is on</description>
        <inlineHelpText>From MBA saying which plan/trial the store is on</inlineHelpText>
        <label>MBA Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BatchSubscriptionCleanup.cls
/**
 * BatchSubscriptionCleanup
 * Author: Steve O'Neal
 * Date: 7/14/2016
 * Purpose: Cleans up subscriptions with an account mismatch by removing the account and saving the record again.
 * Not all subscriptions can be cleaned this way, but a large chunk can be.
 * Never run this batch with a scope larger than 10 due to callouts being made during the save.
 */
global class BatchSubscriptionCleanup implements Database.Batchable<sObject> {
	
	global String query;
	
	/**
	 * Instantiates the job and generates the default query
	 * @author Steve O'Neal
	 * @date   2016-07-14
	 * @ticket link          https://jira.bigcommerce.com/browse/BAP-3991
	 * @return Instance of BatchSubscriptionCleanup
	 */
	global BatchSubscriptionCleanup() {
		query = 'select ID, Account__c, Product__c from Subscription__c where Account_Mismatch__c = true and status__c = \'Active\' and ProductType__c = \'Store\' and (not Product__c like \'%TEST%\') and createddate > 2014-01-01T12:00:00Z';
	}
	
	/**
	 * Queries the database with the given query
	 * @author Steve O'Neal
	 * @date   2016-07-14
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3991
	 * @param  BC         Batchable context
	 * @return            Query locator representing the results of the query
	 */
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	/**
	 * Updates the subscriptions by clearing out the account
	 * @author Steve O'Neal
	 * @date   2016-07-14
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3991
	 * @param  BC         Batchable context
	 * @param  scope      Current scope
	 * @return            Nothing
	 */
   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
	
		List<Subscription__c> subsToUpdate = new List<Subscription__c>();
		for (sObject sub : scope)
		{
			Subscription__c subToUpdate = (Subscription__c)sub;
		    subToUpdate.Account__c = null;
		    subsToUpdate.add(subToUpdate);
		}

		database.update(subsToUpdate,false);		
	}
	
	/**
	 * Finishes the batch job
	 * @author Steve O'Neal
	 * @date   2016-07-14
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3991
	 * @param  BC         Batchable context
	 * @return            Nothing
	 */
	global void finish(Database.BatchableContext BC) {
		
	}
	
}