src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/BI_Data__c.object
<CustomObject>
    <description>To hold store information from BI.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lifetime_GMV__c</fullName>
        <inlineHelpText>Lifetime GMV since 1/1/13 or Store provision date if provisioned after.</inlineHelpText>
        <label>Lifetime GMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Month_GMV_Date__c</fullName>
        <description>Date corresponding to the Previous month GMV.</description>
        <inlineHelpText>This is the date for which the previous month GMV was obtained.</inlineHelpText>
        <label>Previous Month GMV Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Previous_months_GMV__c</fullName>
        <inlineHelpText>GMV corresponding to previous month of activity (not necessarily calendar last month).</inlineHelpText>
        <label>Previous month&apos;s GMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CampaignRules__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Rules to set campaigns</description>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <label>Campaign ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ending_GMV__c</fullName>
        <label>Ending GMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rule_Name__c</fullName>
        <label>Rule Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starting_GMV__c</fullName>
        <label>Starting GMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Campaign Rules</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_MBA_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Contact with an email match to the MBA Account admin email address</inlineHelpText>
        <label>Primary MBA Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BI_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BI Data</label>
        <referenceTo>BI_Data__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchaseDate__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status from MBA</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Back to Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT/QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Live</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hidden</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unpublished</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coming Soon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft - Under Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Share Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The subscription is not related to the account on the opportunity</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>The subscription is not related to the account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact associated with the subscription</description>
        <inlineHelpText>Contact associated with the subscription</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lifetime_GMV__c</fullName>
        <description>Lifetime GMV from the BI Data object</description>
        <inlineHelpText>Lifetime GMV, rolled up from the BI Data object</inlineHelpText>
        <label>Lifetime GMV</label>
        <summarizedField>BI_Data__c.Lifetime_GMV__c</summarizedField>
        <summaryForeignKey>BI_Data__c.Subscription__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Was used by Acq on forecast subs but can probably be deleted now</description>
        <label>zOpportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PurchaseDate__c</fullName>
        <description>From MBA.  Date when the sub became a paid plan</description>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CampaignContactUpdateTest.cls
@isTest
public class CampaignContactUpdateTest {

	
  @testSetup static void setup() {
        // Create 
		Campaign cam = new Campaign(name ='!0K GMV');
		insert cam;
		system.debug(cam.Id);
		Campaign camRet = new Campaign(name ='Retention Campaign');
		insert camRet;
		
		CampaignMemberStatus cms1 = new CampaignMemberStatus(CampaignId=camRet.Id, HasResponded=false, Label='Not Sent', SortOrder=3);	
		CampaignMemberStatus cms2 = new CampaignMemberStatus(CampaignId=camRet.Id, HasResponded=false, Label='Sent', SortOrder=4); 
		CampaignMemberStatus cms3 = new CampaignMemberStatus(CampaignId=camRet.Id, HasResponded=false, Label='Attended', SortOrder=5);
 
		insert new List<CampaignMemberStatus>{cms1, cms2, cms3};
////		CampaignMemberStatus  cms2 = [select Id, Label, isDefault from CampaignMemberStatus where  CampaignId = :camRet.Id ];
//		if (cms2.isDefault ==true)   cms2.isDefault=false;                   
		
//		update cms2;
//		CampaignMemberStatus  cms1 = new CampaignMemberStatus ( SortOrder=2,
//		                           Label = 'Not Sent', IsDefault = true, CampaignId = camRet.Id );
	
//		insert cms1;
        List<CampaignRules__c > rules = new List<CampaignRules__c >();
        CampaignRules__c ruleg = new CampaignRules__c (
        				Name = '1000',
        				Starting_GMV__c =0.00,
        				Ending_GMV__c=10000,
        				Rule_Name__c = 'GMV',
        				Campaign_ID__c  = cam.Id);
        
        rules.add(ruleg);
        CampaignRules__c rulezero = new CampaignRules__c (
        				Name = 'zero',
        				Starting_GMV__c =0.00,
        				Ending_GMV__c=0.01,
        				Rule_Name__c = 'GMV',
        				Campaign_ID__c  = cam.Id);
        
        rules.add(rulezero);
 // retention       
        CampaignRules__c rulerc = new CampaignRules__c (
        				Name = 'Retention Campaign',
        				Starting_GMV__c =0.00,
        				Ending_GMV__c=100.00,
        				Rule_Name__c = 'Retention Campaign',
        				Campaign_ID__c  = camRet.Id);
        
        rules.add(rulerc);
        
        insert rules;
        
        String zeroCamId = CampaignUtility.getCampaignId(0);
        
        system.debug('zero '+zerocamid);
        system.debug('100'+CampaignUtility.getCampaignId(0));
        
        Id storeRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_StorePurchase).getRecordTypeId();
    	TestDataGenerator td = new TestDataGenerator();
      
      	list<Contact> lstCon = td.getContacts(true);
      	list<Opportunity> lstOpps = new List<Opportunity>();
      	List<BI_Data__c> lstbi = new List<BI_Data__c>();
      	list<Subscription__c> subs = td.getSubscriptions(true);
      // Create a new opportunity for the account
      
        for (Contact a :lstCon)
        {
	        Opportunity obj = new Opportunity();
	        obj.Name = 'Test ';
	        obj.CloseDate = Date.today().addDays(1);
	        obj.StageName = 'Purchased';
	        obj.Contact__c = a.Id;
	        obj.AccountId = a.AccountId;
	        obj.PurchaseDate__c = Date.today().addMonths(-2);
	        obj.RecordTypeId = storeRecordTypeId;
	        obj.Status__c = 'Active';
        //o.Pricebook2Id = getPricebook(true).Id;
        	lstOpps.add(obj);
        	a.Primary_MBA_Contact__c = true;
        	
        	BI_Data__c bi = new BI_Data__c (Lifetime_GMV__c =80.00, Opportunity__c = obj.Id, Subscription__c = subs[0].Id, Previous_Months_GMV__c = 100.00, Previous_Month_GMV_Date__c = Date.Today() );
			lstbi.add(bi);
        }
        update lstCon;
        insert lstOpps;  
        insert lstbi;  
  }     
    
     public static testmethod void test_batchAddCampaign() {
        
        String CRON_EXP = '0 0 0 3 9 ? 2022';
        Test.startTest();
// Schedule the test job
        String jobId = System.schedule('testBasicScheduledApex', CRON_EXP, new BatchAddToCampaign());
        // Get the information from the CronTrigger API object  
        CronTrigger ct = [SELECT id, CronExpression, TimesTriggered, 
        NextFireTime
        FROM CronTrigger WHERE id = :jobId];
        
        // Verify the expressions are the same 
        System.assertEquals(CRON_EXP, ct.CronExpression);
        
        // Verify the job has not run  
        
        System.assertEquals(0, ct.TimesTriggered);
        
        // Verify the next time the job will run  
        
        System.assertEquals('2022-09-03 00:00:00', String.valueOf(ct.NextFireTime));
        
        //Test the actual code run
        CampaignContactsUpdate opps = new CampaignContactsUpdate();
     
        Id storeRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_StorePurchase).getRecordTypeId();
 
        String query1 = 'Select contact__r.Id, contact__r.Primary_MBA_Contact__c, RecordTypeId, AccountId, bi_Data__r.Previous_months_GMV__c, bi_Data__r.Previous_Month_GMV_Date__c  From Opportunity where RecordTypeId = :storeRecordTypeId ';
 		query1 = query1 + ' limit 2';
        
        opps.query = query1;
        Database.executeBatch(opps,90);      
        
        Test.StopTest();
    }
     
 
    public static testmethod void test_updateCamStatus() 
    {
    	
    	List<Contact> cons = [Select Id from Contact limit 1];
    	CampaignRules__c camrule = CampaignUtility.getCampaignByName('Retention Campaign');
    	
    	String retCamId = camrule.Campaign_Id__c;

    	CampaignMember cm = new CampaignMember(contactId = cons[0].Id, CampaignId = retCamId, Status ='Not Sent' );
   		insert cm;
    	Task tsk = new Task(WhoId = cons[0].Id,ActivityDate=System.today(),Subject='Mass Email Test', Status = 'Completed');
   		insert tsk;
   		
    	String msg = UpdateCampaignStatus.updateRecords(retCamId);
    }
    	
    	
    
}