src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SupportPin__c</fullName>
        <label>Support Pin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type is set from BMP on the contact.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner RV Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactUtility.cls
public class ContactUtility {
	
    //This method will bring the contact record using email address
    
	public static List<Contact> getContactFromEmail(String emailadd){
		
		List<Contact> cons = new List<Contact>([select Id, firstName, lastName, AccountId, Account.SupportPin__c from Contact where email = :emailadd]);
		
		 return cons;

	}
//Zuora/BMP contacts	
	public static List<Contact> getBMPContacts(Id accID){
		
		List<Contact> cons = new List<Contact>([select Id, Name,  Type__c, AccountId from Contact where AccountId = :accId and Type__c <> null]);
		
		 return cons;

	}
	
	public static Contact getPrimaryContact(Id accID){
		
		Contact con = [select Id, Name,  Type__c, AccountId from Contact where AccountId = :accId and Type__c = 'Primary Contact' limit 1];
		
		 return con;
	
	}
	
	public static Contact getBillContact(Id accID){
		
		Contact con = [select Id, Name,  Type__c, AccountId from Contact where AccountId = :accId and Type__c = 'Billing Contact' limit 1];
		
		 return con;
	
	}
}