src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>iDev_Partner_ID__c</fullName>
        <description>Used to port new partner ID from the iDev commissions system; assigns new leads coming from the partner to the partner account owner. jw</description>
        <externalId>true</externalId>
        <label>iDev Partner ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MBA_Staging_Account__c.object
<CustomObject>
    <description>Used for the integration between MBA and Salesforce.  Fields are to be read only for all users and object is only visible to admins.</description>
    <fields>
        <fullName>CompanyName__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>MBA Staging Account</label>
    <nameField>
        <displayFormat>MSA-{0000}</displayFormat>
        <label>MBA Staging Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MBA Staging Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MBA_Staging_Contact__c.object
<CustomObject>
    <description>Used for the integration between MBA and Salesforce. Fields are to be read only for all users and object is only visible to admins.</description>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>MBA Staging Contact</label>
    <nameField>
        <displayFormat>MSC-{0000}</displayFormat>
        <label>MBA Staging Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MBA Staging Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MBA_Staging_Subscription__c.object
<CustomObject>
    <description>Used for the integration between MBA and Salesforce. Fields are to be read only for all users and object is only visible to admins.</description>
    <fields>
        <fullName>IsTrial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Trial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBAPartnerID__c</fullName>
        <label>MBA Partner ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>MBA Staging Subscription</label>
    <nameField>
        <displayFormat>MSS-{0000}</displayFormat>
        <label>MBA Staging Subscription Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MBA Staging Subscriptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Populated by a workflow capturing the associated contact or lead email address each time the contact name is changed.  Also used in case workflows to send email notifications if no lead or contact is called out on the case</description>
        <inlineHelpText>Populated by a workflow capturing the associated contact or lead email address each time the contact name is changed. Also used in case workflows to send email notifications if no lead or contact is called out on the case</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IsTrial__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Value pushed from MBA and is used in a trigger to convert leads when it&apos;s unchecked. Can also be used to force the account rollups to recalculate</description>
        <inlineHelpText>Value pushed from MBA and is used in a trigger to convert leads when it&apos;s unchecked. Can also be used to force the account rollups to recalculate</inlineHelpText>
        <label>MBA Is Trial</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <description>Unique identifier from MBA of account/user.  ID of the account which owns this subscription</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique identifier from MBA of account/user.  ID of the account which owns this subscription</inlineHelpText>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBAPartnerID__c</fullName>
        <description>Used to map Partner Source from MBA.  The iDev Affiliate ID of the partner, if this subscription is attributed to one</description>
        <label>MBA Partner ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <description>ID specific to the store/product purchased</description>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestSubscription_Utility.cls
@isTest(seeAllData=true) 
public class TestSubscription_Utility
{	
	static testMethod void testSubNewLeadToConvert() 
	{
		// Variables to use in testing
		MBA_Staging_Account__c objMBAAcct;
		MBA_Staging_Subscription__c objMBASub;
		MBA_Staging_Contact__c objMBAContact;
		Subscription__c objSub;
		
		// Start Test
		test.startTest();
			
		// Create Test Data
		TestDataGenerator td = new TestDataGenerator();
		
		// Initialize the Custom Setting Map   
		td.getStagingToTableMappingSettings();
		
		// Create Staging Account records as not Paid and grab one of them
		td.getAccountMBAs(true, false);
		objMBAAcct = td.AccountMBAs[0];		
		
		// Create Staging Contact records as not Paid
		td.getContactMBAs(true, false);
		objMBAContact = td.ContactMBAs[0];
		
		// Create Staging Subscription records as trial, but do NOT save yet; then grab one of them
		td.getStagingSubscriptions(false, true, objMBAAcct.MBAAccountID__c, 9898119);
		objMBASub = td.lstStagingSubscriptions[0];
			
		// Now save just one of the staging subscriptions
		insert objMBASub;
			
		// Capture the Subscription that should have just been created
		objSub = [SELECT Id, IsTrial__c, MBAAccountID__c, Lead__c, Account__c 
					FROM Subscription__c 
					WHERE MBAAccountID__c = :objMBASub.MBAAccountID__c];
		
		// Validate that actual subscriptions was created and associated to a lead
		system.assertNotEquals(objSub, null);
		system.assertNotEquals(objSub.Account__c, null);
		
		// Now create a new sub as paid
		objMBASub = new MBA_Staging_Subscription__c();
		objMBASub = td.lstStagingSubscriptions[1];
		objMBASub.MBAAccountID__c = objSub.MBAAccountID__c;
		objMBASub.IsTrial__c = false;		
		insert objMBASub;
		
		test.stopTest();    
	}
	
	static testMethod void testSubNewLeadByEmail() 
	{
		// Variables to use in testing
		MBA_Staging_Account__c objMBAAcct;
		MBA_Staging_Subscription__c objMBASub;
		MBA_Staging_Contact__c objMBAContact;
		Subscription__c objSub;
		Id leadId;
		
		// Create Test Data
		TestDataGenerator td = new TestDataGenerator();
		
		// Initialize the Custom Setting Map    
		td.getStagingToTableMappingSettings();
		
		// Create Staging Account records as not Paid and grab one of them
		td.getAccountMBAs(true, false);
		objMBAAcct = td.AccountMBAs[0];		
		
		// Create Staging Contact records as not Paid
		td.getContactMBAs(true, false);
		objMBAContact = td.ContactMBAs[0];
		
		// Create Staging Subscription records as trial and save one of them
		td.getStagingSubscriptions(false, true, objMBAAcct.MBAAccountID__c, 9898119);
		objMBASub = td.lstStagingSubscriptions[0];
		
		// Create a lead using the data from the MBA Account, MBA Contact
		Lead objLead = new Lead();
		objLead.FirstName = objMBAContact.FirstName__c;
		objLead.LastName = objMBAContact.LastName__c;
		objLead.Company = objMBAAcct.CompanyName__c;
		objLead.Email = objMBAContact.Email__c;
		
		insert objLead;
			
		// Start Test
		test.startTest();
		
		// Insert the new staging subscription
		insert objMBASub;
		
		test.stopTest();
								
		// Now query the new subscription
		objSub = [SELECT Id, IsTrial__c, MBAAccountID__c, Lead__c, Account__c 
					FROM Subscription__c 
					WHERE MBAAccountID__c = :objMBASub.MBAAccountID__c];

		// Validate that actual subscriptions was created and associated to the lead previously created
		system.assertNotEquals(objSub, null);
		
		// Now query the Lead to ensure it has been updated with a MBA Account ID
		Lead oLead = [SELECT Id, Name, MBAAccountID__c
					FROM Lead
					WHERE Id = :objLead.Id];
		
		system.assertNotEquals(oLead.MBAAccountID__c, null);
	}
	
	static testMethod void testSubNewAccount() 
	{
		// Variables to use in testing
		MBA_Staging_Account__c objMBAAcct;
		MBA_Staging_Subscription__c objMBASub;
		MBA_Staging_Contact__c objMBAContact;
		Subscription__c objSub;
		Id acctId;
		
		// Create Test Data
		TestDataGenerator td = new TestDataGenerator();
		
		// Initialize the Custom Setting Map    
		td.getStagingToTableMappingSettings();
		
		// Create Staging Account records as not Paid and grab one of them
		td.getAccountMBAs(true, false);
		objMBAAcct = td.AccountMBAs[0];	
		
		// Create Staging Contact records as not Paid
		td.getContactMBAs(true, false);
				
		// Create Staging Subscription records as paid
		td.getStagingSubscriptions(false, false, objMBAAcct.MBAAccountID__c, 9898119);
		objMBASub = td.lstStagingSubscriptions[0];
		
		// Start Test
		test.startTest();
		
		insert objMBASub;
		
		// Capture the Subscription that should have just been created
		objSub = [SELECT Id, IsTrial__c, MBAAccountID__c, Lead__c, Account__c, RecordTypeId, MBASubscriptionID__c
					FROM Subscription__c 
					WHERE MBAAccountID__c = :objMBASub.MBAAccountID__c];
		
		// Ensure an account id exists on the sub
		system.assertNotEquals(null, objSub.Account__c);
				
		acctId = objSub.Account__c;
		
		// Now capture the Account that was just created
		Account objAcct = [SELECT Id, Name, MBAAccountID__c, OwnerId
							FROM Account
							WHERE Id = :acctId];
							
		system.assertEquals(objAcct.MBAAccountID__c, objSub.MBAAccountID__c);
				
		Profile p = [SELECT Name, Id 
					FROM Profile  
					WHERE Name = 'System Administrator'];
		
		User usr = td.getUser(p, 'thisisunique');
		insert usr;
		
		// Grab a different account
		td.getAccounts(false);
		Account objAcctPartner = td.accounts[0];
		
		// Set the partner id on the account, and make the owner someone other than the running user
		objAcctPartner.iDev_Partner_ID__c = 55445599;
		objAcctPartner.OwnerID = usr.Id;		
		insert objAcctPartner;
		
		// Now insert a new subscription with the same partner id
		Subscription__c objSub2 = new Subscription__c();
		objSub2.RecordTypeId = objSub.RecordTypeId;
		objSub2.Account__c = null;
		objSub2.Lead__c = null;
		objSub2.MBAPartnerID__c = string.valueOf(objAcctPartner.iDev_Partner_ID__c);
		objSub2.MBASubscriptionID__c = objSub.MBASubscriptionID__c + '-99';
		objSub2.MBAAccountID__c = objAcct.MBAAccountID__c;
		
		insert objSub2;
		
		test.stopTest();
		 
		// Capture the Subscription that should have just been created
		Subscription__c objSub2_Res = [SELECT Id, IsTrial__c, MBAAccountID__c, Lead__c, Account__c, MBASubscriptionID__c, OwnerId
										FROM Subscription__c 
										WHERE Id = :objSub2.Id];
		
		system.debug('*** New Sub for Ownershipt Check: ' + objSub2_Res);
		system.debug('*** Expected Account Id: ' + objAcct.Id);
			
	}
}