src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Assign_To_Team__c</fullName>
        <description>Team to which the LDR would like to round robin the Account</description>
        <inlineHelpText>Team to which the LDR would like to round robin the Account</inlineHelpText>
        <label>LDR Assign To Team</label>
        <picklist>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC Enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC Direct</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Projected_Annual_Revenue__c</fullName>
        <label>Projected Annual Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>&lt; $50,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50,000 - $250,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$250,000 - $500,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$500,000 - $1,000,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$1,000,000 - $2,000,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$2,000,000 - $5,000,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$5,000,000 - $50,000,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50,000,000 +</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>No_Assign__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag used to tell the assignment rules if they should fire. Mainly used in the MBA Integration so code can assign Partner Account as owner without lead being re-assigned via assignment rules</description>
        <label>No Assign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Projected_Annual_Revenue__c</fullName>
        <description>Populated from Hubspot form. Can be updated by a Sales rep.</description>
        <inlineHelpText>Populated from Hubspot form. Can be updated by a Sales rep.</inlineHelpText>
        <label>Projected Annual Revenue</label>
        <picklist>
            <picklistValues>
                <fullName>&lt; $50,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50,000 - $250,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$250,000 - $500,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$500,000 - $1,000,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$1,000,000 - $2,000,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$2,000,000 - $5,000,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$5,000,000 - $50,000,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>$50,000,000 +</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Round_Robin_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Last_Number_Used__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This number will be updated by the Round Robin code and will show the last Round Robin Number used to assign a record for the given Queue.</description>
        <inlineHelpText>This number will be updated by the Round Robin code and will show the last Round Robin Number used to assign a record for the given Queue.</inlineHelpText>
        <label>Last Number Used</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object_API_Name__c</fullName>
        <description>The API name of the Object his queue is used for Round Robin assignment</description>
        <inlineHelpText>The API name of the Object his queue is used for Round Robin assignment</inlineHelpText>
        <label>Object API Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <description>The name (Label) of the queue a record may be assigned to using Assignment rules which Round Robin logic will then re-assign</description>
        <inlineHelpText>The name (Label) of the queue a record may be assigned to using Assignment rules which Round Robin logic will then re-assign</inlineHelpText>
        <label>Queue Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Round Robin Settings</label>
</CustomObject>

src/objects/User_Status__c.object
<CustomObject>
    <description>Used to log sales reps in and out of office for lead round robin</description>
    <fields>
        <fullName>Round_Robin_Queue__c</fullName>
        <description>The queue user belongs to for Round Robin assignment</description>
        <inlineHelpText>The queue user belongs to for Round Robin assignment</inlineHelpText>
        <label>Round Robin Queue</label>
        <picklist>
            <picklistValues>
                <fullName>Acq Lead Distro Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Acquisition Accounts Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC Direct Accounts Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC Enterprise Accounts Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer AU Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Designer Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct AU Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Sales Accounts Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Sales Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Accounts Queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Requests Queue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Out of Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In the Office</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Status</label>
    <nameField>
        <displayFormat>US-{0000}</displayFormat>
        <label>User Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Status</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestRoundRobin.cls
@isTest(seeAllData=true) 
private class TestRoundRobin 
{
    static testMethod void testRoundRobin() 
    {
    	string strQueueName = 'RoundRobinTestQueue';
    	
		// Create Test Data
		TestDataGenerator td = new TestDataGenerator();
		
		// Ensure there is a row in the Robin Robin Custom setting for the new queue
		Round_Robin_Settings__c rrs = new Round_Robin_Settings__c();
		rrs.Name = 'RoundRobinQueueTest';
		rrs.Object_API_Name__c = 'Lead';
		rrs.Queue_Name__c = strQueueName;
		rrs.Last_Number_Used__c = 0;
		insert rrs;
		
		// Create an actual Queue
		Group g = new Group();
		g.Name = strQueueName;
		g.Type = 'Queue';
		insert g;
		
		QueueSobject q = new QueueSobject();
		q.QueueId = g.Id;
		q.SobjectType = 'Lead';
		insert q;
		
		// Create new users
		list<User> lstUsers = td.getUsers(null);
		system.debug('***TestRoundRobin - lstUsers: ' + lstUsers);
		
		list<User_Status__c> lstUStatus = new list<User_Status__c>();
		
		// Create a User Status record for the new users
		for (User u : lstUsers)
		{
			User_Status__c us = new User_Status__c(OwnerId = u.Id);
			us.Round_Robin_Queue__c = strQueueName;
			us.Status__c = 'In the Office';
			lstUStatus.add(us);
		}
		insert lstUStatus;
		
		test.startTest();
		
		// Create leads
		list<Lead> lstLeads = td.getLeads(true);
		
		set<id> stLeadIds = new set<id>();		
		integer x = 0;
		
		// Now update leads to the new queue and ensure they are assigned to the new users
		for (Lead objLead : lstLeads)
		{
			objLead.OwnerId = q.QueueId;
			if (x < 3)
				objLead.No_Assign__c = false;
			else
				objLead.No_Assign__c = true;
				
			stLeadIds.add(objLead.Id);
			
			x++;
		}
		
		system.debug('***TestRoundRobin - Updating Leads: ' + lstLeads);		
		update lstLeads;

		// Run the Round Robin on the new lead		
		RoundRobin.RoundRobinForLead(lstLeads);
		
		test.stopTest();
		
		// Pull back the leads
		list<Lead> lstUpdatedLeads = [SELECT Id, OwnerId, Name, Owner.Name 
									FROM Lead
									WHERE Id IN :stLeadIds];
					
		system.debug('***Leads are now: ' + lstUpdatedLeads);
		x = 0;
		
		for (Lead objLead : lstUpdatedLeads)
		{
			system.debug('***Lead OwnerId: ' + objLead.OwnerId + '; QueueId: ' + q.QueueId + '; User Id: ' + lstUsers[x].Id);
			
			if (x < 3)
			{
				// Verify the lead is now assigned to the correct user
				system.assertNotEquals(objLead.OwnerId, q.QueueId);
			}
			else
			{
				// Verify lead is still assigned to the queue
				system.assertequals(objLead.OwnerId, q.QueueId);
			}
			x++;
		}
    }
    
    static testMethod void testRRAccount() 
    {
    	TestDataGenerator td = new TestDataGenerator();
        
	 	list<Account> lstAcct = td.getAccounts(true);
	  
	    InvokeRoundRobin instance = new InvokeRoundRobin();
    
 //       lstAcct[0].Projected_Annual_Revenue__c = 'Less than $100,000';
 		 lstAcct[0].Assign_To_Team__c = 'Enterprise';
        
        update lstAcct;
        
        PageReference pageRef = Page.RoundRobin;
        Test.setCurrentPage(pageRef);      
       
        System.currentPageReference().getParameters().put('id', lstAcct[0].Id);
        
    	Test.startTest();
    	
    	instance.autoRun();
    	
    	Test.stopTest();
    }
    static testMethod void testQualifyAccount() 
    {
    	TestDataGenerator td = new TestDataGenerator();
        
	 	list<Account> lstAcct = td.getAccounts(true);
	  
	    InvokeRoundRobin instance = new InvokeRoundRobin();
        
        PageReference pageRef = Page.QualifyButton;
        Test.setCurrentPage(pageRef);      
       
        System.currentPageReference().getParameters().put('id', lstAcct[0].Id);
        
    	Test.startTest();
    	
    	instance.autoRun();
    	
    	Test.stopTest();
    }
}