src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Account Status.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contracting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pursuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onboarding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the store this case is in reference to</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_Pin__c</fullName>
        <description>Formula : Pulled from associated account</description>
        <formula>Subscription__r.Support_PIN__c</formula>
        <inlineHelpText>Pulled from associated account</inlineHelpText>
        <label>Support Pin</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CaseSubmissionSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for custom Web2Case and LiveAgent pre-Chat code</description>
    <fields>
        <fullName>Default_Support_Account_ID__c</fullName>
        <description>Default Account ID used for initially orphaned Contacts created from the Live Agent pre-Chat form</description>
        <inlineHelpText>Default Account ID used for initially orphaned Contacts created from the Live Agent pre-Chat form</inlineHelpText>
        <label>Default Support Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Support_Owner_ID__c</fullName>
        <description>Default User ID for Contacts created in the Live Agent pre-Chat form</description>
        <inlineHelpText>Default User ID for Contacts created in the Live Agent pre-Chat form</inlineHelpText>
        <label>Default Support Owner ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LiveAgent_Button_Name__c</fullName>
        <description>The Developer name of the LiveAgent Button used in this Case Submission Setting entry</description>
        <inlineHelpText>The Developer name of the LiveAgent Button used in this Case Submission Setting entry</inlineHelpText>
        <label>LiveAgent Button Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Submission Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Support_PIN__c</fullName>
        <formula>Account.SupportPin__c</formula>
        <label>Support PIN</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Shows the current status of the store from MBA but does not always indicate if we have received payment yet.</description>
        <inlineHelpText>Status. Populated from MBA.</inlineHelpText>
        <label>MBA Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terminated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraud</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on Client</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>StoreURL__c</fullName>
        <description>URL of the BC trial or store populated by MBA</description>
        <inlineHelpText>URL of the BC trial or store populated by MBA</inlineHelpText>
        <label>MBA Store URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Support_PIN__c</fullName>
        <description>Formula pulling the pin value from the associated account or lead</description>
        <formula>IF(
ISBLANK(Account__r.SupportPin__c), Lead__r.SupportPin__c ,Account__r.SupportPin__c)</formula>
        <label>Support Pin</label>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/LiveAgentChatController.cls
public class LiveAgentChatController {
    
    public Contact theContact {get; set;}
    public Subscription__c theSub {get; set;}
    public String endpoint {get; set;}
    public String csse {get; set;}
    public String jsSubmitForm {get; set;}
    public String liveChatBtnId{get; set;}    
    public String liveChatDepId{get; set;}
    public String formPIN{get; set;}
    public String formURL{get; set;}
    public String formURLqry{get; set;}
    public String formEmail{get; set;}
    public String formFname{get; set;}
    public String formLname{get; set;}
    public String tempURL { get; set; }
    public Boolean chatPanelOn{get; set;}
    public Id subId{get; set;}
    public Id AcctId{get; set;}
    public Id AcctOwn{get; set;}
        
    public LiveAgentChatController(){

        jsSubmitForm = '';
        theContact = new Contact();
        theSub = new Subscription__c();
        chatPanelOn = False;

        //get the querystring data passed in by the button.  This is the liveagent form action
        //EX: ?endpoint=https%3A%2F%2F1.la1a1.salesforceliveagent.com... etc..
        endpoint = '';
        csse = '';
        PageReference pageRef = ApexPages.currentPage();
        if (pageRef.getParameters() != null) {
            if (pageRef.getParameters().containsKey('endpoint')) {
                if (pageRef.getParameters().get('endpoint') != null) {
                    endpoint = pageRef.getParameters().get('endpoint');
                }
            }           
        }       

        if (pageRef.getParameters() != null) {
            if (pageRef.getParameters().containsKey('SupportSetting')) {
                if (pageRef.getParameters().get('SupportSetting') != null) {
                    csse = pageRef.getParameters().get('SupportSetting');
                }
            }
        }
        // Get the csse (Case Submission Setting entry from the VF page)
        system.debug('SupportSetting Parameter from VF page: '+csse);
        // TODO: API 29 supports pre-Chat API which will allow passing of parameters, until then hardcode Custom Setting
        CaseSubmissionSettings__c css = CaseSubmissionSettings__c.getValues('LiveAgent');
        system.debug('css Setting value: '+css);


        LiveChatButton lCBId = [SELECT Id FROM LiveChatButton WHERE DeveloperName =: css.LiveAgent_Button_Name__c];
        
        Datetime tempDate = datetime.newInstance(0000, 00, 0, 00, 00, 0);
        String latestId;
                
        List<LiveChatDeployment> lDIds = [SELECT Id, CreatedDate FROM LiveChatDeployment];
        
        for (LiveChatDeployment d : lDids){
            if (d.CreatedDate > tempDate){
                latestId = d.Id;
            }    
        }
        liveChatBtnId = String.valueOf(lCBId.id); 
        liveChatDepId = latestId;
        system.debug('***** Chat Button ID: '+liveChatBtnId);
        system.debug('***** Chat Deploy ID: '+liveChatDepId);

    }

    public pagereference clickChat() {      
        PageReference pr = null;        

        // Get the csse (Case Submission Setting entry from the VF page)
        //String csse = ApexPages.currentPage().getParameters().get('csse');
        system.debug('csse Parameter from VF page: '+csse);
        CaseSubmissionSettings__c css = CaseSubmissionSettings__c.getValues('LiveAgent');
        
        if ( AcctId == null ){
            Id AcctId = css.Default_Support_Account_ID__c; //ID for the Account to parent these Contacts
        }
        Id OwnId = css.Default_Support_Owner_ID__c; //ID for a default user to set as the owner of the Contact 

        system.debug('***** clickChat fields: ' + endpoint + ', ' + AcctId + ', ' + OwnId + ', ' + formPIN + ', ' + 
                                                formURL + ', ' + formEmail + ', ' + formFname + ', ' + formLname);

        //see if the email submitted exists as a contact
        List<Contact> contactList = new List<Contact>();
        if ( (formEmail != null) && (formEmail != '') ) {
            contactList = [SELECT Id FROM Contact WHERE email=:formEmail LIMIT 1];
            system.debug('***** Contact List: '+contactList);
            if (contactList.isEmpty()) {
                if(formLname == null){
                	formLname = formFname;
                }
                //create the contact
                Contact c = new Contact(
                    FirstName = formFname,
                    LastName = formLname,
                    Email = formEmail,
                    LeadSource = 'Chat',
                    AccountId = AcctId,
                    OwnerId = AcctOwn);
                insert c;
            }   
        }  

        jsSubmitForm = 'jQuery(\'#preChatFormSubmit\').submit();';
        
        return pr;      
    }

    public Id validatePIN(){
        List<Subscription__c> subList = new List<Subscription__c>();
        String PINArticleURL = '<a href=\"https://support.bigcommerce.com/questions/1207/What+is+my+support+PIN+and+where+do+I+find+it%3F\">What is my support PIN</a>';
        tempURL = '';
        
        // TODO: parse/trim Store URL to remove http:// or https://
        if(formURL.startsWith('http://')) {
            formURL = formURL.removeStart('http://');
        }
        
        if(formURL.startsWith('https://')) {
            formURL = formURL.removeStart('https://');
        }
        
        if(formURL.endsWith('/')){
        	formURL = formURL.removeEnd('/');
        }
        
        if(formURL.startsWith('www.')) {
        	formURL = formURL.removeStart('www.');
        }
        
        formURLqry = '%'+formURL+'%';
        
        try{
            subList = [SELECT Id, Account__r.Id, Account__r.OwnerId, Support_PIN__c, StoreURL__c FROM Subscription__c
                    WHERE Support_PIN__c =: formPIN AND StoreURL__c LIKE :formURLqry
                    AND Status__c = 'Active' LIMIT 1];
        } catch (ListException le){
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.FATAL, 'The Support URL/PIN combination provided cannot be verified. Please confirm with Account owner and try again. If you continue to experience difficulty please refer to this article - '+PINArticleURL);
            ApexPages.addMessage(msg);
        } catch (Exception e){
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.FATAL, 'The Support URL/PIN combination provided cannot be verified. Please confirm with Account owner and try again. If you continue to experience difficulty please refer to this article - '+PINArticleURL);
            ApexPages.addMessage(msg);
        }
        
        if(subList.size() > 0){
            chatPanelOn = True;
            subId = subList[0].Id;
            AcctId = subList[0].Account__r.Id;
            AcctOwn = subList[0].Account__r.OwnerId;
            clickChat();
        } else {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.FATAL, 'The Support URL/PIN combination provided cannot be verified. Please confirm with Account owner and try again. If you continue to experience difficulty please refer to this article - '+PINArticleURL);
            ApexPages.addMessage(msg);
        }
        return null;
    }

}