src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Ltc__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onboarding Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBD_Segment__c</fullName>
        <description>For Orion</description>
        <label>zSBD Orion Segment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Enterprise Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Consulting_Services__c</fullName>
        <description>Pulls the product names from the PS Opportunity on to the case</description>
        <inlineHelpText>Pulls the product names from the PS Opportunity on to the case</inlineHelpText>
        <label>zConsulting Service</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Store_URL__c</fullName>
        <description>Migrations : This is the client&apos;s current or source store URL, from which data will be migrated. This is NOT the BC Store URL.</description>
        <inlineHelpText>This is the client&apos;s current or source store URL, from which data will be migrated. This is NOT the BC Store URL.</inlineHelpText>
        <label>Current Store URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Migration_Platform__c</fullName>
        <description>Migrations : picklist</description>
        <label>Migration Platform</label>
        <picklist>
            <picklistValues>
                <fullName>1Shopping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3dCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AceShop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon Webstore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon Webstores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AspDotNetSF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ayacart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bigcommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ChannelAdvisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CoreCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CreateAShoppe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRE Loaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CubeCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>digiSHOP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EBAY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoDaddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HHG multistore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interspire (standard SOW)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JooCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LemonStand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lemon Stand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaded Commerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaded Commerce (CRELoaded/OSCommerce)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magento</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magento Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magento Go</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mal&apos;s eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MijoShop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miva Merchant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Account on the Case does not match the Account on the Opportunity</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Opportunity.AccountId</valueField>
            </filterItems>
            <infoMessage>Select Opportunity related to the Account</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Cases</relationshipLabel>
        <relationshipName>OpportunityCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Notes__c</fullName>
        <label>Sales Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the store this case is in reference to</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Migration</fullName>
        <active>true</active>
        <businessProcess>Migration Case Process</businessProcess>
        <description>Used by Sales to request store migrations</description>
        <label>Migration</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Store_URL__c</fullName>
        <inlineHelpText>For Migration Products only, this field must be populated.</inlineHelpText>
        <label>Current Store URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Migration_Platform__c</fullName>
        <inlineHelpText>For Migration products only, this must be populated.</inlineHelpText>
        <label>Migration Platform</label>
        <picklist>
            <picklistValues>
                <fullName>1Shopping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3dCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon Marketplace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon Webstore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon Webstores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ayacart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bigcommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CoreCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CreateAShoppe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRE Loaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CubeCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoDaddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoDaddy QuickCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interspire (standard SOW)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lemon Stand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaded Commerce (CRELoaded/OSCommerce)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magento CE/EE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magento/Magento CE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magento Go</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mal&apos;s eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miva Merchant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miva Merchant V4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miva Merchant V5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OpenCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OptionCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OSCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OsMaxCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portable Shops</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>New_Product_Plan__c</fullName>
        <description>Friendly product plan name (ie not what MBA/BMP is sending)</description>
        <formula>IF( ProductID__c =&apos;65&apos;, &apos;Silver NEXT&apos;, 
IF(ProductID__c =&apos;90&apos;, &apos;Silver NEXT v2 (29.95)&apos; , 
IF (ProductID__c =&apos;66&apos;, &apos;Gold NEXT&apos; , 
IF (ProductID__c =&apos;67&apos;, &apos;Platinum NEXT&apos; , 
IF (ProductID__c =&apos;118&apos;, &apos;Standard Plan&apos; ,  
IF (ProductID__c =&apos;119&apos;, &apos;Plus Plan&apos; ,
IF (ProductID__c =&apos;101&apos;, &apos;Standard&apos; , 
IF (ProductID__c =&apos;130&apos;, &apos;Standard - $14 Test&apos; , 
IF (ProductID__c =&apos;129&apos;, &apos;Standard - $10 Test&apos; ,
IF (ProductID__c =&apos;131&apos;, &apos;15 Day Free Trial - $10 Test&apos; ,
IF (ProductID__c =&apos;132&apos;, &apos;15 Day Free Trial - $14 Test&apos; ,
Product__c ) ))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Friendly product plan name (ie not what MBA/BMP is sending)</inlineHelpText>
        <label>New Product Plan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Notes__c</fullName>
        <label>Sales Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Store_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Store Purchase Opportunity that this is related to.</inlineHelpText>
        <label>Store Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity does not have the same Account</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>Select a Store purchase opportunity</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Professional Services)</relationshipLabel>
        <relationshipName>PSOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The subscription is not related to the account on the opportunity</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>The subscription is not related to the account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>New_Product_Plan__c</fullName>
        <formula>IF( ProductID__c =&apos;65&apos;, &apos;Silver NEXT&apos;, 
IF(ProductID__c =&apos;90&apos;, &apos;Silver NEXT v2 (29.95)&apos; , 
IF (ProductID__c =&apos;66&apos;, &apos;Gold NEXT&apos; , 
IF (ProductID__c =&apos;67&apos;, &apos;Platinum NEXT&apos; ,  
IF (ProductID__c =&apos;118&apos;, &apos;Standard Plan&apos; ,  
IF (ProductID__c =&apos;119&apos;, &apos;Plus Plan&apos; ,  
IF (ProductID__c =&apos;101&apos;, &apos;Standard&apos; , 
Product__c ) ))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>New Product Plan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Was used by Acq on forecast subs but can probably be deleted now</description>
        <label>zOpportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerHandler.cls
/**********************************************************************
Name:  Professional Opportunity Updates
======================================================
 Purpose: Perform Professional Opportunity updates.
======================================================
 
History:   
                                                      
VERSION AUTHOR   DATE       DETAIL     
 
1.0 Maggie Frederick 9/1/2013  Initial development
2.0 Maggie Frederick 2/17/2015 Prevent recursive action
3.0 Maggie Frederick 3/17/2015 Store opportunity for PS Opps
4.0 Maggie Frederick 9/27/2015 RemoveConsulting services opps
 
***********************************************************************/

public class OpportunityTriggerHandler {

 private static  Id idOppRecordType =  Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Professional Services').getRecordTypeId();
// private static  Id idCaseRecordType = Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Professional Services').getRecordTypeId();
 private static  Id idMigCaseRecordType = Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Migration').getRecordTypeId();
 
  
    public void OnAfterUpdate(Opportunity[] newList, Map<ID, Opportunity> OpportunityMap, Opportunity[] oldList)
    {
	    if (!TriggerRecursionController.casesCreatedFromPSOpp)	
	    {    
	        Set <Id> closedwonOpps = new Set <Id>();
	       
	        for (integer i =0; i < newList.size(); i++)
	        {
	// add for is changed....
	            if (newList[i].StageName == 'Closed Won' && 
	                oldList[i].StageName <>'Closed Won' && 
	               newList[i].RecordTypeId == idOppRecordType)
	                {
	                    closedwonOpps.add(newList[i].Id);
	                }
	        }
         
        	if (!closedwonOpps.isEmpty()) 
	        {
        		createCases(closedwonOpps);
	           	TriggerRecursionController.casesCreatedFromPSOpp = true;
	        }
    	}
 
    }
    
 
    private void createCases(Set<Id> oppIds)
    
    {
 		
		List<Case> newCases = new List<Case>();
        
        Map<id, Opportunity> opps = new Map<Id, Opportunity> ([select Id, AccountId, Subscription__r.Id,
                                                              Account.Ssc__r.Id, OwnerId,
                                                              Account.Ltc__r.Id, Sales_Notes__c,
                                                              Store_Opportunity__r.Id,  Store_Opportunity__r.New_Product_Plan__c,
                                                              Current_Store_URL__c, Migration_Platform__c,
                                                              Account.SBD_Segment__c
                                                              from Opportunity
                                                              where Id in :oppIds
                                                              ]);
        Map<id, Id> oppcontact = OpportunityHelper.getContactFromRole(oppIds,'Professional Services Contact');
                                                              
                                                             
        Map<Id, OpportunityLineItem> oppItems = new Map<Id,OpportunityLineItem>([Select Id, TotalPrice, 
                                                        PricebookEntry.Product2.Name, Consulting_Services__c,
                                                        PricebookEntry.Name, PricebookEntry.Product2.Family,                                                      
                                                        OpportunityId
                                                        From OpportunityLineItem  where OpportunityId in :opps.keySet()]);
        
        
        for (Id itemId :oppItems.KeySet())
        {
            OpportunityLineItem item = oppItems.get(itemId);
            Opportunity opp = opps.get(item.OpportunityId);
            Case newCase = new Case();
            newCase.Origin = 'Internal Request';
            newCase.Reason = 'New client purchase';
            newCase.Subject = 'Client purchase of product';
            newCase.Description = 'Client has purchased ' + item.PricebookEntry.Product2.Name;
            newCase.Department__c = 'Professional Services';
            newCase.AccountId = opp.AccountId;
            if (opp.Subscription__r.Id <> null) newCase.Subscription__c = opp.Subscription__r.Id;
            if (opp.Store_Opportunity__r.Id <> null) newCase.Opportunity__c = opp.Store_Opportunity__r.Id;
            if (oppContact.get(opp.Id) <> null) newCase.ContactId = oppContact.get(opp.Id);
            newCase.Price__c = item.TotalPrice;
            newCase.Product_Sold__c = item.PricebookEntry.Product2.Name;
            newCase.Sold_by__c = opp.OwnerId;
            newCase.RecordTypeId = idMigCaseRecordType;
 
            if (opp.Sales_Notes__c <> null) newCase.Sales_Notes__c = opp.Sales_Notes__c;
            system.debug(' ***' +item.PricebookEntry.Product2.Family);

            if (item.PricebookEntry.Product2.Family.contains('Migration'))
            {
            	If (opp.Current_Store_URL__c == null ||
            	    opp.Migration_Platform__C == null)
            	{
// throw error     
//				 ErrorEmailHelper.notifyOnError('Opportunity Trigger Handler', 'Create Case', 'Error in Opportunity Trigger Handler - Migration', 'Error Creating case for: ' + opp.Id);
				 
                 return;
		        }
            	newCase.Current_Store_URL__c = opp.Current_Store_URL__c;
            	newCase.Migration_Platform__c = opp.Migration_Platform__c;
            	newCase.OwnerId = Label.Migration_Case_Queue;
            	newCase.Subject = 'Your Bigcommerce Migration';
 				newCases.add(newCase);
         	}
 			
        }
        
        if (newCases.size() > 0)
        {
            Try{
                insert newCases;
            }
            catch(Exception e) {
 //              ErrorEmailHelper.notifyOnError('Opportunity Trigger Handler', 'Create Case', 'Error in Opportunity Trigger Handler - Create Case', 'Error Creating case for: ' + opp.Id);
                system.debug('Error in Opportunity Trigger Handler - Create Case');
                }   
        
        
        }
        
    }
/*
	public static Id checkOwner(List<Opportunity> opps)
	{
		for(OpportunityFieldHistory obj:[SELECT CreatedById,CreatedDate,Field,Id,OpportunityId,NewValue,OldValue FROM OpportunityFieldHistory WHERE Field = 'Owner' and OpportunityId IN:mapOwnerDiffAsCreatedBy.keyset()   order by CreatedDate DESC])
               {
 				  if (obj.NewValue == mapOwnerDiffAsCreatedBy.get(obj.OpportunityId))	
 				  {
                    if(!mapOwnerAssignDate.containsKey(obj.OpportunityId))
                    {
                        mapOwnerAssignDate.put(obj.OpportunityId, obj.CreatedDate);
                    }
 				  }
                } 
            
   //Query History Table for Stage Change Date 
            Map<String,DateTime> mapOppStages = new Map<String,DateTime>();
  			
            for(OpportunityFieldHistory obj:[SELECT CreatedById,CreatedDate,Field,Id,OpportunityId,NewValue,OldValue FROM OpportunityFieldHistory WHERE Field = 'StageName' and OpportunityId IN:mapTrialOppOwner.keyset()   order by CreatedDate DESC])
                {
 				  if (obj.CreatedById == mapTrialOppOwner.get(obj.OpportunityId))	
 				  {
                    if(!mapOppStages.containsKey(obj.OpportunityId))
                    {
                        mapOppStages.put(obj.OpportunityId, obj.CreatedDate);
                    }
 				  }
                } 
            
	}
*/
}