src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Indicates whether the account exists in MBA or BMP</description>
        <inlineHelpText>Indicates whether the account exists in MBA or BMP</inlineHelpText>
        <label>Provisioning System</label>
        <picklist>
            <picklistValues>
                <fullName>BMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBAClientID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Client ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Indicates whether the account exists in MBA or BMP</description>
        <inlineHelpText>Indicates whether the account exists in MBA or BMP</inlineHelpText>
        <label>Provisioning System</label>
        <picklist>
            <picklistValues>
                <fullName>BMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MBA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBAAccountID__c</fullName>
        <externalId>true</externalId>
        <inlineHelpText>This is what MBA is sending</inlineHelpText>
        <label>MBA Account ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>Indicates whether the account exists in MBA or BMP</description>
        <inlineHelpText>Indicates whether the account exists in MBA or BMP</inlineHelpText>
        <label>Provisioning System</label>
        <picklist>
            <picklistValues>
                <fullName>MBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Trial</fullName>
        <active>true</active>
        <businessProcess>Sales Process %28Trial to Purchase%29</businessProcess>
        <description>Use when the client has created a trial store.</description>
        <label>Trial</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RESTAPICalloutTest.cls
@isTest(SeeAllData=True)
public class RESTAPICalloutTest  {
  
  static testMethod void testBMPRequestAccount() 
  {    
    SingleRequestMock fakeResponse = new SingleRequestMock(200, 'Complete','[Status=OK, StatusCode=200]',null);
    Test.setMock(HttpCalloutMock.class, fakeResponse);
 
// create test data       
        Account a = new Account();
        a.Name = 'Test Account';
        a.Source__c = 'BMP';
        a.MBAAccountID__c = '341726';
        insert a;
  }
 
  
  static testMethod void testBMPRequestContact() 
  {    
    SingleRequestMock fakeResponse = new SingleRequestMock(200, 'Complete','[Status=OK, StatusCode=200]',null);
    Test.setMock(HttpCalloutMock.class, fakeResponse);
 
 // create test data       
      TestDataGenerator td = new TestDataGenerator();
      
      list<Contact> lstCon = td.getContacts(false);
      lstCon[0].MBAAccountID__c = '341726';
      lstCon[0].MBAClientID__c = '941726';
      lstCon[0].Source__c = 'BMP';
        
      insert lstCon;
      
      Opportunity opp = new Opportunity (AccountId = lstCon[0].AccountId,
                           name = 'New Opp', StageName= 'Trial',
                           Contact__c = lstCon[0].Id,
                           closeDate= System.Today(),
                           Source__c = 'BMP',
                           MBAAccountId__c = '341726',
                           MBASubscriptionID__c = '2233445');
      insert opp;
  }
  
}