src/objects/BI_Data__c.object
<CustomObject>
    <description>To hold store information from BI.</description>
    <fields>
        <fullName>Last_Payment_Amount__c</fullName>
        <label>Last Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Payment_Date__c</fullName>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Lifetime_GMV__c</fullName>
        <inlineHelpText>Lifetime GMV since 1/1/13 or Store provision date if provisioned after.</inlineHelpText>
        <label>Lifetime GMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BI_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BI Data</label>
        <referenceTo>BI_Data__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillingCycle__c</fullName>
        <label>Billing Cycle</label>
        <picklist>
            <picklistValues>
                <fullName>One-Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biennially</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The subscription is not related to the account on the opportunity</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>The subscription is not related to the account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>rvpe__RVAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RV Account</label>
        <referenceTo>rvpe__RVAccount__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Commission__c.object
<CustomObject>
    <description>To keep track of client payments andrelated partner details</description>
    <fields>
        <fullName>BIData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BI Data</label>
        <referenceTo>BI_Data__c</referenceTo>
        <relationshipLabel>Partner Commissions</relationshipLabel>
        <relationshipName>Partner_Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IncludeInCurrentMonth__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include in Current Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Partner Commissions</relationshipLabel>
        <relationshipName>Partner_Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <description>Client Payment</description>
        <label>Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RVAccount__c</fullName>
        <label>RV Account</label>
        <referenceTo>rvpe__RVAccount__c</referenceTo>
        <relationshipLabel>Partner Commissions</relationshipLabel>
        <relationshipName>Partner_Commissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Partner Commission</label>
    <nameField>
        <label>Partner Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Commissions</pluralLabel>
    <recordTypes>
        <fullName>Detail</fullName>
        <active>true</active>
        <label>Detail</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>BillingCycle__c</fullName>
        <description>Designates whether the store is billed monthly or annually.  Populated by MBA</description>
        <inlineHelpText>Designates whether the store is billed monthly or annually.  Populated by MBA</inlineHelpText>
        <label>MBA Billing Cycle</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>One-Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biennially</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free Trial/Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lifetime_GMV__c</fullName>
        <description>Lifetime GMV from the BI Data object</description>
        <inlineHelpText>Lifetime GMV, rolled up from the BI Data object</inlineHelpText>
        <label>Lifetime GMV</label>
        <summarizedField>BI_Data__c.Lifetime_GMV__c</summarizedField>
        <summaryForeignKey>BI_Data__c.Subscription__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Was used by Acq on forecast subs but can probably be deleted now</description>
        <label>zOpportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BatchPartnerCommissionsTest.cls
@isTest
private class BatchPartnerCommissionsTest {
	
	@testSetup static void setup() 
    {
      TestDataGenerator td = new TestDataGenerator();
      list<Account> lstAcc = td.getAccounts(true);
      list<Subscription__c> subs = td.getSubscriptions(true);
      // Create a new opportunity for the account
      Id StoreRecordTypeId = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_Recordtype_StorePurchase).getRecordTypeId();
	  rvpe__RVAccount__c  rva = new rvpe__RVAccount__c (Name = 'Test Partner', rvpe__ExtAccountId__c = 912345, Commission__c = 20);
	  insert rva;
	  
      Opportunity o = new Opportunity();
        o.Name = 'Test RV';
        o.RecordTypeId = StoreRecordTypeId;
        o.CloseDate = Date.today().addDays(1);
        o.StageName = 'Purchased';
        o.rvpe__RVAccount__c = rva.Id;
        o.BillingCycle__c = 'Monthly';
        o.AccountId = lstAcc[0].Id;
        //o.Pricebook2Id = getPricebook(true).Id;
        insert o;
        
        Opportunity o2 = new Opportunity();
        o2.Name = 'Test RV Annual';
        o2.RecordTypeId = StoreRecordTypeId;
        o2.CloseDate = Date.today().addDays(10);
        o2.StageName = 'Purchased';
        o2.rvpe__RVAccount__c = rva.Id;
        o2.BillingCycle__c = 'Annually';
        o2.AccountId = lstAcc[0].Id;
        //o.Pricebook2Id = getPricebook(true).Id;
        insert o2;
        
        BI_Data__c bi = new BI_Data__c (Lifetime_GMV__c =1000.00, Opportunity__c = o.Id, Subscription__c = subs[0].Id, Last_Payment_Amount__c =20.00, Last_Payment_Date__c = Date.Today() );
  		insert bi;
  		
  		date nextdate = Date.Today().addmonths(-3);
  		
  		BI_Data__c bia = new BI_Data__c (Lifetime_GMV__c =2000.00, Opportunity__c = o2.Id, Subscription__c = subs[1].Id, Last_Payment_Amount__c =2000.00, Last_Payment_Date__c = nextDate );
  		insert bia;
        
        Id detailRecordTypeId = Partner_Commission__c.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Detail').getRecordTypeId();
		
      	Partner_Commission__C newc = new Partner_Commission__C(Name = 'Test past', Opportunity__c = o.id, 
																		BIData__c = bi.Id,
																		RVAccount__c = rva.Id,
																		Payment_Date__c = nextDate,
																		RecordTypeId = detailRecordTypeId,
																		IncludeInCurrentMonth__c = true,
																		Payment__c = 200);
      	insert newc;
    }
    
   @isTest static void testUpdateCurrent() 
   {
   	  
   	  List<Partner_Commission__c>  pc = [select Name from Partner_Commission__c ];
   	  
   	  //Start the Testing! 
 //      Test.startTest(); 

       BatchSetCurrentMonthCommissions bc= new BatchSetCurrentMonthCommissions(); 
       bc.execute(null);
  //     Test.stopTest();

    
   		
   } 
   
   @isTest static void testBatchSummary() 
   {
   	  
 //  	  List<Partner_Commission__c>  pc = [select Name from Partner_Commission__c ];
   	  
   	  //Start the Testing! 
       Test.startTest(); 

       BatchPartnerCommissions bc= new BatchPartnerCommissions(); 
       bc.execute(null);
       Test.stopTest();

    
   		
   }
      
   @isTest static void testBatchUpdateStatus() 
   {
   	  
   	  
   	  //Start the Testing! 
       Test.startTest(); 
		String q = 'Select Id, Commission_Payment_Status__c from rvpe__RVAccount__c  ';
		String e = 'rvpe__RVAccount__c';
		String f = 'Commission_Payment_Status__c';
		String v = 'Completed';
		Id batchInstanceId = Database.executeBatch(new UpdateFields(q,e,f,v), 95); 
       
       Test.stopTest();

    
   		
   }
   
}