src/objects/BI_Data__c.object
<CustomObject>
    <description>To hold store information from BI.</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Month_GMV_Date__c</fullName>
        <description>Date corresponding to the Previous month GMV.</description>
        <inlineHelpText>This is the date for which the previous month GMV was obtained.</inlineHelpText>
        <label>Previous Month GMV Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Previous_months_GMV__c</fullName>
        <inlineHelpText>GMV corresponding to previous month of activity (not necessarily calendar last month).</inlineHelpText>
        <label>Previous month&apos;s GMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_MBA_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Contact with an email match to the MBA Account admin email address</inlineHelpText>
        <label>Primary MBA Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BI_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BI Data</label>
        <referenceTo>BI_Data__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CampaignContactsUpdate.cls
global class CampaignContactsUpdate implements Database.Batchable<sObject>, Database.Stateful
{
	public String query;
    global Database.QueryLocator start(Database.BatchableContext BC)
    {           
        Id storeRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_StorePurchase).getRecordTypeId();
 
        return Database.getQueryLocator(query);     
    }
	
  	global void execute(Database.BatchableContext BC, List<sObject> scope)
  	{
        map<string, Id> mpNameCamId = new map<string, Id>();
        map<Id,string> mpNewContactCamId = new map<Id, string>();
        map<Id, Decimal> mpContactRev = new map<Id, Decimal>();
        
 		Set<Id> contactIds = new Set<Id>();
 		
       	mpNameCamId = CampaignUtility.LoadNameCampaignIdMap('GMV');
        List<Opportunity> listContacts = (List<Opportunity>)scope;
        system.debug(' Scope ' +listContacts.size());
        Date lastMonthDate = Date.Today().addMonths(-2);
        String zeroCamId = CampaignUtility.getCampaignId(0);
        
        
        for (Opportunity o: listContacts)
  		{
  			String newcamId ;
  			If (o.contact__r.Id <> null && o.contact__r.Primary_MBA_Contact__c == true)
  			{   
  				contactIds.add(o.contact__r.Id);
	  			Decimal prevgmv = 0.0;
	  			if (o.bi_Data__r.Previous_months_GMV__c <> null)
	  			   prevgmv = o.bi_Data__r.Previous_months_GMV__c;
	  			
	  			if (mpContactRev.containsKey(o.contact__r.Id))
	  			{
	  				Decimal rev = mpContactRev.get(o.contact__r.Id) + + prevgmv;
	  				mpContactRev.remove(o.contact__r.Id);
	  				mpContactRev.put(o.contact__r.Id, rev);
	  				
	  			}
	  			else {mpContactRev.put(o.contact__r.Id, prevgmv);}
	  			
	  			if (o.bi_Data__r.Previous_month_GMV_Date__c  <> null && 
	  			    o.bi_Data__r.Previous_month_GMV_Date__c > lastMonthDate)
	  			{
	  				newcamId = CampaignUtility.getCampaignId(o.bi_Data__r.Previous_months_GMV__c);
	  			}
	  			else 
	  			newcamId = zerocamId;
	  			
	  			if (mpNewContactCamId.containsKey(o.contact__r.Id))
	  			{
	  				mpNewContactCamId.remove(o.contact__r.Id);
	  				mpNewContactCamId.put(o.contact__r.Id, newcamId);
	  				
	  			}
	  			else {mpNewContactCamId.put(o.contact__r.Id, newcamId);}
  			}
  		}
  		
  		CampaignUtility.AddContactToCampaign(mpNewContactCamId);
/*  		
  		Map<Id, CampaignMember > mapContactCampaign = new Map<Id, CampaignMember >();
        for (CampaignMember cm : [SELECT Id, CampaignId, ContactId FROM CampaignMember 
        							where CampaignId in :mpNameCamId.Values() and 
        							contactId in :contactIds])
        {
        	 mapContactCampaign.put(cm.ContactId, cm);
        }

// add to campaign
		List<CampaignMember> addCamMem  = new List<CampaignMember>();
		List<CampaignMember> remCamMem  = new List<CampaignMember>();

		for (Id contId : mpNewContactCamId.KeySet())
		{
			String newCampId ='';
			String existCamId ='';

			if (mapContactCampaign.get(contId) <> null)
			{
			    CampaignMember existCam = mapContactCampaign.get(contId);
			    existCamId = existCam.CampaignId;
			}
			newCampId = mpNewContactCamId.get(contId);
			system.debug(' new campaign id '+newCampId);
			system.debug(' existing campaign id '+existCamId);

			if (!existCamId.contains(newCampId) )
			{
				CampaignMember cm = new CampaignMember(ContactId = contId, CampaignId = newCampId );
				addCamMem.add(cm);
				if (existCamId <> '' ) remCamMem.add(mapContactCampaign.get(contId)); 
		 	
			}
			
		}
		
		insert addCamMem;
		delete remCamMem;
*/
  	} 
   
   global void finish(Database.BatchableContext BC)
    {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] {'maggie.frederick@bigcommerce.com'});
        //mail.setReplyTo('batch@acme.com');
        //mail.setSenderDisplayName('Batch Processing');
        mail.setSubject('Batch Process Campaign Update Completed');
        mail.setPlainTextBody('Batch Process has completed');
       // Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }     

}