src/objects/BI_Data__c.object
<CustomObject>
    <description>To hold store information from BI.</description>
    <fields>
        <fullName>Lifetime_GMV__c</fullName>
        <inlineHelpText>Lifetime GMV since 1/1/13 or Store provision date if provisioned after.</inlineHelpText>
        <label>Lifetime GMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CampaignRules__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Rules to set campaigns</description>
    <fields>
        <fullName>Campaign_ID__c</fullName>
        <label>Campaign ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ending_GMV__c</fullName>
        <label>Ending GMV</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Campaign Rules</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_MBA_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Contact with an email match to the MBA Account admin email address</inlineHelpText>
        <label>Primary MBA Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BI_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BI Data</label>
        <referenceTo>BI_Data__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RetentionCampaignUpdate.cls
global class RetentionCampaignUpdate implements Database.Batchable<sObject>, Database.Stateful
{
	public String query;
    global Database.QueryLocator start(Database.BatchableContext BC)
    {           
        Id storeRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_StorePurchase).getRecordTypeId();
 
        return Database.getQueryLocator(query);     
    }
	
  	global void execute(Database.BatchableContext BC, List<sObject> scope)
  	{
        map<string, Id> mpNameCamId = new map<string, Id>();
        map<Id,string> mpContactCamId = new map<Id, string>();
        map<Id, Decimal> mpContactRev = new map<Id, Decimal>();
		
//       	mpNameCamId = CampaignUtility.LoadNameCampaignIdMap('Retention Campaign');
        CampaignRules__c camrule = CampaignUtility.getCampaignByName('Retention Campaign');
        
        List<Opportunity> listContacts = (List<Opportunity>)scope;
        system.debug(' Scope ' +listContacts.size());
 //       Date lastMonthDate = Date.Today().addMonths(-2);
 //       Date SixMonthDate = Date.Today().addMonths(-6);
                
        
        for (Opportunity o: listContacts)
  		{
  			
  			If (o.contact__r.Id <> null && o.contact__r.Primary_MBA_Contact__c == true)
  			{   
 // 				contactIds.add(o.contact__r.Id);
	  			Decimal gmv = 0.0;
	  			if (o.bi_Data__r.Lifetime_GMV__c <> null)
	  			   gmv = o.bi_Data__r.Lifetime_GMV__c;
	  			
	  			if (mpContactRev.containsKey(o.contact__r.Id))
	  			{
	  				gmv = mpContactRev.get(o.contact__r.Id) + + gmv;
	  				mpContactRev.remove(o.contact__r.Id);
  				
	  			}
	  			
	  			mpContactRev.put(o.contact__r.Id, gmv);
			
  			}	
  		}
  		
  		for (Id conId :mpContactRev.KeySet())	
  		{	  			
	  		if (mpContactRev.get(conId) < camrule.Ending_GMV__c)
	  		{
	  			mpContactCamId.put(conId, camrule.Campaign_Id__c);	
	  		}
  		}
  		CampaignUtility.AddContactToCampaign(mpContactCamId);

  	} 
   
   global void finish(Database.BatchableContext BC)
    {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] {'maggie.frederick@bigcommerce.com'});
        //mail.setReplyTo('batch@acme.com');
        //mail.setSenderDisplayName('Batch Processing');
        mail.setSubject('Batch Process Campaign Update Completed');
        mail.setPlainTextBody('Batch Process has completed');
       // Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }     



}