src/objects/BI_Data__c.object
<CustomObject>
    <description>To hold store information from BI.</description>
    <fields>
        <fullName>Last_Payment_Amount__c</fullName>
        <label>Last Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Last_Payment_Date__c</fullName>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MBA_Subscription_ID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>BI Data</relationshipLabel>
        <relationshipName>BI_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <formula>Opportunity__r.rvpe__RVAccount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Term__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Indicates 1 for Monthly and 12 for Annual</description>
        <label>Payment Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>BI Data</label>
    <nameField>
        <displayFormat>BI-{000000}</displayFormat>
        <label>BI Data ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BI_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BI Data</label>
        <referenceTo>BI_Data__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BillingCycle__c</fullName>
        <label>Billing Cycle</label>
        <picklist>
            <picklistValues>
                <fullName>One-Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annually</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biennially</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5 Yearly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free Account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <picklist>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seasonal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>rvpe__RVAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RV Account</label>
        <referenceTo>rvpe__RVAccount__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Partner_Commission__c.object
<CustomObject>
    <description>To keep track of client payments andrelated partner details</description>
    <fields>
        <fullName>Annual_Billing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Created from Annual Billing</description>
        <label>Annual Billing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BIData__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BI Data</label>
        <referenceTo>BI_Data__c</referenceTo>
        <relationshipLabel>Partner Commissions</relationshipLabel>
        <relationshipName>Partner_Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IncludeInCurrentMonth__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include in Current Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Partner Commissions</relationshipLabel>
        <relationshipName>Partner_Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaymentMonth__c</fullName>
        <formula>MONTH( Payment_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PaymentYear__c</fullName>
        <formula>YEAR( Payment_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Terms__c</fullName>
        <label>Payment Terms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <description>Client Payment</description>
        <label>Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RVAccount__c</fullName>
        <label>RV Account</label>
        <referenceTo>rvpe__RVAccount__c</referenceTo>
        <relationshipLabel>Partner Commissions</relationshipLabel>
        <relationshipName>Partner_Commissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Store_Plan__c</fullName>
        <label>Store Plan</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Partner Commission</label>
    <nameField>
        <label>Partner Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Commissions</pluralLabel>
    <recordTypes>
        <fullName>Detail</fullName>
        <active>true</active>
        <label>Detail</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PartnerCommissionsHelper.cls
public  class PartnerCommissionsHelper {
    
    public Id detailRecordTypeId = Partner_Commission__c.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Detail').getRecordTypeId();
    
    public static void createCommrecords(Map<Id, BI_Data__c> mapOppBi )
    {
        Id detailRecordTypeId = Partner_Commission__c.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Detail').getRecordTypeId();
        List<Partner_Commission__C> updcommList = new List<Partner_Commission__C>();
        Map<Id, Partner_Commission__C> mapOppComm = new Map<Id, Partner_Commission__C>();
        Set<Id> updRecs = new Set<Id>();
        
        for (Partner_Commission__c pc :[Select Id, Opportunity__r.Id, Opportunity__r.BillingCycle__c, Payment_Date__c ,  Payment__c, PaymentMonth__c, PaymentYear__c, Annual_Billing__c
                                     from Partner_Commission__c
                                     where RecordTypeId = :detailRecordTypeId
                                     and Opportunity__c in :mapOppBi.KeySet()
                                     and (Payment_Date__c = this_month
                                     	or (Payment_Date__c >  this_month and annual_billing__c =true))
                                     ])
        {
        	BI_Data__c bid = mapOppBi.get(pc.Opportunity__r.Id);
        	Boolean annual = false;
//        	if (pc.Opportunity__r.BillingCycle__c == 'Annaully')
			if (bid.Payment_Term__c >1)  
        		annual = true;
        	if (bid.Last_Payment_Date__c.Month() == pc.PaymentMonth__c 
        		&& bid.Last_Payment_Date__c.Year() == pc.PaymentYear__c
        		&& !annual)
        	{
            	pc.Payment__c = bid.Last_Payment_Amount__c;
        		pc.Payment_Date__c = bid.Last_Payment_Date__c;
        		updcommList.add(pc);
        		updRecs.add(pc.Opportunity__r.Id);
        	}
        	else if (annual && pc.annual_billing__c == true)
        	{
        		pc.Payment__c = bid.Last_Payment_Amount__c/12;
        		updcommList.add(pc);
        		updRecs.add(pc.Opportunity__r.Id);
        	}
        }
        
        List<Partner_Commission__C> commList = new List<Partner_Commission__C>();
        List<Partner_Commission__C> anncommList = new List<Partner_Commission__C>();
        
        List< BI_Data__c> mbids = new List<Bi_Data__c>();
        for (Opportunity o :[Select Id, rvpe__RVAccount__c, BillingCycle__c,Product__c  from Opportunity where Id in:mapOppBi.KeySet()])
        {
          if ( !updRecs.contains(o.Id))
          {  
            BI_Data__c bid = mapOppBi.get(o.id);
            String cname = String.valueOf(bid.Last_Payment_Date__c) +' '+ bid.MBA_Subscription_ID__c;
            Partner_Commission__C newc = new Partner_Commission__C(Name = cname, Opportunity__c = o.id, 
                                                                    BIData__c = bid.Id,
                                                                    RVAccount__c = bid.Partner_Account__c,
                                                                    Payment_Date__c = bid.Last_Payment_Date__c,
                                                                    Store_Plan__c = o.Product__c,
                                                                    RecordTypeId = detailRecordTypeId,
                                                                    Payment_Terms__c = bid.Payment_Term__c,
                                                                    IncludeInCurrentMonth__c = true
                                                                    );
            
 //           if (o.BillingCycle__c == 'Annually')
 			if (bid.Payment_Term__c >1)  
            {
            	newc.Payment__c = bid.Last_Payment_Amount__c/12;
            	newc.Annual_Billing__c = true;
                anncommList.add(newc);
            }
            else 
            {
            	newc.Payment__c = bid.Last_Payment_Amount__c;
            }
            commList.add(newc);
          }
        }
        
        if (!anncommList.isEmpty())   
        {
            List<Partner_Commission__C> mcomms = createAnnualCommrecords(anncommList);
            commList.addAll(mcomms);
        }
             
        update updcommList;
        insert commList;
    }

/*
    public static List<Partner_Commission__C> createAnnualCommrecords(List <BI_Data__c> mbids)      
    {
        List<Partner_Commission__C> moncommList = new List<Partner_Commission__C>();
        Id detailRecordTypeId = Partner_Commission__c.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Detail').getRecordTypeId();
        Integer cyy = Date.Today().year();
        Integer cmm = Date.Today().month();
        
        for (Bi_Data__c  bid :mbids)
            {
                
                Double monthlyamt = bid.Last_Payment_Amount__c/12;
                 for(Integer i=1;i<bid.Payment_Terms__c;i++)
                 {
                    date nextdate = bid.Last_Payment_Date__c.addmonths(i);
                    String cname = String.valueOf(bid.Last_Payment_Date__c) +' '+ bid.MBA_Subscription_ID__c;
                     
                    Partner_Commission__C newc = new Partner_Commission__C(Name = cname, Opportunity__c = bid.Opportunity__c, 
                                                                            BIData__c = bid.Id,
                                                                            RVAccount__c = bid.Partner_Account__c,
                                                                            Payment_Date__c = nextdate,
                                                             //               Store_Plan__c = o.Product__c,
                                                                            Annual_Billing__c = true,
                                                                            RecordTypeId = detailRecordTypeId,
                                                                            Payment__c = monthlyamt);
                     
                    if (cmm == nextdate.month() && cyy == nextdate.Year()) newc.IncludeInCurrentMonth__c = true;
                    moncommList.add(newc);
                 }
                
            }
            
        
        return moncommList;
   
    } 
 */   
    public static List<Partner_Commission__C> createAnnualCommrecords(List<Partner_Commission__C> pcList)      
    {
        List<Partner_Commission__C> moncommList = new List<Partner_Commission__C>();
        Integer cyy = Date.Today().year();
        Integer cmm = Date.Today().month();
        String spaceChar = ' ';
        for (Partner_Commission__c  pc :pcList)
            {
 
                 for(Integer i=1;i<pc.Payment_Terms__c;i++)
                 {
                    date nextdate = pc.Payment_Date__c.addmonths(i);
                    String cname = pc.Name.substringAfter(spaceChar);
                    cname = String.valueOf(pc.Payment_Date__c) +' ' +cname;
                    Partner_Commission__C newc = new Partner_Commission__C(Name = cname, Opportunity__c = pc.Opportunity__c, 
                                                                            BIData__c = pc.BIData__c ,
                                                                            RVAccount__c = pc.RVAccount__c,
                                                                            Payment_Date__c = nextdate,
                                                                            Store_Plan__c = pc.Store_Plan__c,
                                                                            Annual_Billing__c = true,
                                                                            RecordTypeId = pc.RecordTypeId,
                                                                            Payment_Terms__c = pc.Payment_Terms__c,
                                                                            Payment__c = pc.Payment__c);
                     
                    if (cmm == nextdate.month() && cyy == nextdate.Year()) newc.IncludeInCurrentMonth__c = true;
                    moncommList.add(newc);
                 }
                
            }
            
        
        return moncommList;
   
    } 
     
}