src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Change_Owner__c</fullName>
        <label>Change Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Support Queue</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Me</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>API Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Out of Scope</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Design Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager Callback</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CaseOwnerQueue__mdt.object
<CustomObject>
    <fields>
        <fullName>ChangeOwner_Value__c</fullName>
        <label>ChangeOwner Value</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <label>Queue Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>CaseOwnerQueue</label>
    <pluralLabel>CaseOwnerQueues</pluralLabel>
</CustomObject>

src/classes/CaseOwnerUpdateTest.cls
@isTest
private  class CaseOwnerUpdateTest {
	
	static testMethod void testCaseOwnerUpdate() 
    {
		Test.startTest();
		Id idCSCaseRecordType =  Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Client Success').getRecordTypeId();
  
		TestDataGenerator td = new TestDataGenerator();
	      
	    list<Account> lstAcct = td.getAccounts(true);
	    Case c = td.createCase(lstAcct[0].Id, '', true);
	      
// Make sure the case is associated to the correct account and user
		c.AccountId = lstAcct[0].Id;
		c.RecordTypeId = idCSCaseRecordType;
	    c.OwnerId = UserInfo.getUserId();
	    update c;
		
		Map <String, String> caseOwnerQueue = new Map<String, String>();
		for (CaseOwnerQueue__mdt s :[select ChangeOwner_Value__c, Queue_Name__c from CaseOwnerQueue__mdt ])
		{
			caseOwnerQueue.put(s.ChangeOwner_Value__c, s.Queue_Name__c);
		}
			 
		
		for (String sname :caseOwnerQueue.KeySet())
		{
			c.Change_Owner__c = sname;
		}
		update c;

		Test.stopTest();
		
    }
}