src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Chat_Key__c</fullName>
        <externalId>true</externalId>
        <label>Chat Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the store this case is in reference to</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact associated with the subscription</description>
        <inlineHelpText>Contact associated with the subscription</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Populated by a workflow capturing the associated contact or lead email address each time the contact name is changed.  Also used in case workflows to send email notifications if no lead or contact is called out on the case</description>
        <inlineHelpText>Populated by a workflow capturing the associated contact or lead email address each time the contact name is changed. Also used in case workflows to send email notifications if no lead or contact is called out on the case</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Populated by workflow if contact or lead changes</description>
        <label>zPhone</label>
        <type>Phone</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Support_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CaseSurveys</relationshipLabel>
        <relationshipName>CaseSurveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Chat_Key__c</fullName>
        <externalId>true</externalId>
        <label>Chat Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Chat_Transcript__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Live Chat Transcript</label>
        <referenceTo>LiveChatTranscript</referenceTo>
        <relationshipLabel>CaseSurveys</relationshipLabel>
        <relationshipName>CaseSurveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Support Survey</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Support Survey Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestBatch.cls
@isTest(seeAllData=false) 
public class TestBatch {

    public static testmethod void test_batch() {
        
        String CRON_EXP = '0 0 0 3 9 ? 2022';
        Test.startTest();
// Schedule the test job
        String jobId = System.schedule('testBasicScheduledApex', CRON_EXP, new BatchDataUpdate());
        // Get the information from the CronTrigger API object  
        CronTrigger ct = [SELECT id, CronExpression, TimesTriggered, 
        NextFireTime
        FROM CronTrigger WHERE id = :jobId];
        
        // Verify the expressions are the same 
        System.assertEquals(CRON_EXP, ct.CronExpression);
        
        // Verify the job has not run  
        
        System.assertEquals(0, ct.TimesTriggered);
        
        // Verify the next time the job will run  
        
        System.assertEquals('2022-09-03 00:00:00', String.valueOf(ct.NextFireTime));
        
        //Test the actual code run
        DataUpdatev2 sCons = new DataUpdatev2();
 //        sCons.query = 'Select s.Contact__c, Contact__r.Email, Contact__r.Phone, s.Email__c, s.Phone__c from Subscription__c s where Contact__c <> null limit 1';
         sCons.query = 'Select c.Status, c.RecordTypeId, c.CaseNumber, c.AccountId From Case c where RecordTypeId = \'012a0000001NV9N\' limit 1';
        
        Database.executeBatch(sCons);
        Test.StopTest();
    }

    public static testmethod void test_batchupdSurvey() {
        
        String CRON_EXP = '0 0 0 3 9 ? 2022';
        Test.startTest();
// Schedule the test job
        String jobId = System.schedule('testBasicScheduledApex', CRON_EXP, new BatchUpDateSurveys());
        // Get the information from the CronTrigger API object  
        CronTrigger ct = [SELECT id, CronExpression, TimesTriggered, 
        NextFireTime
        FROM CronTrigger WHERE id = :jobId];
        
        // Verify the expressions are the same 
        System.assertEquals(CRON_EXP, ct.CronExpression);
        
        // Verify the job has not run  
        
        System.assertEquals(0, ct.TimesTriggered);
        
        // Verify the next time the job will run  
        
        System.assertEquals('2022-09-03 00:00:00', String.valueOf(ct.NextFireTime));
        
        //Test the actual code run
        DataUpdateSurvey dbu = new DataUpdateSurvey();
        String query1 = 'select Id, Name, chat_key__c,Case__c, Live_Chat_Transcript__c from Support_Survey__c where Live_Chat_Transcript__c = null and chat_key__c  <> null limit 1';
 
        dbu.query = query1 ;
        Database.executeBatch(dbu,90);        
        
        Test.StopTest();
    }
    

}