src/objects/CaseEmailTemplate__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <label>Record Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Template_Id__c</fullName>
        <label>Template Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Case Email Template</label>
</CustomObject>

src/classes/SmartTemplateLoader.cls
// class referred to by SF to load email templates on the email action in console
global class SmartTemplateLoader implements Support.EmailTemplateSelector {
    // Empty constructor
    global SmartTemplateLoader() {}
    global ID getDefaultEmailTemplateId(ID caseId) {
    // Select the case we're interested in, choosing any fields that are relevant to our decision
    Case c = [SELECT Origin, Subject, Description, Recordtype.Name FROM Case WHERE Id=:caseId];
	system.debug('case subject' +c.Subject);
	List<CaseEmailTemplate__c> cRules = CaseEmailTemplate__c.getAll().Values();
    Map<String, ID> mpOriginValueId = new Map <string, Id>();
    Map<String, ID> mpRecValueId = new Map <string, Id>();
    for (CaseEmailTemplate__c aet :cRules)
  	{
    	if (aet.Origin__c <> null) mpOriginValueId.put(aet.Origin__c, aet.Template_Id__c);
    	else if (aet.Record_Type__c <> null) mpRecValueId.put(aet.Record_Type__c, aet.Template_Id__c);
     
  	}
    
    Id etId;

    if (mpOriginValueId.get(c.Origin) <> null) {
        etId = mpOriginValueId.get(c.Origin);
    } else if(mpRecValueId.get(c.RecordType.Name) <> null) {
		etId = mpRecValueId.get(c.RecordType.Name);
//        et = [SELECT id FROM EmailTemplate WHERE DeveloperName = 'EnhancementTemplate'];
    } 

    // Return the ID of the template selected
    return etId;
}
    
    
}