src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the store this case is in reference to</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Promoter_io_Callout__c.object
<CustomObject>
    <fields>
        <fullName>API_URL__c</fullName>
        <label>API URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PageNumber__c</fullName>
        <label>PageNumber</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Session_Time__c</fullName>
        <label>Session Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Unique_ID__c</fullName>
        <externalId>true</externalId>
        <label>Unique ID</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Promoter.io Callout</label>
    <nameField>
        <displayFormat>PC-{00000000}</displayFormat>
        <label>Promoter.io  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoter.io Callouts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Promoter_io_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_External_ID__c</fullName>
        <label>Campaign External ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact_External_ID__c</fullName>
        <label>Contact External ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Promoter.io Feedbacks</relationshipLabel>
        <relationshipName>Promoter_io_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feedback_ID__c</fullName>
        <label>Feedback ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Feedback_URL__c</fullName>
        <label>Feedback URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Feedback_Unique_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Feedback Unique External ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Posted_Date__c</fullName>
        <label>Posted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SF_Account_ID__c</fullName>
        <label>SF Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Contact_Id__c</fullName>
        <label>SF Contact Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score_Type__c</fullName>
        <label>Score Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Session_Time__c</fullName>
        <label>Session Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Store_ID__c</fullName>
        <label>Store ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Promoter.io Feedbacks</relationshipLabel>
        <relationshipName>Promoter_io_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promoter.io Feedback</label>
    <nameField>
        <displayFormat>PIO-{00000000}</displayFormat>
        <label>Promoter.io Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoter.io Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PromoterioSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>End_Point__c</fullName>
        <label>End Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fetch_All__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fetch All</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Run_On__c</fullName>
        <label>Last Run On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Previous_Run_Date__c</fullName>
        <label>Previous Run Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Specific_Campaign_ID__c</fullName>
        <label>Specific Campaign ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Token__c</fullName>
        <label>Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Promoter.io Settings</label>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact associated with the subscription</description>
        <inlineHelpText>Contact associated with the subscription</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Populated by a workflow capturing the associated contact or lead email address each time the contact name is changed.  Also used in case workflows to send email notifications if no lead or contact is called out on the case</description>
        <inlineHelpText>Populated by a workflow capturing the associated contact or lead email address each time the contact name is changed. Also used in case workflows to send email notifications if no lead or contact is called out on the case</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SF_Account_ID__c</fullName>
        <description>Formula to pull the associated account&apos;s salesforce ID for reports and list views</description>
        <formula>IF(ISBLANK( Account__c ),Account__r.Account_Unique_ID__c,NULL)</formula>
        <inlineHelpText>Salesforce Account ID</inlineHelpText>
        <label>Salesforce Account ID</label>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/JSONParserUtil.cls
public class JSONParserUtil {
    
    public static integer pagenum;
    public static void promoterioCallout() {
		Integer i=0;
        Integer j=0;
        Integer t =0;
         
          if(pagenum==null){
              pagenum=0;
          }
		PromoterioSettings__c pioSettings = PromoterioSettings__c.getOrgDefaults();
        Boolean Alltime = pioSettings.Fetch_All__c;        
		String SpecificCampaign;
          if( pioSettings.Specific_Campaign_ID__c != null ){
               SpecificCampaign = pioSettings.Specific_Campaign_ID__c; 
          } 		
             Http httpProtocol = new Http();
            // Create HTTP request to send.
            HttpRequest request = new HttpRequest();
            // Set the endpoint URL.
            String endpoint;
          if(SpecificCampaign!=null){
              endpoint = pioSettings.End_Point__c+'?&survey__campaign='+SpecificCampaign; 
          }	else {
              endpoint = pioSettings.End_Point__c;
          }          
            request.setHeader('Authorization', 'Token '+pioSettings.Token__c);
            request.setEndPoint(endpoint);
            // Set the HTTP verb to GET.
            request.setMethod('GET');
            // Send the HTTP request and get the response.
            // The response is in JSON format.
            HttpResponse response = httpProtocol.send(request);
            // Parse entire JSON response.
            JSONParser parser = JSON.createParser(response.getBody());
            jsonresponse jres = (jsonresponse)parser.readValueAs(jsonresponse.class);
            if(jres.count!=null){
                t=math.round(jres.count/100);
            } 
          List< Promoter_io_Callout__c> picList = new List< Promoter_io_Callout__c>();
          Datetime SessionTime = system.now();        
          if(pioSettings.Last_Run_On__c!=null){pioSettings.Previous_Run_Date__c = pioSettings.Last_Run_On__c.date();}
          pioSettings.Last_Run_On__c = SessionTime;
          upsert pioSettings;
          
          for(integer l=1;l<t+2;l++){
              pagenum=pagenum+1;
              Promoter_io_Callout__c  pic = new Promoter_io_Callout__c();
              if(SpecificCampaign!=null){
              	pic.API_URL__c = pioSettings.End_Point__c+'?page='+pagenum+'&survey__campaign='+SpecificCampaign; 
              } else {
              	pic.API_URL__c = pioSettings.End_Point__c+'?page='+pagenum;
              }
              pic.Session_Time__c = SessionTime;
              pic.PageNumber__c = pagenum;
              pic.Unique_ID__c = SessionTime+'-'+pagenum;
              picList.add(pic);
          }
          if(!picList.isEmpty()){
              upsert picList Unique_ID__c;
          }
    	} 
    

	public static List<Promoter_io_Feedback__c> promoterioJSONParser(integer pagenumf) {

        Boolean stoplooping;
        promoterioSettings__c pioSettings = promoterioSettings__c.getOrgDefaults();
		String SpecificCampaign;
          if( pioSettings.Specific_Campaign_ID__c != null ){
               SpecificCampaign = pioSettings.Specific_Campaign_ID__c; 
          }  
        Http httpProtocol = new Http();
        // Create HTTP request to send.
        HttpRequest request = new HttpRequest();
        // Set the endpoint URL.
        system.debug('>><< pagenumf for endpoint is = '+pagenumf);
        String endpoint;
        if(SpecificCampaign!=null){
            endpoint = pioSettings.End_Point__c+'?page='+pagenumf+'&survey__campaign='+SpecificCampaign;
        } else {
        	endpoint = pioSettings.End_Point__c+'?page='+pagenumf;
        }
        request.setHeader('Authorization', 'Token '+pioSettings.Token__c);
        request.setEndPoint(endpoint);
        // Set the HTTP verb to GET.
        request.setMethod('GET');
        // Send the HTTP request and get the response.
        // The response is in JSON format.
        HttpResponse response = httpProtocol.send(request);
        // Parse entire JSON response.
        JSONParser parser = JSON.createParser(response.getBody());
        jsonresponse jres = (jsonresponse)parser.readValueAs(jsonresponse.class);

        List<Promoter_io_Feedback__c> piofList = new List<Promoter_io_Feedback__c>();
        set<string> feedbackidset = new set<string>();
        
        Date cutoffdate;
        if(pioSettings.Previous_Run_Date__c!=null){
            cutoffDate = pioSettings.Previous_Run_Date__c.addDays(-1);
        } else {
            cutoffDate = system.today().addYears(-1);
        }
        if(jres.results!=null){
            for(cls_results res:jres.results){
                if(!feedbackidset.contains(res.campaign+'-'+res.id)&&res.posted_date.date()>cutoffDate){
                    Promoter_io_Feedback__c piof = new Promoter_io_Feedback__c();
                    piof.Campaign_External_ID__c = res.campaign;
                    piof.Comment__c = res.comment;
                    piof.Contact_External_ID__c  = res.Contact.id;
                    if(res.Contact.attributes.SF_AccountID!=null){
                    	piof.SF_Account_ID__c = res.Contact.attributes.SF_AccountID;
                    } else if(res.Contact.attributes.SF_Account_ID!=null){
                        piof.SF_Account_ID__c = res.Contact.attributes.SF_Account_ID;
                    }
                    if(res.Contact.attributes.SF_Contact_Id!=null){
                    	piof.SF_Contact_ID__c = res.Contact.attributes.SF_Contact_Id;
                    }
                    piof.Email__c = res.Contact.email;
                    piof.Feedback_Unique_External_ID__c = res.campaign+'-'+res.id;
                    piof.Feedback_ID__c = res.id;
                    piof.Feedback_URL__c = res.followup_href;
                    piof.FirstName__c = res.Contact.first_name;
                    piof.LastName__c = res.Contact.last_name;
                    piof.Posted_Date__c = res.posted_date;
                    piof.Score__c = res.score;
                    piof.Score_Type__c = res.score_type;
                    if(res.Contact.attributes.StoreID!=null){
                    	piof.Store_ID__c = res.Contact.attributes.StoreID;
                    } else if(res.Contact.attributes.Store_ID!=null){
                        piof.Store_ID__c = res.Contact.attributes.Store_ID;
                    }
                    piof.Session_Time__c = pioSettings.Last_Run_On__c;
                    feedbackidset.add(res.campaign+'-'+res.id);
                    piofList.add(piof);
                }
            }

        } else {
            if(jres.next==null){
            	stoplooping=true; 
        	}
        }
        return piofList;
    } 
    
    // Inner classes used for serialization by readValuesAs(). 
    
    public class jsonresponse {
        public integer count;
        public string next;
        public String previous;
        public List<cls_results> results;      
    }  
    
    public class cls_results {
        public String campaign;
        public Integer score;
        public String score_type;
        public String comment;
        public Datetime posted_date;
        public con Contact;  
        public string id;
        public string followup_href;
    }  
    
    public class Con {
        public String first_name;
        public String last_name;
        public String email;
        public string id;
        Public cls_attributes attributes;
    }  
    
    public class cls_attributes {
        public String SF_AccountID;
        public String SF_account_id;
        public String sf_contact_id;
        public String StoreID;
        public String Store_ID;
        public String StoreAcctNum;
    }
    
    public static List<Case> assignFeedbackToCase(List<Case> cases){
        List<Case> caseList = (List<Case>)cases;
        List<Case> updateCaseList = new List<Case>();
        Set<Id> conIds = new Set<Id>();
        for(Case cs:caseList){
            conIds.add(cs.contactid);
        }
        Map<String,Promoter_io_Feedback__c> MapFeedbacktoCon = new Map<String,Promoter_io_Feedback__c>();
       	List<Promoter_io_Feedback__c> listPioFeedbacks = new List<Promoter_io_Feedback__c>([Select id, contact__c,contact__r.id, Subscription__c, Posted_Date__c  from Promoter_io_Feedback__c where Contact__c in :conIds and id NOT in (select Promoter_io_Feedback__c from Case where Contactid in :conIds)]);
        for(Promoter_io_Feedback__c piof:listPioFeedbacks){
            if(piof.Contact__r.id!=null&&piof.Posted_Date__c!=null){
                MapFeedbacktoCon.put(string.valueOf(piof.Contact__r.id).left(15)+'-'+string.valueOf(piof.Posted_Date__c.date()),piof);
            }
        }

        if(!caseList.isEmpty()){
            for(case cs:caseList){
                if(cs.contactid!=null&&cs.Promoter_io_Feedback_Date__c!=null){
                    if(MapFeedbacktoCon.get(string.valueOf(cs.ContactId).left(15)+'-'+string.valueOf(cs.Promoter_io_Feedback_Date__c))!=null){
                        cs.Promoter_io_Feedback__c = MapFeedbacktoCon.get(string.valueOf(cs.ContactId).left(15)+'-'+string.valueOf(cs.Promoter_io_Feedback_Date__c)).id;

                        if(MapFeedbacktoCon.get(string.valueOf(cs.ContactId).left(15)+'-'+string.valueOf(cs.Promoter_io_Feedback_Date__c)).Subscription__c !=null&&cs.Subscription__c==null){
                            cs.Subscription__c = MapFeedbacktoCon.get(string.valueOf(cs.ContactId).left(15)+'-'+string.valueOf(cs.Promoter_io_Feedback_Date__c)).Subscription__c;
                        }                        
                    }
                    updateCaseList.add(cs);
                }
            }
  
        } 
        
        return updateCaseList;
    }
}