src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Change_Owner__c</fullName>
        <label>Change Owner</label>
        <picklist>
            <picklistValues>
                <fullName>Support Queue</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Me</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Escalation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>API Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Out of Scope</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Design Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager Callback</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <description>Use to transfer case ownership to other departmental queues; WFRs fire based on value</description>
        <inlineHelpText>Use to transfer case ownership to other departmental queues</inlineHelpText>
        <label>Department</label>
        <picklist>
            <picklistValues>
                <fullName>Support</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Billing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>API</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal/Abuse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Design_Approved_By__c</fullName>
        <description>User who clicked the Design Approved button</description>
        <label>Design Approved By</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Design_Approved_Date__c</fullName>
        <description>Date when assigned to Design Approved the first time</description>
        <label>Design Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Design_Denied_By__c</fullName>
        <description>User who clicked the Design Out of Scope button</description>
        <label>Design Denied By</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Design_Denied_Date__c</fullName>
        <description>Date when assigned to Design Out of Scope the first time</description>
        <label>Design Denied Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Design_Escalated_By__c</fullName>
        <description>User who clicked the Design Support button</description>
        <label>Design Escalated By</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Design_Escalation_Date__c</fullName>
        <description>Date when assigned to Design Support the first time</description>
        <label>Design Escalation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Do_Not_Send_Survey__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Support : used in WFRs for spam cases</description>
        <label>Do Not Send Survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Escalated_By__c</fullName>
        <description>Support : user taking action that causes the escalation workflow to fire</description>
        <label>Escalated By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Escalated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Support : populated by WFR when a case is escalated via ownership, status or status reason</description>
        <inlineHelpText>Has this case ever been transferred to one of the Escalation queues?</inlineHelpText>
        <label>Escalated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Escalation_Date__c</fullName>
        <description>Support : Populated via workflow - last date case was set to Escalated status</description>
        <inlineHelpText>Populated via workflow - last date case was set to Escalated status</inlineHelpText>
        <label>Escalation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Manager_Callback_Date__c</fullName>
        <description>CS: Populated by workflow if the case owner is Support - Manager Callback queue</description>
        <label>Manager Callback Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Manager_Callback_Requestor__c</fullName>
        <description>CS: Populated by workflow if the case owner is Support - Manager Callback queue</description>
        <label>Manager Callback Requestor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manager_Callback__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CS: Identifies cases that have been escalated and need a manager to call the client.  Populated by workflow if the case owner is Support - Manager Callback queue</description>
        <label>Manager Callback</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tier_2_Request_Date__c</fullName>
        <description>The date time when Tier 2 help was requested</description>
        <label>Tier 2 Request Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Tier_2_Requested_By__c</fullName>
        <description>Tier 2 Requested By agent name</description>
        <label>Tier 2 Requested By</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Billing</fullName>
        <active>true</active>
        <businessProcess>Billing Support Process</businessProcess>
        <description>For account merges, splits, credits, refunds and invoices</description>
        <label>Billing</label>
    </recordTypes>
    <recordTypes>
        <fullName>Cancellations</fullName>
        <active>true</active>
        <businessProcess>Cancellation Support Process</businessProcess>
        <description>For all cancellation requests and saves</description>
        <label>Cancellations</label>
    </recordTypes>
    <recordTypes>
        <fullName>Migration</fullName>
        <active>true</active>
        <businessProcess>Migration Case Process</businessProcess>
        <description>Used by Sales to request store migrations</description>
        <label>Migration</label>
    </recordTypes>
    <recordTypes>
        <fullName>Trash</fullName>
        <active>true</active>
        <businessProcess>Client Success Support Process</businessProcess>
        <description>Trash and spam cases</description>
        <label>Trash</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CaseOwnerQueue__mdt.object
<CustomObject>
    <fields>
        <fullName>ChangeOwner_Value__c</fullName>
        <label>ChangeOwner Value</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <label>Queue Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>CaseOwnerQueue</label>
    <pluralLabel>CaseOwnerQueues</pluralLabel>
</CustomObject>

src/classes/CaseOwnerUpdate.cls
public class CaseOwnerUpdate {
	
	private static final Id USERID = UserInfo.getUserId();
    private static final User CURUSER = [SELECT Id, Name, UserRole.Name, Profile.Name, Division FROM User WHERE Id = :UserInfo.getUserId()];
	
	private map<String, QueueSobject> mpQName2Queue
    {
        get
        {
            if (mpQName2Queue == null)
            {
                mpQName2Queue = new map<String, QueueSobject>();
                
                for (QueueSobject q : [SELECT SobjectType, Queue.Name, QueueId, Id 
                                            FROM QueueSobject
                                            WHERE SobjectType = 'Case'
                                            ORDER BY Queue.Name])
                {
                    mpQName2Queue.put(q.Queue.Name, q);
                }
            }
            
            return mpQName2Queue;
        }
        set;
    }
    private Map<String, String> mapOwnerQueue
    {
        get
        {
            if (mapOwnerQueue == null)
            {
                mapOwnerQueue = new map<String, String>();
                for (CaseOwnerQueue__mdt s :[select ChangeOwner_Value__c, Queue_Name__c from CaseOwnerQueue__mdt ])
				{
					mapOwnerQueue.put(s.ChangeOwner_Value__c, s.Queue_Name__c);
				}
                
            }
            
            return mapOwnerQueue;
        }
        set;
    }
       		    
    public CaseOwnerUpdate(){
    
    }
    
    public void setCaseOwner(List<Case> caseList)
    {
	   for (Case objCase :caseList) 
	   { 
         string selectedQueue = mapOwnerQueue.get(objCase.Change_Owner__c);
         
         if(objCase.Change_Owner__c == 'Support Queue')
         {
		    objCase.RecordTypeId =  Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Client Success').getRecordTypeId();
       		objCase.Department__c = 'Support';
//		 	selectedQueue = 'Support';
         }
         else if(objCase.Change_Owner__c == 'Billing')
         {
		     objCase.Department__c = 'Billing';
		     objCase.Escalation_Date__c = System.now();  
		     objCase.RecordTypeId =  Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Billing').getRecordTypeId();
//		     selectedQueue = 'Billing Queue';
         }
		 else if(objCase.Change_Owner__c == 'Cancellations')
         {
		    objCase.Department__c = 'Cancellations';
       		objCase.RecordTypeId =  Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Cancellations').getRecordTypeId();
 //    		selectedQueue = 'Cancellation Queue';
         }
		 else if(objCase.Change_Owner__c == 'Trash')
         {
		    objCase.Do_Not_Send_Survey__c = true;
       		objCase.RecordTypeId =  Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Trash').getRecordTypeId();
 //    		selectedQueue = 'Support - Trash';
         }
         else if(objCase.Change_Owner__c == 'Legal')
         {
         	objCase.Do_Not_Send_Survey__c = true;
     		objCase.Department__c = 'Legal/Abuse';
 //           selectedQueue = 'Support - Legal/Abuse';
         }
         else if(objCase.Change_Owner__c == 'Design Support')
         {
        	if (objCase.Design_Escalated_By__c == null)
		     {
		       objCase.Design_Escalated_By__c = UserInfo.getName();
		       objCase.Design_Escalation_Date__c = System.now();
		     }
 //       	selectedQueue ='Design Support';
         }
         else if(objCase.Change_Owner__c == 'Design Approved')
         { 
         	if (objCase.Design_Approved_By__c == null)
		     {
		       objCase.Design_Approved_By__c= UserInfo.getName();
		       objCase.Design_Approved_Date__c = System.now();    
		     }
		     
  //   		selectedQueue ='Support - Design Support Approved';
         
         }
         else if(objCase.Change_Owner__c == 'Design Out Of Scope')
         { 
         	if (objCase.Design_Denied_By__c == null)
		     {
		       objCase.Design_Denied_By__c= UserInfo.getName();
		       objCase.Design_Denied_Date__c = System.now();    
		     }
 //    		selectedQueue ='Support - Design Support Out Of Scope';
         
         }
         else if(objCase.Change_Owner__c == 'API Support')
         {
         	if (objCase.Escalated_By__c == null)
		     {
		       objCase.Escalated_By__c = UserInfo.getName();
		       objCase.Escalation_Date__c = System.now();  
		     }
//     objCase.Do_Not_Send_Survey__c = true;

 //    		selectedQueue ='Support - API';
         }
         else if(objCase.Change_Owner__c == 'Tier 2')
         {
	          if (objCase.Tier_2_Requested_By__c == null)
		     {
		       objCase.Tier_2_Requested_By__c = UserInfo.getName();
		       objCase.Tier_2_Request_Date__c = System.now();    
		     }
 //      		selectedQueue ='Tier 2 Support Queue';
         }
         else if(objCase.Change_Owner__c == 'Escalation')
         {
          if (objCase.Escalated_By__c == null)
		     {
		       objCase.Escalated_By__c = UserInfo.getName();
		       objCase.Escalation_Date__c = System.now();  
		     }
     
     		objCase.RecordTypeId =  Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Client Success').getRecordTypeId();
      		objCase.Department__c = 'Support';

//     objCase.Do_Not_Send_Survey__c = true;
     		objCase.Escalated__c = true;

  //   		selectedQueue = 'Support - Escalated Level 1';
         }
         else if(objCase.Change_Owner__c == 'Manager Callback')
         {
         	if (objCase.Manager_Callback_Requestor__c == null)
		     {
		       objCase.Manager_Callback_Requestor__c = UserInfo.getName();
		       objCase.Manager_Callback__c = true;
		       objCase.Manager_Callback_Date__c = System.Now();  
		     }

//     objCase.Do_Not_Send_Survey__c = true;
  //       	selectedQueue ='Support - Manager Callback';
         }
		 else if(objCase.Change_Owner__c == 'Migrations Specialists')
         {
		      //Check if the profile name contains Client success
	         if(!Label.Support_Escalation_Profiles.contains(CURUSER.Profile.Name))
	         {  
//	           showError = true;
	           ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Please request your manager to reassign Case to Migration Specialist.');
	      		ApexPages.addMessage(myMsg);
             }
      		objCase.RecordTypeId =  Case.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Migration Specialist').getRecordTypeId();
      		objCase.Status = 'Open Unsolved';
//		    selectedQueue = 'Migrations Specialists';
         }
         
 	     if (mpQName2Queue.containsKey(selectedQueue))
                {
                  system.debug('***CaseOwner - user selected Queue');
                    objCase.OwnerId = mpQName2Queue.get(selectedQueue).QueueId;         
                    
                } 
//	     changeOwner('Billing Queue');
	   }
    }
 /*
    public void changeOwner(String SelectedQueue)
    {
        // Ensure a case exists
        if (objCaseId != null)
        {   
                               
                // Check if user selected a queue
                if (selectedQueue != null && mpQName2Queue.containsKey(selectedQueue))
                {
                  system.debug('***CaseOwner - user selected Queue');
                    objCase.OwnerId = mpQName2Queue.get(selectedQueue).QueueId;         
                    
                }
                else
                {
                  system.debug('***CaseStopWorkingController:changeOwner - User not previously with queue and no queue selected');
                }
      	 }
   
    }

 */   

}