src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>The Account on the Case does not match the Account on the Opportunity</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>Opportunity.AccountId</valueField>
            </filterItems>
            <infoMessage>Select Opportunity related to the Account</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Cases</relationshipLabel>
        <relationshipName>OpportunityCases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paused_plan_prior_price__c</fullName>
        <description>The price of the client&apos;s subscription plan when the cancellation case was opened.</description>
        <inlineHelpText>The price of the client&apos;s subscription plan when the cancellation case was opened.</inlineHelpText>
        <label>Paused Plan - Prior Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Plan_at_Pause_Offer__c</fullName>
        <description>What was the store plan when the paused plan was offered?</description>
        <inlineHelpText>What was the store plan when the paused plan was offered?</inlineHelpText>
        <label>Plan at Pause Offer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_ID__c</fullName>
        <description>Product ID Captured at case creation, used for cancellation reporting.</description>
        <inlineHelpText>Product ID Captured at case creation, used for cancellation reporting.</inlineHelpText>
        <label>Product ID at Cancel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product of the Subscription associated with this case.</description>
        <formula>IF( ISBLANK( Opportunity__c ) = FALSE, Opportunity__r.Product__c, 
IF( ISBLANK( Subscription__c ) = FALSE, Subscription__r.Product__c , 
NULL))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Product of the Subscription associated with this case.</inlineHelpText>
        <label>Product Plan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup field to the store this case is in reference to</description>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillingAmount__c</fullName>
        <label>Billing Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <description>ID specific to the plan name since plans can have different ID iterations yet maintain the same name in MBA.</description>
        <label>Product ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <lookupFilter>
            <active>false</active>
            <errorMessage>The subscription is not related to the account on the opportunity</errorMessage>
            <filterItems>
                <field>Subscription__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>The subscription is not related to the account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>BillingAmount__c</fullName>
        <description>The amount charged per billing cycle.  Populated by MBA</description>
        <inlineHelpText>The amount charged per billing cycle.  Populated by MBA</inlineHelpText>
        <label>MBA Billing Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact associated with the subscription</description>
        <inlineHelpText>Contact associated with the subscription</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <description>ID specific to the store/product purchased</description>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Was used by Acq on forecast subs but can probably be deleted now</description>
        <label>zOpportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <description>ID specific to the plan name since plans can have different ID iterations yet maintain the same name in MBA
Populated by MBA</description>
        <inlineHelpText>ID specific to the plan name since plans can have different ID iterations yet maintain the same name in MBA</inlineHelpText>
        <label>MBA Product ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>From MBA saying which plan/trial the store is on</description>
        <inlineHelpText>From MBA saying which plan/trial the store is on</inlineHelpText>
        <label>MBA Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CreateCancelCasefromOpp.cls
/***
@Author: Maria Huemmer
@Description: Creat Cancellation Case from Opportunity
@History: July-21-2015 Maria Huemmer 
***/

public class CreateCancelCasefromOpp {
// Constructor - this only really matters if the autoRun function doesn't work right
    private Opportunity o;
    public string theId;
    public CreateCancelCasefromOpp(ApexPages.StandardController stdController) {
        this.o = (Opportunity)stdcontroller.getRecord();
    }
    
    // Code we will invoke on page load - visualforce page will be "triggering" it via a custom button
    public PageReference autoRun() {
 
        theId = ApexPages.currentPage().getParameters().get('id');
 		System.debug('OppId' + theId);
		// Display the Visualforce page's content if no Id is passed over
        if (theId == null) {
            
            return null;
        }
        
                    
      //Create a case with the ID we got
       
       case c = createcase();
       
        // Get the URL for the newly created case's "edit" page and return the user there 
       PageReference pageRef = new PageReference('/' + c.Id+'/e?retURL=%2F'+ c.Id);
       pageRef.setRedirect(true);
       return pageRef;
 
    }    
         
    private case CreateCase() {
        // Get the opportunity data we want to populate on the case
      Opportunity o = [select id, name, AccountId, BillingAmount__c, Contact__c, MBASubscriptionID__c, ProductId__c, Product__c, Subscription__C from Opportunity where id =:theId]; {
       System.debug('AccountId' + o.AccountId);
        

        //Store the userid to pass to the case as the case owner
        String userid = UserInfo.getUserId();
        System.debug('UserID' + userid);
        //Create a case with all the data
        Case c = new Case(AccountId = o.AccountId, ContactId=o.Contact__c, Opportunity__c=o.id, 
        				Origin='Phone', OwnerId=userid,  Paused_plan_prior_price__c = o.BillingAmount__c, 
        				Plan_at_Pause_Offer__c = o.Product__c,Product_ID__c = o.ProductID__c,
        				RecordTypeId = '012a0000001NYWL', Status = 'New', Subject = 'Cancellation ' + o.Name);  
        if (o.Subscription__c <> null ) c.Subscription__c = o.Subscription__c;
        insert c;
        return c;
    }
        
    }

}