src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product of the Subscription associated with this case.</description>
        <formula>IF( ISBLANK( Opportunity__c ) = FALSE, Opportunity__r.Product__c, 
IF( ISBLANK( Subscription__c ) = FALSE, Subscription__r.Product__c , 
NULL))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Product of the Subscription associated with this case.</inlineHelpText>
        <label>Product Plan</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BillingAmount__c</fullName>
        <label>Billing Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <description>ID specific to the plan name since plans can have different ID iterations yet maintain the same name in MBA.</description>
        <label>Product ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateCancelCasefromOppTest.cls
/***
@Author: Maria Huemmer
@Description: Test Class to test Cancellation Case Creation from Opportunity
@History: July-21-2015 Maria Huemmer 
***/

@isTest

private class CreateCancelCasefromOppTest {
    static testMethod void testAutoRun(){
   
               
    //Create the stuff we need for the test
    //Insert user...WHEW!....
    Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
    User u = new User(Alias = 'standt', Email='standarduser@bigcommercetestorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@bigcommercetestorg.com');
    String userid = u.id;
   
  
        //Make the Test Stuff
        
        TestDataGenerator td = new TestDataGenerator();
        
                 
        list<Account> lstAcct = td.getAccounts(true);
        ApexPages.StandardController a = new ApexPages.Standardcontroller(lstAcct[0]);
        AccountButtonController abc = new AccountButtonController(a);       
        
        list<Contact> lstCon = td.getContacts(true);
        ApexPages.StandardController c = new ApexPages.Standardcontroller(lstCon[0]);
        
        
        list<Opportunity> lstOpp = td.getOpportunities(true);
        
        //Start Test
        Test.startTest();
        
        Opportunity o = new Opportunity(CloseDate=Date.today(), StageName = 'Closed Won', AccountId = lstAcct[0].id, Name = 'Test Opp', BillingAmount__c = 10, Contact__c = lstCon[0].id, MBASubscriptionID__c = '7', ProductId__c = '7', Product__c = '7');
       
        insert o;
        System.debug(o.id);
        PageReference pageRef = Page.CreateCancelCaseFromOpp;
        Test.setCurrentPage(pageRef);      
        pageRef.getParameters().put('Id', o.Id);
        ApexPages.StandardController sc = new ApexPages.Standardcontroller(o);
     
        CreateCancelCasefromOpp def = new CreateCancelCasefromOpp(sc);
        
        def.autorun();
        
        PageReference pageNull = Page.CreateCancelCaseFromOpp;
        Test.setCurrentPage(pageNull);
        def.autorun();
        
        Test.stopTest(); 
   }
}