src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Chat_Key__c</fullName>
        <externalId>true</externalId>
        <label>Chat Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Migration_Verified_Clicktools__c</fullName>
        <description>Did the client confirm that the migration is verified via clicktools?</description>
        <inlineHelpText>Did the client confirm that the migration is verified via clicktools?</inlineHelpText>
        <label>Migration Verified - Clicktools</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recommend__c</fullName>
        <label>NPS Recommend</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Satisfaction__c</fullName>
        <description>Support : survey field</description>
        <inlineHelpText>How satisfied are you with your (phone, chat, or web) support interaction?
1 Not satisfied | 5 very satisfied</inlineHelpText>
        <label>NPS Satisfaction</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey_Completion_Date__c</fullName>
        <description>Support : survey field, also used by migration team</description>
        <inlineHelpText>Support : survey field, also used by migration team</inlineHelpText>
        <label>Survey Completion Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <description>Support : survey field</description>
        <inlineHelpText>What survey was sent on this case?</inlineHelpText>
        <label>Survey Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Migration</fullName>
        <active>true</active>
        <businessProcess>Migration Case Process</businessProcess>
        <description>Used by Sales to request store migrations</description>
        <label>Migration</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Support_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CaseSurveys</relationshipLabel>
        <relationshipName>CaseSurveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category_Name_transfer_successful__c</fullName>
        <label>Category name transfer successful?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category_Structure_transfer_successful__c</fullName>
        <label>Category structure transfer successful?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Chat_Key__c</fullName>
        <externalId>true</externalId>
        <label>Chat Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content_transfer_successful__c</fullName>
        <label>Content pages transfer successful?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_Info_transfer_successful__c</fullName>
        <label>Customer info transfer successful?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Design_transfer_successful__c</fullName>
        <label>Visual elements transfer successful?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Options_transfer_successful__c</fullName>
        <label>Product Options transfer successful?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_details_transfer_successful__c</fullName>
        <label>Product details transfer successful?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_image_transfer_successful__c</fullName>
        <label>Product image transfer successful?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Recommend__c</fullName>
        <label>Recommend ?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Redirect_301_transfer_successful__c</fullName>
        <label>301 redirect transfer successful?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Satisfaction__c</fullName>
        <label>Satisfaction</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Survey_Completion_Date__c</fullName>
        <label>Survey Completion Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Survey_Name__c</fullName>
        <label>Survey Name</label>
        <picklist>
            <picklistValues>
                <fullName>Support Basic CSAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support - Post-Chat Popup Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Support NPS Next - Chat</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Support NPS Phone Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancellation Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration CSAT Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration Verification Checklist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Support Survey</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Support Survey Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Support Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestSupportSurveyTrigger.cls
@isTest(SeeAllData=true)
private class TestSupportSurveyTrigger {


	static testmethod void testsurveytrigger()
	
	{
		
// Create test data
	TestDataGenerator td = new TestDataGenerator();
	  
	  list<Account> lstAcct = td.getAccounts(true);
	  Case c = td.createCase(lstAcct[0].Id, 'Support', true);
	  c.AccountId = lstAcct[0].Id;
	  update c;
      
      
    LiveChatTranscript l = new LiveChatTranscript();
    LiveChatVisitor visit = new LiveChatVisitor();
    l.chatkey = 'abcdefghji';
    l.CaseId = c.Id;
    insert visit;
    l.Status = 'Completed';
    
    l.StartTime = System.now().addMinutes(-6);
    l.EndTime = System.now().addMinutes(-4);    
    l.LiveChatVisitorId = visit.Id;
    insert l;
    
    Support_Survey__c  ss = new Support_Survey__c();
    ss.chat_key__c = 'abcdefghji';
    insert ss;
    
     // Pull back the survey
     Support_Survey__c  s = [SELECT Id, Case__c, chat_key__c  FROM Support_Survey__c   WHERE Id = :ss.Id];
    system.debug('test chat key '+s.Chat_Key__c);
    // Validate that the total case time is accurate
    system.assertEquals(s.Case__c ,c.Id);
    
	}

	static testmethod void testMigsurveytrigger()
	
	{
		
// Create test data
	TestDataGenerator td = new TestDataGenerator();
	  
	List<Account> lstAcct = td.getAccounts(true);
	Case c = td.createCase(lstAcct[0].Id, 'Migration', true);
	c.AccountId = lstAcct[0].Id;
	 
	update c;
   
    Support_Survey__c  Verified = new Support_Survey__c(Case__c = c.Id,
                                   	Redirect_301_transfer_successful__c = 'YES',
                                  	Survey_Name__c = 'Migration Verification Checklist' ,
                                 	Product_image_transfer_successful__c = 'YES' ,
            						Product_details_transfer_successful__c = 'YES',
           							Product_Options_transfer_successful__c = 'YES',
            						Design_transfer_successful__c = 'YES',
           							Customer_Info_transfer_successful__c = 'YES',
           							Content_transfer_successful__c ='YES',
            						Category_Structure_transfer_successful__c = 'Yes',
            						Category_Name_transfer_successful__c = 'YES');
    insert Verified;
    
     // Pull back the survey
     Case cs = [SELECT Id, Migration_Verified_Clicktools__c  FROM Case  WHERE Id = :c.Id];
    
    // Validate that the total case time is accurate
    system.assertEquals(cs.Migration_Verified_Clicktools__c ,'Yes');
    
	}
		
	
	static testmethod void testPhonesurveytrigger()
	
	{
		
// Create test data
	TestDataGenerator td = new TestDataGenerator();
	  
	List<Account> lstAcct = td.getAccounts(true);
	 Case c = td.createCase(lstAcct[0].Id, 'Support', true);
	 c.origin = 'Phone';
	c.AccountId = lstAcct[0].Id;
	 
	update c;
   
    Support_Survey__c  Verified = new Support_Survey__c(Case__c = c.Id,
                                    Survey_Completion_Date__c = Date.Today(),
                                  	Survey_Name__c = 'Support NPS Phone Survey' ,
                                  	Satisfaction__c = 10,
                                  	Recommend__c = 10
                                 	);
    insert Verified;
    
     // Pull back the survey
     Case cs = [SELECT Id, Satisfaction__c FROM Case  WHERE Id = :c.Id];
    
    // Validate that the total case time is accurate
    system.assertEquals(cs.Satisfaction__c ,10);
    
	}
}