src/objects/JiraSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Credentials__c</fullName>
        <label>Credentials</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Issue_Type__c</fullName>
        <description>standard JIRA issue type values range from &apos;1&apos; to &apos;4&apos; . &apos;1&apos; is for Bug and so on</description>
        <label>Issue Type</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JIRA_URL__c</fullName>
        <label>JIRA URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Project_Key__c</fullName>
        <description>Jira Project Key Under which JIRA Project you want to create the issue.</description>
        <label>Project Key</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Id__c</fullName>
        <description>Your system Id in Connection. You should check this in JIRA under Connections</description>
        <label>System Id</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <description>User Name in the Jira instance</description>
        <label>UserName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Jira Settings</label>
</CustomObject>

src/classes/JIRAConnectorWebserviceCallout.cls
global class JIRAConnectorWebserviceCallout {
    @future (callout=true)
    WebService static void createIssue( String jiraType, String objectId ) {
 // get all values for this call

        JiraSettings__c settings = JiraSettings__c.getValues(jiraType);
        
        //Set your username and password here
        String username = settings.UserName__c;
        String password = settings.Credentials__c;
        String jiraURL  = settings.Jira_URL__c;
        String systemId = settings.System_Id__c;
        String objectType = 'Case';
        String projectKey = settings.Project_Key__c;
        String issueType =settings.Issue_Type__c;
        
        //Construct HTTP request and response
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http = new Http();
 
        //Construct Authorization and Content header
        Blob headerValue = Blob.valueOf(username+':'+password);
        String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
        req.setHeader('Authorization', authorizationHeader);
        req.setHeader('Content-Type','application/json');
 
        //Construct Endpoint
        String endpoint = jiraURL+'/rest/customware/connector/1.0/'+systemId+'/'+objectType+'/'+objectId+'/issue/create.json';
        system.debug(' end point' +endpoint);
        //Set Method and Endpoint and Body
        req.setMethod('POST');
        req.setEndpoint(endpoint);
        req.setBody('{"project":"'+projectKey+'", "issueType":"'+issueType+'"}');
 
        try {
           //Send endpoint to JIRA
           res = http.send(req);
        } catch(System.CalloutException e) {
            System.debug(res.toString());
        }
    }
    
    @future (callout=true)
    WebService static void syncIssue( String jiraType, String objectId ) {
 // get all values for this call

        JiraSettings__c settings = JiraSettings__c.getValues(jiraType);
        
        //Set your username and password here
        String username = settings.UserName__c;
        String password = settings.Credentials__c;
        String jiraURL  = settings.Jira_URL__c;
        String systemId = settings.System_Id__c;
        String objectType = 'Case';
        String projectKey = settings.Project_Key__c;
        String issueType =settings.Issue_Type__c;
        
        //Construct HTTP request and response
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http = new Http();
 
        //Construct Authorization and Content header
        Blob headerValue = Blob.valueOf(username+':'+password);
        String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
        req.setHeader('Authorization', authorizationHeader);
        req.setHeader('Content-Type','application/json');
 
        //Construct Endpoint
        String endpoint = jiraURL+'/rest/customware/connector/1.0/'+systemId+'/'+objectType+'/'+objectId+'/issue/synchronize.json';
        system.debug(' end point' +endpoint);
        //Set Method and Endpoint and Body
        req.setMethod('PUT');
        req.setEndpoint(endpoint);
        req.setBody('{"project":"'+projectKey+'", "issueType":"'+issueType+'"}');
 
        try {
           //Send endpoint to JIRA
           res = http.send(req);
        } catch(System.CalloutException e) {
            System.debug(res.toString());
        }
    }
}