src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <inlineHelpText>Why did this lead close rather than convert to a sale?</inlineHelpText>
        <label>Unqualified Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Unable to Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accidental Trial/No ecomm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Mature Enough/No Products/Too Small</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Integration/3rd Party Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Merchandising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Wholesale/B2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Promotions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Multi-Language Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Multiple Store Backend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Omni Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Misc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timing - Reengage 1-3 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timing - Reengage 4-12 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Timing - Reengage 12+ months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infrastructure &amp; Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Migration Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influenced by 3rd Party</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No longer in business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate Record</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trial expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data Cleanup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unable to Contact Through Flow</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Owner_ID__c</fullName>
        <formula>OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Team__c</fullName>
        <formula>Owner:User.Department</formula>
        <label>Owner Team</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Lead_Retrieved__c.object
<CustomObject>
    <fields>
        <fullName>Lead_Owner_Assign_Date__c</fullName>
        <label>Lead Owner Assign Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Owner__c</fullName>
        <label>New Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Leads_Retrieved</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner_ID__c</fullName>
        <label>Owner ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <label>Owner Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Team__c</fullName>
        <label>Owner Team</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <label>zLead Owner Assignment</label>
    <nameField>
        <displayFormat>LR{00000000}</displayFormat>
        <label>Sequence No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads Retrieved</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead_Update_Owner__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Queue_Owner__c</fullName>
        <label>Queue/Owner</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Update__c</fullName>
        <defaultValue>false</defaultValue>
        <description>TO run in Update mode</description>
        <label>Update?</label>
        <type>Checkbox</type>
    </fields>
    <label>Lead Update Owners</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <label>Closed Lost Reason</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Unable to Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost to Competitor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor In-Trial Client Success Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Price</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Feature/Functionality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Risk of Migration Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsell Closed/Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Phone Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auto Closed Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App will not install</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App does not function</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>App does not meet minimum requirements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No contact from developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contract declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accidental Trial/No ecomm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Mature Enough/No Products/Too Small</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SQL Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Integration w/3rd Party Tool</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Merchandising</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Wholesale/B2B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product/Promotions</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Owner_Team__c</fullName>
        <formula>Owner.Department</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseDate__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UpdateOwner.cls
global class  UpdateOwner implements Database.Batchable<sObject>, Database.Stateful
{ 
    public String query;
    
    global Boolean Flag;
    global Database.QueryLocator start(Database.BatchableContext BC)
    {           
        Flag =false;   
 		Id upgradeRecordTypeId = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_Upgrade).getRecordTypeId();
	    Id trialRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_Trial).getRecordTypeId();
        Id storeRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_StorePurchase).getRecordTypeId();
 		
        return Database.getQueryLocator(query);     
    }

    //Method where business logic gets executed
    global void execute(Database.BatchableContext BC, List<sObject> scope)
    {
        //Delete existing records in custom table
        purgeReportTable();
	    Id upgradeRecordTypeId = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_Upgrade).getRecordTypeId();
	    Id trialRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_Trial).getRecordTypeId();
        Id storeRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_StorePurchase).getRecordTypeId();

        //Collect where ownerId is equal and not equal to createdById
        Map<String,String> mapOwnerSameAsCreatedBy = new Map<String,String>();
        Map<String,String> mapOwnerDiffAsCreatedBy = new Map<String,String>();
        Map<Id, Id> mapAccOwner = new Map<Id, Id>();
        Map<Id, Id> mapTrialOppOwner = new Map<Id, Id>();
        Map<String,DateTime> mapOwnerAssignDate = new Map<String,DateTime>();
 		
 		List<String> lstAcctIds = new List<String>();
 		
        for(Sobject s : scope)
        { 
	        System.Debug('User1 scope size#'+scope.size());
	        Opportunity obj = (Opportunity)s;
	        System.Debug('User1 scope '+obj.Id);
 			if (obj.RecordTypeId == storeRecordTypeId || obj.CreatedById == obj.OwnerId)
 			{
               mapOwnerSameAsCreatedBy.put(obj.Id,obj.OwnerId);
               mapOwnerAssignDate.put(obj.Id,obj.PurchaseDate__c);
 			}  
             else
			 {  
               //if ownerId is not same as Created User
                if(obj.CreatedById != obj.OwnerId)
                {
                    mapOwnerDiffAsCreatedBy.put(obj.Id,obj.OwnerId);
                }
                          
 			}
 			if (obj.RecordTypeId == trialRecordTypeId)
 			{
 				mapTrialOppOwner.put(obj.Id,obj.OwnerId);
 			}
			lstAcctIds.add(obj.AccountId);
            mapAccOwner.put(obj.AccountId, obj.OwnerId);
        }

            //Query History Table for Owner Change Date 
            Map<String,DateTime> mapOpps = new Map<String,DateTime>();
          
            if(!mapOwnerDiffAsCreatedBy.keyset().isEmpty())
            {
                for(OpportunityFieldHistory obj:[SELECT CreatedById,CreatedDate,Field,Id,OpportunityId,NewValue,OldValue FROM OpportunityFieldHistory WHERE Field = 'Owner' and OpportunityId IN:mapOwnerDiffAsCreatedBy.keyset()   order by CreatedDate DESC])
                {
 				  if (obj.NewValue == mapOwnerDiffAsCreatedBy.get(obj.OpportunityId))	
 				  {
                    if(!mapOwnerAssignDate.containsKey(obj.OpportunityId))
                    {
                        mapOwnerAssignDate.put(obj.OpportunityId, obj.CreatedDate);
                    }
 				  }
                } 
            }
   //Query History Table for Stage Change Date 
            Map<String,DateTime> mapOppStages = new Map<String,DateTime>();
  			if(!mapTrialOppOwner.keyset().isEmpty())
            {
                for(OpportunityFieldHistory obj:[SELECT CreatedById,CreatedDate,Field,Id,OpportunityId,NewValue,OldValue FROM OpportunityFieldHistory WHERE Field = 'StageName' and OpportunityId IN:mapTrialOppOwner.keyset()   order by CreatedDate DESC])
                {
 				  if (obj.CreatedById == mapTrialOppOwner.get(obj.OpportunityId))	
 				  {
                    if(!mapOppStages.containsKey(obj.OpportunityId))
                    {
                        mapOppStages.put(obj.OpportunityId, obj.CreatedDate);
                    }
 				  }
                } 
            }
 //          System.Debug('Opportunity Map with Created/Owner change date:'+mapOppOwnerAssignDate);
// if it was not created by user or it does not have opp field history - done before 12/14 add the date.
			Date olddate = system.today().addDays(-150);
			for (Id idmiss :mapOwnerDiffAsCreatedBy.KeySet())
			{
				if (!mapOwnerAssignDate.containsKey(idmiss))
				mapOwnerAssignDate.put(idmiss, olddate);
			}

//			mapOppOwner.putAll(mapOwnerDiffAsCreatedBy);
//			mapOppOwner.putAll(mapOwnerSameAsCreatedBy);
			
            //Collect all  Ids
            List<String> lstOppIds = new List<String>();
            lstOppIds.addAll(mapOwnerDiffAsCreatedBy.keyset());
            lstOppIds.addAll(mapOwnerSameAsCreatedBy.keyset());
 
            //Collect all Owner Ids
            List<String> lstOppOwnerIds = new List<String>();
            lstOppOwnerIds.addAll(mapOwnerDiffAsCreatedBy.values());
            lstOppOwnerIds.addAll(mapOwnerSameAsCreatedBy.values());
 

            //Query for Tasks for all the Opps
            Map<Id,List<Task>> mapAccTasks = new Map<Id,List<Task>>();
            Map<String,List<Task>> mapTaskForOpps = new Map<String,List<Task>>();
            Map<String,Boolean> mapInboundEmailForOpps = new Map<String,Boolean>();
            Set<String> setCallResult = new Set<String>{'correct contact','contact','set callback', 'Success'};
            if(!mapOwnerAssignDate.keyset().isEmpty())
            {
                for(Task obj:[SELECT AccountId, WhoId,ActivityDate,CallDisposition, ToutApp__Tout_Replied__c, ToutApp__Tout_Replied_At__c, CreatedDate,Description,Id,IsClosed,Subject,Type, OwnerId FROM Task where AccountId IN:lstAcctIds and ( CreatedDate = LAST_90_DAYS OR ToutApp__Tout_Replied_At__c  = LAST_90_DAYS) ])
                {
   //                 System.Debug('Tasks:'+obj);
 					Id oppOwner = mapAccOwner.get(obj.AccountId);
                    if(obj.OwnerId == oppOwner && obj.Subject!=null && obj.Type.equalsIgnoreCase('Email') && (obj.Subject.startsWith('←') || obj.ToutApp__Tout_Replied__c == true ))
                    {
                        if(!mapInboundEmailForOpps.containsKey(obj.AccountId))
                        mapInboundEmailForOpps.put(obj.AccountId,true);
                    }
                     
                    if(obj.OwnerId == oppOwner && obj.Type!=null && obj.Type.equalsIgnoreCase('Call') && obj.CallDisposition!=null && setCallResult.contains(obj.CallDisposition.toLowerCase()))
                    {   
                        List<Task> tsk = new List<Task>();
                        if(!mapTaskForOpps.containsKey(obj.AccountId))
                        {
                            tsk.add(obj);
                            mapTaskForOpps.put(obj.AccountId,tsk);
                        }
                        else
                        {
                            tsk.addAll(mapTaskForOpps.get(obj.AccountId));
                            tsk.add(obj);
                            mapTaskForOpps.put(obj.AccountId,tsk);
                        }
                    }  
                }
            }
  //          System.Debug('InboundEmail for Opps:'+mapInboundEmailForOpps);
            System.Debug('Tasks for Opps:'+mapTaskForOpps);

            //Retrieve custom settings to roles and there SLA
            Map<String, Lead_Update_Owner__c> ownerRoles = Lead_Update_Owner__c.getAll();

            //Process the Opps
            List<Opportunity> lstOppsToUpdate = new List<Opportunity>();
            List<Lead_Retrieved__c> lstOppsToRetreive = new List<Lead_Retrieved__c>();
            for(Sobject s : scope)
            {  
                Opportunity obj = (Opportunity)s;
              
                if(mapTaskForOpps.get(obj.AccountId) == null && mapInboundEmailForOpps.get(obj.AccountId) == null )
                {
 					system.debug(' assign date'+mapOwnerAssignDate.get(obj.Id));
                    system.debug(' role '+obj.Owner_Team__c);
                    if(mapOwnerAssignDate.get(obj.Id) <= System.today().addDays(- Integer.valueof(ownerRoles.get(obj.Owner_Team__c).SLA__c))
                    	&& mapOppStages.get(obj.Id) <= System.today().addDays(- Integer.valueof(ownerRoles.get(obj.Owner_Team__c).SLA__c))
                       )
                    {
                     //If processes is true then update else retrieve
 						Lead_Retrieved__c sObj = new Lead_Retrieved__c();
						sObj.Opportunity__c = obj.Id;
						sObj.Owner_ID__c = obj.OwnerId ;
						sObj.Owner_Team__c = obj.Owner_Team__c;
						sObj.Owner_Name__c = obj.Owner.Name;
						sObj.New_Owner__c = ownerRoles.get(obj.Owner_Team__c).Queue_Owner__c;
						
                         if(ownerRoles.get(obj.Owner_Team__c).Update__c)

                                {
                                  obj.OwnerId = ownerRoles.get(obj.Owner_Team__c).Queue_Owner__c;
                                  if (obj.RecordTypeId == trialRecordTypeId)
						 		  {
						 			 obj.StageName = 'Closed Lost';
						 			 obj.Closed_Lost_Reason__c = 'Auto Closed Lost';
						 		   }
                                   lstOppsToUpdate.add(obj);
								   sObj.Processed__c = true;
                                }
                         else
                                {
                                    if(mapOwnerAssignDate.get(obj.Id)!=null)

                                    {
                                        sObj.Lead_Owner_Assign_Date__c = Date.valueOf(mapOwnerAssignDate.get(obj.Id));

                                    }
                                    else
                                    {
                                        sObj.Lead_Owner_Assign_Date__c = Date.valueOf(obj.CreatedDate);

                                    }
                                   
                                    
									sObj.Processed__c = false;
                                }
                          lstOppsToRetreive.add(sObj);
                     }
               }
                    
                
            }

            if(!lstOppsToUpdate.isEmpty())
            {
                 update lstOppsToUpdate;
            }
                   
            if(!lstOppsToRetreive.isEmpty())
            {
                insert lstOppsToRetreive;
            }

    }

    global void finish(Database.BatchableContext BC)
    {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setToAddresses(new String[] {'maggie.frederick@bigcommerce.com'});
        //mail.setReplyTo('batch@acme.com');
        //mail.setSenderDisplayName('Batch Processing');
        mail.setSubject('Batch Process Opp Update Owners Completed');
        mail.setPlainTextBody('Batch Process has completed');
       // Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    private void purgeReportTable()
    {
        System.Debug('#Flag# start purge'+Flag);
        if(!Flag)
        {   
            // Query the Lead Data From Lead Retrieved Object.
            List<Lead_Retrieved__c> lstRetData = new List<Lead_Retrieved__c>([Select Id from Lead_Retrieved__c Where Processed__c = false and Opportunity__c <> null LIMIT 50000]);
/*            for(Lead_Retrieved__c obj:[Select Id from Lead_Retrieved__c Where Processed__c = false LIMIT 50000])
            {
  //              obj.Processed__c = true;
                lstRetData.add(obj);
            }
 */           
            // Update the Lead List.
            if(!lstRetData.isEmpty() && !Test.isRunningTest())delete lstRetData;
                  
            Flag = true;
        }
        System.Debug('#Flag# end'+Flag);
    }
    
}