src/objects/Learning__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>kb_internal_learning_article</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>Learning_kav</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>This article type contains the learning guides for the support site.</description>
    <fields>
        <fullName>Article__c</fullName>
        <label>Article</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Back_Button_URL__c</fullName>
        <description>This is the URL for the previous chapter in the current learning guide</description>
        <inlineHelpText>Enter the URL for the previous chapter in this learning guide</inlineHelpText>
        <label>Back Button URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Chapter_List__c</fullName>
        <description>This field should contain an ordered list with a link to each chapter in the guide. Active class should be on the current chapter</description>
        <inlineHelpText>Ordered list of chapters with titles, links, and active class set on current chapter</inlineHelpText>
        <label>Chapter List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Chapter__c</fullName>
        <defaultValue>&quot;Chapter &quot;</defaultValue>
        <description>This field should contain the word &apos;Chapter&apos; followed by the chapter number.</description>
        <inlineHelpText>e.g. Chapter 1, Chapter 2, or Chapter 5</inlineHelpText>
        <label>Chapter</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nav_Title__c</fullName>
        <description>This field should contain the title used in the left navigation to be set as active</description>
        <inlineHelpText>Enter the navigation title from the left menu that should be active</inlineHelpText>
        <label>Nav Title</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Button_Text__c</fullName>
        <description>The title of the next chapter(article) in the guide</description>
        <inlineHelpText>Enter the title of the next chapter in this guide</inlineHelpText>
        <label>Next Button Text</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Button_URL__c</fullName>
        <description>The URL for the next chapter(article) in this learning guide</description>
        <inlineHelpText>Enter the URL for the next chapter in this learning guide</inlineHelpText>
        <label>Next Button URL</label>
        <type>Url</type>
    </fields>
    <label>Learning</label>
    <pluralLabel>Learning</pluralLabel>
</CustomObject>

src/objects/Public__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>kb_Internal_Public_Article</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>kb_Public_Article_kav</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Article__c</fullName>
        <label>Article</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Feedback_Visible__c</fullName>
        <label>Feedback Visible</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nav_Title__c</fullName>
        <label>Nav Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Public</label>
    <pluralLabel>Public</pluralLabel>
</CustomObject>

src/objects/University__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>kb_University_Internal_kav</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>kb_University_kav</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Additional_Resources__c</fullName>
        <label>Additional Resources</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Nav_Title__c</fullName>
        <label>Nav Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Video_Link_Text__c</fullName>
        <label>Next Video Link Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Video_Thumbnail__c</fullName>
        <label>Next Video Thumbnail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Video_URL__c</fullName>
        <label>Next Video URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prev_Video_Link_Text__c</fullName>
        <label>Prev Video Link Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prev_Video_Thumbnail__c</fullName>
        <label>Prev Video Thumbnail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prev_Video_URL__c</fullName>
        <label>Prev Video URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Video_URL__c</fullName>
        <inlineHelpText>Must be the video ID in the address bar Ex: /watch?v=[id]</inlineHelpText>
        <label>Video ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>University</label>
    <pluralLabel>University</pluralLabel>
</CustomObject>

src/classes/ArticlePageHelper.cls
public with sharing class ArticlePageHelper {
	
	//Used by ArticlePageController    
    public static University__kav  getUnivArticle(String artId) 
    {
        List <University__kav> artList = new List <University__kav> ([Select Id, Title, Description__c , UrlName, ArticleType, Prev_Video_URL__c,  Prev_Video_Thumbnail__c, Prev_Video_Link_Text__c, Next_Video_URL__c,Next_Video_Thumbnail__c,Next_Video_Link_Text__c,Additional_Resources__c,Video_URL__c
                                                                        From University__kav p 
                                                                        WHERE PublishStatus = 'Online' AND Language = 'en_US'
                                                                        and KnowledgeArticleId =:artId Limit 1]) ;
        
               
        return artList[0];
    }
    
    public static Public__kav  getPublicArticle(String artId) 
    {
        List <Public__kav> artList = new List <Public__kav> ([Select Id, Title, Feedback_Visible__c,   Article__c, Summary, UrlName, ArticleType, ArticleNumber, KnowledgeArticleId
                                                              From Public__kav p 
                                                              WHERE PublishStatus = 'Online' AND Language = 'en_US'
                                                              and KnowledgeArticleId =:artId Limit 1]) ;
        
               
        return artList[0];
    }
    
    public static Learning__kav  getLearnArticle(String artId) 
    {
        List <Learning__kav> artList = new List <Learning__kav> ([Select Id, Title, Nav_Title__c, ArticleType, UrlName, Chapter__c, Chapter_List__c,  Next_Button_URL__c,Back_Button_URL__c, Next_Button_Text__c, Article__c
                                                              	From Learning__kav p 
                                                              	WHERE PublishStatus = 'Online' AND Language = 'en_US'
                                                              	and KnowledgeArticleId =:artId Limit 1]) ;
             return artList[0];
    }                                                      
 // end ArticlePageController methods
    
}