src/objects/Learning__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>kb_internal_learning_article</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>Learning_kav</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>This article type contains the learning guides for the support site.</description>
    <fields>
        <fullName>Article__c</fullName>
        <label>Article</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Back_Button_URL__c</fullName>
        <description>This is the URL for the previous chapter in the current learning guide</description>
        <inlineHelpText>Enter the URL for the previous chapter in this learning guide</inlineHelpText>
        <label>Back Button URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Chapter_List__c</fullName>
        <description>This field should contain an ordered list with a link to each chapter in the guide. Active class should be on the current chapter</description>
        <inlineHelpText>Ordered list of chapters with titles, links, and active class set on current chapter</inlineHelpText>
        <label>Chapter List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Chapter__c</fullName>
        <defaultValue>&quot;Chapter &quot;</defaultValue>
        <description>This field should contain the word &apos;Chapter&apos; followed by the chapter number.</description>
        <inlineHelpText>e.g. Chapter 1, Chapter 2, or Chapter 5</inlineHelpText>
        <label>Chapter</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nav_Title__c</fullName>
        <description>This field should contain the title used in the left navigation to be set as active</description>
        <inlineHelpText>Enter the navigation title from the left menu that should be active</inlineHelpText>
        <label>Nav Title</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Button_Text__c</fullName>
        <description>The title of the next chapter(article) in the guide</description>
        <inlineHelpText>Enter the title of the next chapter in this guide</inlineHelpText>
        <label>Next Button Text</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Button_URL__c</fullName>
        <description>The URL for the next chapter(article) in this learning guide</description>
        <inlineHelpText>Enter the URL for the next chapter in this learning guide</inlineHelpText>
        <label>Next Button URL</label>
        <type>Url</type>
    </fields>
    <label>Learning</label>
    <pluralLabel>Learning</pluralLabel>
</CustomObject>

src/objects/Public__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>kb_Internal_Public_Article</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>kb_Public_Article_kav</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Article__c</fullName>
        <label>Article</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Feedback_Visible__c</fullName>
        <label>Feedback Visible</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Nav_Title__c</fullName>
        <label>Nav Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Public</label>
    <pluralLabel>Public</pluralLabel>
</CustomObject>

src/objects/University__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <page>kb_University_Internal_kav</page>
            <template>Page</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <page>kb_University_kav</page>
            <template>Page</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Additional_Resources__c</fullName>
        <label>Additional Resources</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Nav_Title__c</fullName>
        <label>Nav Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Video_Link_Text__c</fullName>
        <label>Next Video Link Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Video_Thumbnail__c</fullName>
        <label>Next Video Thumbnail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_Video_URL__c</fullName>
        <label>Next Video URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prev_Video_Link_Text__c</fullName>
        <label>Prev Video Link Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prev_Video_Thumbnail__c</fullName>
        <label>Prev Video Thumbnail</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prev_Video_URL__c</fullName>
        <label>Prev Video URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Video_URL__c</fullName>
        <inlineHelpText>Must be the video ID in the address bar Ex: /watch?v=[id]</inlineHelpText>
        <label>Video ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>University</label>
    <pluralLabel>University</pluralLabel>
</CustomObject>

src/classes/ArticlePageController.cls
public with sharing class ArticlePageController {
	
  	public KnowledgeArticleRecord kar { get; set; }
//   	public String searchText 		{ get; set; }
//  	public pkb_controller pkbcon 	{get;set;}
  	public Id karticleId 			{get;set;}
  	public String karticleType 		{get;set;}
   	 
	public ArticlePageController() {
//		String qryString = 'SELECT Id, title, UrlName, Summary, ArticleType FROM KnowledgeArticleVersion WHERE (PublishStatus = \'online\' and Language = \'en_US\' )';
//  		List<KnowledgeArticleVersion> articleList= Database.query(qryString);
  
  	}
  	 
  	public PageReference getKArticle()
  	{
	   kar = new KnowledgeArticleRecord ();
	   system.debug( '### article Id' + karticleId);
	   system.debug( '### article Type' + karticleType);
//	    karticleId = 'kA613000000TPV0';
//	    karticleType = 'Public_kav';
	     
	   if (karticleType == 'Public__kav')
	   {   
	       Public__kav kav = new Public__kav(); 
	       kav = ArticlePageHelper.getPublicArticle(karticleId);
	       kar = new KnowledgeArticleRecord(kav);
	   }  
	   else if (karticleType == 'University__kav')  
	   {
	   		University__kav kav = new University__kav(); 
	   		kav = ArticlePageHelper.getUnivArticle(karticleId);
	   		kar = new KnowledgeArticleRecord(kav);
	   }
	   else if (karticleType == 'Learning__kav')  
	   {
	   		Learning__kav kav = new Learning__kav(); 
	   		kav = ArticlePageHelper.getLearnArticle(karticleId);
	   		kar = new KnowledgeArticleRecord(kav);
	   }
	      
	      system.debug('kar'+kar.Id);
	      return null;
	    
  	}
 	
     
 

  public class KnowledgeArticleRecord {
    public String id                     { get; set; } 
    public String title                  { get; set; }
    public String summary                { get; set; }
    public String urlName                { get; set; }
    public String articleTypeName        { get; set; }
    
    public string Nav_Title				{ get; set; }
    public string FeedbackVisible		{ get; set; }
    public string chapterList 			{ get; set; }
    public string  nextButtonUrl 		{ get; set; }
    public string  backButtonUrl 		{ get; set; }
    public string  nextButtonText		{ get; set; }
    public string  Addition_Resources	{ get; set; }
    public string  description 			{ get; set; }
    public string Prev_Video_URL		{ get; set; }
    public string Prev_Video_Thumbnail	{ get; set; }
    public string  Prev_Video_Link_Text	{ get; set; }
    public string  Next_Video_URL		{ get; set; }
    public string  Next_Video_Thumbnail { get; set; }
    public string Next_Video_Link_Text	{ get; set; }
    public string Additional_Resources	{ get; set; }
    public string  Video_URL			{ get; set; }
    public string  Chapter				{ get; set; }
    
    public String Article_kar			{ get; set; }
//    public String articleNumber          { get; set; }
    public Id	kavId		 			{ get; set; }
  
    // ctor for empty KAD
    public KnowledgeArticleRecord() { }

   
    public KnowledgeArticleRecord(Public__kav kav) {
      init(kav);
    }
	
	public KnowledgeArticleRecord(University__kav kav) {
      initUniv(kav);
    }
	
	public KnowledgeArticleRecord(Learning__kav kav) {
      initLearn(kav);
    }
	public void init(Public__kav kav) {
        
      id = kav.Id;
      title = kav.Title;
      summary = kav.Summary;
      urlName = kav.UrlName;
      articleTypeName = kav.ArticleType;
      article_kar = kav.Article__c;
//      articleNumber = kav.ArticleNumber;
      FeedbackVisible= kav.Feedback_Visible__c;
      kavId = kav.KnowledgeArticleId;
    }
    public void initlearn(Learning__kav kav) {
 
      id = kav.Id;
      title = kav.Title;
//      summary = kav.Summary;
      urlName = kav.UrlName;
      articleTypeName = kav.ArticleType;
 	  Nav_Title	= kav.Nav_Title__c;
      chapterList = kav.Chapter_List__c; 
      nextButtonUrl = kav.Next_Button_URL__c;
      backButtonUrl = kav.Back_Button_URL__c; 
      nextButtonText = kav.Next_Button_Text__c;
      article_kar = kav.Article__c;
      Chapter = kav.Chapter__c;
 //     articleNumber = kav.ArticleNumber;
//      FeedbackVisible= kav.Feedback_Visible__c;
//      kavId = kav.KnowledgeArticleId;
    }
    public void initUniv(University__kav kav) {
  
      id = kav.Id;
      title = kav.Title;
//      summary = kav.Summary;
      urlName = kav.UrlName;
      articleTypeName = kav.ArticleType;
	  description = kav.Description__c ;
	  Prev_Video_URL = kav.Prev_Video_URL__c;
	  Prev_Video_Thumbnail = kav.Prev_Video_Thumbnail__c;
	  Prev_Video_Link_Text = kav.Prev_Video_Link_Text__c; 
	  Next_Video_URL = kav.Next_Video_URL__c;
	  Next_Video_Thumbnail = kav.Next_Video_Thumbnail__c;
	  Next_Video_Link_Text= kav.Next_Video_Link_Text__c;
	  Additional_Resources = kav.Additional_Resources__c;
	  Video_URL =kav.Video_URL__c;

//    articleNumber = kav.ArticleNumber;
//     FeedbackVisible= kav.Feedback_Visible__c;
//     kavId = kav.KnowledgeArticleId;
    }
  }
	
    
}