src/objects/LghtIdeasSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LghtIdeas Settings</label>
</CustomObject>

src/classes/LghtIdeasInstallHandlerTest.cls
@isTest
public class LghtIdeasInstallHandlerTest { 
	@isTest
	static void testOnInstall() {
		LghtIdeasInstallHandler installHandler = new LghtIdeasInstallHandler();
		Test.testInstall(installHandler, null);
		
		List<LghtIdeasSettings__c> settingsCommunity = [SELECT Value__c FROM LghtIdeasSettings__c WHERE Name = 'community'];
		
		if (settingsCommunity.size() == 1) {
			System.assertEquals(settingsCommunity[0].Value__c, 'undefined', 'Invalid value');
		}
		else {
			System.assertEquals(false, true, 'Settings value has not been created');
		}
	}
}