src/objects/LghtIdeasSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Label__c</fullName>
        <description>Settings variable label</description>
        <inlineHelpText>Settings variable label</inlineHelpText>
        <label>Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>LghtIdeas Settings</label>
</CustomObject>

src/classes/LghtIdeasInstallHandler.cls
global class LghtIdeasInstallHandler implements InstallHandler { 
	global void onInstall(InstallContext context) {
		if(context.previousVersion() == null) {
			//first install
		}

		this.checkConfigurationValues();
	}


	private void checkConfigurationValues() {
		List<LghtIdeasSettings__c> settingsCommunity = [SELECT Id FROM LghtIdeasSettings__c WHERE Name = 'community'];
		
		if (settingsCommunity.size() == 0) {
			LghtIdeasSettings__c communitySettings = new LghtIdeasSettings__c(Name='community', Label__c='Idea Zone Name', Value__c='undefined');
			insert communitySettings;
		}
	}
}