src/objects/Marketing_Material__c.object
<CustomObject>
    <description>PRM Portal materials for channel partners</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag to determine if the record should show up in the Portal</description>
        <inlineHelpText>Flag to determine if the record should show up in the Portal</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <description>Mainly used for Logos, what is the size of the image</description>
        <inlineHelpText>Mainly used for Logos, what is the size of the image</inlineHelpText>
        <label>Size</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Code__c</fullName>
        <description>The actual HTML or other code you are providing to the user</description>
        <inlineHelpText>The actual HTML or other code you are providing to the user</inlineHelpText>
        <label>Source Code</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Target_URL__c</fullName>
        <label>Target URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Text_Version__c</fullName>
        <description>Any ASCII/Text version of the Source Code if needed</description>
        <inlineHelpText>Any ASCII/Text version of the Source Code if needed</inlineHelpText>
        <label>Text Version</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Logo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tell a Friend</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>View_Order__c</fullName>
        <description>If you want this record to show at the top or bottom or in a specific order add a number here</description>
        <inlineHelpText>If you want this record to show at the top or bottom or in a specific order add a number here</inlineHelpText>
        <label>View Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Marketing Material</label>
    <nameField>
        <displayFormat>MM-{0}</displayFormat>
        <label>Marketing Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MarketingMaterialsController.cls
public without sharing class MarketingMaterialsController 
{
	public MarketingMaterialsController()
	{
		LoadMaterials();
	}
	
	public MarketingMaterialsController(Apexpages.StandardController sc)
	{
		Id MMId = sc.getId();
		if (MMId != null)
		{
			Marketing_Material__c mm = [SELECT Source_Code__c FROM Marketing_Material__c WHERE Id = :MMId];
			MMSourceCode = mm.Source_Code__c.replace('{!PartnerId}', string.ValueOf(PartnerPortalHelper.PartnerAccount.iDev_Partner_ID__c));
		}
		else
		{
			MMSourceCode = 'Error finding Web Page';
		}
	}
	
	// Public variables used when this is loaded by the Marketing Materials Page Viewer
	public string MMSourceCode {get; set;}
	
	// Public variables used when this is loaded by the Marketing Materials page
	public string MMType {get; set;}
	public list<clsMaterial> lstMaterials {get; set;}
	public list<string> stTypes 
	{
		get
		{
			list<string> lstResults = new list<string>();
			
			Schema.DescribeFieldResult fieldResult = Marketing_Material__c.Type__c.getDescribe();
			list<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
			
			for(Schema.PicklistEntry f : ple)
			{
				lstResults.add(f.getValue());
				//options.add(new SelectOption(f.getLabel(), f.getValue()));
			} 
			
			return lstResults;
		}
	}
	
	public void LoadMaterials()
	{
		lstMaterials = new list<clsMaterial>();
		
		if (MMType == null || MMType == '')
		{
			MMType = 'Logo';
		}
		
		clsMaterial cls;
		
		// Load the Marketing Materials
		for (Marketing_Material__c mm : [SELECT Id, Name, Name__c, Type__c, Target_URL__c, Size__c, Active__c, Description__c, Source_Code__c, Text_Version__c, 
											(SELECT Id FROM Attachments WHERE ContentType like 'image%' LIMIT 1)
										FROM Marketing_Material__c
										WHERE Type__c = :MMType
										ORDER BY Type__c, View_Order__c ASC NULLS last])
		{
			cls = new clsMaterial(mm);
			lstMaterials.add(cls);
		}
	}
	
	public void SelectMarketing()
	{
		MMType = ApexPages.currentPage().getParameters().get('mmType');
		
		LoadMaterials();
	}
	
	public class clsMaterial
	{
		private Marketing_Material__c objMaterial {get; set;}
		
		public string MaterialType
		{
			get
			{
				if (objMaterial != null)
				{
					return objMaterial.Type__c;
				}
				else
				{
					return null;
				}
			} 
		}
		
		public string MaterialName 
		{
			get
			{
				if (objMaterial != null)
				{
					return objMaterial.Name__c;
				}
				else
				{
					return null;
				}
			} 
		}
		
		public string TargetURL 
		{
			get
			{
				if (objMaterial != null)
				{
					return objMaterial.Target_URL__c;
				}
				else
				{
					return null;
				}
			} 
		}
		
		public string Size 
		{
			get
			{
				if (objMaterial != null)
				{
					return objMaterial.Size__c;
				}
				else
				{
					return null;
				}
			} 
		}
		
		public string MaterialDesc
		{
			get
			{
				if (objMaterial != null)
				{
					return objMaterial.Description__c;
				}
				else
				{
					return null;
				}
			} 
		}
		
		public string SourceCode 
		{
			get
			{
				if (objMaterial != null)
				{
					if (objMaterial.Source_Code__c != null)
					{
						return objMaterial.Source_Code__c.replace('{!PartnerId}', string.ValueOf(PartnerPortalHelper.PartnerAccount.iDev_Partner_ID__c)).replace('{!PartnerFName}', (PartnerPortalHelper.CurrentUserRecord.FirstName == null ? PartnerPortalHelper.CurrentUserRecord.LastName : PartnerPortalHelper.CurrentUserRecord.FirstName));
					}
					else
					{
						return null;
					}
				}
				else
				{
					return null;
				}
			} 
			set;
		}
		
		public string TextVersion 
		{
			get
			{
				if (objMaterial != null)
				{
					if (objMaterial.Text_Version__c != null)
					{
						return objMaterial.Text_Version__c.replace('{!PartnerId}', string.ValueOf(PartnerPortalHelper.PartnerAccount.iDev_Partner_ID__c)).replace('{!PartnerFName}', (PartnerPortalHelper.CurrentUserRecord.FirstName == null ? PartnerPortalHelper.CurrentUserRecord.LastName : PartnerPortalHelper.CurrentUserRecord.FirstName));
					}
					else
					{
						return null;
					}
				}
				else
				{
					return null;
				}
			} 
			set;
		}
		
		public boolean isActive 
		{
			get
			{
				if (objMaterial != null)
				{
					return objMaterial.Active__c;
				}
				else
				{
					return null;
				}
			} 
		}
		
		public string ImageID 
		{
			get
			{
				if (objMaterial != null)
				{
					if (objMaterial.Attachments != null)
					{
						Attachment a = objMaterial.Attachments; 
						return a.Id;
					}
					else
					{
						return null;
					}
				}
				else
				{
					return null;
				}
			} 
		}
		
		public string RecordID
		{
			get
			{
				if (objMaterial != null)
				{
					return objMaterial.Id;
				}
				else
				{
					return null;
				}
			} 
		}
		
		public clsMaterial(Marketing_Material__c objMM)
		{
			objMaterial = objMM;
		}
	}
}