src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Store_URL__c</fullName>
        <inlineHelpText>For Migration Products only, this field must be populated.</inlineHelpText>
        <label>Current Store URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Migration_Platform__c</fullName>
        <inlineHelpText>For Migration products only, this must be populated.</inlineHelpText>
        <label>Migration Platform</label>
        <picklist>
            <picklistValues>
                <fullName>1Shopping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3dCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon Marketplace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon Webstore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amazon Webstores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ayacart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bigcommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CoreCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CreateAShoppe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRE Loaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CubeCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoDaddy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GoDaddy QuickCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interspire (standard SOW)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lemon Stand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loaded Commerce (CRELoaded/OSCommerce)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magento CE/EE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magento/Magento CE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Magento Go</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mal&apos;s eCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miva Merchant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miva Merchant V4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miva Merchant V5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OpenCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OptionCart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OSCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OsMaxCommerce</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portable Shops</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Store_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Store Purchase Opportunity that this is related to.</inlineHelpText>
        <label>Store Opportunity</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Opportunity does not have the same Account</errorMessage>
            <filterItems>
                <field>$Source.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <infoMessage>Select a Store purchase opportunity</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities (Professional Services)</relationshipLabel>
        <relationshipName>PSOpportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestOpportunityTrigger.cls
@isTest(SeeAllData=true)
private class TestOpportunityTrigger
{

    static testMethod void testCreateCaseFromOpp() 
    {
    	TestDataGenerator td = new TestDataGenerator();
    	
    	list<Contact> lstCon = td.getContacts(true);
    	
    	// Create a new opportunity for the account
    	
    	Opportunity o = new Opportunity();
        o.Name = 'Test ';
        o.CloseDate = Date.today().addDays(1);
        o.StageName = 'Purchased';
       
        o.AccountId = lstCon[0].AccountId;
        insert o;
	
    	Test.startTest();
    	    
		 OpportunityHelper oh = new OpportunityHelper();
         Opportunity opp = oh.createOppProfFromCon(lstCon[0].Id);  
         PriceBookEntry pb = [select Id, Name from PriceBookEntry where 
                                          Pricebook2.Name ='BigCommerce' and isActive = true 
                                          and Name like '%Mig%' limit 1]   ;
         OpportunityLineItem oli = new OpportunityLineItem(OpportunityId =opp.Id,
                                       PricebookEntryId= pb.Id,       
                                       TotalPrice =100, Quantity =1);
		 insert oli;
		 opp.StageName = 'Closed Won';
		 opp.Store_Opportunity__c = o.Id;
		 opp.Migration_Platform__c = 'Test';
		 opp.Current_Store_URL__c = 'http://test.com';
		 update opp;
		Test.stopTest();
	}
	
	static testMethod void testOppTeamRetention() 
    {
    	TestDataGenerator td = new TestDataGenerator();
    	
    	list<Opportunity> lstOpp = td.getOpportunities(true);
    	
    	List<OpportunityTeamMember> otms = [select Id from OpportunityTeamMember where OpportunityId in :lstOpp];

		System.assertEquals(otms.size(), lstOpp.size());
		
		User usr1 = [Select Id,Name, Department from User Where IsActive=true and Department =:Label.Inbound_Sales LIMIT 1];
		
  		lstOpp[0].OwnerId = usr1.Id;
  		update lstOpp[0];
  		   	
  		List<OpportunityTeamMember> otmsa = [select Id from OpportunityTeamMember where OpportunityId in :lstOpp];
  		system.debug(lstOpp.size()+1);
  		System.assertEquals(otmsa.size(), lstOpp.size()+1);
  		
    }
}