src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Owner_Team__c</fullName>
        <formula>Owner.Department</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseDate__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Trial</fullName>
        <active>true</active>
        <businessProcess>Sales Process %28Trial to Purchase%29</businessProcess>
        <description>Use when the client has created a trial store.</description>
        <label>Trial</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchUpdateOwner.cls
global class BatchUpdateOwner implements Schedulable {
 global void execute(SchedulableContext sc) {
  
   Id TrialRecordTypeId =  Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get('Trial').getRecordTypeId();

     //Prepare Query to query all Opps where owner is not Queue or partner prospect record type
     string queryTrial ='Select Id, Name, PurchaseDate__c, AccountId, OwnerId, Owner.Name, StageName, CreatedDate, CreatedById, RecordTypeId, Owner_Team__c from Opportunity Where  RecordTypeId = :trialRecordTypeId  ' ;
     queryTrial = queryTrial + Label.ROE_Trial_Query;

     system.Debug('#query# '+queryTrial); 
     
     
     UpdateOwner b = new UpdateOwner(); 
     b.query = queryTrial;
     database.executebatch(b);
   }

 }