src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>AppRev_Share_Payment_Amount__c</fullName>
        <description>Amount of the partner&apos;s most recent payment</description>
        <inlineHelpText>Amount of the partner&apos;s most recent payment</inlineHelpText>
        <label>App Rev Share Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>App_Rev_Share_Payment_Date__c</fullName>
        <description>Date of app partner&apos;s last rev share payment</description>
        <inlineHelpText>Date of app partner&apos;s last rev share payment</inlineHelpText>
        <label>App Rev Share Payment Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/acctAppTemplt.cls
public  class acctAppTemplt
{
    public Id accountId {get;set;}
    public List<Opportunity> getopptys()
    {
        List<Opportunity> opptylist;
        
        Id AppRecordTypeId  = Opportunity.getSObjectType().getDescribe().getRecordTypeInfosByName().get(Label.Opportunity_RecordType_App).getRecordTypeId();
        String published = 'Published';         
        opptylist = [SELECT Name, StageName,App_Rev_Share_Payment_Date__c, AppRev_Share_Payment_Amount__c FROM Opportunity WHERE Accountid =: accountId AND RecordTypeId = :AppRecordTypeId AND STAGENAME =:published];
        return opptylist;
    }
}