src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Owner_Team__c</fullName>
        <formula>Owner.Department</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Team</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseDate__c</fullName>
        <label>Purchase Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchUpdatePurchaseOwner.cls
global class BatchUpdatePurchaseOwner implements Schedulable {
   global void execute(SchedulableContext sc) {
      
       //Prepare Query to query all Opps where owner is not Queue or partner prospect record type
        string queryPurchase ='Select Id, Name, AccountId, OwnerId, StageName, PurchaseDate__c, CreatedDate, CreatedById, RecordTypeId, Owner_Team__c from Opportunity Where  RecordTypeId = :storeRecordTypeId  ' ;
 		queryPurchase = queryPurchase + Label.ROE_Purchase_Query;
 		if(Test.isRunningTest()){   queryPurchase = queryPurchase + ' limit 2';}
        system.Debug('#query# '+queryPurchase); 
      
      UpdateOwner b = new UpdateOwner(); 
      b.query = queryPurchase;
      database.executebatch(b);

   }

}