src/objects/Partner_Commission_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for Partner Commissions  functionality.
When making a change to the start date, make sure to also change the Partner Commission Payment rollup on RV Account so that the numbers can be calculated properly.  The date there should reflect one month after the date on this custom setting.</description>
    <fields>
        <fullName>Earliest_Possible_Start_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>If the start date is left blank on a partner commission run, this is the earliest BI Data to pull in</inlineHelpText>
        <label>Earliest Possible Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Day_of_Bill_Cycle__c</fullName>
        <description>For BAP-3698 - Partner Commission v2</description>
        <inlineHelpText>Indicates the day of the month we should consider as the start of a new bill cycle.  If the number is greater than the number of days in the month, the first day of the following month will be used.</inlineHelpText>
        <label>First Day of Bill Cycle</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Commission Settings</label>
</CustomObject>

src/objects/Partner_Commission_Summary__c.object
<CustomObject>
    <description>Roles up all customer payments to a reselling partner and calculates the earned commission</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The latest payment date that can be used to collect payment data for this partner</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partner_Account__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The Partner Account (RV Account) that this Partner Commission is tied to.</inlineHelpText>
        <label>Partner Account</label>
        <referenceTo>rvpe__RVAccount__c</referenceTo>
        <relationshipLabel>Partner Commission Summaries</relationshipLabel>
        <relationshipName>Partner_Commission_Summaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partner_Commission_Summary_Dedupe_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>A unique key that prevents duplicate summaries for the same scope and partner to be created</inlineHelpText>
        <label>Partner Commission Summary Dedupe Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The earliest customer payment date to include when calculating this partner&apos;s commissions</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Partner Commission Summary</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Partner Commission Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Commission Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchPartnerCommissionCreateSummaries.cls
/**
 * BatchPartnerCommissionCreateSummaries
 * Author: Steve O'Neal
 * Ticket: BAP-3698
 * Description: Creates Partner Commission Summary objects in advance of creating the detail records.
 * Technically this process isn't necessary except to make sure that a zero-dollar summary is created for each partner for each bill period, 
 * driving it entirely by BI Data would leave data gaps if no payments were made.
 */
global class BatchPartnerCommissionCreateSummaries implements Database.Batchable<sObject> {
	
	global String query;
	global Date startDate;
	global Date endDate;
	private Date earliestDate;
	global List<rvpe__RVAccount__c> targetPartnerAccounts;
	global integer firstDayOfBillCycle;
	global boolean CreateDetailsWhenFinished;
	global boolean ProcessEveryMonthUntilToday;

	
	/**
	 * Builds the query for the batch process.  Note that this will not run if the query is manually overridden.
	 * @author Steve O'Neal
	 * @date   2016-06-09
	 * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
	 * @return String representing a SOQL query
	 */
	private string buildQuery()
	{
		if (!String.isEmpty(query))
		{
			return query;
		}

		// make sure that start date is within the parameters
		if (startDate == null || startDate < earliestDate)
		{
			startDate = earliestDate;
		}
		string retVal = ' select id, name, This_Month_s_Partner_Commission_Summary__c, Last_Month_s_Partner_Commission_Summary__c, Approved_Date__c, Inactivated_Date__c, IDev_ID__c, rvpe__ExtAccountId__c';
		retVal +=		' from rvpe__RVAccount__c';
		retVal +=		' where Commission__c != null';
		// filter for all partner that could have possibly collected revenue in this period
		retVal +=		' 	and (Approved_Date__c <= ' + BatchPartnerCommissionCreateDetails.formatDateForQuery(endDate) + ' or IDev_ID__c != null)';
		retVal +=		' 	and (Inactivated_Date__c = null or Inactivated_Date__c >= ' + BatchPartnerCommissionCreateDetails.formatDateForQuery(endDate) + ')';
		retVal +=		'	and rvpe__ExtAccountId__c != 0';

		if (targetPartnerAccounts.size() > 0)
		{
			// filter the results to only the specified partners
			retVal += 	'	and ID in (';
			string comma = '';
			for (rvpe__RVAccount__c pAcct : targetPartnerAccounts)
			{
				retVal += comma + '\'' + String.valueOf(pAcct.Id).Left(15) + '\'';
				comma = ',';
			}
			retVal +=	')';
		}

		System.Debug('Generated SOQL query: ' + retVal);
		return retVal;
	}


	/**
	 * Instantiator
	 * @author Steve O'Neal
	 * @date   2016-06-10
	 * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
	 * @return Creates an instance of the batch job and initializes the variables
	 */
	global BatchPartnerCommissionCreateSummaries() {
		Partner_Commission_Settings__c pcs = Partner_Commission_Settings__c.getInstance();
		firstDayOfBillCycle = (pcs.First_Day_of_Bill_Cycle__c != null)?Integer.valueOf(pcs.First_Day_of_Bill_Cycle__c):1;
		earliestDate = (pcs.Earliest_Possible_Start_Date__c != null)?pcs.Earliest_Possible_Start_Date__c:Date.newInstance(2013, 1, 1);
		startDate = earliestDate;
		// get the last day of the current bill cycle using the custom setting.
		endDate = Date.newInstance(Date.today().year(), Date.today().month(), firstDayOfBillCycle).addMonths(1).addDays(-1);
		// by default, chain up the detail calculation batch job when this is finished
		CreateDetailsWhenFinished = true;
		targetPartnerAccounts = new List<rvpe__RVAccount__c>();
		ProcessEveryMonthUntilToday = false;
	}
	
	/**
	 * QueryLocator gets the records from the db based on the generated query
	 * @author Steve O'Neal
	 * @date   2016-06-10
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
	 * @param  BC         Batchable context
	 * @return            Query locator that represents the scope of the batch
	 */
	global Database.QueryLocator start(Database.BatchableContext BC) {
		query = buildQuery();

		return Database.getQueryLocator(query);
	}

	/**
	 * Execute the scope
	 * @author Steve O'Neal
	 * @date   2016-06-10
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
	 * @param  BC         Batchable context
	 * @param  scope      Current scope of batch
	 * @return            Nothing
	 */
   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		List<Partner_Commission_Summary__c> pcSummaries = new List<Partner_Commission_Summary__c>();

		Date thisMonthsLastDay = Date.newInstance(Date.today().year(), Date.today().month(), 1).addMonths(1).addDays(-1);
		Date lastMonthsLastDay = Date.newInstance(Date.today().year(), Date.today().month(), 1).addDays(-1);
		Map<Id, rvpe__RVAccount__c> rvAccountMap = new Map<Id, rvpe__RVAccount__c>();

		for (sObject sobj : scope)
		{
			rvpe__RVAccount__c rvAccount = (rvpe__RVAccount__c)sobj;
			Partner_Commission_Summary__c pcs = new Partner_Commission_Summary__c();
			pcs.Start_Date__c = startDate;
			pcs.End_Date__c = endDate;
			pcs.Partner_Account__c = sobj.Id;
			pcs.RecordTypeId = PartnerCommissionSummaryTriggerHandler.OpenRecordType.Id;
			pcs.Partner_Commission_Summary_Dedupe_Key__c = PartnerCommissionSummaryTriggerHandler.GetDedupeKey(String.valueOf(rvAccount.rvpe__ExtAccountId__c), startDate, endDate);
			pcSummaries.add(pcs);

			rvAccountMap.put(rvAccount.id, rvAccount);
		}

		// insert the records into the db
		Database.insert(pcSummaries, false);

		// also record the current month's and previous month's commission summary
		List<Partner_Commission_Summary__c> pcSummaries2 = [Select Id, Partner_Account__c, Start_Date__c, End_Date__c, Partner_Commission_Summary_Dedupe_Key__c from Partner_Commission_Summary__c where Partner_Account__c in :rvAccountMap.KeySet() and (End_Date__c = :thisMonthsLastDay or End_Date__c = :lastMonthsLastDay)];

		if (pcSummaries2.size() > 0)
		{
			for (Partner_Commission_Summary__c pcs : pcSummaries2)
			{
				if (pcs.End_Date__c == thisMonthsLastDay)
				{
					rvAccountMap.get(pcs.Partner_Account__c).This_Month_s_Partner_Commission_Summary__c = pcs.Id;
				}
				else if (pcs.End_Date__c == lastMonthsLastDay)
				{
					rvAccountMap.get(pcs.Partner_Account__c).Last_Month_s_Partner_Commission_Summary__c = pcs.Id;
				}
			}

			Database.update(rvAccountMap.values(), false);
		}


	}
	

	/**
	 * Post-processing logic
	 * @author Steve O'Neal
	 * @date   2016-06-10
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
	 * @param  BC         Batchable context
	 * @return            nothing
	 */
	global void finish(Database.BatchableContext BC) {
		if (CreateDetailsWhenFinished)
		{
			BatchPartnerCommissionCreateDetails bpccd = new BatchPartnerCommissionCreateDetails();
			bpccd.startDate = startDate;
			bpccd.endDate = endDate;
			bpccd.targetPartnerAccounts = targetPartnerAccounts;
			bpccd.firstDayOfBillCycle = firstDayOfBillCycle;
			bpccd.ProcessEveryMonthUntilToday = ProcessEveryMonthUntilToday;

			database.executeBatch(bpccd, 200);
		}
	}
	
}