src/objects/Partner_Commission_Summary_History__c.object
<CustomObject>
    <description>Stores daily metrics against Partner Commissions to ease in reporting

For BAP-3698 - Partner Commissions v2</description>
    <fields>
        <fullName>Active_Partners_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of active reseller partners for closed Partner Commission Summaries</inlineHelpText>
        <label>Active Partners - Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Active_Partners_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of active reseller partners for open Partner Commission Summaries</inlineHelpText>
        <label>Active Partners - Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Active_Partners__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <formula>Active_Partners_Closed__c +  Active_Partners_Open__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total number of active reseller partners for Partner Commission Summaries</inlineHelpText>
        <label>Active Partners</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <formula>Commission_Earned__c  -  Payment_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The net amount owed to partners</inlineHelpText>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Earned_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>Total commission earned for open Partner Commission Summaries</inlineHelpText>
        <label>Commission Earned - Closed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Earned_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>Total commission earned for open Partner Commission Summaries</inlineHelpText>
        <label>Commission Earned - Open</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Earned__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <formula>Commission_Earned_Closed__c + Commission_Earned_Open__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total commission earned for open Partner Commission Summaries</inlineHelpText>
        <label>Commission Earned</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissionable_Revenue_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total transaction value that can be used for calculating commissions in closed Partner Commission Summaries</inlineHelpText>
        <label>Commissionable Revenue - Closed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissionable_Revenue_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total transaction value that can be used for calculating commissions in open Partner Commission Summaries</inlineHelpText>
        <label>Commissionable Revenue - Open</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissionable_Revenue__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <formula>Commissionable_Revenue_Closed__c +  Commissionable_Revenue_Open__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total transaction value that can be used for calculating commissions in closed Partner Commission Summaries</inlineHelpText>
        <label>Commissionable Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissionable_Transactions_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of commissionable transactions for closed Partner Commission Summaries</inlineHelpText>
        <label>Commissionable Transactions - Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commissionable_Transactions_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of commissionable transactions for open Partner Commission Summaries</inlineHelpText>
        <label>Commissionable Transactions - Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commissionable_Transactions__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <formula>Commissionable_Transactions_Closed__c + Commissionable_Transactions_Open__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total number of commissionable transactions for Partner Commission Summaries</inlineHelpText>
        <label>Commissionable Transactions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Date_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The earliest start date for closed Partner Commissions</inlineHelpText>
        <label>Earliest Start Date - Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Date_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The earliest start date for open Partner Commissions</inlineHelpText>
        <label>Earliest Start Date - Open</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <formula>IF( OR(Earliest_Start_Date_Open__c &lt;  Earliest_Start_Date_Closed__c,  ISNULL(Earliest_Start_Date_Closed__c)), Earliest_Start_Date_Open__c, Earliest_Start_Date_Closed__c)</formula>
        <inlineHelpText>The earliest start date for Partner Commissions</inlineHelpText>
        <label>Earliest Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique key to ensure that only one record is created per day</inlineHelpText>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Latest_End_Date_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The latest end date for closed Partner Commission Summaries</inlineHelpText>
        <label>Latest End Date - Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Latest_End_Date_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The latest end date for open Partner Commission Summaries</inlineHelpText>
        <label>Latest End Date - Open</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Latest_End_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <formula>IF( OR(Latest_End_Date_Open__c &gt; Latest_End_Date_Closed__c, ISNULL(Latest_End_Date_Closed__c)), Latest_End_Date_Open__c, Latest_End_Date_Closed__c)</formula>
        <inlineHelpText>The latest end date for Partner Commission Summaries</inlineHelpText>
        <label>Latest End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partners_Paid__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of partners that have been paid to date</inlineHelpText>
        <label>Partners Paid</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total amount paid out to partners</inlineHelpText>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payments__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The number of payments made to our partners</inlineHelpText>
        <label>Payments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Summary_Count_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of closed Partner Commission Summary records</inlineHelpText>
        <label>Summary Count - Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Summary_Count_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of open Partner Commission Summary records</inlineHelpText>
        <label>Summary Count - Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Summary_Count__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <formula>Summary_Count_Closed__c + Summary_Count_Open__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total number of Partner Commission Summary records</inlineHelpText>
        <label>Summary Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Commission Summary History</label>
    <nameField>
        <displayFormat>PCM-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Partner Commission Summary History Numbe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Commission Summary Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PartnerCommissionToolsController.cls
/**
 * ParterCommissionToolsController
 * Author: Steve O'Neal
 * Date: 6-25-2016
 * Purpose: For monitoring batch jobs and PartnerCommissionSummaryHistory
 */
public with sharing class PartnerCommissionToolsController {

    private final sObject mysObject;
    private Partner_Commission_Summary_History__c pvtPartnerCommissionSummaryHistory;
    private Map<Id,ApexClass> batchJobs;
    private Map<String,String> batchNames;
    private List<String> batchStatuses;
    private BatchMonitor currentBatchStatus;

    /**
     * Instantiator
     * @author Steve O'Neal
     * @date   2016-07-05
     * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
     * @return An instance of the page controller
     */
    public PartnerCommissionToolsController()
    {
        initializeMe();
    }

    /**
     * Intializes all local variables
     * @author Steve O'Neal
     * @date   2016-07-05
     * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
     */
    private void initializeMe()
    {
        // fill in the list of batches we will monitor
        batchNames = new Map<String,String>();
        batchNames.put('BatchPartnerCommissionCleanup', 'Cleanup');
        batchNames.put('BatchPartnerCommissionCreateSummaries', 'Create Summaries');
        batchNames.put('BatchPartnerCommissionCreateDetails', 'Create Details');
        batchNames.put('BatchPartnerCommissionCreateHistory', 'Create History');

        // fill in the statuses of batches we will monitor
        batchStatuses = new List<String>();
        batchStatuses.add('Holding');
        batchStatuses.add('Queued');
        batchStatuses.add('Preparing');
        batchStatuses.add('Processing');

        // get the setup data to query the batch jobs
        batchJobs = new Map<Id,ApexClass>([Select Id, Name from ApexClass where Name in :batchNames.keyset()]);

        RefreshPageData();
    }

    /**
     * Returns the most recent Partner Commission Summary History
     * @author Steve O'Neal
     * @date   2016-07-05
     * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
     * @return The most recent instance of the commission summary history
     */
    public Partner_Commission_Summary_History__c GetPartnerCommissionSummaryHistory()
    {
        return pvtPartnerCommissionSummaryHistory;
    }


    /**
     * Refreshes the page data
     * @author Steve O'Neal
     * @date   2016-07-05
     * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
     * @return Null
     */
    public PageReference RefreshPageData()
    {
        fillBillingPeriodData();
        createBatchStatus();

        return null;
    }

    /**
     * Fetches the most recent partner commission summary history from the database
     * @author Steve O'Neal
     * @date   2016-07-05
     * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
     */
    private void fillBillingPeriodData()
    {
        pvtPartnerCommissionSummaryHistory = new Partner_Commission_Summary_History__c();

        // get the most recent record from the db
        List<Partner_Commission_Summary_History__c> pcshResults = [select Id, Name, Key__c, Active_Partners__c, Active_Partners_Closed__c, Active_Partners_Open__c, Commissionable_Revenue__c, Commissionable_Revenue_Closed__c, Commissionable_Revenue_Open__c, Commissionable_Transactions__c, Commissionable_Transactions_Closed__c, Commissionable_Transactions_Open__c, Commission_Earned__c, Commission_Earned_Closed__c, Commission_Earned_Open__c, Earliest_Start_Date__c, Earliest_Start_Date_Closed__c, Earliest_Start_Date_Open__c, Latest_End_Date__c, Latest_End_Date_Closed__c, Latest_End_Date_Open__c, Summary_Count__c, Summary_Count_Closed__c, Summary_Count_Open__c, LastModifiedDate, Partners_Paid__c, Payment_Amount__c, Payments__c, Balance__c from Partner_Commission_Summary_History__c order by Key__c desc limit 1];
        if (pcshResults.size() > 0)
        {
            pvtPartnerCommissionSummaryHistory = pcshResults[0];
        }

    }

    /**
     * Fetches the current running batch job
     * @author Steve O'Neal
     * @date   2016-07-05
     * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
     */
    private void createBatchStatus()
    {
        List<AsyncApexJob> apexJobs = [select Id, createdDate, ApexClassID, Status, ExtendedStatus, JobItemsProcessed, JobType, MethodName, TotalJobItems, NumberOfErrors, CompletedDate from AsyncApexJob where JobType = 'BatchApex' and ApexClassId in :batchJobs.keyset() and Status in :batchStatuses order by createddate desc];
        currentBatchStatus = new BatchMonitor();

        if (apexJobs.size() > 0)
        {
            // fill in the data from the first record
            currentBatchStatus.Id = apexJobs[0].Id;
            currentBatchStatus.Status = apexJobs[0].Status;
            currentBatchStatus.CreatedDate = apexJobs[0].CreatedDate;
            // get the friendly name of the batch job
            currentBatchStatus.JobName = batchNames.get(batchJobs.get(apexJobs[0].ApexClassID).Name);
            currentBatchStatus.NumberOfBatches = apexJobs[0].TotalJobItems;
            currentBatchStatus.NumberOfBatchesProcessed = apexJobs[0].JobItemsProcessed;
        }
    }

    /**
     * Returns the most recent batch status
     * @author Steve O'Neal
     * @date   2016-07-05
     * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
     * @return The most recent batch status
     */
    public BatchMonitor getBatchStatus()
    {
        return currentBatchStatus;
    }
    
    /**
     * Class used for encapsulating the batch details
     */
    public class BatchMonitor
    {
        public Datetime CreatedDate {get;set;}
        public string Id {get;set;}
        public string JobName {get;set;}
        public string Status {get;set;}
        public integer BatchSize {get;set;}
        public integer NumberOfBatches {get;set;}
        public integer NumberOfBatchesProcessed {get;set;}

        /**
         * Gets the number of records being processed, assuming a 200 record batch size
         * @author Steve O'Neal
         * @date   2016-07-05
         * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
         * @return Number of estimated records being processed in the batch
         */
        public integer getNumberOfRecords()
        {
            return NumberOfBatches * BatchSize;
        }

        /**
         * Gets the number of records already processed, assuming a 200 record batch size
         * @author Steve O'Neal
         * @date   2016-07-05
         * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
         * @return Estimated number of records already processed
         */
        public integer getNumberOfRecordsProcessed()
        {
            return NumberOfBatchesProcessed * BatchSize;
        }

        /**
         * Gets the percent completed of the batch job
         * @author Steve O'Neal
         * @date   2016-07-05
         * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
         * @return The percent completed of the batch job
         */
        public integer getProgressPercent()
        {
            if (NumberOfBatches == 0)
            {
                return 0;
            }
            else
            {
                return (NumberOfBatchesProcessed * 100) / NumberOfBatches;
            }
        }

        /**
         * Instantiator
         * @author Steve O'Neal
         * @date   2016-07-05
         * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
         * @return An instance of BatchMonitor
         */
        public BatchMonitor()
        {
            Id = '';
            BatchSize = 200;
            NumberOfBatches = 0;
            NumberOfBatchesProcessed = 0;
            Status = 'Sleeping';
            JobName = 'N/A';
        }
    }

}