src/objects/Partner_Commission__c.object
<CustomObject>
    <description>To keep track of client payments andrelated partner details</description>
    <fields>
        <fullName>Current_Month__c</fullName>
        <formula>IF(MONTH( Payment_Date__c )= MONTH( TODAY()) &amp;&amp; YEAR( Payment_Date__c )= YEAR( TODAY() ) , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IncludeInCurrentMonth__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include in Current Month</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PaymentMonth__c</fullName>
        <formula>MONTH( Payment_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Month</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PaymentYear__c</fullName>
        <formula>YEAR( Payment_Date__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Payment Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <label>Partner Commission</label>
    <nameField>
        <label>Partner Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BatchSetCurrentMonthCommissions.cls
global class BatchSetCurrentMonthCommissions implements Schedulable {
   global void execute(SchedulableContext sc) {
      
		string queryDetails='Select Id, p.Payment_Date__c, p.PaymentYear__c, p.PaymentMonth__c, p.IncludeInCurrentMonth__c, p.Current_Month__c From Partner_Commission__c p ';
     	 queryDetails =  queryDetails +'where (current_month__c = true  and IncludeInCurrentMonth__c = false) or (current_month__c = false and IncludeInCurrentMonth__c = true) ';
 //		if(!Test.isRunningTest()){   query = query + ' limit 2';}

 //      system.Debug('#query# '+queryTrial); 
      
     
      SetCommissionsCurrent commissions = new SetCommissionsCurrent(); 
      commissions.query = queryDetails;
      database.executebatch(commissions);

   }
}