src/objects/Partner_Commission_Summary__c.object
<CustomObject>
    <description>Roles up all customer payments to a reselling partner and calculates the earned commission</description>
    <fields>
        <fullName>Commissionable_Revenue__c</fullName>
        <description>For BAP-3698 - Partner Commission v2</description>
        <inlineHelpText>Net transactions that can be used to pay out commissions</inlineHelpText>
        <label>Commissionable Revenue</label>
        <summarizedField>Partner_Commission_Invoice_Transaction__c.Accrued_Transaction_Amount__c</summarizedField>
        <summaryForeignKey>Partner_Commission_Invoice_Transaction__c.Partner_Commission_Summary__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The latest payment date that can be used to collect payment data for this partner</inlineHelpText>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Number_of_Invoice_Transactions__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total count of invoice transactions associated with this summary</inlineHelpText>
        <label>Number of Invoice Transactions</label>
        <summaryForeignKey>Partner_Commission_Invoice_Transaction__c.Partner_Commission_Summary__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Partner_Commission_Earned__c</fullName>
        <description>For BAP-3698 - Partner Commission v2</description>
        <inlineHelpText>Total commissions earned in this summary</inlineHelpText>
        <label>Partner Commission Earned</label>
        <summarizedField>Partner_Commission_Invoice_Transaction__c.Partner_Commission_Earned__c</summarizedField>
        <summaryForeignKey>Partner_Commission_Invoice_Transaction__c.Partner_Commission_Summary__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The earliest customer payment date to include when calculating this partner&apos;s commissions</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Partner Commission Summary</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Partner Commission Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Commission Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner_Commission_Summary_History__c.object
<CustomObject>
    <description>Stores daily metrics against Partner Commissions to ease in reporting

For BAP-3698 - Partner Commissions v2</description>
    <fields>
        <fullName>Active_Partners_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of active reseller partners for closed Partner Commission Summaries</inlineHelpText>
        <label>Active Partners - Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Active_Partners_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of active reseller partners for open Partner Commission Summaries</inlineHelpText>
        <label>Active Partners - Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commission_Earned_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>Total commission earned for open Partner Commission Summaries</inlineHelpText>
        <label>Commission Earned - Closed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commission_Earned_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>Total commission earned for open Partner Commission Summaries</inlineHelpText>
        <label>Commission Earned - Open</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissionable_Revenue_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total transaction value that can be used for calculating commissions in closed Partner Commission Summaries</inlineHelpText>
        <label>Commissionable Revenue - Closed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissionable_Revenue_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total transaction value that can be used for calculating commissions in open Partner Commission Summaries</inlineHelpText>
        <label>Commissionable Revenue - Open</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissionable_Revenue__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <formula>Commissionable_Revenue_Closed__c +  Commissionable_Revenue_Open__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The total transaction value that can be used for calculating commissions in closed Partner Commission Summaries</inlineHelpText>
        <label>Commissionable Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Commissionable_Transactions_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of commissionable transactions for closed Partner Commission Summaries</inlineHelpText>
        <label>Commissionable Transactions - Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Commissionable_Transactions_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of commissionable transactions for open Partner Commission Summaries</inlineHelpText>
        <label>Commissionable Transactions - Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Date_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The earliest start date for closed Partner Commissions</inlineHelpText>
        <label>Earliest Start Date - Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Earliest_Start_Date_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The earliest start date for open Partner Commissions</inlineHelpText>
        <label>Earliest Start Date - Open</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique key to ensure that only one record is created per day</inlineHelpText>
        <label>Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Latest_End_Date_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The latest end date for closed Partner Commission Summaries</inlineHelpText>
        <label>Latest End Date - Closed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Latest_End_Date_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The latest end date for open Partner Commission Summaries</inlineHelpText>
        <label>Latest End Date - Open</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total amount paid out to partners</inlineHelpText>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payments__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The number of payments made to our partners</inlineHelpText>
        <label>Payments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Summary_Count_Closed__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of closed Partner Commission Summary records</inlineHelpText>
        <label>Summary Count - Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Summary_Count_Open__c</fullName>
        <description>For BAP-3698 - Partner Commissions v2</description>
        <inlineHelpText>The total number of open Partner Commission Summary records</inlineHelpText>
        <label>Summary Count - Open</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Partner Commission Summary History</label>
    <nameField>
        <displayFormat>PCM-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Partner Commission Summary History Numbe</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Commission Summary Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchPartnerCommissionCreateHistory.cls
/**
 * BatchPartnerCommissionCreateHistory
 * Author: Steve O'Neal
 * Ticket: BAP-3698
 * Description: After Partner Commission details are updated or created, creates a history object for reporting purposes
 */
global class BatchPartnerCommissionCreateHistory implements Database.Batchable<sObject> {
	
	global Date endDate;
	global String query;

	/**
	 * Builds the query for the batch process.  Note that this will not run if the query is manually overridden.
	 * @author Steve O'Neal
	 * @date   2016-06-20
	 * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
	 * @return String representing a SOQL query
	 */
	private string buildQuery()
	{
		if (!String.isEmpty(query))
		{
			return query;
		}

		string retVal = 'SELECT ID, Start_Date__c, End_Date__c, Commissionable_Revenue__c, Partner_Commission_Earned__c, Number_of_Invoice_Transactions__c, RecordTypeId from Partner_Commission_Summary__c where End_Date__c  <= ' + BatchPartnerCommissionCreateDetails.formatDateForQuery(endDate);
		System.Debug('Generated SOQL query: ' + retVal);

		return retVal;
	}

	/**
	 * Instantiator
	 * @author Steve O'Neal
	 * @date   2016-06-20
	 * @ticket link          https://jira.bigcommerce.com/browse/BAP-3698
	 * @return nothing
	 */
	global BatchPartnerCommissionCreateHistory() {
		endDate = Date.today();
	}
	
	/**
	 * QueryLocator gets the records from the db based on the generated query
	 * @author Steve O'Neal
	 * @date   2016-06-20
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
	 * @param  BC         Batchable context
	 * @return            Query locator that represents the scope of the batch
	 */
	global Database.QueryLocator start(Database.BatchableContext BC) {
		// always re-initialize the instance of the commission history
	  	Partner_Commission_Summary_History__c pcsh = BatchPartnerCommissionCreateHistory.getPartnerCommissionSummaryHistory(endDate);
	  	pcsh = BatchPartnerCommissionCreateHistory.initializeHistoryObject(pcsh, endDate);
	  	upsert pcsh;

		return Database.getQueryLocator(buildQuery());
	}


	global static Partner_Commission_Summary_History__c getPartnerCommissionSummaryHistory(Date endDate)
	{
  		string pcshKey = BatchPartnerCommissionCreateDetails.formatDateForQuery(endDate);
		Partner_Commission_Summary_History__c retVal = new Partner_Commission_Summary_History__c();
   		List<Partner_Commission_Summary_History__c> pcshList = [Select id, Key__c, Active_Partners_Open__c, Commissionable_Revenue_Open__c, Commissionable_Transactions_Open__c, Commission_Earned_Open__c, Summary_Count_Open__c, Earliest_Start_Date_Open__c, Latest_End_Date_Open__c,  Active_Partners_Closed__c, Commissionable_Revenue_Closed__c, Commissionable_Transactions_Closed__c, Commission_Earned_Closed__c, Summary_Count_Closed__c, Earliest_Start_Date_Closed__c, Latest_End_Date_Closed__c, Payment_Amount__c, Payments__c from Partner_Commission_Summary_History__c where Key__c =:pcshKey limit 1];
   		
   		if (pcshList.size() > 0)
		{
			retVal = pcshList[0];
		}
		else
		{
			retVal = BatchPartnerCommissionCreateHistory.initializeHistoryObject(retVal, endDate);
		}

		return retVal;
	} 

	global static Partner_Commission_Summary_History__c initializeHistoryObject(Partner_Commission_Summary_History__c pcsh, Date endDate)
	{
  		string pcshKey = BatchPartnerCommissionCreateDetails.formatDateForQuery(endDate);
		pcsh.Key__c = pcshKey;
		pcsh.Active_Partners_Open__c = 0;
		pcsh.Commissionable_Revenue_Open__c = 0;
		pcsh.Commissionable_Transactions_Open__c = 0;
		pcsh.Commission_Earned_Open__c = 0;
		pcsh.Summary_Count_Open__c = 0;
		pcsh.Earliest_Start_Date_Open__c = null;
		pcsh.Latest_End_Date_Open__c = null;

		pcsh.Active_Partners_Closed__c = 0;
		pcsh.Commissionable_Revenue_Closed__c = 0;
		pcsh.Commissionable_Transactions_Closed__c = 0;
		pcsh.Commission_Earned_Closed__c = 0;
		pcsh.Summary_Count_Closed__c = 0;
		pcsh.Earliest_Start_Date_Closed__c = null;
		pcsh.Latest_End_Date_Closed__c = null;

		pcsh.Payments__c = 0;
		pcsh.Payment_Amount__c = 0;

		return pcsh;
	}


 	/**
	 * Execute the scope
	 * @author Steve O'Neal
	 * @date   2016-06-20
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
	 * @param  BC         Batchable context
	 * @param  scope      Current scope of batch
	 * @return            Nothing
	 */
  	global void execute(Database.BatchableContext BC, List<sObject> scope) {
  		if (scope.size() > 0)
  		{
	  		Partner_Commission_Summary_History__c pcsh = BatchPartnerCommissionCreateHistory.getPartnerCommissionSummaryHistory(endDate);

	   		for (sObject sobj : scope)
	   		{
   				Partner_Commission_Summary__c pcs = (Partner_Commission_Summary__c)sobj;
	   			if (pcs.RecordTypeId == PartnerCommissionSummaryTriggerHandler.OpenRecordType.Id)
	   			{
	   				pcsh.Commissionable_Revenue_Open__c += pcs.Commissionable_Revenue__c;
	   				pcsh.Commissionable_Transactions_Open__c += pcs.Number_of_Invoice_Transactions__c;
	   				pcsh.Commission_Earned_Open__c += pcs.Partner_Commission_Earned__c;
	   				pcsh.Summary_Count_Open__c++;
	   				if (pcsh.Earliest_Start_Date_Open__c == null || pcsh.Earliest_Start_Date_Open__c > pcs.Start_Date__c)
	   				{
	   					pcsh.Earliest_Start_Date_Open__c = pcs.Start_Date__c;
	   				}
	   				if (pcsh.Latest_End_Date_Open__c == null || pcsh.Latest_End_Date_Open__c < pcs.End_Date__c)
	   				{
		   				pcsh.Latest_End_Date_Open__c = pcs.End_Date__c;
		   			}
	   			}
	   			else
	   			{
	   				pcsh.Commissionable_Revenue_Closed__c += pcs.Commissionable_Revenue__c;
	   				pcsh.Commissionable_Transactions_Closed__c += pcs.Number_of_Invoice_Transactions__c;
	   				pcsh.Commission_Earned_Closed__c += pcs.Partner_Commission_Earned__c;
	   				pcsh.Summary_Count_Closed__c++;
	   				if (pcsh.Earliest_Start_Date_Closed__c == null || pcsh.Earliest_Start_Date_Closed__c > pcs.Start_Date__c)
	   				{
	   					pcsh.Earliest_Start_Date_Closed__c = pcs.Start_Date__c;
	   				}
	   				if (pcsh.Latest_End_Date_Closed__c == null || pcsh.Latest_End_Date_Closed__c < pcs.End_Date__c)
	   				{
		   				pcsh.Latest_End_Date_Closed__c = pcs.End_Date__c;
		   			}
	   			}
	   		}

   			upsert(pcsh);

	   	}

	}
	
	/**
	 * Post-processing logic
	 * @author Steve O'Neal
	 * @date   2016-06-20
	 * @ticket link       https://jira.bigcommerce.com/browse/BAP-3698
	 * @param  BC         Batchable context
	 * @return            nothing
	 */
	global void finish(Database.BatchableContext BC) {
		// add payment data
		BatchPartnerCommissionAddPaymentHistory bpcch = new BatchPartnerCommissionAddPaymentHistory();
		bpcch.endDate = endDate;
		database.executeBatch(bpcch, 200);
		
	}
	
}