src/objects/Pricing__c.object
<CustomObject>
    <fields>
        <fullName>AOV__c</fullName>
        <label>AOV</label>
        <picklist>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Incr_Fee__c</fullName>
        <label>Incr Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Incr_Price_Per_Order__c</fullName>
        <formula>IF(  Tier__c = &quot;Standard&quot; || Tier__c = &quot;Plus&quot;,0,Incr_Fee__c * 12/ Order_Increment__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Incr Price Per Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Max_Base_AOV__c</fullName>
        <label>Max Base AOV</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Base_AOV__c</fullName>
        <label>Min Base AOV</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Minimum_Price__c</fullName>
        <label>Minimum Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order_Increment__c</fullName>
        <label>Order Increment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Order_Max__c</fullName>
        <label>Order Max</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Price_per_Order__c</fullName>
        <formula>Target_Price__c *12/ Order_Max__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Price per Order</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_Price__c</fullName>
        <label>Target Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Target_Take_Rate__c</fullName>
        <label>Target Take Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Tier_Value__c</fullName>
        <formula>IF(NOT ISBLANK(Tier__c), VALUE( TRIM(SUBSTITUTE( Tier__c , &apos;T&apos;,&apos;&apos;)) ) , 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tier Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <label>Tier</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Pricing</label>
    <nameField>
        <label>Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Target_Price__c.object
<CustomObject>
    <description>Custom object used to define different tier and bucket pricing with Steelbrick</description>
    <fields>
        <fullName>MInimum_Price__c</fullName>
        <label>MInimum Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Target Price</label>
    <nameField>
        <label>Target Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Target Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PricingHelper.cls
public class PricingHelper {
	
	
	public static Pricing__c  getPricing(integer annualOrderCount, decimal aov, boolean samReqd, boolean forceEntPlan)
		
	{
        string qaov ;
        string planType ='';
        integer newOrderCount ;
        Pricing__c pplan = new Pricing__c();
        
        if (aov <= 25) qaov = 'Low';
        else if (aov > 25 && aov <= 300) qaov = 'Normal';
        else if (aov > 300) qaov = 'High';
        
        Decimal annualGMV = annualOrderCount * aov;
        boolean basicTier = true;
        
        system.debug(' SAM '+samReqd);
        
        If (annualGMV > 1000000) planType = 'Enterprise';
        else if (samReqd == false && annualGMV <= 50000) planType = 'Standard';
        else if (samReqd == false && annualGMV > 50000 && annualGMV <= 125000) planType = 'Plus';
        else if (annualGMV > 125000 ) basicTier = false;
        
 	    if (planType == 'Standard' || planType ==  'Plus' )
	        { newOrderCount = 0 ;}
	    else
	        { newOrderCount = annualOrderCount ;}
        
        system.debug('order count '+annualOrderCount);
        system.debug('plan  '+planType);
        
        String query = 'Select Id, Name, AOV__c,Incr_Fee__c,Plan_Type__c, Incr_Price_Per_Order__c, Order_Increment__c,Order_Max__c,Price_per_Order__c,Minimum_Price__c, Target_Price__c,Target_Take_Rate__c,Tier__c from Pricing__c ';
        query = query + 'where AOV__c =:qaov and Order_Max__c >= :newOrderCount and Min_Base_AOV__c < :aov ';
        
        if ( qaov <> 'High')
        {
            query = query + ' and Max_Base_AOV__c >= :aov ';
        }
		
		if (basicTier == false)
		{
			query = query + ' and Tier__c <> null and Tier__c <> \'\'';
		}
		if (forceEntPlan == true)
		{
			planType = 'Enterprise';
			query = query + ' and Tier_Value__c > 9 ';
		}
		if (samReqd == true)
		{
			query = query + ' and ((Minimum_Price__c < 2500 and Target_Price__c > 2500) Or Target_Price__c > 2500 ) ';
		}
		
//        if (planType == 'Enterprise')
		if (planType <> '')
        {
            query =  query + ' and Plan_Type__c = \'' +planType  +'\'';
            
        }
        
        
        query = query + ' order by Order_Max__c, Tier__c, Plan_Type__c asc ';
        List<Pricing__c> pplanlist = database.query(query);
        
        if(pplanList.size() > 0)
        { pplan = pplanList[0];}
        
		return pplan;
	}
}