src/objects/Promoter_io_Callout_Session__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Errors__c</fullName>
        <label>Errors</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Number_of_Batches__c</fullName>
        <label>Number of Batches</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Session_Start_Time__c</fullName>
        <label>Session Start Time</label>
        <type>DateTime</type>
    </fields>
    <label>Promoter.io Callout Session</label>
    <nameField>
        <displayFormat>PCS-{00000000}</displayFormat>
        <label>Promoter.io Callout Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoter.io Callout Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Promoter_io_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Promoter.io Feedbacks</relationshipLabel>
        <relationshipName>Promoter_io_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_External_ID__c</fullName>
        <label>Contact External ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Promoter.io Feedbacks</relationshipLabel>
        <relationshipName>Promoter_io_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Posted_Date__c</fullName>
        <label>Posted Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SF_Account_ID__c</fullName>
        <label>SF Account ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Contact_Id__c</fullName>
        <label>SF Contact Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Session_Time__c</fullName>
        <label>Session Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Store_ID__c</fullName>
        <label>Store ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Promoter.io Feedbacks</relationshipLabel>
        <relationshipName>Promoter_io_Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promoter.io Feedback</label>
    <nameField>
        <displayFormat>PIO-{00000000}</displayFormat>
        <label>Promoter.io Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promoter.io Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PromoterioSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Fetch_All__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fetch All</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Run_On__c</fullName>
        <label>Last Run On</label>
        <type>DateTime</type>
    </fields>
    <label>Promoter.io Settings</label>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>MBA User ID associated to subscription purchases</description>
        <inlineHelpText>Account associated with the subscription</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact associated with the subscription</description>
        <inlineHelpText>Contact associated with the subscription</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Populated by a workflow capturing the associated contact or lead email address each time the contact name is changed.  Also used in case workflows to send email notifications if no lead or contact is called out on the case</description>
        <inlineHelpText>Populated by a workflow capturing the associated contact or lead email address each time the contact name is changed. Also used in case workflows to send email notifications if no lead or contact is called out on the case</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MBASubscriptionID__c</fullName>
        <description>ID specific to the store/product purchased</description>
        <externalId>true</externalId>
        <label>MBA Subscription ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SF_Account_ID__c</fullName>
        <description>Formula to pull the associated account&apos;s salesforce ID for reports and list views</description>
        <formula>IF(ISBLANK( Account__c ),Account__r.Account_Unique_ID__c,NULL)</formula>
        <inlineHelpText>Salesforce Account ID</inlineHelpText>
        <label>Salesforce Account ID</label>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BatchProcessPromoterIoFeedback.cls
public class BatchProcessPromoterIoFeedback implements Database.Batchable<sObject>, Database.stateful{
	public Promoter_io_Callout_Session__c piocs;
    public string errors;
    public Set<Id> allContactIds = new Set<Id>();
    public Database.QueryLocator start(Database.BatchableContext BC){
        promoterioSettings__c pios = promoterioSettings__c.getOrgDefaults();
        Datetime CurrentRun;
        if(pios.Last_Run_On__c!=null){
            CurrentRun = pios.Last_Run_On__c;
        }
        Boolean Alltime = pios.Fetch_All__c;
        String Query;
        Query = 'select id, Email__c, Contact_External_ID__c,SF_Account_ID__c,SF_Contact_Id__c,FirstName__c,LastName__c,';
        Query += 'Posted_Date__c, Subscription__c, Store_ID__c, Score__c  from Promoter_io_Feedback__c ';
        Query += 'where (Contact__c = null OR Subscription__c = null)';
        if(!Alltime&&CurrentRun!=null){
            query += ' and Session_Time__c = :CurrentRun';
        }
        if(currentRun!=null){
        	List<Promoter_io_Callout_Session__c> piocsList = new List<Promoter_io_Callout_Session__c>([select id,Count__c,Errors__c,Number_of_Batches__c,Session_Start_Time__c from Promoter_io_Callout_Session__c 
                where Session_Start_Time__c = :CurrentRun limit 1]);
            if(!piocsList.isEmpty()){
                piocs = piocsList[0];
            }
        }

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope){
       	List<Promoter_io_Feedback__c> listPioFeedbacks = (List<Promoter_io_Feedback__c>)scope;
        List<Promoter_io_Feedback__c> updatelistPioFeedbacks = new List<Promoter_io_Feedback__c>();
        Set<Id> AccountIds = new Set<Id>();
        Set<Id> ContactIds = new Set<Id>();
        Set<String> SubIds = new Set<String>();
        for(Promoter_io_Feedback__c piof:listPioFeedbacks){
            if(piof.SF_Account_Id__c!=null){
            	AccountIds.add(Id.valueOf(piof.SF_Account_Id__c));
            }
            if(piof.SF_Contact_Id__c!=null){
            	AccountIds.add(Id.valueOf(piof.SF_Account_Id__c));
            }
            if(piof.Store_ID__c!=null){
            	SubIds.add(piof.Store_ID__c);
            }
        }
        if(listPioFeedbacks != null && listPioFeedbacks.size() > 0){
			List<Contact> conList = new List<Contact>([select id, email, accountid, LastName, Last_Promoter_io_NPS__c, Account.Last_Promoter_io_NPS__c  from Contact where accountid in :AccountIds]);
            List<Subscription__c> subList = new List<Subscription__c>([select id, MBASubscriptionID__c from Subscription__c where MBASubscriptionID__c in :SubIds]);
			Map<String,id> conEmailToContact = new Map<string,id>();
            Map<String,id> conInfoToContact = new Map<string,id>();   
            Map<String,id> MapMBASubIDtoSFID = new Map<string,id>();
            
            Map<Id,Id> ContoAccountMap = new Map<Id,Id>();
            system.debug('BatchProcessPromoterIoFeedback conList = '+conList);
            for(contact con:conList){
                conInfoToContact.put(con.Email+string.valueOf(con.AccountId).left(15)+con.LastName, con.Id);//@@try spinning a method
                ContoAccountMap.put(con.id,con.AccountId);
                allContactIds.add(con.id);
            }
            for(Subscription__c sub:subList){
                MapMBASubIDtoSFID.put(sub.MBASubscriptionID__c, sub.id);
            }
            for(Promoter_io_Feedback__c piof:listPioFeedbacks){
                if(piof.sf_contact_id__c!=null){
                    piof.contact__c = id.valueOf(piof.sf_Contact_id__c);
                    piof.Account__c = ContoAccountMap.get(piof.contact__c);
                } 
                else if(conInfoToContact.get(piof.Email__c+piof.SF_Account_Id__c.left(15)+piof.LastName__c)!=null){
                    piof.contact__c = conInfoToContact.get(piof.Email__c+piof.SF_Account_Id__c.left(15)+piof.LastName__c);
                    piof.Account__c = ContoAccountMap.get(piof.contact__c);
                } else if(piof.SF_Account_Id__c!=null){
                    piof.account__c = id.valueOf(piof.SF_Account_Id__c);
                }
                if(piof.Store_ID__c!=null&&MapMBASubIDtoSFID.get(piof.Store_ID__c)!=null){
                    piof.Subscription__c = MapMBASubIDtoSFID.get(piof.Store_ID__c);
                }
                updatelistPioFeedbacks.add(piof);
        		
            }
            if(!updatelistPioFeedbacks.isEmpty()){
                database.update(updatelistPioFeedbacks,false);
                integer iter=0;
            	Database.saveResult[] saveResultList = database.Update(updatelistPioFeedbacks,false);
                for(database.saveResult res:saveResultList){
                    if(!res.success&&iter<6){
                        for(database.Error err:res.getErrors()){
                            iter = iter+1;
                            if(iter==1&&errors==null){
                                errors = 'BatchProcessPromoterIoFeedback:'+'"\n\n';
                            } else if(iter==1&&errors!=null){
                                errors += '"\n\n';
                                errors += 'BatchProcessPromoterIoFeedback:'+'"\n\n';
                            }
                            errors += res.getId()+': '+err.getStatusCode() + ': ' + err.getMessage()+'"\n\n';
                            break;
                        }
                    }
                    if(iter==6){ break;}
        		}
            } 
        } 
    }

    public void finish(Database.BatchableContext BC){
        if(errors!=null&&piocs!=null){
            piocs.Errors__c = errors;
        	upsert piocs;
        }
        BatchUpdatePromoterIoNPSonContacts bpfNPSc = new BatchUpdatePromoterIoNPSonContacts(allContactIds);
        database.executeBatch(bpfNPSc,100);
    }
}