src/objects/Subscription__c.object
<CustomObject>
    <description>Child object of Accounts to track a user&apos;s purchases : stores, SSLs, services, etc</description>
    <fields>
        <fullName>StoreURL__c</fullName>
        <description>URL of the BC trial or store populated by MBA</description>
        <inlineHelpText>URL of the BC trial or store populated by MBA</inlineHelpText>
        <label>MBA Store URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Support_PIN__c</fullName>
        <description>Formula pulling the pin value from the associated account or lead</description>
        <formula>IF(
ISBLANK(Account__r.SupportPin__c), Lead__r.SupportPin__c ,Account__r.SupportPin__c)</formula>
        <label>Support Pin</label>
        <type>Text</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TestSubmitCase.cls
@isTest(seeAllData=true)
private class TestSubmitCase {
/**
    static testMethod void validatePINTest1() {
	// Test with Valid URL/PIN
        String testcsse = 'Web2Case';
    	TestDataGenerator_SubscriptionValidation td = new TestDataGenerator_SubscriptionValidation();
        
        PageReference pg = Page.LiveAgentPreChatSupport;
        Test.setCurrentPage(pg);

        ApexPages.currentPage().getParameters().put('csse', testcsse);      
        
        SubmitCaseController scc = new SubmitCaseController();
    	list<Subscription__c> lstSubs = td.getSubscriptions(true);

        scc.formURL = lstSubs[0].StoreURL__c;
        scc.formPIN = lstSubs[0].Support_PIN__c;
        
        scc.validatePIN();

    }

/*    static testMethod void submitCaseTest1() {
        scc.ct.FirstName = 'John';
        scc.ct.LastName = 'Smith';
        scc.ct.Email = 'johnsmith@test.com';
        scc.ct.Description = 'This some text';
    } */
}